package com.casapellas.socketpos;
// Generated Nov 16, 2016 4:16:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

import com.casapellas.util.PropertiesSystem;

/**
 * HistoricoCobrosSocketpos generated by hbm2java
 */
public class HistoricoCobrosSocketpos  implements java.io.Serializable {

 
	private static final long serialVersionUID = 8739913526454464314L;
	private int idhistoricosp;
     private int caid;
     private String codcomp;
     private String terminalid;
     private String acqnumber;
     private String invoicenumber;
     private String entrymode;
     private BigDecimal amount;
     private String cardnumber;
     private String duedate;
     private int status;
     private String responsecode;
     private String module;
     private String submodule;
     private long usercode;
     private Date created;
     private Date updated;

    public HistoricoCobrosSocketpos() {
    }

    public HistoricoCobrosSocketpos(int caid, String codcomp,
			String terminalid, String acqnumber, String invoicenumber,
			String entrymode, BigDecimal amount, String cardnumber,
			String duedate, int status, String responsecode, String module,
			String submodule, long usercode) {
		super();
		this.caid = caid;
		this.codcomp = codcomp;
		this.terminalid = terminalid;
		this.acqnumber = acqnumber;
		this.invoicenumber = invoicenumber;
		this.entrymode = entrymode;
		this.amount = amount;
		this.cardnumber = cardnumber;
		this.duedate = duedate;
		this.status = status;
		this.responsecode = responsecode;
		this.module = module;
		this.submodule = submodule;
		this.usercode = usercode;
	}

	public HistoricoCobrosSocketpos(int idhistoricosp, int caid, String codcomp, String terminalid, String acqnumber, String invoicenumber, String entrymode, BigDecimal amount, String cardnumber, String duedate, int status, String responsecode, String module, String submodule, long usercode, Date created, Date updated) {
       this.idhistoricosp = idhistoricosp;
       this.caid = caid;
       this.codcomp = codcomp;
       this.terminalid = terminalid;
       this.acqnumber = acqnumber;
       this.invoicenumber = invoicenumber;
       this.entrymode = entrymode;
       this.amount = amount;
       this.cardnumber = cardnumber;
       this.duedate = duedate;
       this.status = status;
       this.responsecode = responsecode;
       this.module = module;
       this.submodule = submodule;
       this.usercode = usercode;
       this.created = created;
       this.updated = updated;
    }
   
    public int getIdhistoricosp() {
        return this.idhistoricosp;
    }
    
    public void setIdhistoricosp(int idhistoricosp) {
        this.idhistoricosp = idhistoricosp;
    }
    public int getCaid() {
        return this.caid;
    }
    
    public void setCaid(int caid) {
        this.caid = caid;
    }
    public String getCodcomp() {
        return this.codcomp;
    }
    
    public void setCodcomp(String codcomp) {
        this.codcomp = codcomp;
    }
    public String getTerminalid() {
        return this.terminalid;
    }
    
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid;
    }
    public String getAcqnumber() {
        return this.acqnumber;
    }
    
    public void setAcqnumber(String acqnumber) {
        this.acqnumber = acqnumber;
    }
    public String getInvoicenumber() {
        return this.invoicenumber;
    }
    
    public void setInvoicenumber(String invoicenumber) {
        this.invoicenumber = invoicenumber;
    }
    public String getEntrymode() {
        return this.entrymode;
    }
    
    public void setEntrymode(String entrymode) {
        this.entrymode = entrymode;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getCardnumber() {
        return this.cardnumber;
    }
    
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }
    public String getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(String duedate) {
        this.duedate = duedate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getResponsecode() {
        return this.responsecode;
    }
    
    public void setResponsecode(String responsecode) {
        this.responsecode = responsecode;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getSubmodule() {
        return this.submodule;
    }
    
    public void setSubmodule(String submodule) {
        this.submodule = submodule;
    }
    public long getUsercode() {
        return this.usercode;
    }
    
    public void setUsercode(long usercode) {
        this.usercode = usercode;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

	public String updateStatment() {

		return " UPDATE " + PropertiesSystem.ESQUEMA
				+ ".HISTORICO_COBROS_SOCKETPOS SET STATUS = " + status
				+ ", updated = current_timestamp, responsecode = '"
				+ responsecode + "' " + " WHERE TERMINALID = '" + terminalid
				+ "' AND INVOICENUMBER = '" + invoicenumber + "' and AMOUNT = "
				+ amount.toString() + " and CARDNUMBER = '" + cardnumber + "' ";

	}
    
    
    public String insertStatement(){
    	
    	String insert =   "INSERT INTO @BDCAJA.HISTORICO_COBROS_SOCKETPOS" +
			" ( CAID, CODCOMP, TERMINALID, ACQNUMBER, INVOICENUMBER, ENTRYMODE, AMOUNT, CARDNUMBER, DUEDATE, STATUS, RESPONSECODE, MODULE, SUBMODULE, USERCODE) " +
			" VALUES " +
			"( @CAID, '@CODCOMP', '@TERMINALID', '@ACQNUMBER', '@INVOICENUMBER', '@ENTRYMODE', @AMOUNT, '@CARDNUMBER', '@DUEDATE', @STATUS, '@RESPONSECODE', '@MODULE', '@SUBMODULE', @USERCODE )" ;
    	
    	return insert.replace("@BDCAJA", PropertiesSystem.ESQUEMA   ) 
    			.replace("@CAID",   String.valueOf(caid) ) 
    			.replace("@CODCOMP", codcomp   ) 
    			.replace("@TERMINALID",  terminalid ) 
    			.replace("@ACQNUMBER",  acqnumber ) 
    			.replace("@INVOICENUMBER",  invoicenumber ) 
    			.replace("@ENTRYMODE",   entrymode) 
    			.replace("@AMOUNT",  amount.toString()  ) 
    			.replace("@CARDNUMBER", cardnumber  ) 
    			.replace("@DUEDATE",  duedate ) 
    			.replace("@STATUS",  String.valueOf(status) ) 
    			.replace("@RESPONSECODE", responsecode  ) 
    			.replace("@MODULE",  module ) 
    			.replace("@SUBMODULE",  submodule ) 
    			.replace("@USERCODE", String.valueOf(usercode) ) ;
    	
    }


}


