// (c) 2008 Infragistics - Do NOT modify the content of this file
// Version 9.2.20092.1000

if(ig){if(!ig.dw){function IgWebDialogWindowPackage(){this.TYPE_DIALOG_WINDOW="DialogWindow";this.TYPE_DIALOG_WINDOW_RESIZER="DialogWindowResizer";this.STATE_NORMAL=0;this.STATE_MINIMIZED=1;this.STATE_MAXIMIZED=2;this.STATE_HIDDEN=3;this.EVENT_SS_MOVED="dwMoved";this.EVENT_SS_RESIZED="dwResized";this.EVENT_SS_STATE_CHANGED="dwStateChanged";this.IMG_STATE_NORMAL=0;this.IMG_STATE_HOVER=1;this.IMG_STATE_ACTIVE=2;this.mouseHandlerAdded=false;this.moveWindow=null;this.nextZIndex=0;this.nextZIndexModal=1000;this.modalLayerZIndex=999;this.dialogWindows=[];this.activeDialogWindow=null;this.modalLayer=null;this.moveOccured=false;this.moveStartX=0;this.moveStartY=0;this.moveDiffX=0;this.moveDiffY=0;this.resizeOccured=false;this.resizeStartW=0;this.resizeStartH=0;this.resizeStartX=0;this.resizeStartY=0;this.maintainLocX=ig.getScrollLeft();this.maintainLocY=ig.getScrollTop();this.maintainLocDialogs=[];this.init=function(){ig.factory.addClass(ig.dw.TYPE_DIALOG_WINDOW,IgDialogWindow);ig.factory.addClass(ig.dw.TYPE_DIALOG_WINDOW_RESIZER,IgDialogWindowResizer);};this.initDialogWindow=function(id,modal,minimizedWidth,centered,initialState,movable,resizerEnabled,modalBackground,pinWhenMinimized,maintainLocationOnScroll,minW,minH,maxW,maxH,postBackOnMove,postBackOnResize,postBackOnStateChange,clientSideListeners){this.removeDwWindows(id);var igElm=ig.getTargetUIElement(id,ig.dw.TYPE_DIALOG_WINDOW);if(!ig.isNull(igElm)){igElm.init(modal,minimizedWidth,centered,initialState,movable,resizerEnabled,modalBackground,pinWhenMinimized,maintainLocationOnScroll,minW,minH,maxW,maxH,postBackOnMove,postBackOnResize,postBackOnStateChange,clientSideListeners);}};this.initDialogWindowResizer=function(id,parentDw){var igElm=ig.getTargetUIElement(id,ig.dw.TYPE_DIALOG_WINDOW_RESIZER);if(!ig.isNull(igElm)){igElm.init(parentDw);}};this.resizeInternals=function(jsNode){var resizerDiv=jsNode.elm.firstChild;if(resizerDiv.tagName!="DIV"){resizerDiv=resizerDiv.nextSibling;}
if(ig.isNull(resizerDiv))return;var resizerDivJs=new IgDomNode(resizerDiv);var headerDiv=resizerDiv.nextSibling;if(ig.isNull(headerDiv))return;var headerDivTable=headerDiv.firstChild;if(ig.isNull(headerDivTable))return;var contentDiv=headerDiv.nextSibling;if(ig.isNull(contentDiv))return;if(ig.isNull(contentDiv.firstChild))return;if(ig.isNull(contentDiv.firstChild.firstChild))return;if(ig.isNull(contentDiv.firstChild.firstChild.firstChild))return;var tableRow1=contentDiv.firstChild.firstChild.firstChild;var leftCell=tableRow1.firstChild;if(ig.isNull(leftCell))return;var contentCell=leftCell.nextSibling;if(ig.isNull(contentCell))return;var contentCellDiv=contentCell.firstChild;if(ig.isNull(contentCellDiv))return;var rightCell=contentCell.nextSibling;if(ig.isNull(rightCell))return;if(ig.isNull(tableRow1.nextSibling))return;if(ig.isNull(tableRow1.nextSibling.firstChild))return;var tableRow2Cell1=tableRow1.nextSibling.firstChild;var tableRow2Cell1Height=0;if(tableRow2Cell1.currentStyle){tableRow2Cell1Height=tableRow2Cell1.currentStyle.height;}else{tableRow2Cell1Height=tableRow2Cell1.offsetHeight;}
var newContentHeight=ig.toFloat(jsNode.getHeight())-jsNode.getBorder("height")-jsNode.getPadding("height")-headerDiv.offsetHeight;var igHeaderDivTable=new IgDomNode(headerDivTable);igHeaderDivTable.setStyle("height",headerDiv.offsetHeight+"px");var igContentDiv=new IgDomNode(contentDiv);igContentDiv.setStyle("height",newContentHeight+"px");var contentCellHeight=newContentHeight-ig.toFloat(tableRow2Cell1Height);var igContentCell=new IgDomNode(contentCell);igContentCell.setStyle("height",contentCellHeight+"px");var contentCellDivAsJsNode=new IgUIElement(contentCellDiv);var totalVerToCut=0;totalVerToCut=totalVerToCut+contentCellDivAsJsNode.getMargin("top");totalVerToCut=totalVerToCut+contentCellDivAsJsNode.getMargin("bottom");totalVerToCut=totalVerToCut+contentCellDivAsJsNode.getBorder("top");totalVerToCut=totalVerToCut+contentCellDivAsJsNode.getBorder("bottom");totalVerToCut=totalVerToCut+contentCellDivAsJsNode.getPadding("top");totalVerToCut=totalVerToCut+contentCellDivAsJsNode.getPadding("bottom");contentCellDivAsJsNode.setStyle("height",(contentCellHeight-totalVerToCut)+"px");var ig_iframeId=jsNode.elm.id+"_iframe";var iframeObject=document.getElementById(ig_iframeId);if(!ig.isNull(iframeObject)){var totalHorToCut=0;var contentCellWidth=ig.toFloat(contentCell.offsetWidth);totalHorToCut=totalHorToCut+contentCellDivAsJsNode.getMargin("left");totalHorToCut=totalHorToCut+contentCellDivAsJsNode.getMargin("right");totalHorToCut=totalHorToCut+contentCellDivAsJsNode.getBorder("left");totalHorToCut=totalHorToCut+contentCellDivAsJsNode.getBorder("right");totalHorToCut=totalHorToCut+contentCellDivAsJsNode.getPadding("left");totalHorToCut=totalHorToCut+contentCellDivAsJsNode.getPadding("right");contentCellDiv.setStyle("width",(contentCellWidth-totalHorToCut)+"px");}
if(resizerDiv.firstChild){var resizerDivImgJs=new IgDomNode(resizerDiv.firstChild);var newResizerLeft=jsNode.getWidth()-jsNode.getBorder('left')-jsNode.getPadding('left')-resizerDivImgJs.getWidth();var newResizerTop=jsNode.getHeight()-jsNode.getBorder('top')-jsNode.getPadding('top')-resizerDivImgJs.getHeight();resizerDivJs.setPosition(newResizerLeft,newResizerTop);}};this.getDwJsNodeById=function(winId){var result=null;for(i=0;i<ig.dw.dialogWindows.length;i++){if(ig.dw.dialogWindows[i].elm.id==winId){return ig.dw.dialogWindows[i];}}
return null;};this.removeDwWindows=function(winId){for(i=0;i<ig.dw.dialogWindows.length;i++){if(ig.dw.dialogWindows[i].elm.id==winId){ig.dw.dialogWindows.splice(i,1);}}}
this.activate=function(winId){var newTopWindow=ig.dw.getDwJsNodeById(winId);if(newTopWindow!=null){if(newTopWindow.igModal){if(newTopWindow.elm.style.zIndex==ig.dw.nextZIndexModal-1){ig.dw.activeDialogWindow=newTopWindow;return;}
for(i=0;i<ig.dw.dialogWindows.length;i++){if(ig.dw.dialogWindows[i].igModal){if(ig.dw.dialogWindows[i].elm.style.zIndex>newTopWindow.elm.style.zIndex){ig.dw.dialogWindows[i].elm.style.zIndex=ig.dw.dialogWindows[i].elm.style.zIndex-1;}}}
newTopWindow.elm.style.zIndex=ig.dw.nextZIndexModal-1;ig.dw.activeDialogWindow=newTopWindow;}else{if(newTopWindow.elm.style.zIndex==ig.dw.nextZIndex-1){ig.dw.activeDialogWindow=newTopWindow;return;}
for(i=0;i<ig.dw.dialogWindows.length;i++){if(!ig.dw.dialogWindows[i].igModal){if(ig.dw.dialogWindows[i].elm.style.zIndex>newTopWindow.elm.style.zIndex){ig.dw.dialogWindows[i].elm.style.zIndex=ig.dw.dialogWindows[i].elm.style.zIndex-1;}}}
newTopWindow.elm.style.zIndex=ig.dw.nextZIndex-1;ig.dw.activeDialogWindow=newTopWindow;}}};this.headerMouseOver=function(winId,evt){var jsNode=ig.dw.getDwJsNodeById(winId);jsNode._raiseClientEvent("HeaderMouseOver","MouseOver",evt,null);};this.headerMouseOut=function(winId,evt){var jsNode=ig.dw.getDwJsNodeById(winId);jsNode._raiseClientEvent("HeaderMouseOut","MouseOut",evt,null);};this.resizerMouseOver=function(winId,evt){var jsNode=ig.dw.getDwJsNodeById(winId);jsNode._raiseClientEvent("ResizerMouseOver","MouseOver",evt,null);};this.resizerMouseOut=function(winId,evt){var jsNode=ig.dw.getDwJsNodeById(winId);jsNode._raiseClientEvent("ResizerMouseOut","MouseOut",evt,null);};this.beginMove=function(winId,evt){var jsNode=ig.dw.getDwJsNodeById(winId);if(jsNode!=null&&jsNode.igMovable&&jsNode.igState!=ig.dw.STATE_MAXIMIZED){if(jsNode.igState==ig.dw.STATE_MINIMIZED&&jsNode.igPinWhenMinimized)return;ig.dw.moveStartX=ig.toFloat(jsNode.elm.offsetLeft);ig.dw.moveStartY=ig.toFloat(jsNode.elm.offsetTop);ig.dw.moveDiffX=ig.ui.x-ig.dw.moveStartX;ig.dw.moveDiffY=ig.ui.y-ig.dw.moveStartY;if(ig.isIE){ig.dw.moveDiffX+=ig.getScrollLeft();ig.dw.moveDiffY+=ig.getScrollTop();}
ig.dw.moveWindow=jsNode;jsNode._raiseClientEvent("HeaderMouseDown","MouseDown",evt,null);var ourEvent=ig.toEvent(evt);ourEvent.preventDefault();}};this.endMove=function(evt){if(ig.dw.moveWindow!=null){var oldX=ig.dw.moveStartX;var oldY=ig.dw.moveStartY;var newX=ig.ui.x-ig.dw.moveDiffX;var newY=ig.ui.y-ig.dw.moveDiffY;if(ig.isIE){newX+=ig.getScrollLeft();newY+=ig.getScrollTop();}
var args=null;if(ig.dw.moveOccured){args=ig.dw.moveWindow._raiseClientEvent("Moved","Move",evt,ig.dw.moveWindow.igPostBackOnMove?1:0,newX,newY,oldX,oldY);ig.dw.moveOccured=false;}
if(args!=null&&args.get_cancel()){ig.dw.moveWindow.elm.style.left=oldX+"px";ig.dw.moveWindow.elm.style.top=oldY+"px";}else{ig.dw.moveWindow.elm.style.left=newX+"px";ig.dw.moveWindow.elm.style.top=newY+"px";}
if((args==null&&ig.dw.moveWindow.igPostBackOnMove)||(args!=null&&args.get_postBack()==1)){var compId=ig.dw.moveWindow.elm.id;var evtName=ig.dw.EVENT_SS_MOVED;var evtArgs="ox:"+oldX+";oy:"+oldX+";x:"+newX+";y:"+newY;ig.smartSubmit(compId,evtName,evtArgs,null,null);}
ig.dw.moveWindow._raiseClientEvent("HeaderMouseUp","MouseUp",evt,null);ig.dw.moveWindow=null;var ourEvent=ig.toEvent(evt);ourEvent.preventDefault();}};this.handleMouseMove=function(evt){if(ig.dw.moveWindow!=null){var oldX=ig.toFloat(ig.dw.moveWindow.elm.style.left);var oldY=ig.toFloat(ig.dw.moveWindow.elm.style.top);var newX=evt.clientX-ig.dw.moveDiffX+ig.getScrollLeft();var newY=evt.clientY-ig.dw.moveDiffY+ig.getScrollTop();var eventCanceled=false;var args=ig.dw.moveWindow._raiseClientEvent("Moving","Move",evt,null,newX,newY,oldX,oldY);if(args!=null&&args.get_cancel())eventCanceled=true;if(!eventCanceled){ig.dw.moveWindow.elm.style.left=newX+"px";ig.dw.moveWindow.elm.style.top=newY+"px";ig.dw.moveOccured=true;}
var ourEvent=ig.toEvent(evt);ourEvent.preventDefault();}};this.minWin=function(winId,event){var jsNode=ig.dw.getDwJsNodeById(winId);if(jsNode!=null){if(jsNode.igState==ig.dw.STATE_NORMAL||jsNode.igState==ig.dw.STATE_MAXIMIZED){jsNode.set_windowState(ig.dw.STATE_MINIMIZED);}else{jsNode.set_windowState(ig.dw.STATE_NORMAL);}}};this.maxWin=function(winId,event){var jsNode=ig.dw.getDwJsNodeById(winId);if(jsNode!=null){if(jsNode.igState==ig.dw.STATE_NORMAL||jsNode.igState==ig.dw.STATE_MINIMIZED){jsNode.set_windowState(ig.dw.STATE_MAXIMIZED);}else{jsNode.set_windowState(ig.dw.STATE_NORMAL);}}};this.closeWin=function(winId,event){var jsNode=ig.dw.getDwJsNodeById(winId);if(jsNode!=null){jsNode.set_windowState(ig.dw.STATE_HIDDEN);}};this.maintainLocationHandler=function(){var dX=ig.getScrollLeft()-ig.dw.maintainLocX;var dY=ig.getScrollTop()-ig.dw.maintainLocY;if(dX!=0||dY!=0){for(i=0;i<ig.dw.maintainLocDialogs.length;i++){var newX=ig.toFloat(ig.dw.maintainLocDialogs[i].elm.style.left)+dX;var newY=ig.toFloat(ig.dw.maintainLocDialogs[i].elm.style.top)+dY;ig.dw.maintainLocDialogs[i].elm.style.left=newX+"px";ig.dw.maintainLocDialogs[i].elm.style.top=newY+"px";}
ig.dw.maintainLocX=ig.getScrollLeft();ig.dw.maintainLocY=ig.getScrollTop();}};this.setImageSources=function(imgId,normal,hover,active,altNormal,altHover,altActive,text,altText){var el=ig.getElementById(imgId);if(el!=null){el.igImgAltMode=false;el.igImgNormal=normal;el.igImgHover=hover;el.igImgActive=active;el.igImgAltNormal=altNormal;el.igImgAltHover=altHover;el.igImgAltActive=altActive;el.igText=text;el.igAltText=altText;}};this.setImageAltMode=function(imgId,altMode){var el=ig.getElementById(imgId);if(el!=null){el.igImgAltMode=altMode;}};this.setImageState=function(imgId,newState){var el=ig.getElementById(imgId);if(el!=null){if(newState==ig.dw.IMG_STATE_NORMAL){if(el.igImgAltMode){el.src=el.igImgAltNormal;el.alt=el.igAltText;}else{el.src=el.igImgNormal;el.alt=el.igText;}}else
if(newState==ig.dw.IMG_STATE_HOVER){if(el.igImgAltMode){el.src=el.igImgAltHover;el.alt=el.igAltText;}else{el.src=el.igImgHover;el.alt=el.igText;}}else
if(newState==ig.dw.IMG_STATE_ACTIVE){if(el.igImgAltMode){el.src=el.igImgAltActive;el.alt=el.igAltText;}else{el.src=el.igImgActive;el.alt=el.igText;}}}};};ig.dw=new IgWebDialogWindowPackage();function IgDialogWindow(e){this.IgUIComponent(e);};IgDialogWindow.prototype.init=function(modal,minimizedWidth,centered,initialState,movable,resizerEnabled,modalBackground,pinWhenMinimized,maintainLocationOnScroll,minW,minH,maxW,maxH,postBackOnMove,postBackOnResize,postBackOnStateChange,clientSideListeners){if(!ig.dw.mouseHandlerAdded){if(ig.isBrowser("msie",null)){ig.addEventListener(document.body,ig.event.EVENT_MOUSEMOVE,ig.dw.handleMouseMove,false);}else{ig.addEventListener(window,ig.event.EVENT_MOUSEMOVE,ig.dw.handleMouseMove,false);}
ig.dw.mouseHandlerAdded=true;}
if(minW>0)this.igResizerMinWidth=minW;if(minH>0)this.igResizerMinHeight=minH;if(maxW>0)this.igResizerMaxWidth=maxW;if(maxH>0)this.igResizerMaxHeight=maxH;this.igPostBackOnMove=postBackOnMove;this.igPostBackOnResize=postBackOnResize;this.igPostBackOnStateChange=postBackOnStateChange;this.igModal=modal;if(modal){if(ig.dw.modalLayer==null){if(ig.isBrowser("msie",null)){ig.dw.modalLayer=document.createElement("iframe");ig.dw.modalLayer.style.visibility="hidden";ig.dw.modalLayer.frameBorder="no";ig.dw.modalLayer.className=modalBackground;var theParent=this.elm.parentNode;theParent.insertBefore(ig.dw.modalLayer,this.elm);ig.dw.modalLayer.allowTransparency="true";var modalLayerDocument=ig.dw.modalLayer.contentWindow.document;modalLayerDocument.open();modalLayerDocument.close();modalLayerDocument.body.style.backgroundColor="transparent";modalLayerDocument.body.style.padding="0px";modalLayerDocument.body.style.margin="0px";var fogListener=ig.dw.modalLayer.contentWindow.document;ig.addEventListener(fogListener,ig.event.EVENT_MOUSEMOVE,ig.dw.handleMouseMove,false);}else{ig.dw.modalLayer=document.createElement("div");ig.dw.modalLayer.style.visibility="hidden";var theParent=this.elm.parentNode;theParent.appendChild(ig.dw.modalLayer);ig.dw.modalLayer.className=modalBackground;}
ig.dw.modalLayer.style.zIndex=ig.dw.modalLayerZIndex;}
this.elm.style.zIndex=ig.dw.nextZIndexModal;ig.dw.nextZIndexModal++;}else{this.elm.style.zIndex=ig.dw.nextZIndex;ig.dw.nextZIndex++;}
ig.dw.dialogWindows.push(this);ig.dw.activeDialogWindow=this;if(!this.elm.style.width||ig.isNull(this.elm.style.width)){this.setStyle("width","300px");}
if(!this.elm.style.height||ig.isNull(this.elm.style.height)){this.setStyle("height","200px");}
if(!this.elm.style.left||ig.isNull(this.elm.style.left)){var newLeft=(ig.getClientWidth()-this.getWidth())/2+ig.getScrollLeft();this.elm.style.left=newLeft+"px";}
if(!this.elm.style.top||ig.isNull(this.elm.style.top)){var newTop=(ig.getClientHeight()-this.getHeight())/2+ig.getScrollTop();this.elm.style.top=newTop+"px";}
this.setStyle("height",this.getHeight()-this.getBorder("height")+"px");this.setStyle("width",this.getWidth()-this.getBorder("width")+"px");ig.dw.resizeInternals(this);this.igResizerEnabled=resizerEnabled;if(!this.igResizerMinWidth)this.igResizerMinWidth=100;if(!this.igResizerMinHeight)this.igResizerMinHeight=60;if(!this.igResizerMaxWidth)this.igResizerMaxWidth=0;if(!this.igResizerMaxHeight)this.igResizerMaxHeight=0;this.igRestoreLeft=0;this.igRestoreTop=0;this.igRestoreWidth=300;this.igRestoreHeight=200;this.igStateOld=ig.dw.STATE_NORMAL;this.igState=ig.dw.STATE_NORMAL;this.igMinimizedWidth=minimizedWidth+"px";this.igMovable=movable;this.igPinWhenMinimized=pinWhenMinimized;this.igMaintainLocationOnScroll=maintainLocationOnScroll;if(this.igMaintainLocationOnScroll){if(ig.dw.maintainLocDialogs.length==0){ig.addEventListener(window,ig.event.EVENT_SCROLL,ig.dw.maintainLocationHandler,false);}
ig.dw.maintainLocDialogs.push(this);}
if(centered){var screenWidth=ig.getClientWidth();var screenHeight=ig.getClientHeight();var dialogWidth=this.elm.offsetWidth;var dialogHeight=this.elm.offsetHeight;if(screenWidth&&screenHeight&&dialogWidth&&dialogHeight){var newLeft=(screenWidth-dialogWidth)/2+ig.getScrollLeft();var newTop=(screenHeight-dialogHeight)/2+ig.getScrollTop();if(newTop<0){newTop=0;}
if(newLeft<0){newLeft=0;}
this.elm.style.left=newLeft+"px";this.elm.style.top=newTop+"px";}
this.igInitialPosition=1;}else{this.igInitialPosition=0;}
if(initialState==ig.dw.STATE_NORMAL){this.igState=initialState;this._show();ig.dw.resizeInternals(this);}else
if(initialState==ig.dw.STATE_MINIMIZED){this._show();this._toMin();this.igState=ig.dw.STATE_MINIMIZED;}else
if(initialState==ig.dw.STATE_MAXIMIZED){this._show();this._toMax();this.igState=ig.dw.STATE_MAXIMIZED;}else
if(initialState==ig.dw.STATE_HIDDEN){this.igState=ig.dw.STATE_HIDDEN;this._hide();}
if(this.igModal&&initialState!=ig.dw.STATE_HIDDEN){this._fixTabIndexes(true,false);}
this._initClientEventsForObject(this,clientSideListeners);var args=this.__raiseClientEvent("Initialize");};IgDialogWindow.prototype.__raiseClientEvent=function(clientEventName,evntArgs,eventArgsParams){var args=null;var clientEvent=this._clientEvents[clientEventName];if(clientEvent!=null){if(evntArgs==null){args=new $IG.EventArgs();}else{args=new evntArgs(eventArgsParams);}
args=this._raiseSenderClientEvent(this,clientEvent,args);}
return args;};IgDialogWindow.prototype._maxHeight=function(){var scrollableHeight;var clientHeight=ig.getClientHeight();if((ig.DOC_MODE==ig.STRICT_MODE)&&(document.documentElement&&document.documentElement.scrollHeight))
{scrollableHeight=document.documentElement.scrollHeight;}
else if((ig.DOC_MODE==ig.QUIRKS_MODE)&&(document.body&&document.body.scrollHeight))
{scrollableHeight=parseInt(document.body.scrollHeight);}
if(scrollableHeight!=clientHeight)
return Math.max(scrollableHeight,clientHeight);else
return clientHeight;};IgDialogWindow.prototype._show=function(){if(this.igModal&&ig.dw.modalLayer!=null){ig.dw.modalLayer.style.visibility="visible";ig.dw.modalLayer.style.left="0px";ig.dw.modalLayer.style.top="0px";ig.dw.modalLayer.style.width=ig.getClientWidth()+"px";ig.dw.modalLayer.style.height=this._maxHeight()+"px";}
this.elm.style.visibility="visible";var elContent=ig.getElementById(this.elm.id+"_c");if(elContent!=null){elContent.style.display="block";elContent.style.visibility="visible";}
var elResizer=ig.getElementById(this.elm.id+"_r");if(elResizer!=null){elResizer.style.display="block";elResizer.style.visibility="visible";}
if(this.igModal){this._fixTabIndexes(true,false);}};IgDialogWindow.prototype._hide=function(){this.elm.style.visibility="hidden";var elContent=ig.getElementById(this.elm.id+"_c");if(elContent!=null){elContent.style.display="none";elContent.style.visibility="hidden";}
var elResizer=ig.getElementById(this.elm.id+"_r");if(elResizer!=null){elResizer.style.display="none";elResizer.style.visibility="hidden";}
if(this.igModal&&ig.dw.modalLayer!=null){var oneVisibleModal=false;for(i=0;i<ig.dw.dialogWindows.length;i++){if(ig.dw.dialogWindows[i].igModal){if(ig.dw.dialogWindows[i].elm.style.visibility!="hidden"){oneVisibleModal=true;break;}}}
if(!oneVisibleModal){ig.dw.modalLayer.style.visibility="hidden";}}
if(this.igModal){this._fixTabIndexes(false,false);}};IgDialogWindow.prototype.get_moveable=function(){return this.igMovable;};IgDialogWindow.prototype.get_maintainLocationOnScroll=function(){return this.igMaintainLocationOnScroll;};IgDialogWindow.prototype.get_initialLocation=function(){return this.igInitialPosition;};IgDialogWindow.prototype.set_initialLocation=function(initialPosition){this.igInitialPosition=initialPosition;};IgDialogWindow.prototype.get_windowState=function(){return this.igState;};IgDialogWindow.prototype.get_left=function(){return this.elm.style.left;};IgDialogWindow.prototype.set_left=function(value){this.elm.style.left=value;};IgDialogWindow.prototype.get_top=function(){return this.elm.style.top;};IgDialogWindow.prototype.set_top=function(value){this.elm.style.top=value;};IgDialogWindow.prototype.get_width=function(){return this.getWidth();};IgDialogWindow.prototype.set_width=function(value){this.elm.style.width=value;ig.dw.resizeInternals(this);};IgDialogWindow.prototype.get_height=function(){return this.getHeight();};IgDialogWindow.prototype.set_height=function(value){this.setStyle("height",value);ig.dw.resizeInternals(this);};IgDialogWindow.prototype.set_windowState=function(newState){if(newState==this.igState)return;if(newState==ig.dw.STATE_NORMAL){var normCanceled=false;var args=this._raiseClientEvent("StateChanging","WindowStateCancel",null,null,this.igState,ig.dw.STATE_NORMAL);normCanceled=args!=null&&args.get_cancel();if(!normCanceled){if(this.igState==ig.dw.STATE_HIDDEN){this._show();}
if(this.igState==ig.dw.STATE_MINIMIZED){ig.dw.setImageAltMode(this.elm.id+"_minBox",false);ig.dw.setImageState(this.elm.id+"_minBox",ig.dw.IMG_STATE_NORMAL);this.setStyle("width",this.igRestoreWidth);this.setStyle("height",this.igRestoreHeight);var elContent=ig.getElementById(this.elm.id+"_c");if(elContent!=null){elContent.style.display="block";elContent.style.visibility="visible";}
var elResizer=ig.getElementById(this.elm.id+"_r");if(elResizer!=null){elResizer.style.display="block";elResizer.style.visibility="visible";}
ig.dw.resizeInternals(this);}else
if(this.igState==ig.dw.STATE_MAXIMIZED){ig.dw.setImageAltMode(this.elm.id+"_maxBox",false);ig.dw.setImageState(this.elm.id+"_maxBox",ig.dw.IMG_STATE_NORMAL);this.elm.style.left=this.igRestoreLeft;this.elm.style.top=this.igRestoreTop;this.setStyle("width",this.igRestoreWidth+"px");this.setStyle("height",this.igRestoreHeight+"px");ig.dw.resizeInternals(this);}
this.igStateOld=this.igState;this.igState=ig.dw.STATE_NORMAL;args=this._raiseClientEvent("StateChanged","WindowStatePostBack",null,this.igPostBackOnStateChange?1:0,this.igStateOld,this.igState);if((args==null&&this.igPostBackOnStateChange)||(args!=null&&args.get_postBack()==1)){var compId=this.elm.id;var evtName=ig.dw.EVENT_SS_STATE_CHANGED;var evtArgs="os:"+this.igStateOld+";ns:"+this.igState+";";ig.smartSubmit(compId,evtName,evtArgs,null,null);}}}else
if(newState==ig.dw.STATE_MINIMIZED){var minCanceled=false;var args=this._raiseClientEvent("StateChanging","WindowStateCancel",null,null,this.igState,ig.dw.STATE_MINIMIZED);minCanceled=args!=null&&args.get_cancel();if(!minCanceled){if(this.igState==ig.dw.STATE_HIDDEN){this._show();}
this._toMin();this.igStateOld=this.igState;this.igState=ig.dw.STATE_MINIMIZED;args=this._raiseClientEvent("StateChanged","WindowStatePostBack",null,this.igPostBackOnStateChange?1:0,this.igStateOld,this.igState);if((args==null&&this.igPostBackOnStateChange)||(args!=null&&args.get_postBack()==1)){var compId=this.elm.id;var evtName=ig.dw.EVENT_SS_STATE_CHANGED;var evtArgs="os:"+this.igStateOld+";ns:"+this.igState+";";ig.smartSubmit(compId,evtName,evtArgs,null,null);}}}else
if(newState==ig.dw.STATE_MAXIMIZED){var maxCanceled=false;var args=this._raiseClientEvent("StateChanging","WindowStateCancel",null,null,this.igState,ig.dw.STATE_MAXIMIZED);maxCanceled=args!=null&&args.get_cancel();if(!maxCanceled){if(this.igState==ig.dw.STATE_HIDDEN){this._show();}
this._toMax();this.igStateOld=this.igState;this.igState=ig.dw.STATE_MAXIMIZED;args=this._raiseClientEvent("StateChanged","WindowStatePostBack",null,this.igPostBackOnStateChange?1:0,this.igStateOld,this.igState);if((args==null&&this.igPostBackOnStateChange)||(args!=null&&args.get_postBack()==1)){var compId=this.elm.id;var evtName=ig.dw.EVENT_SS_STATE_CHANGED;var evtArgs="os:"+this.igStateOld+";ns:"+this.igState+";";ig.smartSubmit(compId,evtName,evtArgs,null,null);}}}else
if(newState==ig.dw.STATE_HIDDEN){var closedCanceled=false;var args=this._raiseClientEvent("StateChanging","WindowStateCancel",null,null,this.igState,ig.dw.STATE_HIDDEN);closedCanceled=args!=null&&args.get_cancel();if(!closedCanceled){this._hide();this.igStateOld=this.igState;this.igState=ig.dw.STATE_HIDDEN;args=this._raiseClientEvent("StateChanged","WindowStatePostBack",null,this.igPostBackOnStateChange?1:0,this.igStateOld,this.igState);if((args==null&&this.igPostBackOnStateChange)||(args!=null&&args.get_postBack()==1)){var compId=this.elm.id;var evtName=ig.dw.EVENT_SS_STATE_CHANGED;var evtArgs="os:"+this.igStateOld+";ns:"+this.igState+";";ig.smartSubmit(compId,evtName,evtArgs,null,null);}}}};IgDialogWindow.prototype._toMin=function(){ig.dw.setImageAltMode(this.elm.id+"_minBox",true);ig.dw.setImageState(this.elm.id+"_minBox",ig.dw.IMG_STATE_NORMAL);ig.dw.setImageAltMode(this.elm.id+"_maxBox",false);ig.dw.setImageState(this.elm.id+"_maxBox",ig.dw.IMG_STATE_NORMAL);if(this.igState==ig.dw.STATE_NORMAL){this.igRestoreLeft=this.elm.style.left;this.igRestoreTop=this.elm.style.top;this.igRestoreWidth=this.getWidth();this.igRestoreHeight=this.getHeight();}
if(this.igState==ig.dw.STATE_MAXIMIZED){this.elm.style.left=this.igRestoreLeft;this.elm.style.top=this.igRestoreTop;}
this.setStyle("width",this.igMinimizedWidth);var elHeader=ig.getElementById(this.elm.id+"_h");if(elHeader!=null){this.setStyle("height",elHeader.style.height);}
var elContent=ig.getElementById(this.elm.id+"_c");if(elContent!=null){elContent.style.display="none";elContent.style.visibility="hidden";}
var elResizer=ig.getElementById(this.elm.id+"_r");if(elResizer!=null){elResizer.style.display="none";elResizer.style.visibility="hidden";}};IgDialogWindow.prototype._toMax=function(){ig.dw.setImageAltMode(this.elm.id+"_minBox",false);ig.dw.setImageState(this.elm.id+"_minBox",ig.dw.IMG_STATE_NORMAL);ig.dw.setImageAltMode(this.elm.id+"_maxBox",true);ig.dw.setImageState(this.elm.id+"_maxBox",ig.dw.IMG_STATE_NORMAL);if(this.igState==ig.dw.STATE_NORMAL){this.igRestoreLeft=this.elm.style.left;this.igRestoreTop=this.elm.style.top;this.igRestoreWidth=this.getWidth();this.igRestoreHeight=this.getHeight();}else
if(this.igState==ig.dw.STATE_MINIMIZED){this.igRestoreLeft=this.elm.style.left;this.igRestoreTop=this.elm.style.top;var elContent=ig.getElementById(this.elm.id+"_c");if(elContent!=null){elContent.style.display="block";elContent.style.visibility="visible";}
var elResizer=ig.getElementById(this.elm.id+"_r");if(elResizer!=null){elResizer.style.display="block";elResizer.style.visibility="visible";}}
this.setPosition(0,0);var clientWidth=ig.getClientWidth()-this.getBorder("width")-this.getPadding("width");var clientHeight=ig.getClientHeight()-this.getBorder("height")-this.getPadding("height");this.setStyle("width",clientWidth+"px");this.setStyle("height",clientHeight+"px");ig.dw.resizeInternals(this);};IgDialogWindow.prototype._fixTabIndexes=function(on,max,doc){var elem,i=-1,stop=this._stop,tabs=this._oldTabs,elem0=this.elm;if(on==this._fixTabOn)
return;this._fixTabOn=on;if(!on)
{if(!tabs)
return;for(var i=0;i<tabs.length;i++)
tabs[i].elem.tabIndex=tabs[i].i;if(stop)
stop.style.display='none';return;}
if(!tabs)
{tabs=this._oldTabs=new Array();this._tags=['INPUT','SELECT','TEXTAREA','BUTTON','A','IFRAME','AREA','DIV','EMBED','OBJECT'];}
else
Array.clear(tabs);if(!stop&&!max)
{this._stop=stop=document.createElement('INPUT');var style=stop.style;style.padding=style.border=style.width=style.height='0px';style.position='absolute';stop.tabIndex=1000;elem0.insertBefore(stop,elem0.firstChild);stop.onfocus=this._onFoc;stop._me=this;}
if(stop)
stop.style.display='';if(!doc)
doc=document;var lenAll,lenMy,ti1=0,ti2=0,j=i=0,tags=this._tags;for(var t=0;t<tags.length;t++)
{var elemsAll=doc.getElementsByTagName(tags[t]);if((lenAll=elemsAll?elemsAll.length:0)<1)
continue;var elemsMy=this.elm.getElementsByTagName(tags[t]);lenMy=elemsMy?elemsMy.length:0;while(lenAll-->0)
{elem=elemsAll[lenAll];j=lenMy;while(j-->0)if(elem==elemsMy[j])
{if(elem==stop||elem.disabled||elem.type=='hidden')
break;var ti=elem.tabIndex;if(!ti)
ti=0;else if((ti=parseInt(ti))<0)
break;if(t<5||ti>0)
{if(!this._anyTab1)
this._anyTab1=elem;else if(!this._anyTab2)
this._anyTab2=elem;if(!this._minTabI)
{this._minTabI=elem;ti1=ti;}
if(ti1>ti)
{this._minTabI=elem;ti1=ti;}}
if(ti<1)
break;if(ti>=ti2)
{ti2=ti;this._maxTabI=elem;}
break;}
if(j<0)
{tabs[i++]={elem:elem,i:elem.tabIndex};elem.tabIndex=-1;}}}
if(stop&&ti2>=stop.tabIndex)
stop.tabIndex=ti2+1;};IgDialogWindow.prototype._onFoc=function(e){if(this._me)
this._me._setTabElem();};IgDialogWindow.prototype._setTabElem=function(elem,foc){var tab=this._lastTab;if((!tab&&!foc)||this._lastTabTime+100<(new Date()).getTime())
return;if(this._isChild(this._targetElement,elem))
return;if(this._shiftKey)
{if(!this._minTab2)
this._minTab2=tab;}
else if(!this._maxTab2)
this._maxTab2=tab;this._tabFoc(null,foc);};ig.augment(IgDialogWindow,IgUIComponent);function IgDialogWindowResizer(e){this.IgUIComponent(e);};IgDialogWindowResizer.prototype.init=function(parentDw){this.elm.igParentDw=parentDw;};IgDialogWindowResizer.prototype.getResizeMode=function(left,bottom,right,top){var dwJsNode=ig.dw.getDwJsNodeById(this.elm.igParentDw);if(dwJsNode!=null){if(dwJsNode.igState==ig.dw.STATE_NORMAL){return 6;}else{return 0;}}else{return 6;}};IgDialogWindowResizer.prototype.doResizeBegin=function(){ig.dw.activate(this.elm.igParentDw);ig.dw.resizeStartW=ig.toFloat(ig.dw.activeDialogWindow.getWidth());ig.dw.resizeStartH=ig.toFloat(ig.dw.activeDialogWindow.getHeight());ig.dw.resizeStartX=ig.ui.x;ig.dw.resizeStartY=ig.ui.y;};IgDialogWindowResizer.prototype.checkResizeWidth=function(newWidth,jsNode){var result=true;if(jsNode.igResizerMinWidth>0){if(newWidth<jsNode.igResizerMinWidth){result=false;}}
if(jsNode.igResizerMaxWidth>0){if(newWidth>jsNode.igResizerMaxWidth){result=false;}}
return result;};IgDialogWindowResizer.prototype.checkResizeHeight=function(newHeight,jsNode){var result=true;if(jsNode.igResizerMinHeight>0){if(newHeight<jsNode.igResizerMinHeight){result=false;}}
if(jsNode.igResizerMaxHeight>0){if(newHeight>jsNode.igResizerMaxHeight){result=false;}}
return result;};IgDialogWindowResizer.prototype.doResizeMove=function(evt){var activeJsNode=ig.dw.activeDialogWindow;var activeDomNode=ig.dw.activeDialogWindow.elm;if(activeJsNode.igState==ig.dw.STATE_MAXIMIZED)return;if(activeJsNode.igResizerEnabled){var oldParentWidth=ig.toFloat(activeJsNode.getWidth());var oldParentHeight=ig.toFloat(activeJsNode.getHeight());var newParentWidth=ig.dw.resizeStartW+ig.ui.x-ig.dw.resizeStartX;var newParentHeight=ig.dw.resizeStartH+ig.ui.y-ig.dw.resizeStartY;var newWidthToBeSet=this.checkResizeWidth(newParentWidth,activeJsNode);var newHeightToBeSet=this.checkResizeHeight(newParentHeight,activeJsNode);if(newWidthToBeSet||newHeightToBeSet){var args=activeJsNode._raiseClientEvent("Resizing","Resize",evt,null,newParentWidth,newParentHeight,oldParentWidth,oldParentHeight);var eventCanceled=args!=null&&args.get_cancel();if(!eventCanceled){if(newWidthToBeSet){activeJsNode.setStyle("width",newParentWidth+"px");}
if(newHeightToBeSet){activeJsNode.setStyle("height",newParentHeight+"px");}
ig.dw.resizeInternals(activeJsNode);ig.dw.resizeOccured=true;}}}};IgDialogWindowResizer.prototype.doResizeEnd=function(evt){var activeJsNode=ig.dw.activeDialogWindow;var activeDomNode=ig.dw.activeDialogWindow.elm;var newParentWidth=ig.dw.resizeStartW+ig.ui.x-ig.dw.resizeStartX;var newParentHeight=ig.dw.resizeStartH+ig.ui.y-ig.dw.resizeStartY;var newWidthToBeSet=this.checkResizeWidth(newParentWidth,activeJsNode);var newHeightToBeSet=this.checkResizeHeight(newParentHeight,activeJsNode);if(newWidthToBeSet||newHeightToBeSet){var args=null;if(ig.dw.resizeOccured){args=activeJsNode._raiseClientEvent("Resized","Resize",evt,activeJsNode.igPostBackOnResize?1:0,newParentWidth,newParentHeight,ig.dw.resizeStartW,ig.dw.resizeStartH);ig.dw.resizeOccured=false;if(args!=null&&args.get_cancel()){activeJsNode.setStyle("width",ig.dw.resizeStartW+"px");activeJsNode.setStyle("height",ig.dw.resizeStartH+"px");ig.dw.resizeInternals(activeJsNode);}
if((args==null&&activeJsNode.igPostBackOnResize)||(args!=null&&args.get_postBack()==1)){var compId=activeDomNode.id;var evtName=ig.dw.EVENT_SS_RESIZED;var evtArgs="ow:"+ig.dw.resizeStartW+";oh:"+ig.dw.resizeStartH;if(newWidthToBeSet){evtArgs=evtArgs+";w:"+newParentWidth;}else{evtArgs=evtArgs+";w:"+ig.dw.resizeStartW;}
if(newHeightToBeSet){evtArgs=evtArgs+";h:"+newParentHeight;}else{evtArgs=evtArgs+";h:"+ig.dw.resizeStartH;}
ig.smartSubmit(compId,evtName,evtArgs,null,null);}}}
ig.dw.resizeOldX=-1;ig.dw.resizeOldY=-1;};ig.augment(IgDialogWindowResizer,IgUIComponent);ig.dw.init();}
$IG.WindowStateCancelEventArgs=function(){$IG.WindowStateCancelEventArgs.initializeBase(this);}
$IG.WindowStateCancelEventArgs.prototype={get_currentWindowState:function(){return this._props[2];},get_newWindowState:function(){return this._props[3];}}
$IG.WindowStateCancelEventArgs.registerClass("Infragistics.Web.UI.WindowStateCancelEventArgs",$IG.CancelEventArgs);$IG.WindowStatePostBackEventArgs=function(){$IG.WindowStatePostBackEventArgs.initializeBase(this);}
$IG.WindowStatePostBackEventArgs.prototype={get_currentWindowState:function(){return this._props[2];},get_newWindowState:function(){return this._props[3];}}
$IG.WindowStatePostBackEventArgs.registerClass("Infragistics.Web.UI.WindowStatePostBackEventArgs",$IG.PostBackEventArgs);}