// (c) 2008 Infragistics - Do NOT modify the content of this file
// Version 9.2.20092.1000

if(ig){if(!ig.ui){function IgUI(){this.state=0;this.STATE_IDLE=0;this.STATE_DRAG=1;this.STATE_RESIZE=2;this.UNDEFINED_NUMBER=-10000;this.COMMAND_MOUSE_DOWN=0;this.COMMAND_MOUSE_MOVE=1;this.COMMAND_MOUSE_UP=2;this.COMMAND_MOUSE_ENTER=3;this.COMMAND_MOUSE_LEAVE=4;this.COMMAND_CLICK=5;this.COMMAND_KEYDOWN=6;this.COMMAND_KEYPRESS=7;this.mouseOverElement=null;this.mouseOverUIElement=null;this.mouseDownX=0;this.mouseDownY=0;this.mouseDownTarget=null;this.dragShadow=null;this.ACTION_DRAG=1;this.PROP_FLOATING="ofltng";this.PROP_DRAGGABLE="odrggbl";this.PROP_DRAGGABLE_VIA_HANDLE="odrggblvh";this.PROP_DRAG_HANDLE="odrghdl";this.PROP_DRAG_MODE="odrgmd";this.PROP_RESIZABLE="orszbl";this.PROP_SORTABLE="osrtbl";this.PROP_MOVABLE="omvbl";this.DRAG_MODE_DRAG="drag";this.DRAG_MODE_MOVE="move";this.DRAG_SHADOW="oddds";this.BOX_MARGIN=0;this.BOX_BORDER=1;this.BOX_PADDING=2;this.BOX_CONTENT=3;this.COMPAT_BACK=0;this.COMPAT_CSS1=1;this.selectedNodes=new ig.ArrayList();this.document=null;this.dragMode=null;this.dragSources=new ig.ArrayList();this.dropTarget=null;this.hoveredElement=null;this.activeComponent=null;this.x=null;this.y=null;this.lastX=null;this.lastY=null;this.lastX=null;this.lastY=null;this.isMouseDown=false;this.alignColumns=function(tables,cws){var rowWidth=0;if(ig.isArray(tables)&&tables.length>1&&ig.isArray(cws)){for(var i=0;i<cws.length;i++){this.setColWidth(tables,i,cws[i]);rowWidth=rowWidth+cws[i];}}
return rowWidth;};this.clearSelection=function(){if(document.selection&&document.selection.empty){document.selection.empty();}
else{if(window.getSelection&&window.getSelection().removeAllRanges){window.getSelection().removeAllRanges();}}};this.createDragEventArg=function(){var o=new Object();o.x=this.x;o.y=this.y;return o;};this.getColCount=function(table){var r=0;if(!ig.isNull(table)){var tr=table.rows[0];if(!ig.isNull(tr)){r=tr.cells.length;}}
return r;};this.getDocument=function(){var r=ig.document;if(ig.isNull(r)){r=document;}
return r;};this.getDocumentBody=function(){var r=ig.ui.getDocument().body;if(ig.isNull(r)){r=ig.ui.getDocument().getElementsByTagName("body")[0];}
return r;};this.getMaxColWidths=function(table){var cws=new Array();if(!ig.isNull(table)){for(var i=0;i<table.rows.length;i++){var row=table.rows[i];for(var j=0;j<row.cells.length;j++){var cell=ig.getUIElementById(row.cells[j]);var cs=cell.elm.colSpan;if(cs<=1){var cw=cell.getWidth();cw-=cell.getBorder("left");cw-=cell.getBorder("right");if(j>=cws.length){cws[j]=cw;}
else{if(cw>cws[j]){cws[j]=cw;}}}}}}
return cws;};this.getColumn=function(table,i){var result=null;if(!ig.isNull(table)){var r=table.rows[0];if(!ig.isNull(r)){result=ig.getUIElementById(r.cells[i]);}}
return result;};this.getRow=function(table,i){var result=null;if(!ig.isNull(table)){var r=table.rows[i];if(!ig.isNull(r)){result=ig.getUIElementById(r);}}
return result;};this.doDragStart=function(e){if(ig.ui.isMouseDown){if(ig.ui.selectedNodes.size()>0){var fn=ig.ui.selectedNodes.get(0);if(!ig.isNull(fn)){if(fn.getDragMode()===ig.ui.DRAG_MODE_MOVE){fn.dragDrop();}
else{var deltaX=Math.abs(ig.ui.x-ig.ui.mouseDownX);var deltaY=Math.abs(ig.ui.y-ig.ui.mouseDownY);if(deltaX>10||deltaY>10){for(var i=0;i<ig.ui.selectedNodes.size();i++){var node=ig.ui.selectedNodes.get(i);if(!ig.isNull(node)){node.dragDrop();}}}}}}}};this.doDragMove=function(e){for(var i=0;i<this.dragSources.size();i++){var n=ig.getUIElementById(this.dragSources.get(i));n.onDrag(e);}
if(!ig.isNull(this.dropTarget)){var dea=ig.ui.createDragEventArg();this.dropTarget.onDragOver(dea);}};this.doDragEnd=function(e){for(var i=0;i<this.dragSources.size();i++){var n=ig.getUIElementById(this.dragSources.get(i));n.onDragEnd();}
if(!ig.isNull(ig.ui.dropTarget)){ig.ui.dropTarget.hideDropCaret();var dea=ig.ui.createDragEventArg();ig.ui.dropTarget.onDrop(dea,ig.ui.dragSources);}
ig.ui.dropTarget=null;this.dragSources.clear();this.action=null;this.dragMode=null;};this.focus=function(elm){elm=ig.getElementById(elm);if(!ig.isNull(elm)){if(elm.focus){elm.focus();}}};this.getHoveredElement=function(){return this.hoveredElement;};this.getDraggableTarget=function(n){var r=null;var t=ig.getTargetUIElement(n);if(!ig.isNull(t)){if(t.isDraggable()){if(!(t.isDraggableViaHandle()&&!t.isDragHandle())){r=t;}}
else{var p=ig.getTargetUIElement(t.elm.parentNode);if(!ig.isNull(p)){if(p.isDraggable()){if(!(p.isDraggableViaHandle()&&!p.isDragHandle())){r=p;}
else{if(!(p.isDraggableViaHandle()&&!t.isDragHandle())){r=p;}}}}}}
return r;};this.getResizeMode=function(target,x,y){if(!target){return 0;}
var posn=target.getPagePosition();var size=target.getSize();var left=x<(posn.x+10);var bottom=y>(posn.y+size.height-10);var right=x>(posn.x+size.width-10);var top=y<(posn.y+10);return target.getResizeMode(left,bottom,right,top);};this.getResizableTarget=function(elm,x,y){var target=null;for(target=ig.getTargetUIElement(elm);target;target=ig.getTargetUIElement(target.elm.parentNode)){if(ig.ui.getResizeMode(target,x,y)!==0){return target;}}
return null;};this.init=function(){ig.factory.addClass("Link",IgLink);ig.factory.addClass("HeaderLink",IgHeaderLink);ig.factory.addClass("PagerLink",IgPagerLink);ig.factory.addClass("UIComponent",IgUIComponent);ig.factory.addClass("UIElement",IgUIElement);ig.factory.addClass("Popup",IgPopup);ig.addEventListener(document,ig.event.EVENT_MOUSEDOWN,ig.ui.onMouseDown,true);ig.addEventListener(document,ig.event.EVENT_MOUSEMOVE,ig.ui.onMouseMove,false);ig.addEventListener(document,ig.event.EVENT_MOUSEOVER,ig.ui.onMouseOver,false);ig.addEventListener(document,ig.event.EVENT_MOUSEUP,ig.ui.onMouseUp,false);ig.addEventListener(document,ig.event.EVENT_CLICK,ig.ui.onClick,false);ig.addEventListener(document,ig.event.EVENT_DOUBLECLICK,ig.ui.onDoubleClick,false);ig.addEventListener(document,ig.event.EVENT_KEYDOWN,ig.ui.onKeyDown,false);ig.addEventListener(document,ig.event.EVENT_KEYPRESS,ig.ui.onKeyPress,false);};this.getResizeCursor=function(resizeMode){var c=null;switch(resizeMode){case 0:c="default";break;case 1:c="w-resize";break;case 2:c="s-resize";break;case 4:c="e-resize";break;case 8:c="n-resize";break;case 3:c="sw-resize";break;case 9:c="nw-resize";break;case 6:c="se-resize";break;case 12:c="ne-resize";break;default:c="move";}
return c;};this.onIdleTransition=function(transition,evt){var target=null;switch(transition){case ig.ui.COMMAND_MOUSE_DOWN:if(!ig.isNull(ig.ui.resizeTarget)){evt.preventDefault();ig.ui.cancelClick=true;ig.ui.state=ig.ui.STATE_RESIZE;ig.ui.resizeTarget.doResizeBegin();return null;}
if(!ig.isNull(ig.ui.dragTarget)){ig.ui.cancelClick=false;ig.ui.state=ig.ui.STATE_DRAG;ig.ui.selectedNodes.add(ig.ui.dragTarget);ig.ui.doDragStart(evt);return null;}
return null;case ig.ui.COMMAND_MOUSE_ENTER:target=ig.getTargetUIElement(evt.target);if(!ig.isNull(target)&&target.isEnabled(target)){target.onMouseEnter(evt);}
return null;case ig.ui.COMMAND_MOUSE_MOVE:ig.ui.resizeTarget=ig.ui.getResizableTarget(evt.target,evt.pageX,evt.pageY);ig.ui.dragTarget=null;if(!ig.isNull(ig.ui.resizeTarget)){ig.ui.resizeMode=ig.ui.getResizeMode(ig.ui.resizeTarget,evt.pageX,evt.pageY);ig.ui.resizeTarget.updateCursor();return null;}
ig.ui.dragTarget=ig.ui.getDraggableTarget(evt.target);if(!ig.isNull(ig.ui.dragTarget)){ig.ui.dragTarget.repaint();ig.ui.dragTarget.updateCursor();return null;}
return null;case ig.ui.COMMAND_MOUSE_LEAVE:target=ig.getTargetUIElement(evt.target);if(!ig.isNull(target)&&target.isEnabled()){ig.ui.resizeTarget=null;ig.ui.dragTarget=null;document.body.style.cursor="auto";target.onMouseLeave(evt);}
return null;case ig.ui.COMMAND_CLICK:target=ig.getTargetUIElement(evt.target);if(!ig.isNull(target)){if(target.isEnabled()){return target.onClick(evt);}
else{evt.preventDefault();}}
return null;case ig.ui.COMMAND_KEYDOWN:target=ig.getTargetUIElement(evt.target);if(!ig.isNull(target)){if(target.isEnabled()||(evt.keyCode===evt.KEY_TAB)){return target.onKeyDown(evt);}
else{evt.preventDefault();}}
if(!ig.isNull(ig.ui.activeComponent)){ig.ui.activeComponent.onKeyDown(evt);}
return null;case ig.ui.COMMAND_KEYPRESS:target=ig.getTargetUIElement(evt.target);if(!ig.isNull(target)){if(target.isEnabled()||(evt.keyCode===evt.KEY_TAB)){return target.onKeyPress(evt);}
else{evt.preventDefault();}}
if(!ig.isNull(ig.ui.activeComponent)){ig.ui.activeComponent.onKeyPress(evt);}
return null;case ig.ui.COMMAND_DOUBLECLICK:target=ig.getTargetUIElement(evt.target);if(!ig.isNull(target)){if(target.isEnabled()){return target.onDoubleClick(evt);}
else{evt.preventDefault();}}
return null;default:break;}
return null;};this.onDragTransition=function(transition,evt){var ret=null;switch(transition){case ig.ui.COMMAND_MOUSE_MOVE:if(ig.ui.action===ig.ui.ACTION_DRAG){return ig.ui.doDragMove(evt);}
else{return ig.ui.doDragStart(evt);}
break;case ig.ui.COMMAND_MOUSE_UP:ig.ui.state=ig.ui.STATE_IDLE;document.body.style.cursor="auto";if(ig.ui.action===ig.ui.ACTION_DRAG){ig.ui.doDragEnd(evt);ig.ui.cancelClick=true;}
return null;case ig.ui.COMMAND_MOUSE_ENTER:if(ig.ui.action===ig.ui.ACTION_DRAG){var target=ig.getTargetUIElement(evt.target);if(!ig.isNull(target)&&target.isDragSourceAccepted(ig.ui.dragSources)){ig.ui.dropTarget=target;ig.ui.dropTarget.onDragEnter(ig.ui.createDragEventArg());}}
return null;case ig.ui.COMMAND_MOUSE_LEAVE:if(ig.ui.action===ig.ui.ACTION_DRAG){if(!ig.isNull(ig.ui.dropTarget)){ig.ui.dropTarget.onDragLeave(ig.ui.createDragEventArg());ig.ui.dropTarget=null;}}
return null;default:break;}
return null;};this.onResizeTransition=function(transition,evt){evt.preventDefault();switch(transition){case ig.ui.COMMAND_MOUSE_MOVE:ig.ui.resizeTarget.doResizeMove(evt);break;case ig.ui.COMMAND_MOUSE_UP:ig.ui.resizeTarget.doResizeEnd(evt);ig.ui.state=ig.ui.STATE_IDLE;document.body.style.cursor="auto";break;case ig.ui.COMMAND_KEYDOWN:ig.ui.resizeTarget.doResizeStop();ig.ui.state=ig.ui.STATE_IDLE;document.body.style.cursor="auto";break;default:break;}
return null;};this.onStateTransition=function(transition,evt){switch(ig.ui.state){case ig.ui.STATE_IDLE:return this.onIdleTransition(transition,evt);case ig.ui.STATE_RESIZE:return this.onResizeTransition(transition,evt);case ig.ui.STATE_DRAG:return this.onDragTransition(transition,evt);default:return null;}};this.onClick=function(e){if(ig.ui.cancelClick){ig.ui.cancelClick=false;return false;}
return ig.ui.onStateTransition(ig.ui.COMMAND_CLICK,ig.toEvent(e));};this.onDoubleClick=function(e){return ig.ui.onStateTransition(ig.ui.COMMAND_DOUBLECLICK,ig.toEvent(e));};this.onKeyDown=function(e){return ig.ui.onStateTransition(ig.ui.COMMAND_KEYDOWN,ig.toEvent(e));};this.onKeyPress=function(e){return ig.ui.onStateTransition(ig.ui.COMMAND_KEYPRESS,ig.toEvent(e));};this.onMouseOver=function(e){var evt=ig.toEvent(e);var mouseOverElement=evt.target;var mouseOverUIElement=ig.getTargetUIElement(mouseOverElement);if(!ig.isNull(mouseOverUIElement)&&mouseOverUIElement.equals(ig.ui.mouseOverUIElement)){return null;}
if(!ig.isNull(ig.ui.mouseOverElement)){evt.target=ig.ui.mouseOverElement;ig.ui.onStateTransition(ig.ui.COMMAND_MOUSE_LEAVE,evt);}
ig.ui.mouseOverElement=mouseOverElement;ig.ui.mouseOverUIElement=mouseOverUIElement;if(!ig.isNull(ig.ui.mouseOverElement)){evt.target=ig.ui.mouseOverElement;ig.ui.onStateTransition(ig.ui.COMMAND_MOUSE_ENTER,evt);}
return null;};this.onMouseDown=function(e){var evt=ig.toEvent(e);ig.ui.mouseDownX=evt.pageX;ig.ui.mouseDownY=evt.pageY;ig.ui.isMouseDown=true;ig.ui.selectedNodes.clear();ig.ui.setActiveComponent(null);return ig.ui.onStateTransition(ig.ui.COMMAND_MOUSE_DOWN,evt);};this.onMouseMove=function(e){var evt=ig.toEvent(e);ig.ui.x=evt.pageX;ig.ui.y=evt.pageY;var ret=ig.ui.onStateTransition(ig.ui.COMMAND_MOUSE_MOVE,evt);ig.ui.lastX=evt.pageX;ig.ui.lastY=evt.pageY;return ret;};this.onMouseUp=function(e){return ig.ui.onStateTransition(ig.ui.COMMAND_MOUSE_UP,ig.toEvent(e));};this.onScroll=function(e){var evt=ig.toEvent(e);var t=ig.getTargetUIElement(evt.target);if(!ig.isNull(t)){if(t.isEnabled()){t.onScroll();}}};this.onScrollTimer=function(e){var evt=ig.toEvent(e);var t=ig.getTargetUIElement(evt.target);if(!ig.isNull(t)){if(t.isEnabled()){if(!ig.NaES(t.getAttribute("igsip"))){t.setAttribute("igsip","true");window.setTimeout("ig.ui.onScrollTimer2(\""+t.elm.id+"\")",100);}}}};this.onScrollTimer2=function(id){var t=ig.getUIElementById(id);if(!ig.isNull(t)){if(ig.NaES(t.getAttribute("igsip"))){t.onScroll();t.setAttribute("igsip","");}}};this.setColWidth=function(tables,ci,w){if(!ig.isNull(tables)){for(var i=0;i<tables.length;i++){var col=this.getColumn(tables[i],ci);if(!ig.isNull(col)){col.setSize(w);}}}};this.setHoveredElement=function(e){var pe=this.getHoveredElement();this.hoveredElement=e;if(!ig.isNull(pe)){pe.repaint();}
if(!ig.isNull(e)){e.repaint();}};this.toBoxingModelIndex=function(bm){var r=-1;if(bm=="margin-box"){r=ig.ui.BOX_MARGIN;}
else if(bm=="border-box"){r=ig.ui.BOX_BORDER;}
else if(bm=="padding-box"){r=ig.ui.BOX_PADDING;}
else if(bm=="content-box"){r=ig.ui.BOX_CONTENT;}
return r;};this.getActiveComponent=function(){return this.activeComponent;}
this.setActiveComponent=function(component){this.activeComponent=component;}}
ig.ui=new IgUI();function IgRect(x,y,width,height){this.x=ig.toFloat(x);this.y=ig.toFloat(y);this.width=ig.toFloat(width);this.height=ig.toFloat(height);}
function IgDomNode(e){this.elm=e;};IgDomNode.prototype.get_id=function(){if(this.elm){return this.elm.id;}
return null;};IgDomNode.prototype.addEventListener=function(anEvent,aListener,useCapture){ig.addEventListener(this.elm,anEvent,aListener,useCapture);};IgDomNode.prototype.clone=function(bkids){if(ig.isNull(bkids)){bkids=false;}
var cn=ig.getUIElementById(this.elm.cloneNode(bkids));cn.hide();var pn=this.elm.parentNode;pn.appendChild(cn.elm);return cn;};IgDomNode.prototype.createDragShadow=function(){var h=this.getOuterHtml();var w=this.getWidth()+4;if(this.elm.nodeName=="TD"||this.elm.nodeName=="TH"){h="<table width='"+w+"'><tr>"+h+"</tr></table>";}
if(this.elm.nodeName=="TR"){h="<table width='"+w+"'>"+h+"</table>";}
var d=new IgPopup(ig.ui.getDocument().createElement("div"));d.elm.innerHTML=h;d.setOpacity(0.8);ig.ui.getDocumentBody().appendChild(d.elm);this.elm.oddds=d.elm;return d;};IgDomNode.prototype.click=function(){};IgDomNode.prototype.remove=function(){var pn=this.elm.parentNode;if(!ig.isNull(pn)){pn.removeChild(this.elm);this.elm=null;}};IgDomNode.prototype.dragDrop=function(){if(ig.isNull(ig.ui.action)){ig.ui.clearSelection();ig.ui.action=ig.ui.ACTION_DRAG;ig.ui.dragMode=this.getDragMode();}
ig.ui.dragSources.add(this.elm);this.onDragStart();};IgDomNode.prototype.equals=function(n){return(!ig.isNull(n))&&(this.elm===n.elm);};IgDomNode.prototype.getAttribute=function(attrn){return ig.getAttribute(this.elm,attrn);};IgDomNode.prototype.getBorder=function(w){var s=0;if(ig.NaES(w)){if(w=="width"){s=this.getBorder("left")+this.getBorder("right");}
else if(w=="height"){s=this.getBorder("top")+this.getBorder("bottom");}
else{w="border-"+w+"-width";s=this.getStyleAsFloat(w);}}
return s;};IgDomNode.prototype.getChildUIElements=function(type){var r=new ig.ArrayList();var cn=this.elm.childNodes;for(var i=0;i<cn.length;i++){var c=cn[i];if(ig.getAttribute(c,"otype")==type){r.add(ig.getUIElementById(c));}}
return r;};IgDomNode.prototype.getStyle=function(p){var result=null;if(ig.NaES(p)){var pc=ig.camelize(p);result=this.elm.style[pc];if(!ig.NaES(result)){if(this.elm.currentStyle){result=this.elm.currentStyle[pc];}
else{var dv=ig.ui.getDocument().defaultView;if(!ig.isNull(dv)){var cs=dv.getComputedStyle(this.elm,"");if(!ig.isNull(cs)){result=cs.getPropertyValue(p);}}
else{if(this.elm.style.getPropertyValue){result=this.elm.style.getPropertyValue(p);}}}}}
return result;};IgDomNode.prototype.getStyleAsFloat=function(propName){return ig.toFloat(this.getStyle(propName));};IgDomNode.prototype.getStyleInline=function(p){var r=null;if(ig.NaES(p)){var pc=ig.camelize(p);r=this.elm.style[pc];}
return r;};IgDomNode.prototype.getDragMode=function(){var r=null;var p=ig.findAncestor(this.elm.parentNode,ig.PROP_TYPE,null,null);if(!ig.isNull(p)){r=p.getAttribute(ig.ui.PROP_DRAG_MODE);}
if(ig.isNull(r)){r=this.getAttribute(ig.ui.PROP_DRAG_MODE);}
if(ig.isNull(r)){r=ig.ui.DRAG_MODE_DRAG;}
return r;};IgDomNode.prototype.getResizeMode=function(left,bottom,right,top){return 0;};IgDomNode.prototype.doResizeBegin=function(){};IgDomNode.prototype.doResizeMove=function(evt){};IgDomNode.prototype.doResizeEnd=function(evt){};IgDomNode.prototype.deleteDragShadow=function(){var ds=this.getDragShadow();if(!ig.isNull(ds)){ds.removeNode();ds=null;this.elm.oddds=null;}};IgDomNode.prototype.getCompatMode=function(){var r=ig.ui.COMPAT_CSS1;if((ig.isIE)||(ig.isOpera)){var cm=ig.ui.getDocument()["compatMode"];if((cm=="BackCompat")||(cm=="QuirksMode")){r=ig.ui.COMPAT_BACK;}}
return r;};IgDomNode.prototype.getBoxingModel=function(){var r=ig.ui.BOX_CONTENT;if((ig.isIE)||(ig.isOpera)){if(this.getCompatMode()==ig.ui.COMPAT_BACK){r=ig.ui.BOX_BORDER;}}
else{r=this.getStyle("-moz-box-sizing");if(!ig.NaES(r)){r=this.getStyle("box-sizing");}
if(ig.NaES(r)){r=ig.ui.toBoxingModelIndex(r);}}
return r;};IgDomNode.prototype.getDragShadow=function(){var r=this.elm.oddds;if(!ig.isNull(r)){r=new IgPopup(r);}
return r;};IgDomNode.prototype.getMaxHeight=function(){var result=0;var tmpDisplay=this.getStyleInline("display");this.setStyle("display","block");var tmpVisibility=this.getStyleInline("visibility");this.setStyle("visibility","");var tmpHeight=this.getStyleInline("height");this.setStyle("height","");result=this.getHeight();this.setStyle("display",tmpDisplay);this.setStyle("visibility",tmpVisibility);this.setStyle("height",tmpHeight);return result;};IgDomNode.prototype.getOriginalCssProperty=function(propName){return this.getAttribute(propName);};IgDomNode.prototype.getOuterHtml=function(){var r=this.elm.outerHTML;if(!ig.NaES(r)){r="<"+this.elm.nodeName+" class='"+this.elm.className+"'>";r=r+this.elm.innerHTML+"</"+this.elm.nodeName+">";}
return r;};IgDomNode.prototype.getFirstChild=function(){var r=null;var childNodes=this.elm.childNodes;for(var i=0;i<childNodes.length;i++){if(childNodes[i].tagName){r=childNodes[i];break;}}
return ig.getUIElementById(r);};IgDomNode.prototype.getFirstTextElement=function(){var r=null;var childNodes=this.elm.childNodes;for(var i=0;i<childNodes.length;i++){var c=childNodes[i];if(!c.tagName){return c;}else{var t=ig.getUIElementById(c).getFirstTextElement();if(t!=null)
return t;}}
return null;};IgDomNode.prototype.getFirstLeaf=function(){var node=this.elm;while(node.firstChild!=null&&node.firstChild.tagName){node=node.firstChild}
return node;};IgDomNode.prototype.getForm=function(){return ig.findAncestor(this.elm,null,null,"FORM");};IgDomNode.prototype.getHeight=function(){return this.elm.offsetHeight;};IgDomNode.prototype.getId=function(){return this.elm.id;};IgDomNode.prototype.getMargin=function(w){var s=0;if(ig.NaES(w)){if(w=="width"){s=this.getMargin("left")+this.getMargin("right");}
else if(w=="height"){s=this.getMargin("top")+this.getMargin("bottom");}
else{w="margin-"+w;s=this.getStyleAsFloat(w);}}
return s;};IgDomNode.prototype.getLastChild=function(){var r=null;var childNodes=this.elm.childNodes;for(var i=childNodes.length-1;i>=0;i--){if(childNodes[i].tagName){r=childNodes[i];break;}}
return ig.getUIElementById(r);};IgDomNode.prototype.getPosition=function(){return{x:this.getStyleAsFloat("left"),y:this.getStyleAsFloat("top")};};IgDomNode.prototype.getOpacity=function(){var result=this.getStyleAsFloat("opacity");if(result==0){result=1.0;}
return result;};IgDomNode.prototype.getPadding=function(w){var s=0;if(ig.NaES(w)){if(w=="width"){s=this.getPadding("left")+this.getPadding("right");}
else if(w=="height"){s=this.getPadding("top")+this.getPadding("bottom");}
else{w="padding-"+w;s=this.getStyleAsFloat(w);}}
return s;};IgDomNode.prototype.getPagePosition=function(){var rect=new IgRect(0,0,0,0);var elm=this.elm;if(!ig.isNull(elm)){var curElm=elm;while(!ig.isNull(curElm)){rect.x=rect.x+curElm.offsetLeft;rect.y=rect.y+curElm.offsetTop;curElm=curElm.offsetParent;}
var sp=this.getScroll(true);rect.x=rect.x-sp.x;rect.y=rect.y-sp.y;}
return rect;};IgDomNode.prototype.getProperty=function(propName){var result=null;if(ig.NaES(propName)){var tmp="this.get"+ig.ucase(propName)+"()";result=eval(tmp);}
return result;};IgDomNode.prototype.getScroll=function(bu){var p={x:0,y:0};var curElm=this.elm;while(curElm&&curElm.nodeName!="BODY"&&curElm.nodeName!="HTML"){if(curElm.style["position"]=="fixed"){break;}
p.x+=curElm.scrollLeft;p.y+=curElm.scrollTop;curElm=curElm.parentNode;if(!(bu===true)){curElm=null;}}
return p;};IgDomNode.prototype.getSize=function(){var r={width:this.elm.offsetWidth,height:this.elm.offsetHeight};return r;};IgDomNode.prototype.getType=function(){return ig.getType(this);};IgDomNode.prototype.getWidth=function(){return this.elm.offsetWidth;};IgDomNode.prototype.hide=function(rs){if(this.getStyleInline("visibility")!="hidden"){this.setStyle("visibility","hidden");}
if(rs===true){if(this.getStyleInline("display")!="none"){this.setStyle("display","none");}}};IgDomNode.prototype.hideDropCaret=function(){};IgDomNode.prototype.isAncestor=function(n){var res=false;if(!ig.isNull(n)){var tmp=n.elm;while(!ig.isNull(tmp)){if(tmp==this.elm){res=true;break;}
tmp=tmp.parentNode;}}
return res;};IgDomNode.prototype.isDraggable=function(){return(this.getAttribute(ig.ui.PROP_DRAGGABLE)=="true");};IgDomNode.prototype.isDraggableViaHandle=function(){return(this.getAttribute(ig.ui.PROP_DRAGGABLE_VIA_HANDLE)=="true");};IgDomNode.prototype.isDragHandle=function(){return(this.getAttribute(ig.ui.PROP_DRAG_HANDLE)=="true");};IgDomNode.prototype.isDragSourceAccepted=function(dragSources){return false;};IgDomNode.prototype.isEnabled=function(){return(this.getAttribute(ig.PROP_DISABLED)!="true");};IgDomNode.prototype.isResizable=function(){return(this.getAttribute(ig.ui.PROP_RESIZABLE,false,"")=="true");};IgDomNode.prototype.isMovable=function(){return(this.getAttribute(ig.ui.PROP_MOVABLE,false,"")=="true");};IgDomNode.prototype.isVisible=function(){return!(this.getStyleInline("visibility")=="hidden"||this.getStyleInline("display")=="none");};IgDomNode.prototype.makeMovable=function(){var p=this.getStyle("position");if(p=="static"){this.setStyle("position","absolute");}};IgDomNode.prototype.moveBy=function(xo,yo){if(ig.isNumber(xo)){xo=xo!=0?xo+this.getStyleAsFloat("left"):null;}
if(ig.isNumber(yo)){yo=yo!=0?yo+this.getStyleAsFloat("top"):null;}
this.setPosition(xo,yo);};IgDomNode.prototype.moveTo=function(x,y){if(ig.isNumber(x)||ig.isNumber(y)){this.makeMovable();this.setStyle("display","");var cx=this.getStyleAsFloat("left");var cy=this.getStyleAsFloat("top");this.setPosition(cx,cy);var curPos=this.getPagePosition();if(ig.isNumber(x)){x=x-curPos.x;}
if(ig.isNumber(y)){y=y-curPos.y;}
this.moveBy(x,y);}};IgDomNode.prototype.onClick=function(){this.click();};IgDomNode.prototype.onDoubleClick=function(){};IgDomNode.prototype.onDragStart=function(dea){var pos=this.getPagePosition();if(ig.ui.dragMode===ig.ui.DRAG_MODE_MOVE){this.moveTo(pos.x,pos.y);}
else{var ds=this.createDragShadow();ds.show(ig.ui.x+10,pos.y);}};IgDomNode.prototype.onDrag=function(){var dx=ig.ui.x-ig.ui.lastX;var dy=ig.ui.y-ig.ui.lastY;if(ig.ui.dragMode===ig.ui.DRAG_MODE_MOVE){var p=this.getPosition();this.moveBy(dx,dy);}
else{var ds=this.getDragShadow();if(!ig.isNull(ds)){var p=ds.getPosition();ds.moveBy(dx,dy);}}};IgDomNode.prototype.onDragEnd=function(dea){this.deleteDragShadow();};IgDomNode.prototype.onDragEnter=function(dea){this.showDropCaret(dea);};IgDomNode.prototype.onDragOver=function(dea){};IgDomNode.prototype.onDragLeave=function(dea){this.hideDropCaret();};IgDomNode.prototype.onDrop=function(dea,dragSources){if(!ig.isNull(dragSources)){for(var i=0;i<dragSources.size();i++){var n=dragSources.get(i);this.elm.appendChild(n);}}};IgDomNode.prototype.onKeyDown=function(e){var c=this.getParentComponent();if(!ig.isNull(c)){c.onKeyDown(e);}};IgDomNode.prototype.onKeyPress=function(e){var c=this.getParentComponent();if(!ig.isNull(c)){c.onKeyPress(e);}};IgDomNode.prototype.onMouseEnter=function(){ig.ui.setHoveredElement(this);};IgDomNode.prototype.onMouseLeave=function(){ig.ui.setHoveredElement(null);};IgDomNode.prototype.onScroll=function(){};IgDomNode.prototype.removeNode=function(){if(this.elm.parentNode){this.elm.parentNode.removeChild(this.elm);}
else{ig.ui.getDocumentBody().removeChild(this.elm);}
this.elm=null;};IgDomNode.prototype.setAttribute=function(n,v){return ig.setAttribute(this.elm,n,v);};IgDomNode.prototype.setCursor=function(v){this.setStyle("cursor",v);};IgDomNode.prototype.setPosition=function(x,y){this.makeMovable();if(ig.isNumber(x)){this.setStyle("left",x+"px");}
if(ig.isNumber(y)){this.setStyle("top",y+"px");}};IgDomNode.prototype.setProperty=function(propName,propValue){var result=null;if(ig.NaES(propName)&&!ig.isNull(propValue)){var tmp="this.set"+ig.ucase(propName)+"("+propValue+")";result=eval(tmp);}
return result;};IgDomNode.prototype.setType=function(type){this.setAttribute(this.elm,ig.PROP_TYPE,type);};IgDomNode.prototype.setOpacity=function(o){var t=Math.max(0,Math.min(o,1));this.setStyle("filter","alpha(opacity:"+Math.round(t*100)+")");this.setStyle("opacity",t);};IgDomNode.prototype.setSize=function(w,h,dnabm){var r=new IgRect(ig.ui.UNDEFINED_NUMBER,ig.ui.UNDEFINED_NUMBER,ig.isNumber(w)?w:ig.ui.UNDEFINED_NUMBER,ig.isNumber(h)?h:ig.ui.UNDEFINED_NUMBER);if(dnabm!=true){this.convertBoxCoordinates(r);}
if(ig.isIE){if(this.getCompatMode()==ig.ui.COMPAT_BACK){if(this.elm.nodeName=="TD"||this.elm.nodeName=="TH"||this.elm.nodeName=="COL"){if(ig.isNumber(w)){r.width=r.width-this.getMargin("left")-this.getMargin("right");r.width=r.width-this.getBorder("left")-this.getBorder("right");r.width=r.width-this.getPadding("left")-this.getPadding("right");}}else if(this.elm.nodeName=="IMG"){if(ig.isNumber(w)){r.width=r.width-this.getBorder("left")-this.getBorder("right");}
if(ig.isNumber(h)){r.height=r.height-this.getBorder("top")-this.getBorder("bottom");}}}else{if(this.elm.nodeName=="COL"){if(ig.isNumber(w)){r.width=r.width-this.getMargin("left")-this.getMargin("right");r.width=r.width-this.getBorder("left")-this.getBorder("right");r.width=r.width-this.getPadding("left")-this.getPadding("right");}}else if(this.elm.nodeName=="TR"||this.elm.nodeName=="TD"||this.elm.nodeName=="TH"||this.elm.nodeName=="TABLE"){if(ig.isNumber(h)){r.height=r.height-this.getBorder("bottom")-this.getBorder("top");r.height=r.height-this.getPadding("top")-this.getPadding("bottom");}}}}else if(ig.isMozilla){if(this.elm.nodeName=="TD"||this.elm.nodeName=="TH"){if(ig.isNumber(h)){r.height=r.height+this.getBorder("top")+this.getBorder("bottom");r.height=r.height+this.getPadding("top")+this.getPadding("bottom");}
if(ig.isNumber(w)){r.width=r.width+(this.getBorder("left")+this.getBorder("right"))/2;}}else if(this.elm.nodeName=="COL"){if(ig.isNumber(w)){r.width=r.width-this.getMargin("left")-this.getMargin("right");r.width=r.width-this.getBorder("left")-this.getBorder("right");r.width=r.width-this.getPadding("left")-this.getPadding("right");}}else if(this.elm.nodeName=="TR"){if(ig.isNumber(h)){r.height=r.height+this.getBorder("top")+this.getBorder("bottom");r.height=r.height+this.getPadding("top")+this.getPadding("bottom");}}}else if(ig.isOpera)
{if(this.elm.nodeName=="DIV")
{if(ig.isNumber(w)){r.width=r.width+6;}}}
if(ig.isNumber(w)){if(r.width>=0){this.elm.style["width"]=r.width+"px";}}
if(ig.isNumber(h)){if(r.height>=0){this.elm.style["height"]=r.height+"px";}}};IgDomNode.prototype.setStyle=function(sn,sv,sp){if(ig.NaES(sn)&&!ig.isNull(sv)){sn=ig.camelize(sn);if(ig.isIE){this.elm.style[sn]=sv+"";}else{if(this.elm.style.setProperty){if(ig.isNull(sp))
sp='';this.elm.style.setProperty(sn,sv,sp);}else{this.elm.style[sn]=sv+"";}}}};IgDomNode.prototype.show=function(x,y,x2,y2){if(ig.isNumber(x)||ig.isNumber(y)){var w=this.getWidth();var sl=ig.getScrollLeft();var cw=ig.getClientWidth();var h=this.getHeight();var ch=ig.getClientHeight();var st=ig.getScrollTop();this.moveTo(x,y);}
if(this.getStyleInline("visibility")!="visible"){this.setStyle("visibility","visible");}
if(ig.NaES(this.getStyleInline("display"))){this.setStyle("display","");}};IgDomNode.prototype.showDropCaret=function(){};IgDomNode.prototype.convertBoxCoordinates=function(rect,sbm,tbm){if(ig.isNull(sbm)){sbm=ig.ui.BOX_BORDER;}
if(ig.isNull(tbm)){tbm=this.getBoxingModel();}
if(!ig.isNull(rect)&&sbm!=tbm&&sbm>=ig.ui.BOX_MARGIN&&sbm<=ig.ui.BOX_CONTENT&&tbm>=ig.ui.BOX_MARGIN&&tbm<=ig.ui.BOX_CONTENT){if(tbm>sbm){var fp=[this.getMargin,this.getBorder,this.getPadding];for(var i=sbm;i<tbm;i++){if(rect.x!=ig.ui.UNDEFINED_NUMBER)rect.x=rect.x+fp[i].call(this,"left");if(rect.y!=ig.ui.UNDEFINED_NUMBER)rect.y=rect.y+fp[i].call(this,"top");if(rect.width!=ig.ui.UNDEFINED_NUMBER)rect.width=rect.width-fp[i].call(this,"width");if(rect.height!=ig.ui.UNDEFINED_NUMBER)rect.height=rect.height-fp[i].call(this,"height");}}
else{var fp=[this.getMargin,this.getBorder,this.getPadding];for(var i=sbm-1;i>=tbm;i--){if(rect.x!=ig.ui.UNDEFINED_NUMBER)rect.x=rect.x-fp[i].call(this,"left");if(rect.y!=ig.ui.UNDEFINED_NUMBER)rect.y=rect.y-fp[i].call(this,"top");if(rect.width!=ig.ui.UNDEFINED_NUMBER)rect.width=rect.width+fp[i].call(this,"width");if(rect.height!=ig.ui.UNDEFINED_NUMBER)rect.height=rect.height+fp[i].call(this,"height");}}}};IgDomNode.prototype.get_element=function(){return this.elm;}
function IgUIElement(e){this.IgDomNode(e);};IgUIElement.prototype.applyClass=function(){var css=this.getClass();if(ig.isString(css)){if(this.elm.className!=css){this.elm.className=css;}}};IgUIElement.prototype.updateCursor=function(){if(!this.isEnabled()){return;}
if(!this.isHovered()){return;}
if(ig.ui.state==ig.ui.STATE_IDLE){if(this.equals(ig.ui.resizeTarget)){document.body.style.cursor=ig.ui.getResizeCursor(ig.ui.resizeMode);return;}
if(this.equals(ig.ui.dragTarget)){if(this.getDragMode()==ig.ui.DRAG_MODE_MOVE){document.body.style.cursor="move";}
else{document.body.style.cursor="pointer";}
return;}
if(this.isSortable&&this.isSortable()){document.body.style.cursor="pointer";return;}}
if(ig.ui.state==ig.ui.STATE_RESIZE){}
if(ig.ui.state==ig.ui.STATE_DRAG){}};IgUIElement.prototype.collapse=function(){var cc=this.getChildContainer();if(!ig.isNull(cc)){cc.hide(true);var pc=this.getParentComponent();if(!ig.isNull(pc)){var sn=pc.getSelectedElement();if(this.isAncestor(sn)){this.select();}}}};IgUIElement.prototype.disable=function(){this.setUIAttribute(ig.PROP_DISABLED,true);};IgUIElement.prototype.enable=function(){this.setUIAttribute(ig.PROP_DISABLED,false);};IgUIElement.prototype.expand=function(){var cc=this.getChildContainer();if(!ig.isNull(cc)){cc.show();}};IgUIElement.prototype.fireEvent=function(eventName,eventArgs,jsCallback,srid){if(ig.isNull(srid)){ig.smartSubmit(this.getId(),eventName,eventArgs,this.getId(),jsCallback);}
else{ig.smartSubmit(this.getId(),eventName,eventArgs,srid,jsCallback);}};IgUIElement.prototype.focus=function(){if(this.isEnabled()){ig.ui.setHoveredElement(this);var link=ig.findDescendant(this.elm,null,null,"a");if(!ig.isNull(link)){link.focus();}}};IgUIElement.prototype.getAttribute=function(attrn,p,s){var tmp=ig.getAttribute(this.elm,attrn);if(p===true&&!ig.NaES(tmp)){var pc=this.getParentComponent();if(!ig.isNull(pc)){if(!ig.isNull(s)){tmp=ig.getAttribute(pc.elm,attrn+s);}
else{tmp=ig.getAttribute(pc.elm,attrn+this.getType());}}}
return tmp;};IgUIElement.prototype.getChildContainer=function(){return ig.getUIElementById(this.getId()+"_cc");};IgUIElement.prototype.getClass=function(){var css=null;if(!this.isEnabled()){css=this.getDisabledClass();}
else{if(this.isSelected()){css=this.getSelectedClass();}
else
{if(this.isHovered()){css=this.getHoverClass();}}
if(!css){css=this.getDefaultClass();}}
return css;};IgUIElement.prototype.getDefaultClass=function(){return this.getAttribute(ig.PROP_DEFAULT_CLASS,true);};IgUIElement.prototype.getDisabledClass=function(){return this.getAttribute(ig.PROP_DISABLED_CLASS,true);};IgUIElement.prototype.getEventArguments=function(){return this.getAttribute("oprmtrs");};IgUIElement.prototype.getFirstChild=function(oe){var cc=this.getChildContainer();if(!ig.isNull(cc)){var t=this.getType();cc=ig.findDescendant(cc.elm,ig.PROP_TYPE,t);cc=ig.getUIElementById(cc);if(oe===true&&!ig.isNull(cc)&&!cc.isEnabled()){cc=cc.getNextSibling(true);}}
return cc;};IgUIElement.prototype.getFirstSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.parentNode.firstChild;while(!ig.isNull(tmp)){if(ig.getType(tmp)==t){r=tmp;break;}
tmp=tmp.nextSibling;}
r=ig.getUIElementById(r);if(oe===true&&!ig.isNull(r)&&!r.isEnabled()){r=r.getNextSibling(true);}
return r;};IgUIElement.prototype.getHoverClass=function(){return this.getAttribute(ig.PROP_HOVER_CLASS,true);};IgUIElement.prototype.getLastChild=function(oe){var r=this.getFirstChild(oe);if(r){r=r.getLastSibling(oe);}
return r;};IgUIElement.prototype.getLastSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.parentNode.lastChild;while(!ig.isNull(tmp)){if(ig.getType(tmp)==t){r=tmp;break;}
tmp=tmp.previousSibling;}
r=ig.getUIElementById(r);if(oe===true&&!ig.isNull(r)&&!r.isEnabled()){r=r.getPreviousSibling(true);}
return r;};IgUIElement.prototype.getNextSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.nextSibling;while(!ig.isNull(tmp)){if(ig.getType(tmp)==t){r=tmp;break;}
tmp=tmp.nextSibling;}
r=ig.getUIElementById(r);if(oe===true&&!ig.isNull(r)&&!r.isEnabled()){r=r.getNextSibling(true);}
return r;};IgUIElement.prototype.getParentType=function(){return null;}
IgUIElement.prototype.getParentComponent=function(){var parentType=this.getParentType();var parent=null;if(!ig.isNull(parentType)){parent=ig.getTargetUIElement(this.elm.parentNode,parentType);if(!ig.isNull(parent)){return parent;}}
var parentId=this.getAttribute(ig.PROP_PARENT_COMPONENT);if(ig.NaES(parentId)){return ig.getUIElementById(parentId);}
var pids=this.getParentIds();if(ig.isArray(pids)){for(var i=0;i<pids.length;i++){parentId=pids[i];if(ig.isUIComponent(parentId)){this.setAttribute(ig.PROP_PARENT_COMPONENT,parentId);return ig.getUIElementById(parentId);}}}
parent=ig.findAncestor(this.elm.parentNode,ig.PROP_COMPONENT,null,null);if(!ig.isNull(parent)){return ig.getUIElementById(parent);}
return null;};IgUIElement.prototype.getParentIds=function(){var pids=new Array();var id=this.getId();if(ig.NaES(id)){var lio=id.length;while(lio>=0){lio=id.lastIndexOf(":",lio-1);if(lio>=0){var anId=id.substring(0,lio);pids.push(anId);}}}
return pids;};IgUIElement.prototype.getParentSibling=function(){var c=this.getAttribute(ig.PROP_PARENT);if(!ig.NaES(c)){var pids=this.getParentIds();if(ig.isArray(pids)){for(var i=0;i<pids.length;i++){var tmp=ig.getElementById(pids[i]);if(ig.isOfType(tmp,this.getType())){this.setAttribute(ig.PROP_PARENT,tmp.id);c=tmp.id;break;}}}
if(!ig.NaES(c)){c=ig.findAncestor(this.elm.parentNode,ig.PROP_TYPE,this.getType(),null);}}
return ig.getUIElementById(c);};IgUIElement.prototype.getPreviousSibling=function(oe){var r=null;var t=this.getType();var tmp=this.elm.previousSibling;while(!ig.isNull(tmp)){if(ig.getType(tmp)==t){r=tmp;break;}
tmp=tmp.previousSibling;}
r=ig.getUIElementById(r);if(oe===true&&!ig.isNull(r)&&!r.isEnabled()){r=r.getPreviousSibling(true);}
return r;};IgUIElement.prototype.hasChild=function(){return(!ig.isNull(this.getChildContainer()));};IgUIElement.prototype.getSelectedClass=function(){return this.getAttribute(ig.PROP_SELECTED_CLASS,true);};IgUIElement.prototype.isAncestor=function(n){var res=false;if(!ig.isNull(n)){var thisId=this.getId();var otherId=n.getId();if(ig.NaES(thisId)&&ig.NaES(otherId)){res=(otherId.indexOf(thisId)===0);}}
return res;};IgUIElement.prototype.isExpanded=function(){var cc=this.getChildContainer();return(!ig.isNull(cc))?(cc.elm.style.visibility!="hidden"&&cc.elm.style.display!="none"):false;};IgUIElement.prototype.isHovered=function(){return this.equals(ig.ui.getHoveredElement());};IgUIElement.prototype.isSelected=function(){var result=null;var comp=this.getParentComponent();if(!ig.isNull(comp)){result=this.equals(comp.getSelectedElement());}
return result;};IgUIElement.prototype.queueEvent=function(evtSrc,evtName,evtValue){if(ig.NaES(evtSrc)){var pcmp=this.getParentComponent();if(!ig.isNull(pcmp)){pcmp.queueEvent(evtSrc,evtName,evtValue);}}};IgUIElement.prototype.removeEvent=function(evtSrc,evtName){if(ig.NaES(evtSrc)){var pcmp=this.getParentComponent();if(!ig.isNull(pcmp)){pcmp.removeEvent(evtSrc,evtName);}}};IgUIElement.prototype.findEvent=function(evtSrc,evtName){if(ig.NaES(evtSrc)){var pcmp=this.getParentComponent();if(!ig.isNull(pcmp)){return pcmp.findEvent(evtSrc,evtName);}}};IgUIElement.prototype.removeChildren=function(){var cc=this.getChildrenContainer();if(!ig.isNull(cc)){var pn=cc.parentNode;if(!ig.isNull(pn)){pn.removeChild(cc);}}};IgUIElement.prototype.repaint=function(){this.applyClass();this.updateCursor();};IgUIElement.prototype.replaceChildren=function(newChildren){this.removeChildren();this.appendChildren();};IgUIElement.prototype.select=function(){var pc=this.getParentComponent();if(!ig.isNull(pc)){pc.selectElement(this);}};IgUIElement.prototype.setUIAttribute=function(n,v){if(this.setAttribute(n,v)){this.repaint();}};IgUIElement.prototype.toggle=function(){if(this.isExpanded()){this.collapse();}
else{this.expand();}};IgUIElement.prototype.unselect=function(){if(this.isSelected()){var pc=this.getParentComponent();if(!ig.isNull(pc)){pc.unselectElement(this);}}};IgUIElement.prototype.get_events=function(){if(!this.elm._events){this.elm._events=new Sys.EventHandlerList();}
return this.elm._events;}
ig.augment(IgUIElement,IgDomNode);function IgUIComponent(e){this.IgUIElement(e);};IgUIComponent.prototype.focus=function(){};IgUIComponent.prototype.getParentComponent=function(){return null;};IgUIComponent.prototype.getSelectedElement=function(){var se=this.getAttribute(ig.PROP_SELECTED_ELEMENT);return ig.getUIElementById(se);};IgUIComponent.prototype.onKeyDown=function(e){};IgUIComponent.prototype.onKeyPress=function(e){};IgUIComponent.prototype.queueEvent=function(evtSrc,evtName,evtValue){var eq=new IgEventQueue(this.getId());if(!ig.isNull(eq)){eq.queueEvent(evtSrc,evtName,evtValue);}};IgUIElement.prototype.removeEvent=function(evtSrc,evtName){var eq=new IgEventQueue(this.getId());if(!ig.isNull(eq)){return eq.removeEvent(evtSrc,evtName);}};IgUIComponent.prototype.findEvent=function(evtSrc,evtName){var eq=new IgEventQueue(this.getId());if(!ig.isNull(eq)){return eq.findEvent(evtSrc,evtName);}};IgUIComponent.prototype.clearEventQueue=function(evtSrc){var eq=new IgEventQueue(this.getId());if(!ig.isNull(eq)){return eq.setValue("");}};IgUIComponent.prototype.select=function(e){};IgUIComponent.prototype.selectElement=function(se){if(!ig.isNull(se)&&!se.isSelected()){this.unselectElement(this.getSelectedElement());if(ig.NaES(se.elm.id)){this.setAttribute(ig.PROP_SELECTED_ELEMENT,se.elm.id);}
else{this.setAttribute(ig.PROP_SELECTED_ELEMENT,se);}
se.repaint();}};IgUIComponent.prototype.unselectElement=function(se){if(!ig.isNull(se)){this.setAttribute(ig.PROP_SELECTED_ELEMENT,null);se.repaint();}};IgUIComponent.prototype.getClientEventPostBack=function(arg0){return null;};IgUIComponent.prototype._initClientEventsForObject=function(owner,vals)
{owner._clientEvents=new Object();var i=vals?vals.length:0;while(i-->0){var evt=vals[i].split(':');this.setClientEvent(owner,evt[0],evt[1],evt[2]);}};IgUIComponent.prototype.setClientEvent=function(owner,evtName,fncName,postBack)
{if(postBack)
postBack=parseInt(postBack,10);else
postBack=0;owner._clientEvents[evtName]={name:evtName,fnc:fncName,postBack:postBack};if(evtName&&fncName)
this.addClientEventHandler(owner,evtName,fncName);};IgUIComponent.prototype.addClientEventHandler=function(owner,evtName,fnc){$util.addClientEvent(owner,evtName,fnc);},IgUIComponent.prototype._raiseClientEventStart=function(param)
{var params=param;if(params.substring){params=arguments;}
return this._raiseCE_0(this,params[0],this.getClientEventPostBack(params[0]),params[1],params);};IgUIComponent.prototype._raiseClientEvent=function(param)
{var args=this._raiseClientEventStart(param.substring?arguments:param);return args?this._raiseClientEventEnd(args,args._name):null;};IgUIComponent.prototype._raiseClientEventEnd=function(args)
{if(args&&args._props&&!(args.get_cancel&&args.get_cancel()))
this._postAction(args,args._name);return args;};IgUIComponent.prototype._raiseSenderClientEvent=function(sender,clientEvent,eventArgs)
{eventArgs=this._raiseSenderClientEventStart(sender,clientEvent,eventArgs);return this._raiseClientEventEnd(eventArgs);};IgUIComponent.prototype._raiseSenderClientEventStart=function(sender,clientEvent,eventArgs)
{return this._raiseCE_0(sender,clientEvent.name,clientEvent.postBack,eventArgs);};IgUIComponent.prototype._raiseCE_0=function(me,evtName,post,args,params)
{var fnc=me.get_events().getHandler(evtName);var str=args&&args.substring;if(!fnc&&post==null)
return str?null:args;if(str)
eval('try{args = new $IG.'+args+'EventArgs();}catch(ex){args = null;}');var i=1,len=params?params.length:0;if(!args)
args=(len<3)?new Sys.EventArgs():new $IG.EventArgs();if(args._props)
while(++i<len)if(params[i]!=null)
args._props[i-2]=params[i];if(post)
{if(!args._props)
args._props=new Array();if(!args._props[1]||args._props[1]==0)
args._props[1]=post;}
if(fnc)
fnc(this,args);if(args._props)
delete args._props[0];args._name=evtName;return args;};IgUIComponent.prototype._postAction=function(args,evtName){}
ig.augment(IgUIComponent,IgUIElement);function IgPopup(e){this.IgDomNode(e);};IgPopup.prototype.createIframe=function(){var ifr=null;if(ig.isIE){var id=this.elm.id;if(!ig.isNull(id)){id=id+"_frm";ifr=ig.getUIElementById(ig.ui.getDocument().createElement("IFRAME"));ifr.elm.frameBorder="no";ifr.elm.id=id;ifr.elm.scrolling="no";ifr.elm.src='javascript:new String("<html></html>")';ifr.elm.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity=0);";ifr.setStyle("z-index",this.getStyle("z-index"));ifr.setStyle("visibility","hidden");ifr.setStyle("display","none");var size=this.getSize();ifr.setSize(size.width,size.height);this.elm.parentNode.insertBefore(ifr.elm,this.elm);}}
return ifr;};IgPopup.prototype.show=function(x,y,x2,y2){this.callSuper("IgDomNode","show",x,y,x2,y2);if(this.needIeFix()){var ifr=this.getIframe();if(ig.isNull(ifr)){ifr=this.createIframe();}
ifr.show(x,y,x2,y2);}};IgPopup.prototype.moveBy=function(x,y){this.callSuper("IgDomNode","moveBy",x,y);if(this.needIeFix()){var ifr=this.getIframe();if(!ig.isNull(ifr)){ifr.moveBy(x,y);}}};IgPopup.prototype.needIeFix=function(rs){return ig.isIE;};IgPopup.prototype.hide=function(rs){this.callSuper("IgDomNode","hide",rs);if(this.needIeFix()){var ifr=this.getIframe();if(!ig.isNull(ifr)){ifr.hide(rs);}}};IgPopup.prototype.getIframe=function(){var id=this.elm.id+"_frm";return ig.getUIElementById(id);};IgPopup.prototype.removeNode=function(){if(this.needIeFix()){var ifr=this.getIframe();if(!ig.isNull(ifr)){ifr.removeNode();}}
this.callSuper("IgDomNode","removeNode");};ig.augment(IgPopup,IgDomNode);function IgPagerLink(e){this.IgUIElement(e);};ig.augment(IgPagerLink,IgUIElement);function IgLink(e){this.IgUIElement(e);};IgLink.prototype.getIconUrl=function(){return this.getAttribute("odiu",false);};IgLink.prototype.getHoverIconUrl=function(){return this.getAttribute("ohiu",false);};IgLink.prototype.repaint=function(){this.callSuper("IgUIElement","repaint");this.updateIcon();};IgLink.prototype.getIcon=function(){return ig.getElementById(this.getId()+"i");};IgLink.prototype.updateIcon=function(){var tmp=(this.isHovered())?this.getHoverIconUrl():this.getIconUrl();if(ig.NaES(tmp)){var e=this.getIcon();if(!ig.isNull(e)){e.src=tmp;}}};ig.augment(IgLink,IgUIElement);function IgHeaderLink(e){this.IgLink(e);};IgHeaderLink.prototype.click=function(){this.toggle();};IgHeaderLink.prototype.collapse=function(){this.callSuper("IgLink","collapse");this.repaint();};IgHeaderLink.prototype.expand=function(){this.callSuper("IgLink","expand");this.repaint();};IgHeaderLink.prototype.getClass=function(){var css=null;if(!this.isEnabled()){css=this.getDisabledClass();}
else{if(this.isExpanded()){if(this.isHovered()){css=this.getExpandedHoverClass();}
else{css=this.getExpandedDefaultClass();}}
else{if(this.isHovered()){css=this.getHoverClass();}}
if(!css){css=this.getDefaultClass();}}
return css;};IgHeaderLink.prototype.getExpandedDefaultClass=function(){return this.getAttribute("oedc",true);};IgHeaderLink.prototype.getExpandedHoverClass=function(){return this.getAttribute("oehc",true);};IgHeaderLink.prototype.getExpandedIconUrl=function(){return this.getAttribute("oediu",false);};IgHeaderLink.prototype.getExpandedHoverIconUrl=function(){return this.getAttribute("oehiu",false);};IgHeaderLink.prototype.updateIcon=function(){var tmp=(this.isHovered())?this.getHoverIconUrl():this.getIconUrl();if(ig.NaES(tmp)){var e=this.getIcon();if(!ig.isNull(e)){e.src=tmp;}}};ig.augment(IgHeaderLink,IgLink);function IgHtmlTable(e){this.IgUIElement(e);};IgHtmlTable.prototype.getCell=function(row,col){var result=null;if(ig.isNumber(row)&&ig.isNumber(col)){var r=this.getRow(row);if(!ig.isNull(r)){var cl=r.elm.cells[col];if(!ig.isNull(cl)){result=new IgDomNode(cl);}}}
return result;};IgHtmlTable.prototype.getColCount=function(){return this.elm.rows[0].cells.length;};IgHtmlTable.prototype.getColGroupCol=function(col){var result=null;var colGroups=this.elm.getElementsByTagName("colgroup");if(ig.isArray(colGroups)){var cols=colGroups[0].getElementsByTagName("col");if(ig.isArray(cols)){if(cols.length>col){result=new IgDomNode(cols[col]);}}}
return result;};IgHtmlTable.prototype.getRow=function(i){var result=null;if(i<this.getRowCount()){var r=this.elm.rows[i];if(!ig.isNull(r)){result=ig.getUIElementById(r);}}
return result;};IgHtmlTable.prototype.getRowCount=function(){return this.elm.rows.length;};IgHtmlTable.prototype.setColGroupColWidth=function(col,w){if(ig.isNumber(col)&&ig.isNumber(w)){var cgc=this.getColGroupCol(col);if(!ig.isNull(cgc)){if(w>0){cgc.setSize(w,null);}}}};IgHtmlTable.prototype.setColumnWidth=function(col,w){var row=this.getRow(0);if(!ig.isNull(row)){var aCell=row.elm.cells[col];if(!ig.isNull(aCell)){aCell=ig.getUIElementById(aCell);aCell.setSize(w);}}
if(this.getRowCount()>1&&ig.isIE){for(var i=0;i<this.getRowCount();i++){row=this.getRow(i);if(!ig.isNull(row)){aCell=row.elm.cells[col];if(!ig.isNull(aCell)){aCell=ig.getUIElementById(aCell);aCell.setSize(w);}}}}};ig.augment(IgHtmlTable,IgUIElement);ig.addEventListener(window,"load",ig.ui.init,false);}}