// (c) 2008 Infragistics - Do NOT modify the content of this file
// Version 9.2.20092.1000

if(ig){if(!ig.bar){function IgWebBarPackage(){this.TYPE_STACKBAR="Stackbar";this.TYPE_STACKBARGROUP="StackbarGroup";this.TYPE_SIDEBAR="Sidebar";this.TYPE_SIDEBARGROUP="SidebarGroup";this.init=function(){ig.factory.addClass(ig.bar.TYPE_STACKBAR,IgStackbar);ig.factory.addClass(ig.bar.TYPE_STACKBARGROUP,IgStackbarGroup);ig.factory.addClass(ig.bar.TYPE_SIDEBAR,IgSidebar);ig.factory.addClass(ig.bar.TYPE_SIDEBARGROUP,IgSidebarGroup);};this.getStackbar=function(domNode){return ig.getTargetUIElement(domNode,this.TYPE_STACKBAR);};this.getSidebar=function(domNode){return ig.getTargetUIElement(domNode,this.TYPE_SIDEBAR);};this.initBar=function(nodeId,clientSideListeners){var igElm=ig.getUIElementById(nodeId);if(igElm.init){igElm.init(clientSideListeners);}else{alert("Bar without 'init' method found");}};}
ig.bar=new IgWebBarPackage();function IgStackbar(e){this.IgUIComponent(e);}
IgStackbar.prototype.init=function(clientSideListeners){this._initClientEventsForObject(this.elm,clientSideListeners);this._raiseClientEvent("Initialize",null,null,null);};ig.augment(IgStackbar,IgUIComponent);function IgStackbarGroup(e){this.IgHeaderLink(e);}
IgStackbarGroup.prototype.collapse=function(){var jsNode=ig.bar.getStackbar(this.elm);var args=jsNode._raiseClientEvent("groupCollapsing","Bar",jsNode,this);if(args!=null&&args.get_cancel())return;this.callSuper("IgHeaderLink","collapse");this.updateIconExpandedState(false);this.queueEvent(this.getId(),"expand","false");jsNode._raiseClientEvent("groupCollapsed","Bar",jsNode,this);};IgStackbarGroup.prototype.expand=function(){var jsNode=ig.bar.getStackbar(this.elm);var args=jsNode._raiseClientEvent("groupExpanding","Bar",jsNode,this);if(args!=null&&args.get_cancel())return;this.callSuper("IgHeaderLink","expand");this.updateIconExpandedState(true);this.queueEvent(this.getId(),"expand","true");jsNode._raiseClientEvent("groupExpanded","Bar",jsNode,this);};IgStackbarGroup.prototype.getParentType=function(){return"Stackbar";};IgStackbarGroup.prototype.updateIconExpandedState=function(isExpandedState){var expandedIconUrl=this.getExpandedIconUrl();var iconUrl=this.getIconUrl();var currentIconUrl=null;if(isExpandedState)
{currentIconUrl=expandedIconUrl;}
else
{currentIconUrl=iconUrl;}
if(ig.NaES(currentIconUrl))
{var e=this.getIcon();if(!ig.isNull(e))
{e.src=currentIconUrl;}}};IgStackbarGroup.prototype.updateIcon=function(){if(this.isExpanded()&&(this.getExpandedIconUrl()!=false))
currentIconUrl=this.getExpandedIconUrl();else
currentIconUrl=this.getIconUrl();var tmp=(this.isHovered())?this.getHoverIconUrl():currentIconUrl;if(ig.NaES(tmp)){var e=this.getIcon();if(!ig.isNull(e)){e.src=tmp;}}};ig.augment(IgStackbarGroup,IgHeaderLink);function IgSidebar(e){this.IgUIComponent(e);}
IgSidebar.prototype.init=function(clientSideListeners){this._initClientEventsForObject(this.elm,clientSideListeners);this._raiseClientEvent("Initialize",null,null,null);};ig.augment(IgSidebar,IgUIComponent);function IgSidebarGroup(e){this.IgHeaderLink(e);}
IgSidebarGroup.prototype.collapse=function(){var jsNode=ig.bar.getSidebar(this.elm);var args=jsNode._raiseClientEvent("groupCollapsing","Bar",jsNode,this);if(args!=null&&args.get_cancel())return;this.callSuper("IgHeaderLink","collapse");this.queueEvent(this.getId(),"expand","false");jsNode._raiseClientEvent("groupCollapsed","Bar",jsNode,this);};IgSidebarGroup.prototype.expand=function(){var jsNode=ig.bar.getSidebar(this.elm);var args=jsNode._raiseClientEvent("groupExpanding","Bar",jsNode,this);if(args!=null&&args.get_cancel())return;this.callSuper("IgHeaderLink","expand");this.queueEvent(this.getId(),"expand","true");jsNode._raiseClientEvent("groupExpanded","Bar",jsNode,this);};IgSidebarGroup.prototype.getParentType=function(){return"Sidebar";};ig.augment(IgSidebarGroup,IgHeaderLink);ig.bar.init();}
$IG.BarEventArgs=function(){$IG.BarEventArgs.initializeBase(this);}
$IG.BarEventArgs.prototype={get_bar:function(){return this._props[0];},get_barGroup:function(){return this._props[1];}}
$IG.BarEventArgs.registerClass("Infragistics.Web.UI.BarEventArgs",$IG.CancelEventArgs);}