// (c) 2008 Infragistics - Do NOT modify the content of this file
// Version 9.2.20092.1000

if(ig){if(!ig.tree){function IgWebTreePackage(){this.TYPE_TREE_VIEW="TreeView";this.TYPE_TREE_NODE="TreeNode";this.FLAG_PLUS_MINUS_ICON="pmi";this.PROP_COLLAPSED_ICON="oci";this.PROP_EXPANDED_ICON="oei";this.PROP_JUNCTION_EXPANDED_ICON="ojei";this.PROP_JUNCTION_COLLAPSED_ICON="ojci";this.init=function(){ig.factory.addClass(ig.tree.TYPE_TREE_VIEW,IgTreeView);ig.factory.addClass(ig.tree.TYPE_TREE_NODE,IgTreeNode);};this.getTree=function(domNode){return ig.getTargetUIElement(domNode,this.TYPE_TREE_VIEW);};this.onExpandedOnDemand=function(httpReq){ig.onPartialRefreshDefault(httpReq);var node=ig.getUIElementById(httpReq.getSourceOfRequest());if(!ig.isNull(node)){node.focus();}};this.onExpandNode=function(node){if(!ig.isNull(node)){var icon=(node.isExpanded())?node.getExpandedIcon():node.getCollapsedIcon();node.updateIcon(icon);if(node.hasChild()){icon=(node.isExpanded())?node.getAttribute(ig.tree.PROP_JUNCTION_EXPANDED_ICON,true):node.getAttribute(ig.tree.PROP_JUNCTION_COLLAPSED_ICON,true);node.updateJunctionIcon(icon);}
node.repaint();}};this.toggleNode=function(nodeId){var node=ig.getUIElementById(nodeId);if(!ig.isNull(node)){if(node.isEnabled()){node.toggle();}}
return false;};this.raiseNodeClickEvent=function(treeId,nodeId){var jsTree=ig.getUIElementById(treeId);var jsNode=ig.getUIElementById(nodeId);var args=jsTree._raiseClientEvent("nodeClicking","DataTreeNodeCancel",null,null,jsNode);if(args!=null&&args.get_cancel())return;jsTree._raiseClientEvent("nodeClicked","DataTreeNode",null,null,jsNode);};this.selectNode=function(nodeId,parentId,smartRefreshComponents){var treeElement=document.getElementById(parentId);var tree=ig.getTargetUIElement(treeElement,this.TYPE_TREE_VIEW);var selectedNodeId=tree.getAttribute("oseid");if(!ig.isNull(selectedNodeId)){var selectedElm=ig.getUIElementById(selectedNodeId);selectedElm.unselect();}
tree.setAttribute("oseid",nodeId);var components=nodeId+","+smartRefreshComponents;ig.smartSubmit(nodeId,null,null,components,null);};this.initTree=function(nodeId,clientSideListeners){var igElm=ig.getUIElementById(nodeId);if(igElm.init){igElm.init(clientSideListeners);}else{alert("TreeView without 'init' method found");}};this.lastTree=null;this.lastCurrentPge=null;this.lastNewPage=null;this.raiseTreeClientEvent=function(treeId,eventType,currentPage,newPage,toEvaluate){if(eventType=="pageChange"){var jsNode=ig.getUIElementById(treeId);ig.tree.lastTree=jsNode;ig.tree.lastCurrentPage=currentPage;ig.tree.lastNewPage=newPage;var args=jsNode._raiseClientEvent("pageChanging","PageChange",null,null,currentPage,newPage);if(args!=null&&args.get_cancel())return;eval(toEvaluate);}};this.raiseTreeEdClientEvent=function(httpReq){ig.onPartialRefreshDefault(httpReq);ig.tree.lastTree._raiseClientEvent("pageChanged","PageChange",null,null,ig.tree.lastCurrentPage,ig.tree.lastNewPage);};};ig.tree=new IgWebTreePackage();function IgTreeView(e){this.IgUIComponent(e);};IgTreeView.prototype.isImmediateTreeNodeCollapseEvent=function(){return ig.NaES(this.getAttribute("igImmediateTreeNodeCollapseEvent"));};IgTreeView.prototype.init=function(clientSideListeners){this._initClientEventsForObject(this,clientSideListeners);this._raiseClientEvent("Initialize",null,null,null);};ig.augment(IgTreeView,IgUIComponent);function IgTreeNode(e){this.IgUIElement(e);};IgTreeNode.prototype.collapse=function(){var tree=ig.tree.getTree(this.elm);var args=tree._raiseClientEvent("nodeCollapsing","DataTreeNodeCancel",null,null,this);if(args!=null&&args.get_cancel())return;var cc=this.getChildContainer();if(!ig.isNull(cc)){cc.hide(true);var pc=this.getParentComponent();if(!ig.isNull(pc)){var sn=pc.getSelectedElement();if(this.isAncestor(sn)){this.select();}}
ig.tree.onExpandNode(this);this.queueEvent(this.getId(),"expand","false");var tree=ig.tree.getTree(this.elm);if(tree.isImmediateTreeNodeCollapseEvent()){ig.smartSubmit(this.getId(),null,null);tree.clearEventQueue();}}
tree._raiseClientEvent("nodeCollapsed","DataTreeNode",null,null,this);};IgTreeNode.prototype.expand=function(){var tree=ig.tree.getTree(this.elm);var args=tree._raiseClientEvent("nodeExpanding","DataTreeNodeCancel",null,null,this);if(args!=null&&args.get_cancel())return;if(this.hasChild()){this.callSuper("IgUIElement","expand");ig.tree.onExpandNode(this);this.queueEvent(this.getId(),"expand","true");}
else{this.fireEvent("expand",null,ig.tree.onExpandedOnDemand);}
tree._raiseClientEvent("nodeExpanded","DataTreeNode",null,null,this);};IgTreeNode.prototype.focus=function(){ig.ui.setHoveredElement(this);if(this.elm.nodeName=='A'){this.elm.focus();}};IgTreeNode.prototype.getExpandedIcon=function(){var tmp=this.getAttribute(ig.tree.PROP_EXPANDED_ICON,false);if(ig.isNull(tmp)){tmp=this.getAttribute(ig.tree.PROP_COLLAPSED_ICON,false);if(!ig.isNull(tmp)){tmp=null;}
else{tmp=this.getAttribute(ig.tree.PROP_EXPANDED_ICON,true);}}
return tmp;};IgTreeNode.prototype.getCollapsedIcon=function(){return this.getAttribute(ig.tree.PROP_COLLAPSED_ICON,true);};IgTreeNode.prototype.getNextNode=function(){var nextNode=null;if(this.isExpanded()){nextNode=this.getFirstChild(true);}
if(ig.isNull(nextNode)){nextNode=this.getNextSibling(true);}
var pn=this.getParentSibling();while(ig.isNull(nextNode)&&!ig.isNull(pn)){nextNode=pn.getNextSibling(true);pn=pn.getParentSibling();}
return nextNode;};IgTreeNode.prototype.getPreviousNode=function(){var prevNode=this.getPreviousSibling(true);var lastChild=(!ig.isNull(prevNode))?prevNode.getLastChild(true):null;while(!ig.isNull(prevNode)&&prevNode.isExpanded()&&!ig.isNull(lastChild)){prevNode=lastChild;lastChild=prevNode.getLastChild(true);}
if(ig.isNull(prevNode)){prevNode=this.getParentSibling();}
return prevNode;};IgTreeNode.prototype.onClick=function(evt){};IgTreeNode.prototype.onKeyDown=function(evt){switch(evt.keyCode){case evt.KEY_UP:var sn=this.getPreviousNode();if(!ig.isNull(sn)){sn.focus();}
evt.preventDefault();break;case evt.KEY_DOWN:var nn=this.getNextNode();if(!ig.isNull(nn)){nn.focus();}
evt.preventDefault();break;case evt.KEY_LEFT:this.collapse();evt.preventDefault();break;case evt.KEY_RIGHT:this.expand();evt.preventDefault();break;case evt.KEY_TAB:if(evt.isShiftKeyPressed()){var pn=this.getPreviousNode();if(!ig.isNull(pn)){pn.focus();evt.preventDefault();}
break;}
else{var nn=this.getNextNode();if(!ig.isNull(nn)){nn.focus();evt.preventDefault();}
break;}}};IgTreeNode.prototype.updateIcon=function(anIcon){if(ig.NaES(anIcon)){var icon=this.elm.childNodes[1];if(!ig.isNull(icon)&&icon.src!=anIcon){icon.src=anIcon;}}};IgTreeNode.prototype.updateJunctionIcon=function(anIcon){if(ig.NaES(anIcon)){var icon=this.elm.childNodes[0];if(!ig.isNull(icon)&&icon.src!=anIcon){icon.src=anIcon;}}};IgTreeNode.prototype.select=function(){this.callSuper("IgUIElement","select");};ig.augment(IgTreeNode,IgUIElement);ig.tree.init();}
$IG.DataTreeNodeEventArgs=function()
{$IG.DataTreeNodeEventArgs.initializeBase(this);}
$IG.DataTreeNodeEventArgs.prototype={getNode:function(){return this._props[2];},_getPostArgs:function()
{return':'+this.getNode()._address;}}
$IG.DataTreeNodeEventArgs.registerClass('Infragistics.Web.UI.DataTreeNodeEventArgs',$IG.CancelEventArgs);$IG.DataTreeNodeCancelEventArgs=function()
{$IG.DataTreeNodeCancelEventArgs.initializeBase(this);}
$IG.DataTreeNodeCancelEventArgs.prototype={getNode:function(){return this._props[2];}}
$IG.DataTreeNodeCancelEventArgs.registerClass('Infragistics.Web.UI.DataTreeNodeCancelEventArgs',$IG.CancelEventArgs);}