package com.casapellas.donacion.entidades;

// Generated 05-19-2015 10:22:08 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DncDonacionJde generated by hbm2java
 */
public class DncDonacionJde implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8687562518950554646L;
	private int idDonacionJde;
	private int caid;
	private String codcomp;
	private int numrec;
	private String tiporec;
	private int iddonacion;
	private int clientecodigo;
	private Date fecha;
	private int numerobatch;
	private int numerodocjde;
	private String tipodocumento;
	private int codigocajero;
	private int estado;
	private int nobatchdevolucion;
	private int nodocjdedevolucion;
	private int numrecdev;
	private String tiporecdev;

	public DncDonacionJde() {
	}

	public DncDonacionJde(int idDonacionJde, int caid, String codcomp,
			int numrec, String tiporec, int iddonacion, int clientecodigo,
			Date fecha, int numerobatch, int numerodocjde,
			String tipodocumento, int codigocajero, int estado,
			int nobatchdevolucion, int nodocjdedevolucion, int numrecdev,
			String tiporecdev) {
		super();
		this.idDonacionJde = idDonacionJde;
		this.caid = caid;
		this.codcomp = codcomp;
		this.numrec = numrec;
		this.tiporec = tiporec;
		this.iddonacion = iddonacion;
		this.clientecodigo = clientecodigo;
		this.fecha = fecha;
		this.numerobatch = numerobatch;
		this.numerodocjde = numerodocjde;
		this.tipodocumento = tipodocumento;
		this.codigocajero = codigocajero;
		this.estado = estado;
		this.nobatchdevolucion = nobatchdevolucion;
		this.nodocjdedevolucion = nodocjdedevolucion;
		this.numrecdev = numrecdev;
		this.tiporecdev = tiporecdev;
	}


	public int getIdDonacionJde() {
		return this.idDonacionJde;
	}

	public void setIdDonacionJde(int idDonacionJde) {
		this.idDonacionJde = idDonacionJde;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public int getIddonacion() {
		return this.iddonacion;
	}

	public void setIddonacion(int iddonacion) {
		this.iddonacion = iddonacion;
	}

	public int getClientecodigo() {
		return this.clientecodigo;
	}

	public void setClientecodigo(int clientecodigo) {
		this.clientecodigo = clientecodigo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getNumerobatch() {
		return this.numerobatch;
	}

	public void setNumerobatch(int numerobatch) {
		this.numerobatch = numerobatch;
	}

	public int getNumerodocjde() {
		return this.numerodocjde;
	}

	public void setNumerodocjde(int numerodocjde) {
		this.numerodocjde = numerodocjde;
	}

	public String getTipodocumento() {
		return this.tipodocumento;
	}

	public void setTipodocumento(String tipodocumento) {
		this.tipodocumento = tipodocumento;
	}

	public int getCodigocajero() {
		return this.codigocajero;
	}

	public void setCodigocajero(int codigocajero) {
		this.codigocajero = codigocajero;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public int getNobatchdevolucion() {
		return nobatchdevolucion;
	}

	public void setNobatchdevolucion(int nobatchdevolucion) {
		this.nobatchdevolucion = nobatchdevolucion;
	}

	public int getNodocjdedevolucion() {
		return nodocjdedevolucion;
	}

	public void setNodocjdedevolucion(int nodocjdedevolucion) {
		this.nodocjdedevolucion = nodocjdedevolucion;
	}

	public int getNumrecdev() {
		return numrecdev;
	}

	public void setNumrecdev(int numrecdev) {
		this.numrecdev = numrecdev;
	}

	public String getTiporecdev() {
		return tiporecdev;
	}

	public void setTiporecdev(String tiporecdev) {
		this.tiporecdev = tiporecdev;
	}

}
