package com.casapellas.donacion.entidades;

// Generated Jul 21, 2015 4:29:50 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.casapellas.util.CodeUtil;

/**
 * VdonacionId generated by hbm2java
 */
public class VdonacionId implements java.io.Serializable {
 
	private static final long serialVersionUID = -647196865095328927L;
	private int numrec;
	private String codcomp;
	private String nomcomp;
	private String codsuc;
	private String nomsuc;
	private Date fecha;
	private Date hora;
	private int codcli;
	private String cliente;
	private String concepto;
	private BigDecimal montoapl;
	private BigDecimal montorec;
	private String cajero;
	private String mpago;
	private String metdesc;
	private String moneda;
	private BigDecimal monto;
	private BigDecimal cambio;
	private String moncam;
	private long numfac;
	private String partida;
	private BigDecimal montfac;
	private int caid;
	private String caprnt;
	private String tiporec;
	private String descrec;
	private BigDecimal tasa;
	private BigDecimal equiv;
	private long nodoco;
	private String tipodoco;
	private BigDecimal totaldoco;
	private String restado;
	private String monfact;
	private String mondev;
	private Date fechafact;
	private long fechadev;
	private String estadofact;
	private String estadodev;
	private BigDecimal pendiente;
	private BigDecimal saldo;
	private String codunineg;
	private String unineg;
	private String refer1;
	private String refer2;
	private String refer3;
	private String refer4;
	private String c4bcrcd;
	private int beneficiariocodigo;
	private String beneficiarionombre;
	private String nombrecaja;
	private int iddonacion;
	private int numrecibocaja;
	private int codcajero;
	
	private String descripcionEstado;

	public VdonacionId() {
	}

	public VdonacionId(int numrec, String codcomp, Date fecha, Date hora,
			int codcli, String cliente, String concepto, BigDecimal montoapl,
			BigDecimal montorec, String mpago, String moneda, BigDecimal monto,
			BigDecimal cambio, String moncam, long numfac, String partida,
			BigDecimal montfac, int caid, String caprnt, String tiporec,
			BigDecimal tasa, BigDecimal equiv, long nodoco, String tipodoco,
			BigDecimal totaldoco, String restado, String monfact,
			String mondev, Date fechafact, long fechadev, String estadofact,
			String estadodev, BigDecimal pendiente, BigDecimal saldo,
			String codunineg, String refer1, String refer2, String refer3,
			String refer4, String c4bcrcd, int beneficiariocodigo,
			String beneficiarionombre, int iddonacion, int numrecibocaja, int codcajero) {
		this.numrec = numrec;
		this.codcomp = codcomp;
		this.fecha = fecha;
		this.hora = hora;
		this.codcli = codcli;
		this.cliente = cliente;
		this.concepto = concepto;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.mpago = mpago;
		this.moneda = moneda;
		this.monto = monto;
		this.cambio = cambio;
		this.moncam = moncam;
		this.numfac = numfac;
		this.partida = partida;
		this.montfac = montfac;
		this.caid = caid;
		this.caprnt = caprnt;
		this.tiporec = tiporec;
		this.tasa = tasa;
		this.equiv = equiv;
		this.nodoco = nodoco;
		this.tipodoco = tipodoco;
		this.totaldoco = totaldoco;
		this.restado = restado;
		this.monfact = monfact;
		this.mondev = mondev;
		this.fechafact = fechafact;
		this.fechadev = fechadev;
		this.estadofact = estadofact;
		this.estadodev = estadodev;
		this.pendiente = pendiente;
		this.saldo = saldo;
		this.codunineg = codunineg;
		this.refer1 = refer1;
		this.refer2 = refer2;
		this.refer3 = refer3;
		this.refer4 = refer4;
		this.c4bcrcd = c4bcrcd;
		this.beneficiariocodigo = beneficiariocodigo;
		this.beneficiarionombre = beneficiarionombre;
		this.iddonacion = iddonacion;
		this.numrecibocaja = numrecibocaja;
		this.codcajero = codcajero;
	}

	public VdonacionId(int numrec, String codcomp, String nomcomp,
			String codsuc, String nomsuc, Date fecha, Date hora, int codcli,
			String cliente, String concepto, BigDecimal montoapl,
			BigDecimal montorec, String cajero, String mpago, String metdesc,
			String moneda, BigDecimal monto, BigDecimal cambio, String moncam,
			long numfac, String partida, BigDecimal montfac, int caid,
			String caprnt, String tiporec, String descrec, BigDecimal tasa,
			BigDecimal equiv, long nodoco, String tipodoco,
			BigDecimal totaldoco, String restado, String monfact,
			String mondev, Date fechafact, long fechadev, String estadofact,
			String estadodev, BigDecimal pendiente, BigDecimal saldo,
			String codunineg, String unineg, String refer1, String refer2,
			String refer3, String refer4, String c4bcrcd,
			int beneficiariocodigo, String beneficiarionombre,
			String nombrecaja, int iddonacion) {
		this.numrec = numrec;
		this.codcomp = codcomp;
		this.nomcomp = nomcomp;
		this.codsuc = codsuc;
		this.nomsuc = nomsuc;
		this.fecha = fecha;
		this.hora = hora;
		this.codcli = codcli;
		this.cliente = cliente;
		this.concepto = concepto;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.cajero = cajero;
		this.mpago = mpago;
		this.metdesc = metdesc;
		this.moneda = moneda;
		this.monto = monto;
		this.cambio = cambio;
		this.moncam = moncam;
		this.numfac = numfac;
		this.partida = partida;
		this.montfac = montfac;
		this.caid = caid;
		this.caprnt = caprnt;
		this.tiporec = tiporec;
		this.descrec = descrec;
		this.tasa = tasa;
		this.equiv = equiv;
		this.nodoco = nodoco;
		this.tipodoco = tipodoco;
		this.totaldoco = totaldoco;
		this.restado = restado;
		this.monfact = monfact;
		this.mondev = mondev;
		this.fechafact = fechafact;
		this.fechadev = fechadev;
		this.estadofact = estadofact;
		this.estadodev = estadodev;
		this.pendiente = pendiente;
		this.saldo = saldo;
		this.codunineg = codunineg;
		this.unineg = unineg;
		this.refer1 = refer1;
		this.refer2 = refer2;
		this.refer3 = refer3;
		this.refer4 = refer4;
		this.c4bcrcd = c4bcrcd;
		this.beneficiariocodigo = beneficiariocodigo;
		this.beneficiarionombre = beneficiarionombre;
		this.nombrecaja = nombrecaja;
		this.iddonacion = iddonacion;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getNomcomp() {
		return this.nomcomp;
	}

	public void setNomcomp(String nomcomp) {
		this.nomcomp = nomcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getNomsuc() {
		return this.nomsuc;
	}

	public void setNomsuc(String nomsuc) {
		this.nomsuc = nomsuc;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public int getCodcli() {
		return this.codcli;
	}

	public void setCodcli(int codcli) {
		this.codcli = codcli;
	}

	public String getCliente() {
		if(this.cliente != null){
			this.cliente = CodeUtil.capitalize(this.cliente.trim(), null);
		}
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public BigDecimal getMontoapl() {
		return this.montoapl;
	}

	public void setMontoapl(BigDecimal montoapl) {
		this.montoapl = montoapl;
	}

	public BigDecimal getMontorec() {
		return this.montorec;
	}

	public void setMontorec(BigDecimal montorec) {
		this.montorec = montorec;
	}

	public String getCajero() {
		if(this.cajero != null){
			this.cajero = CodeUtil.capitalize(this.cajero.trim(), null);
		}
		return this.cajero;
	}

	public void setCajero(String cajero) {
		this.cajero = cajero;
	}

	public String getMpago() {
		return this.mpago;
	}

	public void setMpago(String mpago) {
		this.mpago = mpago;
	}

	public String getMetdesc() {
		return this.metdesc;
	}

	public void setMetdesc(String metdesc) {
		this.metdesc = metdesc;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public BigDecimal getCambio() {
		return this.cambio;
	}

	public void setCambio(BigDecimal cambio) {
		this.cambio = cambio;
	}

	public String getMoncam() {
		return this.moncam;
	}

	public void setMoncam(String moncam) {
		this.moncam = moncam;
	}

	public long getNumfac() {
		return this.numfac;
	}

	public void setNumfac(long numfac) {
		this.numfac = numfac;
	}

	public String getPartida() {
		return this.partida;
	}

	public void setPartida(String partida) {
		this.partida = partida;
	}

	public BigDecimal getMontfac() {
		return this.montfac;
	}

	public void setMontfac(BigDecimal montfac) {
		this.montfac = montfac;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCaprnt() {
		return this.caprnt;
	}

	public void setCaprnt(String caprnt) {
		this.caprnt = caprnt;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public String getDescrec() {
		return this.descrec;
	}

	public void setDescrec(String descrec) {
		this.descrec = descrec;
	}

	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}

	public BigDecimal getEquiv() {
		return this.equiv;
	}

	public void setEquiv(BigDecimal equiv) {
		this.equiv = equiv;
	}

	public long getNodoco() {
		return this.nodoco;
	}

	public void setNodoco(long nodoco) {
		this.nodoco = nodoco;
	}

	public String getTipodoco() {
		return this.tipodoco;
	}

	public void setTipodoco(String tipodoco) {
		this.tipodoco = tipodoco;
	}

	public BigDecimal getTotaldoco() {
		return this.totaldoco;
	}

	public void setTotaldoco(BigDecimal totaldoco) {
		this.totaldoco = totaldoco;
	}

	public String getRestado() {
		return this.restado;
	}

	public void setRestado(String restado) {
		this.restado = restado;
	}

	public String getMonfact() {
		return this.monfact;
	}

	public void setMonfact(String monfact) {
		this.monfact = monfact;
	}

	public String getMondev() {
		return this.mondev;
	}

	public void setMondev(String mondev) {
		this.mondev = mondev;
	}

	public Date getFechafact() {
		return this.fechafact;
	}

	public void setFechafact(Date fechafact) {
		this.fechafact = fechafact;
	}

	public long getFechadev() {
		return this.fechadev;
	}

	public void setFechadev(long fechadev) {
		this.fechadev = fechadev;
	}

	public String getEstadofact() {
		return this.estadofact;
	}

	public void setEstadofact(String estadofact) {
		this.estadofact = estadofact;
	}

	public String getEstadodev() {
		return this.estadodev;
	}

	public void setEstadodev(String estadodev) {
		this.estadodev = estadodev;
	}

	public BigDecimal getPendiente() {
		return this.pendiente;
	}

	public void setPendiente(BigDecimal pendiente) {
		this.pendiente = pendiente;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public String getUnineg() {
		return this.unineg;
	}

	public void setUnineg(String unineg) {
		this.unineg = unineg;
	}

	public String getRefer1() {
		return this.refer1;
	}

	public void setRefer1(String refer1) {
		this.refer1 = refer1;
	}

	public String getRefer2() {
		return this.refer2;
	}

	public void setRefer2(String refer2) {
		this.refer2 = refer2;
	}

	public String getRefer3() {
		return this.refer3;
	}

	public void setRefer3(String refer3) {
		this.refer3 = refer3;
	}

	public String getRefer4() {
		return this.refer4;
	}

	public void setRefer4(String refer4) {
		this.refer4 = refer4;
	}

	public String getC4bcrcd() {
		return this.c4bcrcd;
	}

	public void setC4bcrcd(String c4bcrcd) {
		this.c4bcrcd = c4bcrcd;
	}

	public int getBeneficiariocodigo() {
		return this.beneficiariocodigo;
	}

	public void setBeneficiariocodigo(int beneficiariocodigo) {
		this.beneficiariocodigo = beneficiariocodigo;
	}

	public String getBeneficiarionombre() {
		return this.beneficiarionombre;
	}

	public void setBeneficiarionombre(String beneficiarionombre) {
		this.beneficiarionombre = beneficiarionombre;
	}

	public String getNombrecaja() {
		if(this.nombrecaja != null){
			this.nombrecaja = CodeUtil.capitalize(this.nombrecaja.trim(), null);
		}
		return this.nombrecaja;
	}

	public void setNombrecaja(String nombrecaja) {
		this.nombrecaja = nombrecaja;
	}

	public int getIddonacion() {
		return this.iddonacion;
	}

	public void setIddonacion(int iddonacion) {
		this.iddonacion = iddonacion;
	}

	public String getDescripcionEstado() {
		if(descripcionEstado == null || descripcionEstado.isEmpty() )
			descripcionEstado = "Sin Estado" ;
		return descripcionEstado;
	}

	public void setDescripcionEstado(String descripcionEstado) {
		this.descripcionEstado = descripcionEstado;
	}

	public int getNumrecibocaja() {
		return numrecibocaja;
	}

	public void setNumrecibocaja(int numrecibocaja) {
		this.numrecibocaja = numrecibocaja;
	}

	public int getCodcajero() {
		return codcajero;
	}
	public void setCodcajero(int codcajero) {
		this.codcajero = codcajero;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + beneficiariocodigo;
		result = prime
				* result
				+ ((beneficiarionombre == null) ? 0 : beneficiarionombre
						.hashCode());
		result = prime * result + ((c4bcrcd == null) ? 0 : c4bcrcd.hashCode());
		result = prime * result + caid;
		result = prime * result + ((cajero == null) ? 0 : cajero.hashCode());
		result = prime * result + ((cambio == null) ? 0 : cambio.hashCode());
		result = prime * result + ((caprnt == null) ? 0 : caprnt.hashCode());
		result = prime * result + ((cliente == null) ? 0 : cliente.hashCode());
		result = prime * result + codcajero;
		result = prime * result + codcli;
		result = prime * result + ((codcomp == null) ? 0 : codcomp.hashCode());
		result = prime * result + ((codsuc == null) ? 0 : codsuc.hashCode());
		result = prime * result
				+ ((codunineg == null) ? 0 : codunineg.hashCode());
		result = prime * result
				+ ((concepto == null) ? 0 : concepto.hashCode());
		result = prime * result + ((descrec == null) ? 0 : descrec.hashCode());
		result = prime
				* result
				+ ((descripcionEstado == null) ? 0 : descripcionEstado
						.hashCode());
		result = prime * result + ((equiv == null) ? 0 : equiv.hashCode());
		result = prime * result
				+ ((estadodev == null) ? 0 : estadodev.hashCode());
		result = prime * result
				+ ((estadofact == null) ? 0 : estadofact.hashCode());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		result = prime * result + (int) (fechadev ^ (fechadev >>> 32));
		result = prime * result
				+ ((fechafact == null) ? 0 : fechafact.hashCode());
		result = prime * result + ((hora == null) ? 0 : hora.hashCode());
		result = prime * result + iddonacion;
		result = prime * result + ((metdesc == null) ? 0 : metdesc.hashCode());
		result = prime * result + ((moncam == null) ? 0 : moncam.hashCode());
		result = prime * result + ((mondev == null) ? 0 : mondev.hashCode());
		result = prime * result + ((moneda == null) ? 0 : moneda.hashCode());
		result = prime * result + ((monfact == null) ? 0 : monfact.hashCode());
		result = prime * result + ((montfac == null) ? 0 : montfac.hashCode());
		result = prime * result + ((monto == null) ? 0 : monto.hashCode());
		result = prime * result
				+ ((montoapl == null) ? 0 : montoapl.hashCode());
		result = prime * result
				+ ((montorec == null) ? 0 : montorec.hashCode());
		result = prime * result + ((mpago == null) ? 0 : mpago.hashCode());
		result = prime * result + (int) (nodoco ^ (nodoco >>> 32));
		result = prime * result
				+ ((nombrecaja == null) ? 0 : nombrecaja.hashCode());
		result = prime * result + ((nomcomp == null) ? 0 : nomcomp.hashCode());
		result = prime * result + ((nomsuc == null) ? 0 : nomsuc.hashCode());
		result = prime * result + (int) (numfac ^ (numfac >>> 32));
		result = prime * result + numrec;
		result = prime * result + numrecibocaja;
		result = prime * result + ((partida == null) ? 0 : partida.hashCode());
		result = prime * result
				+ ((pendiente == null) ? 0 : pendiente.hashCode());
		result = prime * result + ((refer1 == null) ? 0 : refer1.hashCode());
		result = prime * result + ((refer2 == null) ? 0 : refer2.hashCode());
		result = prime * result + ((refer3 == null) ? 0 : refer3.hashCode());
		result = prime * result + ((refer4 == null) ? 0 : refer4.hashCode());
		result = prime * result + ((restado == null) ? 0 : restado.hashCode());
		result = prime * result + ((saldo == null) ? 0 : saldo.hashCode());
		result = prime * result + ((tasa == null) ? 0 : tasa.hashCode());
		result = prime * result
				+ ((tipodoco == null) ? 0 : tipodoco.hashCode());
		result = prime * result + ((tiporec == null) ? 0 : tiporec.hashCode());
		result = prime * result
				+ ((totaldoco == null) ? 0 : totaldoco.hashCode());
		result = prime * result + ((unineg == null) ? 0 : unineg.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		VdonacionId other = (VdonacionId) obj;
		if (beneficiariocodigo != other.beneficiariocodigo)
			return false;
		if (beneficiarionombre == null) {
			if (other.beneficiarionombre != null)
				return false;
		} else if (!beneficiarionombre.equals(other.beneficiarionombre))
			return false;
		if (c4bcrcd == null) {
			if (other.c4bcrcd != null)
				return false;
		} else if (!c4bcrcd.equals(other.c4bcrcd))
			return false;
		if (caid != other.caid)
			return false;
		if (cajero == null) {
			if (other.cajero != null)
				return false;
		} else if (!cajero.equals(other.cajero))
			return false;
		if (cambio == null) {
			if (other.cambio != null)
				return false;
		} else if (!cambio.equals(other.cambio))
			return false;
		if (caprnt == null) {
			if (other.caprnt != null)
				return false;
		} else if (!caprnt.equals(other.caprnt))
			return false;
		if (cliente == null) {
			if (other.cliente != null)
				return false;
		} else if (!cliente.equals(other.cliente))
			return false;
		if (codcajero != other.codcajero)
			return false;
		if (codcli != other.codcli)
			return false;
		if (codcomp == null) {
			if (other.codcomp != null)
				return false;
		} else if (!codcomp.equals(other.codcomp))
			return false;
		if (codsuc == null) {
			if (other.codsuc != null)
				return false;
		} else if (!codsuc.equals(other.codsuc))
			return false;
		if (codunineg == null) {
			if (other.codunineg != null)
				return false;
		} else if (!codunineg.equals(other.codunineg))
			return false;
		if (concepto == null) {
			if (other.concepto != null)
				return false;
		} else if (!concepto.equals(other.concepto))
			return false;
		if (descrec == null) {
			if (other.descrec != null)
				return false;
		} else if (!descrec.equals(other.descrec))
			return false;
		if (descripcionEstado == null) {
			if (other.descripcionEstado != null)
				return false;
		} else if (!descripcionEstado.equals(other.descripcionEstado))
			return false;
		if (equiv == null) {
			if (other.equiv != null)
				return false;
		} else if (!equiv.equals(other.equiv))
			return false;
		if (estadodev == null) {
			if (other.estadodev != null)
				return false;
		} else if (!estadodev.equals(other.estadodev))
			return false;
		if (estadofact == null) {
			if (other.estadofact != null)
				return false;
		} else if (!estadofact.equals(other.estadofact))
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		if (fechadev != other.fechadev)
			return false;
		if (fechafact == null) {
			if (other.fechafact != null)
				return false;
		} else if (!fechafact.equals(other.fechafact))
			return false;
		if (hora == null) {
			if (other.hora != null)
				return false;
		} else if (!hora.equals(other.hora))
			return false;
		if (iddonacion != other.iddonacion)
			return false;
		if (metdesc == null) {
			if (other.metdesc != null)
				return false;
		} else if (!metdesc.equals(other.metdesc))
			return false;
		if (moncam == null) {
			if (other.moncam != null)
				return false;
		} else if (!moncam.equals(other.moncam))
			return false;
		if (mondev == null) {
			if (other.mondev != null)
				return false;
		} else if (!mondev.equals(other.mondev))
			return false;
		if (moneda == null) {
			if (other.moneda != null)
				return false;
		} else if (!moneda.equals(other.moneda))
			return false;
		if (monfact == null) {
			if (other.monfact != null)
				return false;
		} else if (!monfact.equals(other.monfact))
			return false;
		if (montfac == null) {
			if (other.montfac != null)
				return false;
		} else if (!montfac.equals(other.montfac))
			return false;
		if (monto == null) {
			if (other.monto != null)
				return false;
		} else if (!monto.equals(other.monto))
			return false;
		if (montoapl == null) {
			if (other.montoapl != null)
				return false;
		} else if (!montoapl.equals(other.montoapl))
			return false;
		if (montorec == null) {
			if (other.montorec != null)
				return false;
		} else if (!montorec.equals(other.montorec))
			return false;
		if (mpago == null) {
			if (other.mpago != null)
				return false;
		} else if (!mpago.equals(other.mpago))
			return false;
		if (nodoco != other.nodoco)
			return false;
		if (nombrecaja == null) {
			if (other.nombrecaja != null)
				return false;
		} else if (!nombrecaja.equals(other.nombrecaja))
			return false;
		if (nomcomp == null) {
			if (other.nomcomp != null)
				return false;
		} else if (!nomcomp.equals(other.nomcomp))
			return false;
		if (nomsuc == null) {
			if (other.nomsuc != null)
				return false;
		} else if (!nomsuc.equals(other.nomsuc))
			return false;
		if (numfac != other.numfac)
			return false;
		if (numrec != other.numrec)
			return false;
		if (numrecibocaja != other.numrecibocaja)
			return false;
		if (partida == null) {
			if (other.partida != null)
				return false;
		} else if (!partida.equals(other.partida))
			return false;
		if (pendiente == null) {
			if (other.pendiente != null)
				return false;
		} else if (!pendiente.equals(other.pendiente))
			return false;
		if (refer1 == null) {
			if (other.refer1 != null)
				return false;
		} else if (!refer1.equals(other.refer1))
			return false;
		if (refer2 == null) {
			if (other.refer2 != null)
				return false;
		} else if (!refer2.equals(other.refer2))
			return false;
		if (refer3 == null) {
			if (other.refer3 != null)
				return false;
		} else if (!refer3.equals(other.refer3))
			return false;
		if (refer4 == null) {
			if (other.refer4 != null)
				return false;
		} else if (!refer4.equals(other.refer4))
			return false;
		if (restado == null) {
			if (other.restado != null)
				return false;
		} else if (!restado.equals(other.restado))
			return false;
		if (saldo == null) {
			if (other.saldo != null)
				return false;
		} else if (!saldo.equals(other.saldo))
			return false;
		if (tasa == null) {
			if (other.tasa != null)
				return false;
		} else if (!tasa.equals(other.tasa))
			return false;
		if (tipodoco == null) {
			if (other.tipodoco != null)
				return false;
		} else if (!tipodoco.equals(other.tipodoco))
			return false;
		if (tiporec == null) {
			if (other.tiporec != null)
				return false;
		} else if (!tiporec.equals(other.tiporec))
			return false;
		if (totaldoco == null) {
			if (other.totaldoco != null)
				return false;
		} else if (!totaldoco.equals(other.totaldoco))
			return false;
		if (unineg == null) {
			if (other.unineg != null)
				return false;
		} else if (!unineg.equals(other.unineg))
			return false;
		return true;
	}
 
	 
}
