package com.casapellas.entidades.fdc;
// Generated Sep 10, 2013 3:23:06 PM by Hibernate Tools 3.2.1.GA



/**
 * A03factcoXxId generated by hbm2java
 */
public class A03factcoXxId  implements java.io.Serializable {


     private String sucursal;
     private String zona;
     private String ruta;
     private int noFactura;
     private String tipoFactura;
     private String codUniNeg;
     private String codSuc;
     private String codItem;
     private String empaque;
     private String nlote;

    public A03factcoXxId() {
    }

    public A03factcoXxId(String sucursal, String zona, String ruta, int noFactura, String tipoFactura, String codUniNeg, String codSuc, String codItem, String empaque, String nlote) {
       this.sucursal = sucursal;
       this.zona = zona;
       this.ruta = ruta;
       this.noFactura = noFactura;
       this.tipoFactura = tipoFactura;
       this.codUniNeg = codUniNeg;
       this.codSuc = codSuc;
       this.codItem = codItem;
       this.empaque = empaque;
       this.nlote = nlote;
    }
   
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public int getNoFactura() {
        return this.noFactura;
    }
    
    public void setNoFactura(int noFactura) {
        this.noFactura = noFactura;
    }
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public String getCodUniNeg() {
        return this.codUniNeg;
    }
    
    public void setCodUniNeg(String codUniNeg) {
        this.codUniNeg = codUniNeg;
    }
    public String getCodSuc() {
        return this.codSuc;
    }
    
    public void setCodSuc(String codSuc) {
        this.codSuc = codSuc;
    }
    public String getCodItem() {
        return this.codItem;
    }
    
    public void setCodItem(String codItem) {
        this.codItem = codItem;
    }
    public String getEmpaque() {
        return this.empaque;
    }
    
    public void setEmpaque(String empaque) {
        this.empaque = empaque;
    }
    public String getNlote() {
        return this.nlote;
    }
    
    public void setNlote(String nlote) {
        this.nlote = nlote;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof A03factcoXxId) ) return false;
		 A03factcoXxId castOther = ( A03factcoXxId ) other; 
         
		 return ( (this.getSucursal()==castOther.getSucursal()) || ( this.getSucursal()!=null && castOther.getSucursal()!=null && this.getSucursal().equals(castOther.getSucursal()) ) )
 && ( (this.getZona()==castOther.getZona()) || ( this.getZona()!=null && castOther.getZona()!=null && this.getZona().equals(castOther.getZona()) ) )
 && ( (this.getRuta()==castOther.getRuta()) || ( this.getRuta()!=null && castOther.getRuta()!=null && this.getRuta().equals(castOther.getRuta()) ) )
 && (this.getNoFactura()==castOther.getNoFactura())
 && ( (this.getTipoFactura()==castOther.getTipoFactura()) || ( this.getTipoFactura()!=null && castOther.getTipoFactura()!=null && this.getTipoFactura().equals(castOther.getTipoFactura()) ) )
 && ( (this.getCodUniNeg()==castOther.getCodUniNeg()) || ( this.getCodUniNeg()!=null && castOther.getCodUniNeg()!=null && this.getCodUniNeg().equals(castOther.getCodUniNeg()) ) )
 && ( (this.getCodSuc()==castOther.getCodSuc()) || ( this.getCodSuc()!=null && castOther.getCodSuc()!=null && this.getCodSuc().equals(castOther.getCodSuc()) ) )
 && ( (this.getCodItem()==castOther.getCodItem()) || ( this.getCodItem()!=null && castOther.getCodItem()!=null && this.getCodItem().equals(castOther.getCodItem()) ) )
 && ( (this.getEmpaque()==castOther.getEmpaque()) || ( this.getEmpaque()!=null && castOther.getEmpaque()!=null && this.getEmpaque().equals(castOther.getEmpaque()) ) )
 && ( (this.getNlote()==castOther.getNlote()) || ( this.getNlote()!=null && castOther.getNlote()!=null && this.getNlote().equals(castOther.getNlote()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSucursal() == null ? 0 : this.getSucursal().hashCode() );
         result = 37 * result + ( getZona() == null ? 0 : this.getZona().hashCode() );
         result = 37 * result + ( getRuta() == null ? 0 : this.getRuta().hashCode() );
         result = 37 * result + this.getNoFactura();
         result = 37 * result + ( getTipoFactura() == null ? 0 : this.getTipoFactura().hashCode() );
         result = 37 * result + ( getCodUniNeg() == null ? 0 : this.getCodUniNeg().hashCode() );
         result = 37 * result + ( getCodSuc() == null ? 0 : this.getCodSuc().hashCode() );
         result = 37 * result + ( getCodItem() == null ? 0 : this.getCodItem().hashCode() );
         result = 37 * result + ( getEmpaque() == null ? 0 : this.getEmpaque().hashCode() );
         result = 37 * result + ( getNlote() == null ? 0 : this.getNlote().hashCode() );
         return result;
   }   


}


