package com.casapellas.entidades.fdc;
// Generated Sep 10, 2013 3:23:06 PM by Hibernate Tools 3.2.1.GA



/**
 * ArqueofactXxId generated by hbm2java
 */
public class ArqueofactXxId  implements java.io.Serializable {


     private String codComp;
     private String codSuc;
     private int caId;
     private int noArqueo;
     private int numFac;
     private String partida;
     private String tipo;
     private String codUniNeg;

    public ArqueofactXxId() {
    }

    public ArqueofactXxId(String codComp, String codSuc, int caId, int noArqueo, int numFac, String partida, String tipo, String codUniNeg) {
       this.codComp = codComp;
       this.codSuc = codSuc;
       this.caId = caId;
       this.noArqueo = noArqueo;
       this.numFac = numFac;
       this.partida = partida;
       this.tipo = tipo;
       this.codUniNeg = codUniNeg;
    }
   
    public String getCodComp() {
        return this.codComp;
    }
    
    public void setCodComp(String codComp) {
        this.codComp = codComp;
    }
    public String getCodSuc() {
        return this.codSuc;
    }
    
    public void setCodSuc(String codSuc) {
        this.codSuc = codSuc;
    }
    public int getCaId() {
        return this.caId;
    }
    
    public void setCaId(int caId) {
        this.caId = caId;
    }
    public int getNoArqueo() {
        return this.noArqueo;
    }
    
    public void setNoArqueo(int noArqueo) {
        this.noArqueo = noArqueo;
    }
    public int getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(int numFac) {
        this.numFac = numFac;
    }
    public String getPartida() {
        return this.partida;
    }
    
    public void setPartida(String partida) {
        this.partida = partida;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCodUniNeg() {
        return this.codUniNeg;
    }
    
    public void setCodUniNeg(String codUniNeg) {
        this.codUniNeg = codUniNeg;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArqueofactXxId) ) return false;
		 ArqueofactXxId castOther = ( ArqueofactXxId ) other; 
         
		 return ( (this.getCodComp()==castOther.getCodComp()) || ( this.getCodComp()!=null && castOther.getCodComp()!=null && this.getCodComp().equals(castOther.getCodComp()) ) )
 && ( (this.getCodSuc()==castOther.getCodSuc()) || ( this.getCodSuc()!=null && castOther.getCodSuc()!=null && this.getCodSuc().equals(castOther.getCodSuc()) ) )
 && (this.getCaId()==castOther.getCaId())
 && (this.getNoArqueo()==castOther.getNoArqueo())
 && (this.getNumFac()==castOther.getNumFac())
 && ( (this.getPartida()==castOther.getPartida()) || ( this.getPartida()!=null && castOther.getPartida()!=null && this.getPartida().equals(castOther.getPartida()) ) )
 && ( (this.getTipo()==castOther.getTipo()) || ( this.getTipo()!=null && castOther.getTipo()!=null && this.getTipo().equals(castOther.getTipo()) ) )
 && ( (this.getCodUniNeg()==castOther.getCodUniNeg()) || ( this.getCodUniNeg()!=null && castOther.getCodUniNeg()!=null && this.getCodUniNeg().equals(castOther.getCodUniNeg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodComp() == null ? 0 : this.getCodComp().hashCode() );
         result = 37 * result + ( getCodSuc() == null ? 0 : this.getCodSuc().hashCode() );
         result = 37 * result + this.getCaId();
         result = 37 * result + this.getNoArqueo();
         result = 37 * result + this.getNumFac();
         result = 37 * result + ( getPartida() == null ? 0 : this.getPartida().hashCode() );
         result = 37 * result + ( getTipo() == null ? 0 : this.getTipo().hashCode() );
         result = 37 * result + ( getCodUniNeg() == null ? 0 : this.getCodUniNeg().hashCode() );
         return result;
   }   


}


