package com.casapellas.entidades.fdc;
// Generated Sep 10, 2013 3:23:06 PM by Hibernate Tools 3.2.1.GA



/**
 * RecibofacXxId generated by hbm2java
 */
public class RecibofacXxId  implements java.io.Serializable {


     private int numRec;
     private String codComp;
     private int caId;
     private String codSuc;
     private String tipoRec;
     private String codUniNeg;
     private String tipoFactura;
     private int numFac;
     private String partida;

    public RecibofacXxId() {
    }

    public RecibofacXxId(int numRec, String codComp, int caId, String codSuc, String tipoRec, String codUniNeg, String tipoFactura, int numFac, String partida) {
       this.numRec = numRec;
       this.codComp = codComp;
       this.caId = caId;
       this.codSuc = codSuc;
       this.tipoRec = tipoRec;
       this.codUniNeg = codUniNeg;
       this.tipoFactura = tipoFactura;
       this.numFac = numFac;
       this.partida = partida;
    }
   
    public int getNumRec() {
        return this.numRec;
    }
    
    public void setNumRec(int numRec) {
        this.numRec = numRec;
    }
    public String getCodComp() {
        return this.codComp;
    }
    
    public void setCodComp(String codComp) {
        this.codComp = codComp;
    }
    public int getCaId() {
        return this.caId;
    }
    
    public void setCaId(int caId) {
        this.caId = caId;
    }
    public String getCodSuc() {
        return this.codSuc;
    }
    
    public void setCodSuc(String codSuc) {
        this.codSuc = codSuc;
    }
    public String getTipoRec() {
        return this.tipoRec;
    }
    
    public void setTipoRec(String tipoRec) {
        this.tipoRec = tipoRec;
    }
    public String getCodUniNeg() {
        return this.codUniNeg;
    }
    
    public void setCodUniNeg(String codUniNeg) {
        this.codUniNeg = codUniNeg;
    }
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public int getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(int numFac) {
        this.numFac = numFac;
    }
    public String getPartida() {
        return this.partida;
    }
    
    public void setPartida(String partida) {
        this.partida = partida;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecibofacXxId) ) return false;
		 RecibofacXxId castOther = ( RecibofacXxId ) other; 
         
		 return (this.getNumRec()==castOther.getNumRec())
 && ( (this.getCodComp()==castOther.getCodComp()) || ( this.getCodComp()!=null && castOther.getCodComp()!=null && this.getCodComp().equals(castOther.getCodComp()) ) )
 && (this.getCaId()==castOther.getCaId())
 && ( (this.getCodSuc()==castOther.getCodSuc()) || ( this.getCodSuc()!=null && castOther.getCodSuc()!=null && this.getCodSuc().equals(castOther.getCodSuc()) ) )
 && ( (this.getTipoRec()==castOther.getTipoRec()) || ( this.getTipoRec()!=null && castOther.getTipoRec()!=null && this.getTipoRec().equals(castOther.getTipoRec()) ) )
 && ( (this.getCodUniNeg()==castOther.getCodUniNeg()) || ( this.getCodUniNeg()!=null && castOther.getCodUniNeg()!=null && this.getCodUniNeg().equals(castOther.getCodUniNeg()) ) )
 && ( (this.getTipoFactura()==castOther.getTipoFactura()) || ( this.getTipoFactura()!=null && castOther.getTipoFactura()!=null && this.getTipoFactura().equals(castOther.getTipoFactura()) ) )
 && (this.getNumFac()==castOther.getNumFac())
 && ( (this.getPartida()==castOther.getPartida()) || ( this.getPartida()!=null && castOther.getPartida()!=null && this.getPartida().equals(castOther.getPartida()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumRec();
         result = 37 * result + ( getCodComp() == null ? 0 : this.getCodComp().hashCode() );
         result = 37 * result + this.getCaId();
         result = 37 * result + ( getCodSuc() == null ? 0 : this.getCodSuc().hashCode() );
         result = 37 * result + ( getTipoRec() == null ? 0 : this.getTipoRec().hashCode() );
         result = 37 * result + ( getCodUniNeg() == null ? 0 : this.getCodUniNeg().hashCode() );
         result = 37 * result + ( getTipoFactura() == null ? 0 : this.getTipoFactura().hashCode() );
         result = 37 * result + this.getNumFac();
         result = 37 * result + ( getPartida() == null ? 0 : this.getPartida().hashCode() );
         return result;
   }   


}


