package com.casapellas.entidades.fdc;
// Generated Sep 10, 2013 3:23:06 PM by Hibernate Tools 3.2.1.GA



/**
 * RecibodetXxId generated by hbm2java
 */
public class RecibodetXxId  implements java.io.Serializable {


     private int numRec;
     private String codComp;
     private int caId;
     private String codSuc;
     private String tipoRec;
     private String mpago;
     private String moneda;

    public RecibodetXxId() {
    }

    public RecibodetXxId(int numRec, String codComp, int caId, String codSuc, String tipoRec, String mpago, String moneda) {
       this.numRec = numRec;
       this.codComp = codComp;
       this.caId = caId;
       this.codSuc = codSuc;
       this.tipoRec = tipoRec;
       this.mpago = mpago;
       this.moneda = moneda;
    }
   
    public int getNumRec() {
        return this.numRec;
    }
    
    public void setNumRec(int numRec) {
        this.numRec = numRec;
    }
    public String getCodComp() {
        return this.codComp;
    }
    
    public void setCodComp(String codComp) {
        this.codComp = codComp;
    }
    public int getCaId() {
        return this.caId;
    }
    
    public void setCaId(int caId) {
        this.caId = caId;
    }
    public String getCodSuc() {
        return this.codSuc;
    }
    
    public void setCodSuc(String codSuc) {
        this.codSuc = codSuc;
    }
    public String getTipoRec() {
        return this.tipoRec;
    }
    
    public void setTipoRec(String tipoRec) {
        this.tipoRec = tipoRec;
    }
    public String getMpago() {
        return this.mpago;
    }
    
    public void setMpago(String mpago) {
        this.mpago = mpago;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecibodetXxId) ) return false;
		 RecibodetXxId castOther = ( RecibodetXxId ) other; 
         
		 return (this.getNumRec()==castOther.getNumRec())
 && ( (this.getCodComp()==castOther.getCodComp()) || ( this.getCodComp()!=null && castOther.getCodComp()!=null && this.getCodComp().equals(castOther.getCodComp()) ) )
 && (this.getCaId()==castOther.getCaId())
 && ( (this.getCodSuc()==castOther.getCodSuc()) || ( this.getCodSuc()!=null && castOther.getCodSuc()!=null && this.getCodSuc().equals(castOther.getCodSuc()) ) )
 && ( (this.getTipoRec()==castOther.getTipoRec()) || ( this.getTipoRec()!=null && castOther.getTipoRec()!=null && this.getTipoRec().equals(castOther.getTipoRec()) ) )
 && ( (this.getMpago()==castOther.getMpago()) || ( this.getMpago()!=null && castOther.getMpago()!=null && this.getMpago().equals(castOther.getMpago()) ) )
 && ( (this.getMoneda()==castOther.getMoneda()) || ( this.getMoneda()!=null && castOther.getMoneda()!=null && this.getMoneda().equals(castOther.getMoneda()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumRec();
         result = 37 * result + ( getCodComp() == null ? 0 : this.getCodComp().hashCode() );
         result = 37 * result + this.getCaId();
         result = 37 * result + ( getCodSuc() == null ? 0 : this.getCodSuc().hashCode() );
         result = 37 * result + ( getTipoRec() == null ? 0 : this.getTipoRec().hashCode() );
         result = 37 * result + ( getMpago() == null ? 0 : this.getMpago().hashCode() );
         result = 37 * result + ( getMoneda() == null ? 0 : this.getMoneda().hashCode() );
         return result;
   }   


}


