package com.casapellas.entidades;

// Generated 2/07/2009 11:36:12 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aplicacion generated by hbm2java
 */
public class Aplicacion implements java.io.Serializable {

	private String codapp;

	private String nombre;

	private String descrip;

	private String url;

	private Date fingreso;

	private String activo;

	private String nomcorto;

	private Set appsecs = new HashSet(0);

	public Aplicacion() {
	}

	public Aplicacion(String codapp, String nombre, String descrip,
			Date fingreso) {
		this.codapp = codapp;
		this.nombre = nombre;
		this.descrip = descrip;
		this.fingreso = fingreso;
	}

	public Aplicacion(String codapp, String nombre, String descrip, String url,
			Date fingreso, String activo, String nomcorto, Set appsecs) {
		this.codapp = codapp;
		this.nombre = nombre;
		this.descrip = descrip;
		this.url = url;
		this.fingreso = fingreso;
		this.activo = activo;
		this.nomcorto = nomcorto;
		this.appsecs = appsecs;
	}

	public String getCodapp() {
		return this.codapp;
	}

	public void setCodapp(String codapp) {
		this.codapp = codapp;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getFingreso() {
		return this.fingreso;
	}

	public void setFingreso(Date fingreso) {
		this.fingreso = fingreso;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public String getNomcorto() {
		return this.nomcorto;
	}

	public void setNomcorto(String nomcorto) {
		this.nomcorto = nomcorto;
	}

	public Set getAppsecs() {
		return this.appsecs;
	}

	public void setAppsecs(Set appsecs) {
		this.appsecs = appsecs;
	}

}
