package com.casapellas.entidades;

// Generated 2/07/2009 11:36:12 by Hibernate Tools 3.2.0.b9

/**
 * AppsecId generated by hbm2java
 */
public class AppsecId implements java.io.Serializable {

	private String codsec;

	private String codapp;

	public AppsecId() {
	}

	public AppsecId(String codsec, String codapp) {
		this.codsec = codsec;
		this.codapp = codapp;
	}

	public String getCodsec() {
		return this.codsec;
	}

	public void setCodsec(String codsec) {
		this.codsec = codsec;
	}

	public String getCodapp() {
		return this.codapp;
	}

	public void setCodapp(String codapp) {
		this.codapp = codapp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppsecId))
			return false;
		AppsecId castOther = (AppsecId) other;

		return ((this.getCodsec() == castOther.getCodsec()) || (this
				.getCodsec() != null
				&& castOther.getCodsec() != null && this.getCodsec().equals(
				castOther.getCodsec())))
				&& ((this.getCodapp() == castOther.getCodapp()) || (this
						.getCodapp() != null
						&& castOther.getCodapp() != null && this.getCodapp()
						.equals(castOther.getCodapp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodsec() == null ? 0 : this.getCodsec().hashCode());
		result = 37 * result
				+ (getCodapp() == null ? 0 : this.getCodapp().hashCode());
		return result;
	}

}
