package com.casapellas.entidades;
// Generated Jun 26, 2013 11:17:48 AM by Hibernate Tools 3.2.1.GA



/**
 * Arqueofact generated by hbm2java
 */
public class Arqueofact  implements java.io.Serializable {


     private ArqueofactId id;

    public Arqueofact() {
    }

    public Arqueofact(ArqueofactId id) {
       this.id = id;
    }
   
    public ArqueofactId getId() {
        return this.id;
    }
    
    public void setId(ArqueofactId id) {
        this.id = id;
    }




}


