package com.casapellas.entidades;

// Generated 01-05-2010 02:37:35 PM by Hibernate Tools 3.2.0.b9

/**
 * Arqueorec generated by hbm2java
 */
public class Arqueorec implements java.io.Serializable {

	private ArqueorecId id;

	public Arqueorec() {
	}

	public Arqueorec(ArqueorecId id) {
		this.id = id;
	}

	public ArqueorecId getId() {
		return this.id;
	}

	public void setId(ArqueorecId id) {
		this.id = id;
	}

}
