package com.casapellas.entidades;

// Generated 05-28-2010 08:58:53 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * ArqueoId generated by hbm2java
 */
public class ArqueoId implements java.io.Serializable {

	private static final long serialVersionUID = 8764945159568679012L;
	private Date hora;
	private Date fecha;
	private int noarqueo;
	private String codsuc;
	private String codcomp;
	private int caid;

	public ArqueoId() {
	}

	public ArqueoId(Date hora, Date fecha, int noarqueo, String codsuc,
			String codcomp, int caid) {
		this.hora = hora;
		this.fecha = fecha;
		this.noarqueo = noarqueo;
		this.codsuc = codsuc;
		this.codcomp = codcomp;
		this.caid = caid;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getNoarqueo() {
		return this.noarqueo;
	}

	public void setNoarqueo(int noarqueo) {
		this.noarqueo = noarqueo;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArqueoId))
			return false;
		ArqueoId castOther = (ArqueoId) other;

		return ((this.getHora() == castOther.getHora()) || (this.getHora() != null
				&& castOther.getHora() != null && this.getHora().equals(
				castOther.getHora())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())))
				&& (this.getNoarqueo() == castOther.getNoarqueo())
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& (this.getCaid() == castOther.getCaid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + this.getNoarqueo();
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result + this.getCaid();
		return result;
	}

}
