package com.casapellas.entidades;

// Generated Apr 28, 2016 3:48:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * BienId generated by hbm2java
 */
public class BienId implements java.io.Serializable {

	private static final long serialVersionUID = -5004727971313267158L;
	private int caid;
	private String codsuc;
	private String codcomp;
	private int numrec;

	public BienId() {
	}

	public BienId(int caid, String codsuc, String codcomp, int numrec) {
		this.caid = caid;
		this.codsuc = codsuc;
		this.codcomp = codcomp;
		this.numrec = numrec;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BienId))
			return false;
		BienId castOther = (BienId) other;

		return (this.getCaid() == castOther.getCaid())
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null && castOther.getCodsuc() != null && this
						.getCodsuc().equals(castOther.getCodsuc())))
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null && castOther.getCodcomp() != null && this
						.getCodcomp().equals(castOther.getCodcomp())))
				&& (this.getNumrec() == castOther.getNumrec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result + this.getNumrec();
		return result;
	}

}
