package com.casapellas.entidades;

// Generated Oct 29, 2013 4:03:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CierreSktpos generated by hbm2java
 */
public class CierreSktpos implements java.io.Serializable {

	private static final long serialVersionUID = -5916414675077952171L;
	private int idcierre;
	private int caid;
	private String codcomp;
	private String codsuc;
	private int noarqueo;
	private int codb;
	private Date fecha;
	private Date hora;
	private String horapos;
	private String fechapos;
	private String referencia;
	private String autorizacion;
	private String purshamount;
	private String retamount;
	private String purshtrans;
	private String rettrans;
	private String systraceno;
	private String termId;

	public CierreSktpos() {
	}

	public CierreSktpos(int idcierre, int caid, String codcomp, String codsuc,
			int noarqueo, int codb, Date fecha, Date hora, String horapos,
			String fechapos, String referencia, String autorizacion,
			String purshamount, String retamount, String purshtrans,
			String rettrans, String systraceno, String termId) {
		this.idcierre = idcierre;
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.noarqueo = noarqueo;
		this.codb = codb;
		this.fecha = fecha;
		this.hora = hora;
		this.horapos = horapos;
		this.fechapos = fechapos;
		this.referencia = referencia;
		this.autorizacion = autorizacion;
		this.purshamount = purshamount;
		this.retamount = retamount;
		this.purshtrans = purshtrans;
		this.rettrans = rettrans;
		this.systraceno = systraceno;
		this.termId = termId;
	}
	public CierreSktpos(int caid, String codcomp, String codsuc,
			int noarqueo, int codb, Date fecha, Date hora, String horapos,
			String fechapos, String referencia, String autorizacion,
			String purshamount, String retamount, String purshtrans,
			String rettrans, String systraceno, String termId) {
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.noarqueo = noarqueo;
		this.codb = codb;
		this.fecha = fecha;
		this.hora = hora;
		this.horapos = horapos;
		this.fechapos = fechapos;
		this.referencia = referencia;
		this.autorizacion = autorizacion;
		this.purshamount = purshamount;
		this.retamount = retamount;
		this.purshtrans = purshtrans;
		this.rettrans = rettrans;
		this.systraceno = systraceno;
		this.termId = termId;
	}

	public int getIdcierre() {
		return this.idcierre;
	}

	public void setIdcierre(int idcierre) {
		this.idcierre = idcierre;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public int getNoarqueo() {
		return this.noarqueo;
	}

	public void setNoarqueo(int noarqueo) {
		this.noarqueo = noarqueo;
	}

	public int getCodb() {
		return this.codb;
	}

	public void setCodb(int codb) {
		this.codb = codb;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getHorapos() {
		return this.horapos;
	}

	public void setHorapos(String horapos) {
		this.horapos = horapos;
	}

	public String getFechapos() {
		return this.fechapos;
	}

	public void setFechapos(String fechapos) {
		this.fechapos = fechapos;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public String getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(String autorizacion) {
		this.autorizacion = autorizacion;
	}

	public String getPurshamount() {
		return this.purshamount;
	}

	public void setPurshamount(String purshamount) {
		this.purshamount = purshamount;
	}

	public String getRetamount() {
		return this.retamount;
	}

	public void setRetamount(String retamount) {
		this.retamount = retamount;
	}

	public String getPurshtrans() {
		return this.purshtrans;
	}

	public void setPurshtrans(String purshtrans) {
		this.purshtrans = purshtrans;
	}

	public String getRettrans() {
		return this.rettrans;
	}

	public void setRettrans(String rettrans) {
		this.rettrans = rettrans;
	}

	public String getSystraceno() {
		return this.systraceno;
	}

	public void setSystraceno(String systraceno) {
		this.systraceno = systraceno;
	}

	public String getTermId() {
		return this.termId;
	}

	public void setTermId(String termId) {
		this.termId = termId;
	}

}
