package com.casapellas.entidades;

// Generated 04-28-2010 03:27:52 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * CredhdrId generated by hbm2java
 */
public class CredhdrId implements java.io.Serializable {

	private static final long serialVersionUID = 7655065481494226727L;
	private String tipofactura;
	private int nofactura;
	private String partida;
	private int codcli;
	private String nomcli;
	private String codunineg;
	private String unineg;
	private String codsuc;
	private String nomsuc;
	private String codcomp;
	private String nomcomp;
	private String moneda;
	private BigDecimal tasa;
	private BigDecimal cpendiente;
	private BigDecimal dpendiente;
	private BigDecimal ctotal;
	private BigDecimal dtotal;
	private BigDecimal cimpuesto;
	private BigDecimal dimpuesto;
	private BigDecimal csubtotal;
	private BigDecimal dsubtotal;
	private BigDecimal monto;
	private BigDecimal montopend;
	private BigDecimal subtotal;
	private BigDecimal impuesto;
	private Date fecha;
	private Date fechavenc;
	private String compenslm;
	private String tipopago;
	private int rpdivj;
	private int rpddj;
	private String rppo;
	private String rpdcto;
	
	private int rpicu;
	private String rpicut;
	private String rpco;
	private int rppa8 ;
	private int rppyr ; 
	private String rppst;
	private int rpjcl ;
	private String rpbcrc;
	private String rpcrrm;
	
	private int rpdgj;
	private int rpddnj;
	private String rpaid;
	private BigDecimal tasaoriginal;
	
	private String lossAccountId;
	private String gainAccountId;
	

	public CredhdrId() {
	}
 
	public CredhdrId(String tipofactura, int nofactura, String partida,
			int codcli, String nomcli, String codunineg, String unineg,
			String codsuc, String codcomp, String nomcomp, String moneda,
			BigDecimal tasa, BigDecimal cpendiente, BigDecimal dpendiente,
			BigDecimal ctotal, BigDecimal dtotal, BigDecimal cimpuesto,
			BigDecimal dimpuesto, BigDecimal csubtotal, BigDecimal dsubtotal,
			BigDecimal monto, BigDecimal montopend, BigDecimal subtotal,
			BigDecimal impuesto, Date fecha, Date fechavenc, String compenslm,
			String tipopago, int rpdivj, int rpddj, String rppo, String rpdcto,
			int rpicu, String rpicut, String rpco, int rppa8, int rppyr,
			String rppst, int rpjcl, String rpbcrc, String rpcrrm,
			int rpdgj, int rpddnj, String rpaid,  BigDecimal tasaoriginal, 
			String lossAccountId,  String gainAccountId ) {
		
		this.tipofactura = tipofactura;
		this.nofactura = nofactura;
		this.partida = partida;
		this.codcli = codcli;
		this.nomcli = nomcli;
		this.codunineg = codunineg;
		this.unineg = unineg;
		this.codsuc = codsuc;
		this.codcomp = codcomp;
		this.nomcomp = nomcomp;
		this.moneda = moneda;
		this.tasa = tasa;
		this.cpendiente = cpendiente;
		this.dpendiente = dpendiente;
		this.ctotal = ctotal;
		this.dtotal = dtotal;
		this.cimpuesto = cimpuesto;
		this.dimpuesto = dimpuesto;
		this.csubtotal = csubtotal;
		this.dsubtotal = dsubtotal;
		this.monto = monto;
		this.montopend = montopend;
		this.subtotal = subtotal;
		this.impuesto = impuesto;
		this.fecha = fecha;
		this.fechavenc = fechavenc;
		this.compenslm = compenslm;
		this.tipopago = tipopago;
		this.rpdivj = rpdivj;
		this.rpddj = rpddj;
		this.rppo = rppo;
		this.rpdcto = rpdcto;
		
		this.rpicu = rpicu ;
		this.rpicut = rpicut;
		this.rpco = rpco ;
		this.rppa8 = rppa8 ;
		this.rppyr = rppyr  ; 
		this.rppst = rppst;
		this.rpjcl = rpjcl;
		
		this.rpdgj = rpdgj;
		this.rpddnj = rpddnj ;
		this.rpaid = rpaid ;
		
		this.tasaoriginal = tasaoriginal;
		
		this.lossAccountId = lossAccountId;
		this.gainAccountId = gainAccountId;
		
		
	}

	public CredhdrId(String tipofactura, int nofactura, String partida,
			int codcli, String nomcli, String codunineg, String unineg,
			String codsuc, String nomsuc, String codcomp, String nomcomp,
			String moneda, BigDecimal tasa, BigDecimal cpendiente,
			BigDecimal dpendiente, BigDecimal ctotal, BigDecimal dtotal,
			BigDecimal cimpuesto, BigDecimal dimpuesto, BigDecimal csubtotal,
			BigDecimal dsubtotal, BigDecimal monto, BigDecimal montopend,
			BigDecimal subtotal, BigDecimal impuesto, Date fecha,
			Date fechavenc, String compenslm, String tipopago, int rpdivj,
			int rpddj, String rppo, String rpdcto) {
		this.tipofactura = tipofactura;
		this.nofactura = nofactura;
		this.partida = partida;
		this.codcli = codcli;
		this.nomcli = nomcli;
		this.codunineg = codunineg;
		this.unineg = unineg;
		this.codsuc = codsuc;
		this.nomsuc = nomsuc;
		this.codcomp = codcomp;
		this.nomcomp = nomcomp;
		this.moneda = moneda;
		this.tasa = tasa;
		this.cpendiente = cpendiente;
		this.dpendiente = dpendiente;
		this.ctotal = ctotal;
		this.dtotal = dtotal;
		this.cimpuesto = cimpuesto;
		this.dimpuesto = dimpuesto;
		this.csubtotal = csubtotal;
		this.dsubtotal = dsubtotal;
		this.monto = monto;
		this.montopend = montopend;
		this.subtotal = subtotal;
		this.impuesto = impuesto;
		this.fecha = fecha;
		this.fechavenc = fechavenc;
		this.compenslm = compenslm;
		this.tipopago = tipopago;
		this.rpdivj = rpdivj;
		this.rpddj = rpddj;
		this.rppo = rppo;
		this.rpdcto = rpdcto;
	}

	public String getTipofactura() {
		return this.tipofactura;
	}

	public void setTipofactura(String tipofactura) {
		this.tipofactura = tipofactura;
	}

	public int getNofactura() {
		return this.nofactura;
	}

	public void setNofactura(int nofactura) {
		this.nofactura = nofactura;
	}

	public String getPartida() {
		return this.partida;
	}

	public void setPartida(String partida) {
		this.partida = partida;
	}

	public int getCodcli() {
		return this.codcli;
	}

	public void setCodcli(int codcli) {
		this.codcli = codcli;
	}

	public String getNomcli() {
		
		if(nomcli == null ) nomcli = "" ;
		
		try{
			nomcli = nomcli.replace("'", "");
		}catch(Exception e){
			e.printStackTrace();
		}
		return this.nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public String getUnineg() {
		return this.unineg;
	}

	public void setUnineg(String unineg) {
		this.unineg = unineg;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getNomsuc() {
		return this.nomsuc;
	}

	public void setNomsuc(String nomsuc) {
		this.nomsuc = nomsuc;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getNomcomp() {
		return this.nomcomp;
	}

	public void setNomcomp(String nomcomp) {
		this.nomcomp = nomcomp;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}

	public BigDecimal getCpendiente() {
		return this.cpendiente;
	}

	public void setCpendiente(BigDecimal cpendiente) {
		this.cpendiente = cpendiente;
	}

	public BigDecimal getDpendiente() {
		return this.dpendiente;
	}

	public void setDpendiente(BigDecimal dpendiente) {
		this.dpendiente = dpendiente;
	}

	public BigDecimal getCtotal() {
		return this.ctotal;
	}

	public void setCtotal(BigDecimal ctotal) {
		this.ctotal = ctotal;
	}

	public BigDecimal getDtotal() {
		return this.dtotal;
	}

	public void setDtotal(BigDecimal dtotal) {
		this.dtotal = dtotal;
	}

	public BigDecimal getCimpuesto() {
		return this.cimpuesto;
	}

	public void setCimpuesto(BigDecimal cimpuesto) {
		this.cimpuesto = cimpuesto;
	}

	public BigDecimal getDimpuesto() {
		return this.dimpuesto;
	}

	public void setDimpuesto(BigDecimal dimpuesto) {
		this.dimpuesto = dimpuesto;
	}

	public BigDecimal getCsubtotal() {
		return this.csubtotal;
	}

	public void setCsubtotal(BigDecimal csubtotal) {
		this.csubtotal = csubtotal;
	}

	public BigDecimal getDsubtotal() {
		return this.dsubtotal;
	}

	public void setDsubtotal(BigDecimal dsubtotal) {
		this.dsubtotal = dsubtotal;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public BigDecimal getMontopend() {
		return this.montopend;
	}

	public void setMontopend(BigDecimal montopend) {
		this.montopend = montopend;
	}

	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	public BigDecimal getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(BigDecimal impuesto) {
		this.impuesto = impuesto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechavenc() {
		return this.fechavenc;
	}

	public void setFechavenc(Date fechavenc) {
		this.fechavenc = fechavenc;
	}

	public String getCompenslm() {
		return this.compenslm;
	}

	public void setCompenslm(String compenslm) {
		this.compenslm = compenslm;
	}

	public String getTipopago() {
		return this.tipopago;
	}

	public void setTipopago(String tipopago) {
		this.tipopago = tipopago;
	}

	public int getRpdivj() {
		return this.rpdivj;
	}

	public void setRpdivj(int rpdivj) {
		this.rpdivj = rpdivj;
	}

	public int getRpddj() {
		return this.rpddj;
	}

	public void setRpddj(int rpddj) {
		this.rpddj = rpddj;
	}

	public String getRppo() {
		return this.rppo;
	}

	public void setRppo(String rppo) {
		this.rppo = rppo;
	}

	public String getRpdcto() {
		return this.rpdcto;
	}

	public void setRpdcto(String rpdcto) {
		this.rpdcto = rpdcto;
	}
	
	public int getRpicu() {
		return rpicu;
	}
	public void setRpicu(int rpicu) {
		this.rpicu = rpicu;
	}
	
	public String getRpicut() {
		return rpicut;
	}
	public void setRpicut(String rpicut) {
		this.rpicut = rpicut;
	}
	public String getRpco() {
		return rpco;
	}
	public void setRpco(String rpco) {
		this.rpco = rpco;
	}
	public int getRppa8() {
		return rppa8;
	}
	public void setRppa8(int rppa8) {
		this.rppa8 = rppa8;
	}
	public int getRppyr() {
		return rppyr;
	}
	public void setRppyr(int rppyr) {
		this.rppyr = rppyr;
	}

	public String getRppst() {
		return rppst;
	}

	public void setRppst(String rppst) {
		this.rppst = rppst;
	}
	
	public int getRpjcl() {
		return rpjcl;
	}

	public void setRpjcl(int rpjcl) {
		this.rpjcl = rpjcl;
	}
	
	public String getRpbcrc() {
		return rpbcrc;
	}

	public void setRpbcrc(String rpbcrc) {
		this.rpbcrc = rpbcrc;
	}

	public String getRpcrrm() {
		return rpcrrm;
	}

	public void setRpcrrm(String rpcrrm) {
		this.rpcrrm = rpcrrm;
	}

	public int getRpdgj() {
		return rpdgj;
	}

	public void setRpdgj(int rpdgj) {
		this.rpdgj = rpdgj;
	}

	public int getRpddnj() {
		return rpddnj;
	}

	public void setRpddnj(int rpddnj) {
		this.rpddnj = rpddnj;
	}

	public String getRpaid() {
		return rpaid;
	}

	public void setRpaid(String rpaid) {
		this.rpaid = rpaid;
	}

	public BigDecimal getTasaoriginal() {
		return tasaoriginal;
	}

	public void setTasaoriginal(BigDecimal tasaoriginal) {
		this.tasaoriginal = tasaoriginal;
	}
	
	public String getLossAccountId() {
		return lossAccountId;
	}

	public void setLossAccountId(String lossAccountId) {
		this.lossAccountId = lossAccountId;
	}

	public String getGainAccountId() {
		return gainAccountId;
	}

	public void setGainAccountId(String gainAccountId) {
		this.gainAccountId = gainAccountId;
	}

	@Override
	protected CredhdrId clone() {
		
		return new CredhdrId(tipofactura, nofactura, partida, codcli, nomcli, 
				codunineg, codunineg, codsuc, nomsuc, codcomp, nomcomp, 
				moneda, tasa, cpendiente, dpendiente, ctotal, dtotal, 
				cimpuesto, dimpuesto, csubtotal, dsubtotal, monto, 
				montopend, csubtotal, cimpuesto, fecha, fechavenc, 
				compenslm, tipopago, rpdivj, rpddj, rppo, rpdcto) ;
		
	}
	
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CredhdrId))
			return false;
		CredhdrId castOther = (CredhdrId) other;

		return ((this.getTipofactura() == castOther.getTipofactura()) || (this
				.getTipofactura() != null && castOther.getTipofactura() != null && this
				.getTipofactura().equals(castOther.getTipofactura())))
				&& (this.getNofactura() == castOther.getNofactura())
				&& ((this.getPartida() == castOther.getPartida()) || (this
						.getPartida() != null && castOther.getPartida() != null && this
						.getPartida().equals(castOther.getPartida())))
				&& (this.getCodcli() == castOther.getCodcli())
				&& ((this.getNomcli() == castOther.getNomcli()) || (this
						.getNomcli() != null && castOther.getNomcli() != null && this
						.getNomcli().equals(castOther.getNomcli())))
				&& ((this.getCodunineg() == castOther.getCodunineg()) || (this
						.getCodunineg() != null
						&& castOther.getCodunineg() != null && this
						.getCodunineg().equals(castOther.getCodunineg())))
				&& ((this.getUnineg() == castOther.getUnineg()) || (this
						.getUnineg() != null && castOther.getUnineg() != null && this
						.getUnineg().equals(castOther.getUnineg())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null && castOther.getCodsuc() != null && this
						.getCodsuc().equals(castOther.getCodsuc())))
				&& ((this.getNomsuc() == castOther.getNomsuc()) || (this
						.getNomsuc() != null && castOther.getNomsuc() != null && this
						.getNomsuc().equals(castOther.getNomsuc())))
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null && castOther.getCodcomp() != null && this
						.getCodcomp().equals(castOther.getCodcomp())))
				&& ((this.getNomcomp() == castOther.getNomcomp()) || (this
						.getNomcomp() != null && castOther.getNomcomp() != null && this
						.getNomcomp().equals(castOther.getNomcomp())))
				&& ((this.getMoneda() == castOther.getMoneda()) || (this
						.getMoneda() != null && castOther.getMoneda() != null && this
						.getMoneda().equals(castOther.getMoneda())))
				&& ((this.getTasa() == castOther.getTasa()) || (this.getTasa() != null
						&& castOther.getTasa() != null && this.getTasa()
						.equals(castOther.getTasa())))
				&& ((this.getCpendiente() == castOther.getCpendiente()) || (this
						.getCpendiente() != null
						&& castOther.getCpendiente() != null && this
						.getCpendiente().equals(castOther.getCpendiente())))
				&& ((this.getDpendiente() == castOther.getDpendiente()) || (this
						.getDpendiente() != null
						&& castOther.getDpendiente() != null && this
						.getDpendiente().equals(castOther.getDpendiente())))
				&& ((this.getCtotal() == castOther.getCtotal()) || (this
						.getCtotal() != null && castOther.getCtotal() != null && this
						.getCtotal().equals(castOther.getCtotal())))
				&& ((this.getDtotal() == castOther.getDtotal()) || (this
						.getDtotal() != null && castOther.getDtotal() != null && this
						.getDtotal().equals(castOther.getDtotal())))
				&& ((this.getCimpuesto() == castOther.getCimpuesto()) || (this
						.getCimpuesto() != null
						&& castOther.getCimpuesto() != null && this
						.getCimpuesto().equals(castOther.getCimpuesto())))
				&& ((this.getDimpuesto() == castOther.getDimpuesto()) || (this
						.getDimpuesto() != null
						&& castOther.getDimpuesto() != null && this
						.getDimpuesto().equals(castOther.getDimpuesto())))
				&& ((this.getCsubtotal() == castOther.getCsubtotal()) || (this
						.getCsubtotal() != null
						&& castOther.getCsubtotal() != null && this
						.getCsubtotal().equals(castOther.getCsubtotal())))
				&& ((this.getDsubtotal() == castOther.getDsubtotal()) || (this
						.getDsubtotal() != null
						&& castOther.getDsubtotal() != null && this
						.getDsubtotal().equals(castOther.getDsubtotal())))
				&& ((this.getMonto() == castOther.getMonto()) || (this
						.getMonto() != null && castOther.getMonto() != null && this
						.getMonto().equals(castOther.getMonto())))
				&& ((this.getMontopend() == castOther.getMontopend()) || (this
						.getMontopend() != null
						&& castOther.getMontopend() != null && this
						.getMontopend().equals(castOther.getMontopend())))
				&& ((this.getSubtotal() == castOther.getSubtotal()) || (this
						.getSubtotal() != null
						&& castOther.getSubtotal() != null && this
						.getSubtotal().equals(castOther.getSubtotal())))
				&& ((this.getImpuesto() == castOther.getImpuesto()) || (this
						.getImpuesto() != null
						&& castOther.getImpuesto() != null && this
						.getImpuesto().equals(castOther.getImpuesto())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getFechavenc() == castOther.getFechavenc()) || (this
						.getFechavenc() != null
						&& castOther.getFechavenc() != null && this
						.getFechavenc().equals(castOther.getFechavenc())))
				&& ((this.getCompenslm() == castOther.getCompenslm()) || (this
						.getCompenslm() != null
						&& castOther.getCompenslm() != null && this
						.getCompenslm().equals(castOther.getCompenslm())))
				&& ((this.getTipopago() == castOther.getTipopago()) || (this
						.getTipopago() != null
						&& castOther.getTipopago() != null && this
						.getTipopago().equals(castOther.getTipopago())))
				&& (this.getRpdivj() == castOther.getRpdivj())
				&& (this.getRpddj() == castOther.getRpddj())
				&& ((this.getRppo() == castOther.getRppo()) || (this.getRppo() != null
						&& castOther.getRppo() != null && this.getRppo()
						.equals(castOther.getRppo())))
				&& ((this.getRpdcto() == castOther.getRpdcto()) || (this
						.getRpdcto() != null && castOther.getRpdcto() != null && this
						.getRpdcto().equals(castOther.getRpdcto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTipofactura() == null ? 0 : this.getTipofactura()
						.hashCode());
		result = 37 * result + this.getNofactura();
		result = 37 * result
				+ (getPartida() == null ? 0 : this.getPartida().hashCode());
		result = 37 * result + this.getCodcli();
		result = 37 * result
				+ (getNomcli() == null ? 0 : this.getNomcli().hashCode());
		result = 37 * result
				+ (getCodunineg() == null ? 0 : this.getCodunineg().hashCode());
		result = 37 * result
				+ (getUnineg() == null ? 0 : this.getUnineg().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getNomsuc() == null ? 0 : this.getNomsuc().hashCode());
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getNomcomp() == null ? 0 : this.getNomcomp().hashCode());
		result = 37 * result
				+ (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		result = 37 * result
				+ (getTasa() == null ? 0 : this.getTasa().hashCode());
		result = 37
				* result
				+ (getCpendiente() == null ? 0 : this.getCpendiente()
						.hashCode());
		result = 37
				* result
				+ (getDpendiente() == null ? 0 : this.getDpendiente()
						.hashCode());
		result = 37 * result
				+ (getCtotal() == null ? 0 : this.getCtotal().hashCode());
		result = 37 * result
				+ (getDtotal() == null ? 0 : this.getDtotal().hashCode());
		result = 37 * result
				+ (getCimpuesto() == null ? 0 : this.getCimpuesto().hashCode());
		result = 37 * result
				+ (getDimpuesto() == null ? 0 : this.getDimpuesto().hashCode());
		result = 37 * result
				+ (getCsubtotal() == null ? 0 : this.getCsubtotal().hashCode());
		result = 37 * result
				+ (getDsubtotal() == null ? 0 : this.getDsubtotal().hashCode());
		result = 37 * result
				+ (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37 * result
				+ (getMontopend() == null ? 0 : this.getMontopend().hashCode());
		result = 37 * result
				+ (getSubtotal() == null ? 0 : this.getSubtotal().hashCode());
		result = 37 * result
				+ (getImpuesto() == null ? 0 : this.getImpuesto().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getFechavenc() == null ? 0 : this.getFechavenc().hashCode());
		result = 37 * result
				+ (getCompenslm() == null ? 0 : this.getCompenslm().hashCode());
		result = 37 * result
				+ (getTipopago() == null ? 0 : this.getTipopago().hashCode());
		result = 37 * result + this.getRpdivj();
		result = 37 * result + this.getRpddj();
		result = 37 * result
				+ (getRppo() == null ? 0 : this.getRppo().hashCode());
		result = 37 * result
				+ (getRpdcto() == null ? 0 : this.getRpdcto().hashCode());
		return result;
	}


}
