package com.casapellas.entidades;

import java.math.BigDecimal;
import java.util.Date;

// Generated 04-28-2010 03:27:52 PM by Hibernate Tools 3.2.0.b9

/**
 * Credhdr generated by hbm2java
 */
public class Credhdr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6360353578991615960L;
	private CredhdrId id;
	private String tipofactura;
	private int nofactura;
	private String partida;
	private BigDecimal montoAplicar;
	private BigDecimal montoPendiente;
	private Date fecha;
	private Date fechavenc;
	private String nomcli;
	private String unineg;
	private String moneda;
	private boolean pagoparcial;
	private BigDecimal nuevoMontoPendiente;
	
	private boolean financimientoAsociado;
	private String estadopago;
	private String estadoPagoDescripcion;
	private String styleClass;

	public Credhdr() {
	}

	public Credhdr(CredhdrId id) {
		this.id = id;
	}

	public CredhdrId getId() {
		return this.id;
	}

	public void setId(CredhdrId id) {
		this.id = id;
	}

	public String getTipofactura() {
		return tipofactura;
	}

	public void setTipofactura(String tipofactura) {
		this.tipofactura = tipofactura;
	}

	public int getNofactura() {
		return nofactura;
	}

	public void setNofactura(int nofactura) {
		this.nofactura = nofactura;
	}

	public String getPartida() {
		return partida;
	}

	public void setPartida(String partida) {
		this.partida = partida;
	}

	public BigDecimal getMontoAplicar() {
		return montoAplicar;
	}

	public void setMontoAplicar(BigDecimal montoAplicar) {
		this.montoAplicar = montoAplicar;
	}

	public BigDecimal getMontoPendiente() {
		return montoPendiente;
	}

	public void setMontoPendiente(BigDecimal montoPendiente) {
		this.montoPendiente = montoPendiente;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechavenc() {
		return fechavenc;
	}

	public void setFechavenc(Date fechavenc) {
		this.fechavenc = fechavenc;
	}

	public String getNomcli() {
		return nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public String getUnineg() {
		return unineg;
	}

	public void setUnineg(String unineg) {
		this.unineg = unineg;
	}

	public String getMoneda() {
		return moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}
	
	public BigDecimal getNuevoMontoPendiente() {
		return nuevoMontoPendiente;
	}

	public void setNuevoMontoPendiente(BigDecimal nuevoMontoPendiente) {
		this.nuevoMontoPendiente = nuevoMontoPendiente;
	}


	public Credhdr(CredhdrId id, String tipofactura, int nofactura,
			String partida, BigDecimal montoAplicar, BigDecimal montoPendiente,
			Date fecha, Date fechavenc, String nomcli, String unineg,
			String moneda) {
		super();
		this.id = id;
		this.tipofactura = tipofactura;
		this.nofactura = nofactura;
		this.partida = partida;
		this.montoAplicar = montoAplicar;
		this.montoPendiente = montoPendiente;
		this.fecha = fecha;
		this.fechavenc = fechavenc;
		this.nomcli = nomcli;
		this.unineg = unineg;
		this.moneda = moneda;
	}
	
	@Override
	public Credhdr clone() {
		return new Credhdr(id.clone(), tipofactura, nofactura, partida,
				montoAplicar, montoPendiente, fecha, fechavenc, nomcli, 
				unineg, moneda);
	}
	public boolean isPagoparcial() {
		return pagoparcial;
	}
	public void setPagoparcial(boolean pagoparcial) {
		this.pagoparcial = pagoparcial;
	}

	public boolean isFinancimientoAsociado() {
		return financimientoAsociado;
	}

	public void setFinancimientoAsociado(boolean financimientoAsociado) {
		this.financimientoAsociado = financimientoAsociado;
	}

	public String getEstadopago() {
		return estadopago;
	}

	public void setEstadopago(String estadopago) {
		this.estadopago = estadopago;
	}

	public String getEstadoPagoDescripcion() {
		return estadoPagoDescripcion;
	}

	public void setEstadoPagoDescripcion(String estadoPagoDescripcion) {
		this.estadoPagoDescripcion = estadoPagoDescripcion;
	}

	public String getStyleClass() {
		return styleClass;
	}

	public void setStyleClass(String styleClass) {
		this.styleClass = styleClass;
	}
	
}
