package com.casapellas.entidades;

// Generated 14/04/2010 3:16:55 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * CreddetId generated by hbm2java
 */
public class CreddetId implements java.io.Serializable {

	private int nofactura;
	private String tipofactura;
	private String coditem;
	private String descitem;
	private BigDecimal preciounit;
	private long cant;
	private String impuesto;
	private BigDecimal factor;
	private String codunineg;
	private String codsuc;

	public CreddetId() {
	}

	public CreddetId(int nofactura, String tipofactura, String coditem,
			String descitem, BigDecimal preciounit, long cant, String impuesto,
			BigDecimal factor, String codunineg, String codsuc) {
		this.nofactura = nofactura;
		this.tipofactura = tipofactura;
		this.coditem = coditem;
		this.descitem = descitem;
		this.preciounit = preciounit;
		this.cant = cant;
		this.impuesto = impuesto;
		this.factor = factor;
		this.codunineg = codunineg;
		this.codsuc = codsuc;
	}

	public int getNofactura() {
		return this.nofactura;
	}

	public void setNofactura(int nofactura) {
		this.nofactura = nofactura;
	}

	public String getTipofactura() {
		return this.tipofactura;
	}

	public void setTipofactura(String tipofactura) {
		this.tipofactura = tipofactura;
	}

	public String getCoditem() {
		return this.coditem;
	}

	public void setCoditem(String coditem) {
		this.coditem = coditem;
	}

	public String getDescitem() {
		return this.descitem;
	}

	public void setDescitem(String descitem) {
		this.descitem = descitem;
	}

	public BigDecimal getPreciounit() {
		return this.preciounit;
	}

	public void setPreciounit(BigDecimal preciounit) {
		this.preciounit = preciounit;
	}

	public long getCant() {
		return this.cant;
	}

	public void setCant(long cant) {
		this.cant = cant;
	}

	public String getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(String impuesto) {
		this.impuesto = impuesto;
	}

	public BigDecimal getFactor() {
		return this.factor;
	}

	public void setFactor(BigDecimal factor) {
		this.factor = factor;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CreddetId))
			return false;
		CreddetId castOther = (CreddetId) other;

		return (this.getNofactura() == castOther.getNofactura())
				&& ((this.getTipofactura() == castOther.getTipofactura()) || (this
						.getTipofactura() != null
						&& castOther.getTipofactura() != null && this
						.getTipofactura().equals(castOther.getTipofactura())))
				&& ((this.getCoditem() == castOther.getCoditem()) || (this
						.getCoditem() != null
						&& castOther.getCoditem() != null && this.getCoditem()
						.equals(castOther.getCoditem())))
				&& ((this.getDescitem() == castOther.getDescitem()) || (this
						.getDescitem() != null
						&& castOther.getDescitem() != null && this
						.getDescitem().equals(castOther.getDescitem())))
				&& ((this.getPreciounit() == castOther.getPreciounit()) || (this
						.getPreciounit() != null
						&& castOther.getPreciounit() != null && this
						.getPreciounit().equals(castOther.getPreciounit())))
				&& (this.getCant() == castOther.getCant())
				&& ((this.getImpuesto() == castOther.getImpuesto()) || (this
						.getImpuesto() != null
						&& castOther.getImpuesto() != null && this
						.getImpuesto().equals(castOther.getImpuesto())))
				&& ((this.getFactor() == castOther.getFactor()) || (this
						.getFactor() != null
						&& castOther.getFactor() != null && this.getFactor()
						.equals(castOther.getFactor())))
				&& ((this.getCodunineg() == castOther.getCodunineg()) || (this
						.getCodunineg() != null
						&& castOther.getCodunineg() != null && this
						.getCodunineg().equals(castOther.getCodunineg())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNofactura();
		result = 37
				* result
				+ (getTipofactura() == null ? 0 : this.getTipofactura()
						.hashCode());
		result = 37 * result
				+ (getCoditem() == null ? 0 : this.getCoditem().hashCode());
		result = 37 * result
				+ (getDescitem() == null ? 0 : this.getDescitem().hashCode());
		result = 37
				* result
				+ (getPreciounit() == null ? 0 : this.getPreciounit()
						.hashCode());
		result = 37 * result + (int) this.getCant();
		result = 37 * result
				+ (getImpuesto() == null ? 0 : this.getImpuesto().hashCode());
		result = 37 * result
				+ (getFactor() == null ? 0 : this.getFactor().hashCode());
		result = 37 * result
				+ (getCodunineg() == null ? 0 : this.getCodunineg().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		return result;
	}

}
