package com.casapellas.entidades;

// Generated May 4, 2012 4:03:35 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Ctaxdeposito generated by hbm2java
 */
public class Ctaxdeposito implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1293421631730595225L;
	private long idctaxdep;
	private Deposito deposito;
	private String idcuenta;
	private String tipomov;
	private BigDecimal monto;
	private String gmmcu;
	private String gmobj;
	private String gmsub;

	public Ctaxdeposito() {
	}

	public Ctaxdeposito(long idctaxdep, Deposito deposito, String idcuenta,
			String tipomov, BigDecimal monto, String gmmcu, String gmobj,
			String gmsub) {
		this.idctaxdep = idctaxdep;
		this.deposito = deposito;
		this.idcuenta = idcuenta;
		this.tipomov = tipomov;
		this.monto = monto;
		this.gmmcu = gmmcu;
		this.gmobj = gmobj;
		this.gmsub = gmsub;
	}

	public long getIdctaxdep() {
		return this.idctaxdep;
	}

	public void setIdctaxdep(long idctaxdep) {
		this.idctaxdep = idctaxdep;
	}

	public Deposito getDeposito() {
		return this.deposito;
	}

	public void setDeposito(Deposito deposito) {
		this.deposito = deposito;
	}

	public String getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(String idcuenta) {
		this.idcuenta = idcuenta;
	}

	public String getTipomov() {
		return this.tipomov;
	}

	public void setTipomov(String tipomov) {
		this.tipomov = tipomov;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public String getGmmcu() {
		return this.gmmcu;
	}

	public void setGmmcu(String gmmcu) {
		this.gmmcu = gmmcu;
	}

	public String getGmobj() {
		return this.gmobj;
	}

	public void setGmobj(String gmobj) {
		this.gmobj = gmobj;
	}

	public String getGmsub() {
		return this.gmsub;
	}

	public void setGmsub(String gmsub) {
		this.gmsub = gmsub;
	}

}
