package com.casapellas.entidades;

// Generated 07-13-2010 09:02:48 AM by Hibernate Tools 3.2.0.b9

/**
 * DepositoId generated by hbm2java
 */
public class DepositoId implements java.io.Serializable {

	private int caid;
	private String codcomp;
	private String codsuc;
	private int nodeposito;

	public DepositoId() {
	}

	public DepositoId(int caid, String codcomp, String codsuc, int nodeposito) {
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.nodeposito = nodeposito;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public int getNodeposito() {
		return this.nodeposito;
	}

	public void setNodeposito(int nodeposito) {
		this.nodeposito = nodeposito;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepositoId))
			return false;
		DepositoId castOther = (DepositoId) other;

		return (this.getCaid() == castOther.getCaid())
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& (this.getNodeposito() == castOther.getNodeposito());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result + this.getNodeposito();
		return result;
	}

}
