package com.casapellas.entidades;
// Generated Jun 26, 2013 11:17:48 AM by Hibernate Tools 3.2.1.GA



/**
 * Detailjde generated by hbm2java
 */
public class Detailjde  implements java.io.Serializable {


     private DetailjdeId id;

    public Detailjde() {
    }

    public Detailjde(DetailjdeId id) {
       this.id = id;
    }
   
    public DetailjdeId getId() {
        return this.id;
    }
    
    public void setId(DetailjdeId id) {
        this.id = id;
    }




}


