package com.casapellas.entidades;

// Generated Jun 26, 2013 11:17:48 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * Df4211Id generated by hbm2java
 */
public class Df4211Id implements java.io.Serializable {

	private static final long serialVersionUID = -6049641845976123810L;
	private int sddoco;
	private String sddcto;
	private String sdnxtr;
	private String sdlttr;
	private int nofactura;
	private String tipofactura;
	private String coditem;
	private String descitem;
	private long preciounit;
	private long cant;
	private String impuesto;
	private int factor;
	private String codunineg;
	private String codsuc;
	private BigDecimal totalcosto;
	private BigDecimal totaldscto;
	private int codcli;
	private int fecha;
	private String lote;
	private int enviadoa;
	private int linea;

	public Df4211Id() {
	}

	
	
	
	public Df4211Id(int sddoco, String sddcto, String sdnxtr, String sdlttr,
			int nofactura, String tipofactura, String coditem, String descitem,
			long preciounit, long cant, String impuesto, int factor,
			String codunineg, String codsuc, BigDecimal totalcosto,
			BigDecimal totaldscto, int codcli, int fecha, String lote,
			int enviadoa, int linea) {
		super();
		this.sddoco = sddoco;
		this.sddcto = sddcto;
		this.sdnxtr = sdnxtr;
		this.sdlttr = sdlttr;
		this.nofactura = nofactura;
		this.tipofactura = tipofactura;
		this.coditem = coditem;
		this.descitem = descitem;
		this.preciounit = preciounit;
		this.cant = cant;
		this.impuesto = impuesto;
		this.factor = factor;
		this.codunineg = codunineg;
		this.codsuc = codsuc;
		this.totalcosto = totalcosto;
		this.totaldscto = totaldscto;
		this.codcli = codcli;
		this.fecha = fecha;
		this.lote = lote;
		this.enviadoa = enviadoa;
		this.linea = linea;
	}




	public Df4211Id(int sddoco, String sddcto, String sdnxtr, String sdlttr,
			int nofactura, String tipofactura, String coditem, String descitem,
			long preciounit, long cant, String impuesto, int factor,
			String codunineg, String codsuc, BigDecimal totalcosto,
			BigDecimal totaldscto, int codcli, int fecha, String lote) {
		this.sddoco = sddoco;
		this.sddcto = sddcto;
		this.sdnxtr = sdnxtr;
		this.sdlttr = sdlttr;
		this.nofactura = nofactura;
		this.tipofactura = tipofactura;
		this.coditem = coditem;
		this.descitem = descitem;
		this.preciounit = preciounit;
		this.cant = cant;
		this.impuesto = impuesto;
		this.factor = factor;
		this.codunineg = codunineg;
		this.codsuc = codsuc;
		this.totalcosto = totalcosto;
		this.totaldscto = totaldscto;
		this.codcli = codcli;
		this.fecha = fecha;
		this.lote = lote;
	}

	public int getSddoco() {
		return this.sddoco;
	}

	public void setSddoco(int sddoco) {
		this.sddoco = sddoco;
	}

	public String getSddcto() {
		return this.sddcto;
	}

	public void setSddcto(String sddcto) {
		this.sddcto = sddcto;
	}

	public String getSdnxtr() {
		return this.sdnxtr;
	}

	public void setSdnxtr(String sdnxtr) {
		this.sdnxtr = sdnxtr;
	}

	public String getSdlttr() {
		return this.sdlttr;
	}

	public void setSdlttr(String sdlttr) {
		this.sdlttr = sdlttr;
	}

	public int getNofactura() {
		return this.nofactura;
	}

	public void setNofactura(int nofactura) {
		this.nofactura = nofactura;
	}

	public String getTipofactura() {
		return this.tipofactura;
	}

	public void setTipofactura(String tipofactura) {
		this.tipofactura = tipofactura;
	}

	public String getCoditem() {
		return this.coditem;
	}

	public void setCoditem(String coditem) {
		this.coditem = coditem;
	}

	public String getDescitem() {
		return this.descitem;
	}

	public void setDescitem(String descitem) {
		this.descitem = descitem;
	}

	public long getPreciounit() {
		return this.preciounit;
	}

	public void setPreciounit(long preciounit) {
		this.preciounit = preciounit;
	}

	public long getCant() {
		return this.cant;
	}

	public void setCant(long cant) {
		this.cant = cant;
	}

	public String getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(String impuesto) {
		this.impuesto = impuesto;
	}

	public int getFactor() {
		return this.factor;
	}

	public void setFactor(int factor) {
		this.factor = factor;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public BigDecimal getTotalcosto() {
		return this.totalcosto;
	}

	public void setTotalcosto(BigDecimal totalcosto) {
		this.totalcosto = totalcosto;
	}

	public BigDecimal getTotaldscto() {
		return this.totaldscto;
	}

	public void setTotaldscto(BigDecimal totaldscto) {
		this.totaldscto = totaldscto;
	}

	public int getCodcli() {
		return this.codcli;
	}

	public void setCodcli(int codcli) {
		this.codcli = codcli;
	}

	public int getFecha() {
		return this.fecha;
	}

	public void setFecha(int fecha) {
		this.fecha = fecha;
	}

	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	public int getEnviadoa() {
		return enviadoa;
	}

	public void setEnviadoa(int enviadoa) {
		this.enviadoa = enviadoa;
	}

	public int getLinea() {
		return linea;
	}

	public void setLinea(int linea) {
		this.linea = linea;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (cant ^ (cant >>> 32));
		result = prime * result + codcli;
		result = prime * result + ((coditem == null) ? 0 : coditem.hashCode());
		result = prime * result + ((codsuc == null) ? 0 : codsuc.hashCode());
		result = prime * result
				+ ((codunineg == null) ? 0 : codunineg.hashCode());
		result = prime * result
				+ ((descitem == null) ? 0 : descitem.hashCode());
		result = prime * result + enviadoa;
		result = prime * result + factor;
		result = prime * result + fecha;
		result = prime * result
				+ ((impuesto == null) ? 0 : impuesto.hashCode());
		result = prime * result + linea;
		result = prime * result + ((lote == null) ? 0 : lote.hashCode());
		result = prime * result + nofactura;
		result = prime * result + (int) (preciounit ^ (preciounit >>> 32));
		result = prime * result + ((sddcto == null) ? 0 : sddcto.hashCode());
		result = prime * result + sddoco;
		result = prime * result + ((sdlttr == null) ? 0 : sdlttr.hashCode());
		result = prime * result + ((sdnxtr == null) ? 0 : sdnxtr.hashCode());
		result = prime * result
				+ ((tipofactura == null) ? 0 : tipofactura.hashCode());
		result = prime * result
				+ ((totalcosto == null) ? 0 : totalcosto.hashCode());
		result = prime * result
				+ ((totaldscto == null) ? 0 : totaldscto.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Df4211Id other = (Df4211Id) obj;
		if (cant != other.cant)
			return false;
		if (codcli != other.codcli)
			return false;
		if (coditem == null) {
			if (other.coditem != null)
				return false;
		} else if (!coditem.equals(other.coditem))
			return false;
		if (codsuc == null) {
			if (other.codsuc != null)
				return false;
		} else if (!codsuc.equals(other.codsuc))
			return false;
		if (codunineg == null) {
			if (other.codunineg != null)
				return false;
		} else if (!codunineg.equals(other.codunineg))
			return false;
		if (descitem == null) {
			if (other.descitem != null)
				return false;
		} else if (!descitem.equals(other.descitem))
			return false;
		if (enviadoa != other.enviadoa)
			return false;
		if (factor != other.factor)
			return false;
		if (fecha != other.fecha)
			return false;
		if (impuesto == null) {
			if (other.impuesto != null)
				return false;
		} else if (!impuesto.equals(other.impuesto))
			return false;
		if (linea != other.linea)
			return false;
		if (lote == null) {
			if (other.lote != null)
				return false;
		} else if (!lote.equals(other.lote))
			return false;
		if (nofactura != other.nofactura)
			return false;
		if (preciounit != other.preciounit)
			return false;
		if (sddcto == null) {
			if (other.sddcto != null)
				return false;
		} else if (!sddcto.equals(other.sddcto))
			return false;
		if (sddoco != other.sddoco)
			return false;
		if (sdlttr == null) {
			if (other.sdlttr != null)
				return false;
		} else if (!sdlttr.equals(other.sdlttr))
			return false;
		if (sdnxtr == null) {
			if (other.sdnxtr != null)
				return false;
		} else if (!sdnxtr.equals(other.sdnxtr))
			return false;
		if (tipofactura == null) {
			if (other.tipofactura != null)
				return false;
		} else if (!tipofactura.equals(other.tipofactura))
			return false;
		if (totalcosto == null) {
			if (other.totalcosto != null)
				return false;
		} else if (!totalcosto.equals(other.totalcosto))
			return false;
		if (totaldscto == null) {
			if (other.totaldscto != null)
				return false;
		} else if (!totaldscto.equals(other.totaldscto))
			return false;
		return true;
	}

}
