package com.casapellas.entidades;
// Generated Jun 26, 2013 11:17:48 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DfactjdeconId generated by hbm2java
 */
public class DfactjdeconId  implements java.io.Serializable {


     private int nofactura;
     private String tipofactura;
     private String coditem;
     private String descitem;
     private long preciounit;
     private long cant;
     private String impuesto;
     private int factor;
     private String codunineg;
     private String codsuc;
     private BigDecimal pcosto;
     private BigDecimal descuento;
     private int codcli;
     private int fecha;
     private String lote;

    public DfactjdeconId() {
    }

    public DfactjdeconId(int nofactura, String tipofactura, String coditem, String descitem, long preciounit, long cant, String impuesto, int factor, String codunineg, String codsuc, BigDecimal pcosto, BigDecimal descuento, int codcli, int fecha, String lote) {
       this.nofactura = nofactura;
       this.tipofactura = tipofactura;
       this.coditem = coditem;
       this.descitem = descitem;
       this.preciounit = preciounit;
       this.cant = cant;
       this.impuesto = impuesto;
       this.factor = factor;
       this.codunineg = codunineg;
       this.codsuc = codsuc;
       this.pcosto = pcosto;
       this.descuento = descuento;
       this.codcli = codcli;
       this.fecha = fecha;
       this.lote = lote;
    }
   
    public int getNofactura() {
        return this.nofactura;
    }
    
    public void setNofactura(int nofactura) {
        this.nofactura = nofactura;
    }
    public String getTipofactura() {
        return this.tipofactura;
    }
    
    public void setTipofactura(String tipofactura) {
        this.tipofactura = tipofactura;
    }
    public String getCoditem() {
        return this.coditem;
    }
    
    public void setCoditem(String coditem) {
        this.coditem = coditem;
    }
    public String getDescitem() {
        return this.descitem;
    }
    
    public void setDescitem(String descitem) {
        this.descitem = descitem;
    }
    public long getPreciounit() {
        return this.preciounit;
    }
    
    public void setPreciounit(long preciounit) {
        this.preciounit = preciounit;
    }
    public long getCant() {
        return this.cant;
    }
    
    public void setCant(long cant) {
        this.cant = cant;
    }
    public String getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(String impuesto) {
        this.impuesto = impuesto;
    }
    public int getFactor() {
        return this.factor;
    }
    
    public void setFactor(int factor) {
        this.factor = factor;
    }
    public String getCodunineg() {
        return this.codunineg;
    }
    
    public void setCodunineg(String codunineg) {
        this.codunineg = codunineg;
    }
    public String getCodsuc() {
        return this.codsuc;
    }
    
    public void setCodsuc(String codsuc) {
        this.codsuc = codsuc;
    }
    public BigDecimal getPcosto() {
        return this.pcosto;
    }
    
    public void setPcosto(BigDecimal pcosto) {
        this.pcosto = pcosto;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    public int getCodcli() {
        return this.codcli;
    }
    
    public void setCodcli(int codcli) {
        this.codcli = codcli;
    }
    public int getFecha() {
        return this.fecha;
    }
    
    public void setFecha(int fecha) {
        this.fecha = fecha;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DfactjdeconId) ) return false;
		 DfactjdeconId castOther = ( DfactjdeconId ) other; 
         
		 return (this.getNofactura()==castOther.getNofactura())
 && ( (this.getTipofactura()==castOther.getTipofactura()) || ( this.getTipofactura()!=null && castOther.getTipofactura()!=null && this.getTipofactura().equals(castOther.getTipofactura()) ) )
 && ( (this.getCoditem()==castOther.getCoditem()) || ( this.getCoditem()!=null && castOther.getCoditem()!=null && this.getCoditem().equals(castOther.getCoditem()) ) )
 && ( (this.getDescitem()==castOther.getDescitem()) || ( this.getDescitem()!=null && castOther.getDescitem()!=null && this.getDescitem().equals(castOther.getDescitem()) ) )
 && (this.getPreciounit()==castOther.getPreciounit())
 && (this.getCant()==castOther.getCant())
 && ( (this.getImpuesto()==castOther.getImpuesto()) || ( this.getImpuesto()!=null && castOther.getImpuesto()!=null && this.getImpuesto().equals(castOther.getImpuesto()) ) )
 && (this.getFactor()==castOther.getFactor())
 && ( (this.getCodunineg()==castOther.getCodunineg()) || ( this.getCodunineg()!=null && castOther.getCodunineg()!=null && this.getCodunineg().equals(castOther.getCodunineg()) ) )
 && ( (this.getCodsuc()==castOther.getCodsuc()) || ( this.getCodsuc()!=null && castOther.getCodsuc()!=null && this.getCodsuc().equals(castOther.getCodsuc()) ) )
 && ( (this.getPcosto()==castOther.getPcosto()) || ( this.getPcosto()!=null && castOther.getPcosto()!=null && this.getPcosto().equals(castOther.getPcosto()) ) )
 && ( (this.getDescuento()==castOther.getDescuento()) || ( this.getDescuento()!=null && castOther.getDescuento()!=null && this.getDescuento().equals(castOther.getDescuento()) ) )
 && (this.getCodcli()==castOther.getCodcli())
 && (this.getFecha()==castOther.getFecha())
 && ( (this.getLote()==castOther.getLote()) || ( this.getLote()!=null && castOther.getLote()!=null && this.getLote().equals(castOther.getLote()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNofactura();
         result = 37 * result + ( getTipofactura() == null ? 0 : this.getTipofactura().hashCode() );
         result = 37 * result + ( getCoditem() == null ? 0 : this.getCoditem().hashCode() );
         result = 37 * result + ( getDescitem() == null ? 0 : this.getDescitem().hashCode() );
         result = 37 * result + (int) this.getPreciounit();
         result = 37 * result + (int) this.getCant();
         result = 37 * result + ( getImpuesto() == null ? 0 : this.getImpuesto().hashCode() );
         result = 37 * result + this.getFactor();
         result = 37 * result + ( getCodunineg() == null ? 0 : this.getCodunineg().hashCode() );
         result = 37 * result + ( getCodsuc() == null ? 0 : this.getCodsuc().hashCode() );
         result = 37 * result + ( getPcosto() == null ? 0 : this.getPcosto().hashCode() );
         result = 37 * result + ( getDescuento() == null ? 0 : this.getDescuento().hashCode() );
         result = 37 * result + this.getCodcli();
         result = 37 * result + this.getFecha();
         result = 37 * result + ( getLote() == null ? 0 : this.getLote().hashCode() );
         return result;
   }   


}


