package com.casapellas.entidades;

import java.math.BigDecimal;

// Generated 28/12/2009 11:38:32 AM by Hibernate Tools 3.2.0.b9

/**
 * Elementofin generated by hbm2java
 */
public class Elementofin implements java.io.Serializable {

	private ElementofinId id;
	private BigDecimal total;

	public Elementofin() {
	}

	public Elementofin(ElementofinId id) {
		this.id = id;
	}

	public ElementofinId getId() {
		return this.id;
	}

	public void setId(ElementofinId id) {
		this.id = id;
	}

	public BigDecimal getTotal() {
		return total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}
}
