package com.casapellas.entidades;

// Generated 16/06/2009 19:00:10 by Hibernate Tools 3.2.0.b9

/**
 * F55ca020 generated by hbm2java
 */
public class F55ca020 implements java.io.Serializable {

	private F55ca020Id id;

	public F55ca020() {
	}

	public F55ca020(F55ca020Id id) {
		this.id = id;
	}

	public F55ca020Id getId() {
		return this.id;
	}

	public void setId(F55ca020Id id) {
		this.id = id;
	}

}
