package com.casapellas.entidades;

// Generated 4/02/2009 17:10:07 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * F55ca013Id generated by hbm2java
 */
public class F55ca013Id implements java.io.Serializable {

	private int c3id;

	private String c3rp01;

	private String c3crcd;

	private BigDecimal c3miam;

	private char c3stat;

	public F55ca013Id() {
	}

	public F55ca013Id(int c3id, String c3rp01, String c3crcd,
			BigDecimal c3miam, char c3stat) {
		this.c3id = c3id;
		this.c3rp01 = c3rp01;
		this.c3crcd = c3crcd;
		this.c3miam = c3miam;
		this.c3stat = c3stat;
	}

	public int getC3id() {
		return this.c3id;
	}

	public void setC3id(int c3id) {
		this.c3id = c3id;
	}

	public String getC3rp01() {
		return this.c3rp01;
	}

	public void setC3rp01(String c3rp01) {
		this.c3rp01 = c3rp01;
	}

	public String getC3crcd() {
		return this.c3crcd;
	}

	public void setC3crcd(String c3crcd) {
		this.c3crcd = c3crcd;
	}

	public BigDecimal getC3miam() {
		return this.c3miam;
	}

	public void setC3miam(BigDecimal c3miam) {
		this.c3miam = c3miam;
	}

	public char getC3stat() {
		return this.c3stat;
	}

	public void setC3stat(char c3stat) {
		this.c3stat = c3stat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof F55ca013Id))
			return false;
		F55ca013Id castOther = (F55ca013Id) other;

		return (this.getC3id() == castOther.getC3id())
				&& ((this.getC3rp01() == castOther.getC3rp01()) || (this
						.getC3rp01() != null
						&& castOther.getC3rp01() != null && this.getC3rp01()
						.equals(castOther.getC3rp01())))
				&& ((this.getC3crcd() == castOther.getC3crcd()) || (this
						.getC3crcd() != null
						&& castOther.getC3crcd() != null && this.getC3crcd()
						.equals(castOther.getC3crcd())))
				&& ((this.getC3miam() == castOther.getC3miam()) || (this
						.getC3miam() != null
						&& castOther.getC3miam() != null && this.getC3miam()
						.equals(castOther.getC3miam())))
				&& (this.getC3stat() == castOther.getC3stat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getC3id();
		result = 37 * result
				+ (getC3rp01() == null ? 0 : this.getC3rp01().hashCode());
		result = 37 * result
				+ (getC3crcd() == null ? 0 : this.getC3crcd().hashCode());
		result = 37 * result
				+ (getC3miam() == null ? 0 : this.getC3miam().hashCode());
		result = 37 * result + this.getC3stat();
		return result;
	}

}
