package com.casapellas.entidades;

// Generated 17/11/2009 15:46:04 by Hibernate Tools 3.2.0.b9

/**
 * F55ca018 generated by hbm2java
 */
public class F55ca018 implements java.io.Serializable {

	private F55ca018Id id;

	public F55ca018() {
	}

	public F55ca018(F55ca018Id id) {
		this.id = id;
	}

	public F55ca018Id getId() {
		return this.id;
	}

	public void setId(F55ca018Id id) {
		this.id = id;
	}

}
