package com.casapellas.entidades;

// Generated 11-24-2009 03:50:56 PM by Hibernate Tools 3.2.0.b9

/**
 * F55ca019Id generated by hbm2java
 */
public class F55ca019Id implements java.io.Serializable {

	private static final long serialVersionUID = -4060366811511259504L;

	private String camcul;

	private String cadoc;

	private String castat;

	private String tipodoc;

	private String cacrcd;

	public F55ca019Id() {
	}

	public F55ca019Id(String camcul, String cadoc, String castat, String tipodoc,
			String cacrcd) {
		this.camcul = camcul;
		this.cadoc = cadoc;
		this.castat = castat;
		this.tipodoc = tipodoc;
		this.cacrcd = cacrcd;
	}

	public String getCamcul() {
		return this.camcul;
	}

	public void setCamcul(String camcul) {
		this.camcul = camcul;
	}

	public String getCadoc() {
		return this.cadoc;
	}

	public void setCadoc(String cadoc) {
		this.cadoc = cadoc;
	}

	public String getCastat() {
		return this.castat;
	}

	public void setCastat(String castat) {
		this.castat = castat;
	}

	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	public String getCacrcd() {
		return this.cacrcd;
	}

	public void setCacrcd(String cacrcd) {
		this.cacrcd = cacrcd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof F55ca019Id))
			return false;
		F55ca019Id castOther = (F55ca019Id) other;

		return ((this.getCamcul() == castOther.getCamcul()) || (this
				.getCamcul() != null
				&& castOther.getCamcul() != null && this.getCamcul().equals(
				castOther.getCamcul())))
				&& ((this.getCadoc() == castOther.getCadoc()) || (this
						.getCadoc() != null
						&& castOther.getCadoc() != null && this.getCadoc()
						.equals(castOther.getCadoc())))
				&& (this.getCastat() == castOther.getCastat())
				&& ((this.getTipodoc() == castOther.getTipodoc()) || (this
						.getTipodoc() != null
						&& castOther.getTipodoc() != null && this.getTipodoc()
						.equals(castOther.getTipodoc())))
				&& ((this.getCacrcd() == castOther.getCacrcd()) || (this
						.getCacrcd() != null
						&& castOther.getCacrcd() != null && this.getCacrcd()
						.equals(castOther.getCacrcd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCamcul() == null ? 0 : this.getCamcul().hashCode());
		result = 37 * result
				+ (getCadoc() == null ? 0 : this.getCadoc().hashCode());
//		result = 37 * result + this.getCastat();
		result = 37 * result
				+ (getTipodoc() == null ? 0 : this.getTipodoc().hashCode());
		result = 37 * result
				+ (getCacrcd() == null ? 0 : this.getCacrcd().hashCode());
		return result;
	}

}
