package com.casapellas.entidades;

// Generated 4/02/2009 17:10:07 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * F55ca016Id generated by hbm2java
 */
public class F55ca016Id implements java.io.Serializable {

	private int c6id;

	private String c6rp01;

	private String c6rp07;

	private String c6afil;

	private BigDecimal c6cot;

	private String c6rmk;

	private char c6stat;

	public F55ca016Id() {
	}

	public F55ca016Id(int c6id, String c6rp01, String c6rp07, String c6afil,
			BigDecimal c6cot, String c6rmk, char c6stat) {
		this.c6id = c6id;
		this.c6rp01 = c6rp01;
		this.c6rp07 = c6rp07;
		this.c6afil = c6afil;
		this.c6cot = c6cot;
		this.c6rmk = c6rmk;
		this.c6stat = c6stat;
	}

	public int getC6id() {
		return this.c6id;
	}

	public void setC6id(int c6id) {
		this.c6id = c6id;
	}

	public String getC6rp01() {
		return this.c6rp01;
	}

	public void setC6rp01(String c6rp01) {
		this.c6rp01 = c6rp01;
	}

	public String getC6rp07() {
		return this.c6rp07;
	}

	public void setC6rp07(String c6rp07) {
		this.c6rp07 = c6rp07;
	}

	public String getC6afil() {
		return this.c6afil;
	}

	public void setC6afil(String c6afil) {
		this.c6afil = c6afil;
	}

	public BigDecimal getC6cot() {
		return this.c6cot;
	}

	public void setC6cot(BigDecimal c6cot) {
		this.c6cot = c6cot;
	}

	public String getC6rmk() {
		return this.c6rmk;
	}

	public void setC6rmk(String c6rmk) {
		this.c6rmk = c6rmk;
	}

	public char getC6stat() {
		return this.c6stat;
	}

	public void setC6stat(char c6stat) {
		this.c6stat = c6stat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof F55ca016Id))
			return false;
		F55ca016Id castOther = (F55ca016Id) other;

		return (this.getC6id() == castOther.getC6id())
				&& ((this.getC6rp01() == castOther.getC6rp01()) || (this
						.getC6rp01() != null
						&& castOther.getC6rp01() != null && this.getC6rp01()
						.equals(castOther.getC6rp01())))
				&& ((this.getC6rp07() == castOther.getC6rp07()) || (this
						.getC6rp07() != null
						&& castOther.getC6rp07() != null && this.getC6rp07()
						.equals(castOther.getC6rp07())))
				&& ((this.getC6afil() == castOther.getC6afil()) || (this
						.getC6afil() != null
						&& castOther.getC6afil() != null && this.getC6afil()
						.equals(castOther.getC6afil())))
				&& ((this.getC6cot() == castOther.getC6cot()) || (this
						.getC6cot() != null
						&& castOther.getC6cot() != null && this.getC6cot()
						.equals(castOther.getC6cot())))
				&& ((this.getC6rmk() == castOther.getC6rmk()) || (this
						.getC6rmk() != null
						&& castOther.getC6rmk() != null && this.getC6rmk()
						.equals(castOther.getC6rmk())))
				&& (this.getC6stat() == castOther.getC6stat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getC6id();
		result = 37 * result
				+ (getC6rp01() == null ? 0 : this.getC6rp01().hashCode());
		result = 37 * result
				+ (getC6rp07() == null ? 0 : this.getC6rp07().hashCode());
		result = 37 * result
				+ (getC6afil() == null ? 0 : this.getC6afil().hashCode());
		result = 37 * result
				+ (getC6cot() == null ? 0 : this.getC6cot().hashCode());
		result = 37 * result
				+ (getC6rmk() == null ? 0 : this.getC6rmk().hashCode());
		result = 37 * result + this.getC6stat();
		return result;
	}

}
