package com.casapellas.entidades;

// Generated 1/07/2009 17:55:54 by Hibernate Tools 3.2.0.b9

/**
 * F55ca017Id generated by hbm2java
 */
public class F55ca017Id implements java.io.Serializable {

	private int c7id;

	private String c7co;

	private String c7mcul;

	private char c7stat;

	private String c7locn;

	public F55ca017Id() {
	}

	public F55ca017Id(int c7id, String c7co, String c7mcul, char c7stat,
			String c7locn) {
		this.c7id = c7id;
		this.c7co = c7co;
		this.c7mcul = c7mcul;
		this.c7stat = c7stat;
		this.c7locn = c7locn;
	}

	public int getC7id() {
		return this.c7id;
	}

	public void setC7id(int c7id) {
		this.c7id = c7id;
	}

	public String getC7co() {
		return this.c7co;
	}

	public void setC7co(String c7co) {
		this.c7co = c7co;
	}

	public String getC7mcul() {
		return this.c7mcul;
	}

	public void setC7mcul(String c7mcul) {
		this.c7mcul = c7mcul;
	}

	public char getC7stat() {
		return this.c7stat;
	}

	public void setC7stat(char c7stat) {
		this.c7stat = c7stat;
	}

	public String getC7locn() {
		return this.c7locn;
	}

	public void setC7locn(String c7locn) {
		this.c7locn = c7locn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof F55ca017Id))
			return false;
		F55ca017Id castOther = (F55ca017Id) other;

		return (this.getC7id() == castOther.getC7id())
				&& ((this.getC7co() == castOther.getC7co()) || (this.getC7co() != null
						&& castOther.getC7co() != null && this.getC7co()
						.equals(castOther.getC7co())))
				&& ((this.getC7mcul() == castOther.getC7mcul()) || (this
						.getC7mcul() != null
						&& castOther.getC7mcul() != null && this.getC7mcul()
						.equals(castOther.getC7mcul())))
				&& (this.getC7stat() == castOther.getC7stat())
				&& ((this.getC7locn() == castOther.getC7locn()) || (this
						.getC7locn() != null
						&& castOther.getC7locn() != null && this.getC7locn()
						.equals(castOther.getC7locn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getC7id();
		result = 37 * result
				+ (getC7co() == null ? 0 : this.getC7co().hashCode());
		result = 37 * result
				+ (getC7mcul() == null ? 0 : this.getC7mcul().hashCode());
		result = 37 * result + this.getC7stat();
		result = 37 * result
				+ (getC7locn() == null ? 0 : this.getC7locn().hashCode());
		return result;
	}

}
