package com.casapellas.entidades;

// default package
// Generated Dec 10, 2011 2:39:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * F55ca034Id generated by hbm2java
 */
public class F55ca034Id implements java.io.Serializable {

	private int b4id;
	private String b4crp01;
	private String b4mcu;
	private String b4obj;
	private String b4sub;
	private String b4crcd;

	public F55ca034Id() {
	}

	public F55ca034Id(int b4id, String b4crp01, String b4mcu, String b4obj,
			String b4sub, String b4crcd) {
		this.b4id = b4id;
		this.b4crp01 = b4crp01;
		this.b4mcu = b4mcu;
		this.b4obj = b4obj;
		this.b4sub = b4sub;
		this.b4crcd = b4crcd;
	}

	public int getB4id() {
		return this.b4id;
	}

	public void setB4id(int b4id) {
		this.b4id = b4id;
	}

	public String getB4crp01() {
		return this.b4crp01;
	}

	public void setB4crp01(String b4crp01) {
		this.b4crp01 = b4crp01;
	}

	public String getB4mcu() {
		return this.b4mcu;
	}

	public void setB4mcu(String b4mcu) {
		this.b4mcu = b4mcu;
	}

	public String getB4obj() {
		return this.b4obj;
	}

	public void setB4obj(String b4obj) {
		this.b4obj = b4obj;
	}

	public String getB4sub() {
		return this.b4sub;
	}

	public void setB4sub(String b4sub) {
		this.b4sub = b4sub;
	}

	public String getB4crcd() {
		return this.b4crcd;
	}

	public void setB4crcd(String b4crcd) {
		this.b4crcd = b4crcd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof F55ca034Id))
			return false;
		F55ca034Id castOther = (F55ca034Id) other;

		return (this.getB4id() == castOther.getB4id())
				&& ((this.getB4crp01() == castOther.getB4crp01()) || (this
						.getB4crp01() != null && castOther.getB4crp01() != null && this
						.getB4crp01().equals(castOther.getB4crp01())))
				&& ((this.getB4mcu() == castOther.getB4mcu()) || (this
						.getB4mcu() != null && castOther.getB4mcu() != null && this
						.getB4mcu().equals(castOther.getB4mcu())))
				&& ((this.getB4obj() == castOther.getB4obj()) || (this
						.getB4obj() != null && castOther.getB4obj() != null && this
						.getB4obj().equals(castOther.getB4obj())))
				&& ((this.getB4sub() == castOther.getB4sub()) || (this
						.getB4sub() != null && castOther.getB4sub() != null && this
						.getB4sub().equals(castOther.getB4sub())))
				&& ((this.getB4crcd() == castOther.getB4crcd()) || (this
						.getB4crcd() != null && castOther.getB4crcd() != null && this
						.getB4crcd().equals(castOther.getB4crcd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getB4id();
		result = 37 * result
				+ (getB4crp01() == null ? 0 : this.getB4crp01().hashCode());
		result = 37 * result
				+ (getB4mcu() == null ? 0 : this.getB4mcu().hashCode());
		result = 37 * result
				+ (getB4obj() == null ? 0 : this.getB4obj().hashCode());
		result = 37 * result
				+ (getB4sub() == null ? 0 : this.getB4sub().hashCode());
		result = 37 * result
				+ (getB4crcd() == null ? 0 : this.getB4crcd().hashCode());
		return result;
	}

}
