package com.casapellas.entidades;

// Generated 4/02/2009 17:10:07 by Hibernate Tools 3.2.0.b9

/**
 * F55ca012 generated by hbm2java
 */
public class F55ca012 implements java.io.Serializable {

	private F55ca012Id id;

	public F55ca012() {
	}

	public F55ca012(F55ca012Id id) {
		this.id = id;
	}

	public F55ca012Id getId() {
		return this.id;
	}

	public void setId(F55ca012Id id) {
		this.id = id;
	}

}
