package com.casapellas.entidades;

// Generated May 28, 2012 5:17:41 PM by Hibernate Tools 3.2.4.GA

/**
 * F55ca014 generated by hbm2java
 */
public class F55ca014 implements java.io.Serializable {

 
	private static final long serialVersionUID = 6886011991598321097L;
	private F55ca014Id id;

	public F55ca014() {
	}

	public F55ca014(F55ca014Id id) {
		this.id = id;
	}

	public F55ca014Id getId() {
		return this.id;
	}

	public void setId(F55ca014Id id) {
		this.id = id;
	}

}
