package com.casapellas.entidades;

// Generated 16/06/2009 19:00:10 by Hibernate Tools 3.2.0.b9

/**
 * F55ca021 generated by hbm2java
 */
public class F55ca021 implements java.io.Serializable {

	private F55ca021Id id;

	public F55ca021() {
	}

	public F55ca021(F55ca021Id id) {
		this.id = id;
	}

	public F55ca021Id getId() {
		return this.id;
	}

	public void setId(F55ca021Id id) {
		this.id = id;
	}

}
