package com.casapellas.entidades;

// Generated May 28, 2012 5:17:41 PM by Hibernate Tools 3.2.4.GA

/**
 * F55ca022 generated by hbm2java
 */
public class F55ca022 implements java.io.Serializable {

	private F55ca022Id id;

	public F55ca022() {
	}

	public F55ca022(F55ca022Id id) {
		this.id = id;
	}

	public F55ca022Id getId() {
		return this.id;
	}

	public void setId(F55ca022Id id) {
		this.id = id;
	}

}
