package com.casapellas.entidades;

// Generated 05-10-2012 02:02:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * F55diaven generated by hbm2java
 */
public class F55diaven implements java.io.Serializable {

	private F55diavenId id;

	public F55diaven() {
	}

	public F55diaven(F55diavenId id) {
		this.id = id;
	}

	public F55diavenId getId() {
		return this.id;
	}

	public void setId(F55diavenId id) {
		this.id = id;
	}

}
