package com.casapellas.entidades;

// Generated 05-10-2012 02:02:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * F55detinte generated by hbm2java
 */
public class F55detinte implements java.io.Serializable {

	private F55detinteId id;

	public F55detinte() {
	}

	public F55detinte(F55detinteId id) {
		this.id = id;
	}

	public F55detinteId getId() {
		return this.id;
	}

	public void setId(F55detinteId id) {
		this.id = id;
	}

}
