package com.casapellas.entidades;

import java.math.BigDecimal;

// Generated 05/03/2010 4:04:20 PM by Hibernate Tools 3.2.0.b9

/**
 * Finandet generated by hbm2java
 */
public class Finandet implements java.io.Serializable {
	
	private static final long serialVersionUID = 3823540505227091441L;
	private FinandetId id;
	private BigDecimal mora;
	private BigDecimal consolidado;
	private BigDecimal montopend;
	private BigDecimal montoAplicar;
	private BigDecimal interesPend;
	
	private int rpdoc;
	private String rpdct;
	private int rpdivj;
	private String compenslm;
	private String rpmcu;
	private String tipopago;
	private String nomcli;
	private BigDecimal montopJDE;
	private BigDecimal montoAplJDE;
	private BigDecimal tasaJDE;
	private BigDecimal montoAplicado;
	
	private BigDecimal cpendiente;
	
	private boolean pagoparcial;
	private boolean abonoPrincipal;
	
	private String numeroBatchIF;
	private String numeroBatchMF;
	private String diasVencidos;
	
	
	public BigDecimal getMontoAplicado() {
		return montoAplicado;
	}

	public void setMontoAplicado(BigDecimal montoAplicado) {
		this.montoAplicado = montoAplicado;
	}

	public Finandet() {
	}

	public Finandet(FinandetId id) {
		this.id = id;
	}

	public FinandetId getId() {
		return this.id;
	}

	public void setId(FinandetId id) {
		this.id = id;
	}

	public BigDecimal getMora() {
		return mora;
	}

	public void setMora(BigDecimal mora) {
		this.mora = mora;
	}

	public BigDecimal getConsolidado() {
		return consolidado;
	}

	public void setConsolidado(BigDecimal consolidado) {
		this.consolidado = consolidado;
	}

	public BigDecimal getMontopend() {
		return montopend;
	}

	public void setMontopend(BigDecimal montopend) {
		this.montopend = montopend;
	}

	public BigDecimal getMontoAplicar() {
		return montoAplicar;
	}

	public void setMontoAplicar(BigDecimal montoAplicar) {
		this.montoAplicar = montoAplicar;
	}

	public int getRpdoc() {
		return rpdoc;
	}

	public void setRpdoc(int rpdoc) {
		this.rpdoc = rpdoc;
	}

	public String getRpdct() {
		return rpdct;
	}

	public void setRpdct(String rpdct) {
		this.rpdct = rpdct;
	}

	public int getRpdivj() {
		return rpdivj;
	}

	public void setRpdivj(int rpdivj) {
		this.rpdivj = rpdivj;
	}

	public String getCompenslm() {
		return compenslm;
	}

	public void setCompenslm(String compenslm) {
		this.compenslm = compenslm;
	}

	public String getRpmcu() {
		return rpmcu;
	}

	public void setRpmcu(String rpmcu) {
		this.rpmcu = rpmcu;
	}

	public String getTipopago() {
		return tipopago;
	}

	public void setTipopago(String tipopago) {
		this.tipopago = tipopago;
	}

	public String getNomcli() {
		return nomcli;
	}

	public void setNomcli(String nomcli) {
		this.nomcli = nomcli;
	}

	public BigDecimal getMontopJDE() {
		return montopJDE;
	}

	public void setMontopJDE(BigDecimal montopJDE) {
		this.montopJDE = montopJDE;
	}

	public BigDecimal getMontoAplJDE() {
		return montoAplJDE;
	}

	public void setMontoAplJDE(BigDecimal montoAplJDE) {
		this.montoAplJDE = montoAplJDE;
	}

	public BigDecimal getTasaJDE() {
		return tasaJDE;
	}

	public void setTasaJDE(BigDecimal tasaJDE) {
		this.tasaJDE = tasaJDE;
	}

	public BigDecimal getInteresPend() {
		return interesPend;
	}

	public void setInteresPend(BigDecimal interesPend) {
		this.interesPend = interesPend;
	}

	public BigDecimal getCpendiente() {
		return cpendiente;
	}

	public void setCpendiente(BigDecimal cpendiente) {
		this.cpendiente = cpendiente;
	}
	public boolean isPagoparcial() {
		return pagoparcial;
	}

	public void setPagoparcial(boolean pagoparcial) {
		this.pagoparcial = pagoparcial;
	}

	public boolean isAbonoPrincipal() {
		return abonoPrincipal;
	}

	public void setAbonoPrincipal(boolean abonoPrincipal) {
		this.abonoPrincipal = abonoPrincipal;
	}

	public String getNumeroBatchIF() {
		return numeroBatchIF;
	}

	public void setNumeroBatchIF(String numeroBatchIF) {
		this.numeroBatchIF = numeroBatchIF;
	}

	public String getNumeroBatchMF() {
		return numeroBatchMF;
	}

	public void setNumeroBatchMF(String numeroBatchMF) {
		this.numeroBatchMF = numeroBatchMF;
	}

	public String getDiasVencidos() {
		return diasVencidos;
	}

	public void setDiasVencidos(String diasVencidos) {
		this.diasVencidos = diasVencidos;
	}
	
	
}
