package com.casapellas.entidades;

// Generated 7/02/2009 11:18:13 by Hibernate Tools 3.2.0.b9

/**
 * Metpago generated by hbm2java
 */
public class Metpago implements java.io.Serializable {

	private MetpagoId id;

	public Metpago() {
	}

	public Metpago(MetpagoId id) {
		this.id = id;
	}

	public MetpagoId getId() {
		return this.id;
	}

	public void setId(MetpagoId id) {
		this.id = id;
	}

}
