package com.casapellas.entidades;

// Generated Oct 25, 2012 1:49:19 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Minutadp generated by hbm2java
 */
public class Minutadp implements java.io.Serializable {

	private static final long serialVersionUID = -8662791803548028731L;
	private int idminuta;
	private String codcomp;
	private String moneda;
	private String cuenta;
	private int banco;
	private String ctacntbl;
	private int nosiguiente;
	private String nombrebco;
	private String nmbrcta;
	private String usrcrea;
	private String usrmod;
	private Date fechamod;
	private Date horamod;
	private Date fechacrea;
	private boolean estado;
	
	private int mindpxcajaNosiguente;
	private String nosiguienteDisplay;
	private int numerominutamanual;

	public Minutadp() {
	}

	public Minutadp(int idminuta, String codcomp, String moneda, String cuenta,
			int banco, String ctacntbl, int nosiguiente, String nombrebco,
			String nmbrcta, String usrcrea, String usrmod, Date fechamod,
			Date horamod, Date fechacrea, boolean estado, int mindpxcajaNosiguente, String nosiguienteDisplay) {
		this.idminuta = idminuta;
		this.codcomp = codcomp;
		this.moneda = moneda;
		this.cuenta = cuenta;
		this.banco = banco;
		this.ctacntbl = ctacntbl;
		this.nosiguiente = nosiguiente;
		this.nombrebco = nombrebco;
		this.nmbrcta = nmbrcta;
		this.usrcrea = usrcrea;
		this.usrmod = usrmod;
		this.fechamod = fechamod;
		this.horamod = horamod;
		this.fechacrea = fechacrea;
		this.estado = estado;
		this.mindpxcajaNosiguente = mindpxcajaNosiguente;
		this.nosiguienteDisplay = nosiguienteDisplay;
	}

	public int getIdminuta() {
		return this.idminuta;
	}

	public void setIdminuta(int idminuta) {
		this.idminuta = idminuta;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	public int getBanco() {
		return this.banco;
	}

	public void setBanco(int banco) {
		this.banco = banco;
	}

	public String getCtacntbl() {
		return this.ctacntbl;
	}

	public void setCtacntbl(String ctacntbl) {
		this.ctacntbl = ctacntbl;
	}

	public int getNosiguiente() {
		return this.nosiguiente;
	}

	public void setNosiguiente(int nosiguiente) {
		this.nosiguiente = nosiguiente;
	}

	public String getNombrebco() {
		return this.nombrebco;
	}

	public void setNombrebco(String nombrebco) {
		this.nombrebco = nombrebco;
	}

	public String getNmbrcta() {
		return this.nmbrcta;
	}

	public void setNmbrcta(String nmbrcta) {
		this.nmbrcta = nmbrcta;
	}

	public String getUsrcrea() {
		return this.usrcrea;
	}

	public void setUsrcrea(String usrcrea) {
		this.usrcrea = usrcrea;
	}

	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public Date getHoramod() {
		return this.horamod;
	}

	public void setHoramod(Date horamod) {
		this.horamod = horamod;
	}

	public Date getFechacrea() {
		return this.fechacrea;
	}

	public void setFechacrea(Date fechacrea) {
		this.fechacrea = fechacrea;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@Override
	public Minutadp clone(){
		return new Minutadp(idminuta, codcomp, moneda, 
				cuenta, banco, ctacntbl, nosiguiente, 
				nombrebco, nmbrcta, usrcrea, 
				usrmod, fechamod, horamod, 
				fechacrea, estado, mindpxcajaNosiguente, nosiguienteDisplay);
	}

	public int getMindpxcajaNosiguente() {
		return mindpxcajaNosiguente;
	}

	public void setMindpxcajaNosiguente(int mindpxcajaNosiguente) {
		this.mindpxcajaNosiguente = mindpxcajaNosiguente;
	}

	public String getNosiguienteDisplay() {
		return nosiguienteDisplay;
	}

	public void setNosiguienteDisplay(String nosiguienteDisplay) {
		this.nosiguienteDisplay = nosiguienteDisplay;
	}

	public int getNumerominutamanual() {
		return numerominutamanual;
	}

	public void setNumerominutamanual(int numerominutamanual) {
		this.numerominutamanual = numerominutamanual;
	}
	
}
