package com.casapellas.entidades;

// Generated Feb 20, 2013 11:20:20 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Monedaxlinea generated by hbm2java
 */
public class Monedaxlinea implements java.io.Serializable {
	
	private static final long serialVersionUID = -3772578478284860425L;
	private int idmonedaxlinea;
	private String lineaneg;
	private String moneda;
	private int codusuario;
	private String usuario;
	private Date fechacrea;
	private Date fechamod;

	public Monedaxlinea() {
	}

	public Monedaxlinea(int idmonedaxlinea, String lineaneg, String moneda,
			int codusuario, String usuario, Date fechacrea, Date fechamod) {
		this.idmonedaxlinea = idmonedaxlinea;
		this.lineaneg = lineaneg;
		this.moneda = moneda;
		this.codusuario = codusuario;
		this.usuario = usuario;
		this.fechacrea = fechacrea;
		this.fechamod = fechamod;
	}

	public int getIdmonedaxlinea() {
		return this.idmonedaxlinea;
	}

	public void setIdmonedaxlinea(int idmonedaxlinea) {
		this.idmonedaxlinea = idmonedaxlinea;
	}

	public String getLineaneg() {
		return this.lineaneg;
	}

	public void setLineaneg(String lineaneg) {
		this.lineaneg = lineaneg;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public int getCodusuario() {
		return this.codusuario;
	}

	public void setCodusuario(int codusuario) {
		this.codusuario = codusuario;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechacrea() {
		return this.fechacrea;
	}

	public void setFechacrea(Date fechacrea) {
		this.fechacrea = fechacrea;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
