package com.casapellas.entidades;

// Generated 08-25-2009 10:16:18 AM by Hibernate Tools 3.2.0.b9

/**
 * NumcajaId generated by hbm2java
 */
public class NumcajaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8447205879135871304L;

	private String codnumeracion;

	private int caid;

	private String codcomp;

	private String codsuc;

	public NumcajaId() {
	}

	public NumcajaId(String codnumeracion, int caid, String codcomp,
			String codsuc) {
		this.codnumeracion = codnumeracion;
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
	}

	public String getCodnumeracion() {
		return this.codnumeracion;
	}

	public void setCodnumeracion(String codnumeracion) {
		this.codnumeracion = codnumeracion;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NumcajaId))
			return false;
		NumcajaId castOther = (NumcajaId) other;

		return ((this.getCodnumeracion() == castOther.getCodnumeracion()) || (this
				.getCodnumeracion() != null
				&& castOther.getCodnumeracion() != null && this
				.getCodnumeracion().equals(castOther.getCodnumeracion())))
				&& (this.getCaid() == castOther.getCaid())
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodnumeracion() == null ? 0 : this.getCodnumeracion()
						.hashCode());
		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		return result;
	}

}
