package com.casapellas.entidades;

// Generated Apr 7, 2009 10:58:25 AM by Hibernate Tools 3.2.0.b9

/**
 * Persecaut generated by hbm2java
 */
public class Persecaut implements java.io.Serializable {

	private PersecautId id;

	private Aplicacion aplicacion;

	private Perfil perfil;

	public Persecaut() {
	}

	public Persecaut(PersecautId id, Aplicacion aplicacion, Perfil perfil) {
		this.id = id;
		this.aplicacion = aplicacion;
		this.perfil = perfil;
	}

	public PersecautId getId() {
		return this.id;
	}

	public void setId(PersecautId id) {
		this.id = id;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

}
