package com.casapellas.entidades;

// Generated 23/12/2009 2:08:58 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * ProductoId generated by hbm2java
 */
public class ProductoId implements java.io.Serializable {

	private String codsuc;
	private int nosol;
	private String tiposol;
	private int codcli;
	private String codprod;
	private String descprod;
	private String codmarca;
	private String descmarca;
	private String codmodelo;
	private String descmodelo;
	private long cant;
	private BigDecimal r2uprc;
	private BigDecimal r2fup;
	private BigDecimal precioun;

	public ProductoId() {
	}

	public ProductoId(String codsuc, int nosol, String tiposol, int codcli,
			String codprod, String descprod, String codmarca, String descmarca,
			String codmodelo, String descmodelo, long cant, BigDecimal r2uprc,
			BigDecimal r2fup, BigDecimal precioun) {
		this.codsuc = codsuc;
		this.nosol = nosol;
		this.tiposol = tiposol;
		this.codcli = codcli;
		this.codprod = codprod;
		this.descprod = descprod;
		this.codmarca = codmarca;
		this.descmarca = descmarca;
		this.codmodelo = codmodelo;
		this.descmodelo = descmodelo;
		this.cant = cant;
		this.r2uprc = r2uprc;
		this.r2fup = r2fup;
		this.precioun = precioun;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public int getNosol() {
		return this.nosol;
	}

	public void setNosol(int nosol) {
		this.nosol = nosol;
	}

	public String getTiposol() {
		return this.tiposol;
	}

	public void setTiposol(String tiposol) {
		this.tiposol = tiposol;
	}

	public int getCodcli() {
		return this.codcli;
	}

	public void setCodcli(int codcli) {
		this.codcli = codcli;
	}

	public String getCodprod() {
		return this.codprod;
	}

	public void setCodprod(String codprod) {
		this.codprod = codprod;
	}

	public String getDescprod() {
		return this.descprod;
	}

	public void setDescprod(String descprod) {
		this.descprod = descprod;
	}

	public String getCodmarca() {
		return this.codmarca;
	}

	public void setCodmarca(String codmarca) {
		this.codmarca = codmarca;
	}

	public String getDescmarca() {
		return this.descmarca;
	}

	public void setDescmarca(String descmarca) {
		this.descmarca = descmarca;
	}

	public String getCodmodelo() {
		return this.codmodelo;
	}

	public void setCodmodelo(String codmodelo) {
		this.codmodelo = codmodelo;
	}

	public String getDescmodelo() {
		return this.descmodelo;
	}

	public void setDescmodelo(String descmodelo) {
		this.descmodelo = descmodelo;
	}

	public long getCant() {
		return this.cant;
	}

	public void setCant(long cant) {
		this.cant = cant;
	}

	public BigDecimal getR2uprc() {
		return this.r2uprc;
	}

	public void setR2uprc(BigDecimal r2uprc) {
		this.r2uprc = r2uprc;
	}

	public BigDecimal getR2fup() {
		return this.r2fup;
	}

	public void setR2fup(BigDecimal r2fup) {
		this.r2fup = r2fup;
	}

	public BigDecimal getPrecioun() {
		return this.precioun;
	}

	public void setPrecioun(BigDecimal precioun) {
		this.precioun = precioun;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductoId))
			return false;
		ProductoId castOther = (ProductoId) other;

		return ((this.getCodsuc() == castOther.getCodsuc()) || (this
				.getCodsuc() != null
				&& castOther.getCodsuc() != null && this.getCodsuc().equals(
				castOther.getCodsuc())))
				&& (this.getNosol() == castOther.getNosol())
				&& ((this.getTiposol() == castOther.getTiposol()) || (this
						.getTiposol() != null
						&& castOther.getTiposol() != null && this.getTiposol()
						.equals(castOther.getTiposol())))
				&& (this.getCodcli() == castOther.getCodcli())
				&& ((this.getCodprod() == castOther.getCodprod()) || (this
						.getCodprod() != null
						&& castOther.getCodprod() != null && this.getCodprod()
						.equals(castOther.getCodprod())))
				&& ((this.getDescprod() == castOther.getDescprod()) || (this
						.getDescprod() != null
						&& castOther.getDescprod() != null && this
						.getDescprod().equals(castOther.getDescprod())))
				&& ((this.getCodmarca() == castOther.getCodmarca()) || (this
						.getCodmarca() != null
						&& castOther.getCodmarca() != null && this
						.getCodmarca().equals(castOther.getCodmarca())))
				&& ((this.getDescmarca() == castOther.getDescmarca()) || (this
						.getDescmarca() != null
						&& castOther.getDescmarca() != null && this
						.getDescmarca().equals(castOther.getDescmarca())))
				&& ((this.getCodmodelo() == castOther.getCodmodelo()) || (this
						.getCodmodelo() != null
						&& castOther.getCodmodelo() != null && this
						.getCodmodelo().equals(castOther.getCodmodelo())))
				&& ((this.getDescmodelo() == castOther.getDescmodelo()) || (this
						.getDescmodelo() != null
						&& castOther.getDescmodelo() != null && this
						.getDescmodelo().equals(castOther.getDescmodelo())))
				&& (this.getCant() == castOther.getCant())
				&& ((this.getR2uprc() == castOther.getR2uprc()) || (this
						.getR2uprc() != null
						&& castOther.getR2uprc() != null && this.getR2uprc()
						.equals(castOther.getR2uprc())))
				&& ((this.getR2fup() == castOther.getR2fup()) || (this
						.getR2fup() != null
						&& castOther.getR2fup() != null && this.getR2fup()
						.equals(castOther.getR2fup())))
				&& ((this.getPrecioun() == castOther.getPrecioun()) || (this
						.getPrecioun() != null
						&& castOther.getPrecioun() != null && this
						.getPrecioun().equals(castOther.getPrecioun())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result + this.getNosol();
		result = 37 * result
				+ (getTiposol() == null ? 0 : this.getTiposol().hashCode());
		result = 37 * result + this.getCodcli();
		result = 37 * result
				+ (getCodprod() == null ? 0 : this.getCodprod().hashCode());
		result = 37 * result
				+ (getDescprod() == null ? 0 : this.getDescprod().hashCode());
		result = 37 * result
				+ (getCodmarca() == null ? 0 : this.getCodmarca().hashCode());
		result = 37 * result
				+ (getDescmarca() == null ? 0 : this.getDescmarca().hashCode());
		result = 37 * result
				+ (getCodmodelo() == null ? 0 : this.getCodmodelo().hashCode());
		result = 37
				* result
				+ (getDescmodelo() == null ? 0 : this.getDescmodelo()
						.hashCode());
		result = 37 * result + (int) this.getCant();
		result = 37 * result
				+ (getR2uprc() == null ? 0 : this.getR2uprc().hashCode());
		result = 37 * result
				+ (getR2fup() == null ? 0 : this.getR2fup().hashCode());
		result = 37 * result
				+ (getPrecioun() == null ? 0 : this.getPrecioun().hashCode());
		return result;
	}

}
