package com.casapellas.entidades;

// Generated 29/10/2009 09:02:08 by Hibernate Tools 3.2.0.b9

/**
 * Recbatch generated by hbm2java
 */
public class Recbatch implements java.io.Serializable {

	private RecbatchId id;

	public Recbatch() {
	}

	public Recbatch(RecbatchId id) {
		this.id = id;
	}

	public RecbatchId getId() {
		return this.id;
	}

	public void setId(RecbatchId id) {
		this.id = id;
	}

}
