package com.casapellas.entidades;

// Generated Jan 31, 2011 11:36:47 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * Recibodet generated by hbm2java
 */
public class Recibodet implements java.io.Serializable {

	private static final long serialVersionUID = 3333305113251010442L;
	private RecibodetId id;
	private BigDecimal monto;
	private BigDecimal tasa;
	private BigDecimal equiv;
	private int numrecm;
	private String refer5;
	private String refer6;
	private String refer7;
	private String vmanual;
	private int caidpos;
	private String nombre;
	private String  terminal;
	private int referencenumber;
	private int depctatran;
	private String mpago;
	
	private String codigomarcatarjeta;
	private String marcatarjeta;
	private int liquidarpormarca ;
	
	private String descripcionformapago;
	
	
	public Recibodet() {
	}

	public Recibodet(RecibodetId id, BigDecimal monto, BigDecimal tasa,
			BigDecimal equiv, int numrecm, String refer5, String refer6,
			String refer7, String vmanual, int caidpos, String nombre,
			String terminal,int referencenumber, int depctatran ) {
		super();
		this.id = id;
		this.monto = monto;
		this.tasa = tasa;
		this.equiv = equiv;
		this.numrecm = numrecm;
		this.refer5 = refer5;
		this.refer6 = refer6;
		this.refer7 = refer7;
		this.vmanual = vmanual;
		this.caidpos = caidpos;
		this.nombre = nombre;
		this.referencenumber = referencenumber;
		this.depctatran = depctatran;
		this.terminal = terminal;
	}
	
	public Recibodet(RecibodetId id, BigDecimal monto, BigDecimal tasa,
			BigDecimal equiv, int numrecm, String refer5, String refer6,
			String refer7, String vmanual, int caidpos, String nombre) {
		this.id = id;
		this.monto = monto;
		this.tasa = tasa;
		this.equiv = equiv;
		this.numrecm = numrecm;
		this.refer5 = refer5;
		this.refer6 = refer6;
		this.refer7 = refer7;
		this.vmanual = vmanual;
		this.caidpos = caidpos;
		this.nombre = nombre;
	}

	public RecibodetId getId() {
		return this.id;
	}

	public void setId(RecibodetId id) {
		this.id = id;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}

	public BigDecimal getEquiv() {
		return this.equiv;
	}

	public void setEquiv(BigDecimal equiv) {
		this.equiv = equiv;
	}

	public int getNumrecm() {
		return this.numrecm;
	}

	public void setNumrecm(int numrecm) {
		this.numrecm = numrecm;
	}

	public String getMpago() {
		return this.mpago;
	}

	public void setMpago(String mpago) {
		this.mpago = mpago;
	}

	
	public String getRefer5() {
		return this.refer5;
	}

	public void setRefer5(String refer5) {
		this.refer5 = refer5;
	}

	public String getRefer6() {
		return this.refer6;
	}

	public void setRefer6(String refer6) {
		this.refer6 = refer6;
	}

	public String getRefer7() {
		return this.refer7;
	}

	public void setRefer7(String refer7) {
		this.refer7 = refer7;
	}

	public String getVmanual() {
		return this.vmanual;
	}

	public void setVmanual(String vmanual) {
		this.vmanual = vmanual;
	}

	public int getCaidpos() {
		return this.caidpos;
	}

	public void setCaidpos(int caidpos) {
		this.caidpos = caidpos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTerminal() {
		return terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}
	public int getReferencenumber() {
		return referencenumber;
	}

	public void setReferencenumber(int referencenumber) {
		this.referencenumber = referencenumber;
	}

	public int getDepctatran() {
		return depctatran;
	}

	public void setDepctatran(int depctatran) {
		this.depctatran = depctatran;
	}

	public String getCodigomarcatarjeta() {
		
		if(codigomarcatarjeta == null)
			codigomarcatarjeta = "" ;
		
		return codigomarcatarjeta;
	}

	public void setCodigomarcatarjeta(String codigomarcatarjeta) {
		this.codigomarcatarjeta = codigomarcatarjeta;
	}

	public String getMarcatarjeta() {
		
		if(marcatarjeta == null)
			marcatarjeta = "" ;
		
		return marcatarjeta;
	}

	public void setMarcatarjeta(String marcatarjeta) {
		this.marcatarjeta = marcatarjeta;
	}

	public int getLiquidarpormarca() {
		return liquidarpormarca;
	}

	public void setLiquidarpormarca(int liquidarpormarca) {
		this.liquidarpormarca = liquidarpormarca;
	}

	public String getDescripcionformapago() {
		return descripcionformapago;
	}

	public void setDescripcionformapago(String p_descripcionformapago) {
		descripcionformapago = p_descripcionformapago;
	}
 
}
