package com.casapellas.entidades;

// Generated Jan 31, 2011 11:36:47 AM by Hibernate Tools 3.2.0.b9

/**
 * RecibodetId generated by hbm2java
 */
public class RecibodetId implements java.io.Serializable {

	private String tiporec;

	private String codsuc;

	private int caid;

	private String codcomp;

	private String refer4;

	private String refer3;

	private String refer2;

	private String refer1;

	private String mpago;

	private String moneda;

	private int numrec;
	
	private double monto;

	public RecibodetId() {
	}

	public RecibodetId(String tiporec, String codsuc, int caid, String codcomp,
			String refer4, String refer3, String refer2, String refer1,
			String mpago, String moneda, int numrec) {
		this.tiporec = tiporec;
		this.codsuc = codsuc;
		this.caid = caid;
		this.codcomp = codcomp;
		this.refer4 = refer4;
		this.refer3 = refer3;
		this.refer2 = refer2;
		this.refer1 = refer1;
		this.mpago = mpago;
		this.moneda = moneda;
		this.numrec = numrec;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getRefer4() {
		return this.refer4;
	}

	public void setRefer4(String refer4) {
		this.refer4 = refer4;
	}

	public String getRefer3() {
		return this.refer3;
	}

	public void setRefer3(String refer3) {
		this.refer3 = refer3;
	}

	public String getRefer2() {
		return this.refer2;
	}

	public void setRefer2(String refer2) {
		this.refer2 = refer2;
	}

	public String getRefer1() {
		return this.refer1;
	}

	public void setRefer1(String refer1) {
		this.refer1 = refer1;
	}

	public String getMpago() {
		return this.mpago;
	}

	public void setMpago(String mpago) {
		this.mpago = mpago;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public double getMonto() {
		return monto;
	}

	public void setMonto(double monto) {
		this.monto = monto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecibodetId))
			return false;
		RecibodetId castOther = (RecibodetId) other;

		return ((this.getTiporec() == castOther.getTiporec()) || (this
				.getTiporec() != null
				&& castOther.getTiporec() != null && this.getTiporec().equals(
				castOther.getTiporec())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& (this.getCaid() == castOther.getCaid())
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& ((this.getRefer4() == castOther.getRefer4()) || (this
						.getRefer4() != null
						&& castOther.getRefer4() != null && this.getRefer4()
						.equals(castOther.getRefer4())))
				&& ((this.getRefer3() == castOther.getRefer3()) || (this
						.getRefer3() != null
						&& castOther.getRefer3() != null && this.getRefer3()
						.equals(castOther.getRefer3())))
				&& ((this.getRefer2() == castOther.getRefer2()) || (this
						.getRefer2() != null
						&& castOther.getRefer2() != null && this.getRefer2()
						.equals(castOther.getRefer2())))
				&& ((this.getRefer1() == castOther.getRefer1()) || (this
						.getRefer1() != null
						&& castOther.getRefer1() != null && this.getRefer1()
						.equals(castOther.getRefer1())))
				&& ((this.getMpago() == castOther.getMpago()) || (this
						.getMpago() != null
						&& castOther.getMpago() != null && this.getMpago()
						.equals(castOther.getMpago())))
				&& ((this.getMoneda() == castOther.getMoneda()) || (this
						.getMoneda() != null
						&& castOther.getMoneda() != null && this.getMoneda()
						.equals(castOther.getMoneda())))
				&& (this.getNumrec() == castOther.getNumrec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTiporec() == null ? 0 : this.getTiporec().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getRefer4() == null ? 0 : this.getRefer4().hashCode());
		result = 37 * result
				+ (getRefer3() == null ? 0 : this.getRefer3().hashCode());
		result = 37 * result
				+ (getRefer2() == null ? 0 : this.getRefer2().hashCode());
		result = 37 * result
				+ (getRefer1() == null ? 0 : this.getRefer1().hashCode());
		result = 37 * result
				+ (getMpago() == null ? 0 : this.getMpago().hashCode());
		result = 37 * result
				+ (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		result = 37 * result + this.getNumrec();
		return result;
	}

}
