package com.casapellas.entidades;

// Generated 7/01/2009 08:58:32 by Hibernate Tools 3.2.0.b9

/**
 * Ruc generated by hbm2java
 */
public class Ruc implements java.io.Serializable {

	private String codcomp;

	private String ruc;

	public Ruc() {
	}

	public Ruc(String codcomp) {
		this.codcomp = codcomp;
	}

	public Ruc(String codcomp, String ruc) {
		this.codcomp = codcomp;
		this.ruc = ruc;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

}
