package com.casapellas.entidades;

// Generated Feb 18, 2010 5:24:37 PM by Hibernate Tools 3.2.0.b9

/**
 * SalidaId generated by hbm2java
 */
public class SalidaId implements java.io.Serializable {

	private static final long serialVersionUID = 2956234488570931822L;

	private int caid;

	private String codsuc;

	private String codcomp;

	private int numsal;

	public SalidaId() {
	}

	public SalidaId(int caid, String codsuc, String codcomp, int numsal) {
		this.caid = caid;
		this.codsuc = codsuc;
		this.codcomp = codcomp;
		this.numsal = numsal;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public int getNumsal() {
		return this.numsal;
	}

	public void setNumsal(int numsal) {
		this.numsal = numsal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalidaId))
			return false;
		SalidaId castOther = (SalidaId) other;

		return (this.getCaid() == castOther.getCaid())
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& (this.getNumsal() == castOther.getNumsal());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result + this.getNumsal();
		return result;
	}

}
