package com.casapellas.entidades;

// Generated 02-09-2009 11:21:48 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * Salidadet generated by hbm2java
 */
public class Salidadet implements java.io.Serializable {

	private SalidadetId id;

	private BigDecimal monto;

	public Salidadet() {
	}

	public Salidadet(SalidadetId id, BigDecimal monto) {
		this.id = id;
		this.monto = monto;
	}

	public SalidadetId getId() {
		return this.id;
	}

	public void setId(SalidadetId id) {
		this.id = id;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

}
