package com.casapellas.entidades;
// Generated Jul 1, 2013 4:27:59 PM by Hibernate Tools 3.2.1.GA



/**
 * SolechequeId generated by hbm2java
 */
public class SolechequeId  implements java.io.Serializable {


     private int nosol;
     private int caid;
     private String codcomp;
     private String codsuc;
     private String codunineg;

    public SolechequeId() {
    }

    public SolechequeId(int nosol, int caid, String codcomp, String codsuc, String codunineg) {
       this.nosol = nosol;
       this.caid = caid;
       this.codcomp = codcomp;
       this.codsuc = codsuc;
       this.codunineg = codunineg;
    }
   
    public int getNosol() {
        return this.nosol;
    }
    
    public void setNosol(int nosol) {
        this.nosol = nosol;
    }
    public int getCaid() {
        return this.caid;
    }
    
    public void setCaid(int caid) {
        this.caid = caid;
    }
    public String getCodcomp() {
        return this.codcomp;
    }
    
    public void setCodcomp(String codcomp) {
        this.codcomp = codcomp;
    }
    public String getCodsuc() {
        return this.codsuc;
    }
    
    public void setCodsuc(String codsuc) {
        this.codsuc = codsuc;
    }
    public String getCodunineg() {
        return this.codunineg;
    }
    
    public void setCodunineg(String codunineg) {
        this.codunineg = codunineg;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SolechequeId) ) return false;
		 SolechequeId castOther = ( SolechequeId ) other; 
         
		 return (this.getNosol()==castOther.getNosol())
 && (this.getCaid()==castOther.getCaid())
 && ( (this.getCodcomp()==castOther.getCodcomp()) || ( this.getCodcomp()!=null && castOther.getCodcomp()!=null && this.getCodcomp().equals(castOther.getCodcomp()) ) )
 && ( (this.getCodsuc()==castOther.getCodsuc()) || ( this.getCodsuc()!=null && castOther.getCodsuc()!=null && this.getCodsuc().equals(castOther.getCodsuc()) ) )
 && ( (this.getCodunineg()==castOther.getCodunineg()) || ( this.getCodunineg()!=null && castOther.getCodunineg()!=null && this.getCodunineg().equals(castOther.getCodunineg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNosol();
         result = 37 * result + this.getCaid();
         result = 37 * result + ( getCodcomp() == null ? 0 : this.getCodcomp().hashCode() );
         result = 37 * result + ( getCodsuc() == null ? 0 : this.getCodsuc().hashCode() );
         result = 37 * result + ( getCodunineg() == null ? 0 : this.getCodunineg().hashCode() );
         return result;
   }   


}


