package com.casapellas.entidades;
// Generated Jul 1, 2013 4:27:59 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Solecheque generated by hbm2java
 */
public class Solecheque  implements java.io.Serializable {


     private SolechequeId id;
     private int numfac;
     private String tipofactura;
     private Date fecha;
     private Date hora;
     private String estado;
     private int codemp;
     private Integer usuariomod;
     private Date fechamod;
     private String observacion;
     private String mpago;
     private String tipoemision;
     private String moneda;
     private BigDecimal monto;
     private String codautoriz;
     private String notarjeta;
     private String fechapago;
     private String idafiliado;
     private BigDecimal tasacambio;
     private int codcli;
     private int fechafac;

    public Solecheque() {
    }

	
    public Solecheque(SolechequeId id, int numfac, String tipofactura, Date fecha, Date hora, String estado, int codemp, String mpago, String tipoemision, String moneda, String codautoriz, String notarjeta, String fechapago, String idafiliado, BigDecimal tasacambio, int codcli, int fechafac) {
        this.id = id;
        this.numfac = numfac;
        this.tipofactura = tipofactura;
        this.fecha = fecha;
        this.hora = hora;
        this.estado = estado;
        this.codemp = codemp;
        this.mpago = mpago;
        this.tipoemision = tipoemision;
        this.moneda = moneda;
        this.codautoriz = codautoriz;
        this.notarjeta = notarjeta;
        this.fechapago = fechapago;
        this.idafiliado = idafiliado;
        this.tasacambio = tasacambio;
        this.codcli = codcli;
        this.fechafac = fechafac;
    }
    public Solecheque(SolechequeId id, int numfac, String tipofactura, Date fecha, Date hora, String estado, int codemp, Integer usuariomod, Date fechamod, String observacion, String mpago, String tipoemision, String moneda, BigDecimal monto, String codautoriz, String notarjeta, String fechapago, String idafiliado, BigDecimal tasacambio, int codcli, int fechafac) {
       this.id = id;
       this.numfac = numfac;
       this.tipofactura = tipofactura;
       this.fecha = fecha;
       this.hora = hora;
       this.estado = estado;
       this.codemp = codemp;
       this.usuariomod = usuariomod;
       this.fechamod = fechamod;
       this.observacion = observacion;
       this.mpago = mpago;
       this.tipoemision = tipoemision;
       this.moneda = moneda;
       this.monto = monto;
       this.codautoriz = codautoriz;
       this.notarjeta = notarjeta;
       this.fechapago = fechapago;
       this.idafiliado = idafiliado;
       this.tasacambio = tasacambio;
       this.codcli = codcli;
       this.fechafac = fechafac;
    }
   
    public SolechequeId getId() {
        return this.id;
    }
    
    public void setId(SolechequeId id) {
        this.id = id;
    }
    public int getNumfac() {
        return this.numfac;
    }
    
    public void setNumfac(int numfac) {
        this.numfac = numfac;
    }
    public String getTipofactura() {
        return this.tipofactura;
    }
    
    public void setTipofactura(String tipofactura) {
        this.tipofactura = tipofactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getCodemp() {
        return this.codemp;
    }
    
    public void setCodemp(int codemp) {
        this.codemp = codemp;
    }
    public Integer getUsuariomod() {
        return this.usuariomod;
    }
    
    public void setUsuariomod(Integer usuariomod) {
        this.usuariomod = usuariomod;
    }
    public Date getFechamod() {
        return this.fechamod;
    }
    
    public void setFechamod(Date fechamod) {
        this.fechamod = fechamod;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getMpago() {
        return this.mpago;
    }
    
    public void setMpago(String mpago) {
        this.mpago = mpago;
    }
    public String getTipoemision() {
        return this.tipoemision;
    }
    
    public void setTipoemision(String tipoemision) {
        this.tipoemision = tipoemision;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getCodautoriz() {
        return this.codautoriz;
    }
    
    public void setCodautoriz(String codautoriz) {
        this.codautoriz = codautoriz;
    }
    public String getNotarjeta() {
        return this.notarjeta;
    }
    
    public void setNotarjeta(String notarjeta) {
        this.notarjeta = notarjeta;
    }
    public String getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(String fechapago) {
        this.fechapago = fechapago;
    }
    public String getIdafiliado() {
        return this.idafiliado;
    }
    
    public void setIdafiliado(String idafiliado) {
        this.idafiliado = idafiliado;
    }
    public BigDecimal getTasacambio() {
        return this.tasacambio;
    }
    
    public void setTasacambio(BigDecimal tasacambio) {
        this.tasacambio = tasacambio;
    }
    public int getCodcli() {
        return this.codcli;
    }
    
    public void setCodcli(int codcli) {
        this.codcli = codcli;
    }
    public int getFechafac() {
        return this.fechafac;
    }
    
    public void setFechafac(int fechafac) {
        this.fechafac = fechafac;
    }




}


