package com.casapellas.entidades;

// Generated 01-05-2010 02:37:35 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud implements java.io.Serializable {

	private SolicitudId id;

	private int autoriza;

	private Date fecha;

	private String obs;

	private String mpago;

	private BigDecimal monto;

	private String moneda;
	
	private String metododesc;

	public Solicitud() {
	}

	public Solicitud(SolicitudId id, int autoriza, Date fecha, String mpago,
			BigDecimal monto, String moneda) {
		this.id = id;
		this.autoriza = autoriza;
		this.fecha = fecha;
		this.mpago = mpago;
		this.monto = monto;
		this.moneda = moneda;
	}

	public Solicitud(SolicitudId id, int autoriza, Date fecha, String obs,
			String mpago, BigDecimal monto, String moneda) {
		this.id = id;
		this.autoriza = autoriza;
		this.fecha = fecha;
		this.obs = obs;
		this.mpago = mpago;
		this.monto = monto;
		this.moneda = moneda;
	}

	public SolicitudId getId() {
		return this.id;
	}

	public void setId(SolicitudId id) {
		this.id = id;
	}

	public int getAutoriza() {
		return this.autoriza;
	}

	public void setAutoriza(int autoriza) {
		this.autoriza = autoriza;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	public String getMpago() {
		return this.mpago;
	}

	public void setMpago(String mpago) {
		this.mpago = mpago;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getMetododesc() {
		return metododesc;
	}

	public void setMetododesc(String metododesc) {
		this.metododesc = metododesc;
	}

}
