package com.casapellas.entidades;

// Generated 4/02/2009 16:00:21 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * TcambioId generated by hbm2java
 */
public class TcambioId implements java.io.Serializable {

	private static final long serialVersionUID = -2206529493251911464L;

	private String cxcrcd;

	private Date cxeft;

	private BigDecimal cxcrr;

	private String cxcrdc;

	private BigDecimal cxcrrd;

	public TcambioId() {
	}

	public TcambioId(String cxcrcd, Date cxeft, BigDecimal cxcrr,
			String cxcrdc, BigDecimal cxcrrd) {
		this.cxcrcd = cxcrcd;
		this.cxeft = cxeft;
		this.cxcrr = cxcrr;
		this.cxcrdc = cxcrdc;
		this.cxcrrd = cxcrrd;
	}

	public String getCxcrcd() {
		return this.cxcrcd;
	}

	public void setCxcrcd(String cxcrcd) {
		this.cxcrcd = cxcrcd;
	}

	public Date getCxeft() {
		return this.cxeft;
	}

	public void setCxeft(Date cxeft) {
		this.cxeft = cxeft;
	}

	public BigDecimal getCxcrr() {
		return this.cxcrr;
	}

	public void setCxcrr(BigDecimal cxcrr) {
		this.cxcrr = cxcrr;
	}

	public String getCxcrdc() {
		return this.cxcrdc;
	}

	public void setCxcrdc(String cxcrdc) {
		this.cxcrdc = cxcrdc;
	}

	public BigDecimal getCxcrrd() {
		return this.cxcrrd;
	}

	public void setCxcrrd(BigDecimal cxcrrd) {
		this.cxcrrd = cxcrrd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TcambioId))
			return false;
		TcambioId castOther = (TcambioId) other;

		return ((this.getCxcrcd() == castOther.getCxcrcd()) || (this
				.getCxcrcd() != null
				&& castOther.getCxcrcd() != null && this.getCxcrcd().equals(
				castOther.getCxcrcd())))
				&& ((this.getCxeft() == castOther.getCxeft()) || (this
						.getCxeft() != null
						&& castOther.getCxeft() != null && this.getCxeft()
						.equals(castOther.getCxeft())))
				&& ((this.getCxcrr() == castOther.getCxcrr()) || (this
						.getCxcrr() != null
						&& castOther.getCxcrr() != null && this.getCxcrr()
						.equals(castOther.getCxcrr())))
				&& ((this.getCxcrdc() == castOther.getCxcrdc()) || (this
						.getCxcrdc() != null
						&& castOther.getCxcrdc() != null && this.getCxcrdc()
						.equals(castOther.getCxcrdc())))
				&& ((this.getCxcrrd() == castOther.getCxcrrd()) || (this
						.getCxcrrd() != null
						&& castOther.getCxcrrd() != null && this.getCxcrrd()
						.equals(castOther.getCxcrrd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCxcrcd() == null ? 0 : this.getCxcrcd().hashCode());
		result = 37 * result
				+ (getCxeft() == null ? 0 : this.getCxeft().hashCode());
		result = 37 * result
				+ (getCxcrr() == null ? 0 : this.getCxcrr().hashCode());
		result = 37 * result
				+ (getCxcrdc() == null ? 0 : this.getCxcrdc().hashCode());
		result = 37 * result
				+ (getCxcrrd() == null ? 0 : this.getCxcrrd().hashCode());
		return result;
	}

}
