package com.casapellas.entidades;

// Generated 08-11-2011 02:48:21 PM by Hibernate Tools 3.2.2.GA

/**
 * TermAfl generated by hbm2java
 */
public class TermAfl implements java.io.Serializable {
	private static final long serialVersionUID = -3521837745547990249L;
	
	private TermAflId id;

	public TermAfl() {
	}

	public TermAfl(TermAflId id) {
		this.id = id;
	}

	public TermAflId getId() {
		return this.id;
	}

	public void setId(TermAflId id) {
		this.id = id;
	}

}
