package com.casapellas.entidades;

// Generated 18/06/2009 09:30:47 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * TpararelaId generated by hbm2java
 */
public class TpararelaId implements java.io.Serializable {

	private String cmono;

	private String cmond;

	private BigDecimal tcambiom;

	private BigDecimal tcambiod;

	private char direc;

	private int fechai;

	private int fechaf;

	public TpararelaId() {
	}

	public TpararelaId(String cmono, String cmond, BigDecimal tcambiom,
			BigDecimal tcambiod, char direc, int fechai, int fechaf) {
		this.cmono = cmono;
		this.cmond = cmond;
		this.tcambiom = tcambiom;
		this.tcambiod = tcambiod;
		this.direc = direc;
		this.fechai = fechai;
		this.fechaf = fechaf;
	}

	public String getCmono() {
		return this.cmono;
	}

	public void setCmono(String cmono) {
		this.cmono = cmono;
	}

	public String getCmond() {
		return this.cmond;
	}

	public void setCmond(String cmond) {
		this.cmond = cmond;
	}

	public BigDecimal getTcambiom() {
		return this.tcambiom;
	}

	public void setTcambiom(BigDecimal tcambiom) {
		this.tcambiom = tcambiom;
	}

	public BigDecimal getTcambiod() {
		return this.tcambiod;
	}

	public void setTcambiod(BigDecimal tcambiod) {
		this.tcambiod = tcambiod;
	}

	public char getDirec() {
		return this.direc;
	}

	public void setDirec(char direc) {
		this.direc = direc;
	}

	public int getFechai() {
		return this.fechai;
	}

	public void setFechai(int fechai) {
		this.fechai = fechai;
	}

	public int getFechaf() {
		return this.fechaf;
	}

	public void setFechaf(int fechaf) {
		this.fechaf = fechaf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpararelaId))
			return false;
		TpararelaId castOther = (TpararelaId) other;

		return ((this.getCmono() == castOther.getCmono()) || (this.getCmono() != null
				&& castOther.getCmono() != null && this.getCmono().equals(
				castOther.getCmono())))
				&& ((this.getCmond() == castOther.getCmond()) || (this
						.getCmond() != null
						&& castOther.getCmond() != null && this.getCmond()
						.equals(castOther.getCmond())))
				&& ((this.getTcambiom() == castOther.getTcambiom()) || (this
						.getTcambiom() != null
						&& castOther.getTcambiom() != null && this
						.getTcambiom().equals(castOther.getTcambiom())))
				&& ((this.getTcambiod() == castOther.getTcambiod()) || (this
						.getTcambiod() != null
						&& castOther.getTcambiod() != null && this
						.getTcambiod().equals(castOther.getTcambiod())))
				&& (this.getDirec() == castOther.getDirec())
				&& (this.getFechai() == castOther.getFechai())
				&& (this.getFechaf() == castOther.getFechaf());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCmono() == null ? 0 : this.getCmono().hashCode());
		result = 37 * result
				+ (getCmond() == null ? 0 : this.getCmond().hashCode());
		result = 37 * result
				+ (getTcambiom() == null ? 0 : this.getTcambiom().hashCode());
		result = 37 * result
				+ (getTcambiod() == null ? 0 : this.getTcambiod().hashCode());
		result = 37 * result + this.getDirec();
		result = 37 * result + this.getFechai();
		result = 37 * result + this.getFechaf();
		return result;
	}

}
