package com.casapellas.entidades;

// Generated 27/02/2009 12:28:20 by Hibernate Tools 3.2.0.b9

/**
 * Uneglinea generated by hbm2java
 */
public class Uneglinea implements java.io.Serializable {

	private UneglineaId id;

	public Uneglinea() {
	}

	public Uneglinea(UneglineaId id) {
		this.id = id;
	}

	public UneglineaId getId() {
		return this.id;
	}

	public void setId(UneglineaId id) {
		this.id = id;
	}

}
