package com.casapellas.entidades;

// Generated Apr 7, 2009 10:58:25 AM by Hibernate Tools 3.2.0.b9

/**
 * UsrungId generated by hbm2java
 */
public class UsrungId implements java.io.Serializable {

	private String coduneg;

	private String coduser;

	public UsrungId() {
	}

	public UsrungId(String coduneg, String coduser) {
		this.coduneg = coduneg;
		this.coduser = coduser;
	}

	public String getCoduneg() {
		return this.coduneg;
	}

	public void setCoduneg(String coduneg) {
		this.coduneg = coduneg;
	}

	public String getCoduser() {
		return this.coduser;
	}

	public void setCoduser(String coduser) {
		this.coduser = coduser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsrungId))
			return false;
		UsrungId castOther = (UsrungId) other;

		return ((this.getCoduneg() == castOther.getCoduneg()) || (this
				.getCoduneg() != null
				&& castOther.getCoduneg() != null && this.getCoduneg().equals(
				castOther.getCoduneg())))
				&& ((this.getCoduser() == castOther.getCoduser()) || (this
						.getCoduser() != null
						&& castOther.getCoduser() != null && this.getCoduser()
						.equals(castOther.getCoduser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCoduneg() == null ? 0 : this.getCoduneg().hashCode());
		result = 37 * result
				+ (getCoduser() == null ? 0 : this.getCoduser().hashCode());
		return result;
	}

}
