package com.casapellas.entidades;

// Generated 2/07/2009 11:36:12 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private String coduser;

	private String tipuser;

	private Integer codreg;

	private String login;

	private String activo;

	private String pswd;

	private Date fregistro;

	public Usuario() {
	}

	public Usuario(String coduser, String tipuser, String login, Date fregistro) {
		this.coduser = coduser;
		this.tipuser = tipuser;
		this.login = login;
		this.fregistro = fregistro;
	}

	public Usuario(String coduser, String tipuser, Integer codreg,
			String login, String activo, String pswd, Date fregistro) {
		this.coduser = coduser;
		this.tipuser = tipuser;
		this.codreg = codreg;
		this.login = login;
		this.activo = activo;
		this.pswd = pswd;
		this.fregistro = fregistro;
	}

	public String getCoduser() {
		return this.coduser;
	}

	public void setCoduser(String coduser) {
		this.coduser = coduser;
	}

	public String getTipuser() {
		return this.tipuser;
	}

	public void setTipuser(String tipuser) {
		this.tipuser = tipuser;
	}

	public Integer getCodreg() {
		return this.codreg;
	}

	public void setCodreg(Integer codreg) {
		this.codreg = codreg;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	public Date getFregistro() {
		return this.fregistro;
	}

	public void setFregistro(Date fregistro) {
		this.fregistro = fregistro;
	}

}
