package com.casapellas.entidades;

// Generated Nov 16, 2015 12:23:53 PM by Hibernate Tools 4.0.0

/**
 * Varqueo generated by hbm2java
 */
public class Varqueo implements java.io.Serializable {


	private static final long serialVersionUID = -1728269035228938005L;
	private VarqueoId id;

	private int noarqueo;

	public int getNoarqueo() {
		return noarqueo;
	}

	public void setNoarqueo(int noarqueo) {
		this.noarqueo = noarqueo;
	}
	
	public Varqueo() {
	}

	public Varqueo(VarqueoId id) {
		this.id = id;
	}

	public VarqueoId getId() {
		return this.id;
	}

	public void setId(VarqueoId id) {
		this.id = id;
	}

}
