package com.casapellas.entidades;

// Generated 07-25-2009 11:46:12 AM by Hibernate Tools 3.2.0.b9

/**
 * Vcambiosrealizadosxdia generated by hbm2java
 */
public class Vcambiosrealizadosxdia implements java.io.Serializable {

	private VcambiosrealizadosxdiaId id;

	public Vcambiosrealizadosxdia() {
	}

	public Vcambiosrealizadosxdia(VcambiosrealizadosxdiaId id) {
		this.id = id;
	}

	public VcambiosrealizadosxdiaId getId() {
		return this.id;
	}

	public void setId(VcambiosrealizadosxdiaId id) {
		this.id = id;
	}

}
