package com.casapellas.entidades;

// default package
// Generated Sep 22, 2011 8:46:14 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VcierresktposId generated by hbm2java
 */
public class VcierresktposId implements java.io.Serializable {

	private int caid;
	private String codcomp;
	private String codsuc;
	private int noarqueo;
	private String moneda;
	private Date fecha;
	private Date hora;
	private String afiliado;
	private String termId;
	private String autorizacion;
	private int purshtrans;
	private BigDecimal purshamount;
	private int rettrans;
	private BigDecimal retamount;

	public VcierresktposId() {
	}

	public VcierresktposId(int caid, String codcomp, String codsuc,
			int noarqueo, String moneda, Date fecha, Date hora,
			String afiliado, String termId, String autorizacion,
			int purshtrans, BigDecimal purshamount, int rettrans,
			BigDecimal retamount) {
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.noarqueo = noarqueo;
		this.moneda = moneda;
		this.fecha = fecha;
		this.hora = hora;
		this.afiliado = afiliado;
		this.termId = termId;
		this.autorizacion = autorizacion;
		this.purshtrans = purshtrans;
		this.purshamount = purshamount;
		this.rettrans = rettrans;
		this.retamount = retamount;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public int getNoarqueo() {
		return this.noarqueo;
	}

	public void setNoarqueo(int noarqueo) {
		this.noarqueo = noarqueo;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(String afiliado) {
		this.afiliado = afiliado;
	}

	public String getTermId() {
		return this.termId;
	}

	public void setTermId(String termId) {
		this.termId = termId;
	}

	public String getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(String autorizacion) {
		this.autorizacion = autorizacion;
	}

	public int getPurshtrans() {
		return this.purshtrans;
	}

	public void setPurshtrans(int purshtrans) {
		this.purshtrans = purshtrans;
	}

	public BigDecimal getPurshamount() {
		return this.purshamount;
	}

	public void setPurshamount(BigDecimal purshamount) {
		this.purshamount = purshamount;
	}

	public int getRettrans() {
		return this.rettrans;
	}

	public void setRettrans(int rettrans) {
		this.rettrans = rettrans;
	}

	public BigDecimal getRetamount() {
		return this.retamount;
	}

	public void setRetamount(BigDecimal retamount) {
		this.retamount = retamount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VcierresktposId))
			return false;
		VcierresktposId castOther = (VcierresktposId) other;

		return (this.getCaid() == castOther.getCaid())
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null && castOther.getCodcomp() != null && this
						.getCodcomp().equals(castOther.getCodcomp())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null && castOther.getCodsuc() != null && this
						.getCodsuc().equals(castOther.getCodsuc())))
				&& (this.getNoarqueo() == castOther.getNoarqueo())
				&& ((this.getMoneda() == castOther.getMoneda()) || (this
						.getMoneda() != null && castOther.getMoneda() != null && this
						.getMoneda().equals(castOther.getMoneda())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getAfiliado() == castOther.getAfiliado()) || (this
						.getAfiliado() != null
						&& castOther.getAfiliado() != null && this
						.getAfiliado().equals(castOther.getAfiliado())))
				&& ((this.getTermId() == castOther.getTermId()) || (this
						.getTermId() != null && castOther.getTermId() != null && this
						.getTermId().equals(castOther.getTermId())))
				&& ((this.getAutorizacion() == castOther.getAutorizacion()) || (this
						.getAutorizacion() != null
						&& castOther.getAutorizacion() != null && this
						.getAutorizacion().equals(castOther.getAutorizacion())))
				&& (this.getPurshtrans() == castOther.getPurshtrans())
				&& ((this.getPurshamount() == castOther.getPurshamount()) || (this
						.getPurshamount() != null
						&& castOther.getPurshamount() != null && this
						.getPurshamount().equals(castOther.getPurshamount())))
				&& (this.getRettrans() == castOther.getRettrans())
				&& ((this.getRetamount() == castOther.getRetamount()) || (this
						.getRetamount() != null
						&& castOther.getRetamount() != null && this
						.getRetamount().equals(castOther.getRetamount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result + this.getNoarqueo();
		result = 37 * result
				+ (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result
				+ (getAfiliado() == null ? 0 : this.getAfiliado().hashCode());
		result = 37 * result
				+ (getTermId() == null ? 0 : this.getTermId().hashCode());
		result = 37
				* result
				+ (getAutorizacion() == null ? 0 : this.getAutorizacion()
						.hashCode());
		result = 37 * result + this.getPurshtrans();
		result = 37
				* result
				+ (getPurshamount() == null ? 0 : this.getPurshamount()
						.hashCode());
		result = 37 * result + this.getRettrans();
		result = 37 * result
				+ (getRetamount() == null ? 0 : this.getRetamount().hashCode());
		return result;
	}

}
