package com.casapellas.entidades;

// Generated 7/02/2009 11:18:13 by Hibernate Tools 3.2.0.b9

/**
 * Vcompania generated by hbm2java
 */
public class Vcompania implements java.io.Serializable {

	private VcompaniaId id;

	public Vcompania() {
	}

	public Vcompania(VcompaniaId id) {
		this.id = id;
	}

	public VcompaniaId getId() {
		return this.id;
	}

	public void setId(VcompaniaId id) {
		this.id = id;
	}

}
