package com.casapellas.entidades;

// Generated Jun 11, 2012 10:20:55 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * VdepositoId generated by hbm2java
 */
public class VdepositoId implements java.io.Serializable {

	private int nodeposito;
	private String codsuc;
	private String codcomp;
	private int caid;
	private String moneda;
	private BigDecimal monto;
	private String referencia;
	private Date fecha;
	private Date hora;
	private Date fechamod;
	private Date horamod;
	private String coduser;
	private String tipodep;
	private BigDecimal tasa;
	private int consecutivo;
	private String mpagodep;
	private String referdep;
	private String estadocnfr;
	private String tipoconfr;
	private int usrconfr;
	private int usrcreate;
	private int codcajero;
	private int idbanco;
	private String usrcreacion;
	private String usrconfirm;
	private String nombrecomp;
	private String nombresuc;
	private String metododesc;
	private String estado;
	private String nomcaja;
	private int nobatch;
	private int recjde;
	private String cajero;

	public VdepositoId() {
	}

	public VdepositoId(int nodeposito, String codsuc, String codcomp, int caid,
			String moneda, BigDecimal monto, String referencia, Date fecha,
			Date hora, Date fechamod, Date horamod, String coduser,
			String tipodep, BigDecimal tasa, int consecutivo, String mpagodep,
			String referdep, String estadocnfr, String tipoconfr, int usrconfr,
			int usrcreate, int codcajero, int idbanco, String usrcreacion,
			String usrconfirm, String nombrecomp, String nombresuc,
			String metododesc, String nomcaja, int nobatch, int recjde,
			String cajero) {
		this.nodeposito = nodeposito;
		this.codsuc = codsuc;
		this.codcomp = codcomp;
		this.caid = caid;
		this.moneda = moneda;
		this.monto = monto;
		this.referencia = referencia;
		this.fecha = fecha;
		this.hora = hora;
		this.fechamod = fechamod;
		this.horamod = horamod;
		this.coduser = coduser;
		this.tipodep = tipodep;
		this.tasa = tasa;
		this.consecutivo = consecutivo;
		this.mpagodep = mpagodep;
		this.referdep = referdep;
		this.estadocnfr = estadocnfr;
		this.tipoconfr = tipoconfr;
		this.usrconfr = usrconfr;
		this.usrcreate = usrcreate;
		this.codcajero = codcajero;
		this.idbanco = idbanco;
		this.usrcreacion = usrcreacion;
		this.usrconfirm = usrconfirm;
		this.nombrecomp = nombrecomp;
		this.nombresuc = nombresuc;
		this.metododesc = metododesc;
		this.nomcaja = nomcaja;
		this.nobatch = nobatch;
		this.recjde = recjde;
		this.cajero = cajero;
	}

	public VdepositoId(int nodeposito, String codsuc, String codcomp, int caid,
			String moneda, BigDecimal monto, String referencia, Date fecha,
			Date hora, Date fechamod, Date horamod, String coduser,
			String tipodep, BigDecimal tasa, int consecutivo, String mpagodep,
			String referdep, String estadocnfr, String tipoconfr, int usrconfr,
			int usrcreate, int codcajero, int idbanco, String usrcreacion,
			String usrconfirm, String nombrecomp, String nombresuc,
			String metododesc, String estado, String nomcaja, int nobatch,
			int recjde, String cajero) {
		this.nodeposito = nodeposito;
		this.codsuc = codsuc;
		this.codcomp = codcomp;
		this.caid = caid;
		this.moneda = moneda;
		this.monto = monto;
		this.referencia = referencia;
		this.fecha = fecha;
		this.hora = hora;
		this.fechamod = fechamod;
		this.horamod = horamod;
		this.coduser = coduser;
		this.tipodep = tipodep;
		this.tasa = tasa;
		this.consecutivo = consecutivo;
		this.mpagodep = mpagodep;
		this.referdep = referdep;
		this.estadocnfr = estadocnfr;
		this.tipoconfr = tipoconfr;
		this.usrconfr = usrconfr;
		this.usrcreate = usrcreate;
		this.codcajero = codcajero;
		this.idbanco = idbanco;
		this.usrcreacion = usrcreacion;
		this.usrconfirm = usrconfirm;
		this.nombrecomp = nombrecomp;
		this.nombresuc = nombresuc;
		this.metododesc = metododesc;
		this.estado = estado;
		this.nomcaja = nomcaja;
		this.nobatch = nobatch;
		this.recjde = recjde;
		this.cajero = cajero;
	}

	public int getNodeposito() {
		return this.nodeposito;
	}

	public void setNodeposito(int nodeposito) {
		this.nodeposito = nodeposito;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public Date getHoramod() {
		return this.horamod;
	}

	public void setHoramod(Date horamod) {
		this.horamod = horamod;
	}

	public String getCoduser() {
		return this.coduser;
	}

	public void setCoduser(String coduser) {
		this.coduser = coduser;
	}

	public String getTipodep() {
		return this.tipodep;
	}

	public void setTipodep(String tipodep) {
		this.tipodep = tipodep;
	}

	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getMpagodep() {
		return this.mpagodep;
	}

	public void setMpagodep(String mpagodep) {
		this.mpagodep = mpagodep;
	}

	public String getReferdep() {
		return this.referdep;
	}

	public void setReferdep(String referdep) {
		this.referdep = referdep;
	}

	public String getEstadocnfr() {
		return this.estadocnfr;
	}

	public void setEstadocnfr(String estadocnfr) {
		this.estadocnfr = estadocnfr;
	}

	public String getTipoconfr() {
		return this.tipoconfr;
	}

	public void setTipoconfr(String tipoconfr) {
		this.tipoconfr = tipoconfr;
	}

	public int getUsrconfr() {
		return this.usrconfr;
	}

	public void setUsrconfr(int usrconfr) {
		this.usrconfr = usrconfr;
	}

	public int getUsrcreate() {
		return this.usrcreate;
	}

	public void setUsrcreate(int usrcreate) {
		this.usrcreate = usrcreate;
	}

	public int getCodcajero() {
		return this.codcajero;
	}

	public void setCodcajero(int codcajero) {
		this.codcajero = codcajero;
	}

	public int getIdbanco() {
		return this.idbanco;
	}

	public void setIdbanco(int idbanco) {
		this.idbanco = idbanco;
	}

	public String getUsrcreacion() {
		return this.usrcreacion;
	}

	public void setUsrcreacion(String usrcreacion) {
		this.usrcreacion = usrcreacion;
	}

	public String getUsrconfirm() {
		return this.usrconfirm;
	}

	public void setUsrconfirm(String usrconfirm) {
		this.usrconfirm = usrconfirm;
	}

	public String getNombrecomp() {
		return this.nombrecomp;
	}

	public void setNombrecomp(String nombrecomp) {
		this.nombrecomp = nombrecomp;
	}

	public String getNombresuc() {
		return this.nombresuc;
	}

	public void setNombresuc(String nombresuc) {
		this.nombresuc = nombresuc;
	}

	public String getMetododesc() {
		return this.metododesc;
	}

	public void setMetododesc(String metododesc) {
		this.metododesc = metododesc;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNomcaja() {
		return this.nomcaja;
	}

	public void setNomcaja(String nomcaja) {
		this.nomcaja = nomcaja;
	}

	public int getNobatch() {
		return this.nobatch;
	}

	public void setNobatch(int nobatch) {
		this.nobatch = nobatch;
	}

	public int getRecjde() {
		return this.recjde;
	}

	public void setRecjde(int recjde) {
		this.recjde = recjde;
	}

	public String getCajero() {
		return this.cajero;
	}

	public void setCajero(String cajero) {
		this.cajero = cajero;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdepositoId))
			return false;
		VdepositoId castOther = (VdepositoId) other;

		return (this.getNodeposito() == castOther.getNodeposito())
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& (this.getCaid() == castOther.getCaid())
				&& ((this.getMoneda() == castOther.getMoneda()) || (this
						.getMoneda() != null
						&& castOther.getMoneda() != null && this.getMoneda()
						.equals(castOther.getMoneda())))
				&& ((this.getMonto() == castOther.getMonto()) || (this
						.getMonto() != null
						&& castOther.getMonto() != null && this.getMonto()
						.equals(castOther.getMonto())))
				&& ((this.getReferencia() == castOther.getReferencia()) || (this
						.getReferencia() != null
						&& castOther.getReferencia() != null && this
						.getReferencia().equals(castOther.getReferencia())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getFechamod() == castOther.getFechamod()) || (this
						.getFechamod() != null
						&& castOther.getFechamod() != null && this
						.getFechamod().equals(castOther.getFechamod())))
				&& ((this.getHoramod() == castOther.getHoramod()) || (this
						.getHoramod() != null
						&& castOther.getHoramod() != null && this.getHoramod()
						.equals(castOther.getHoramod())))
				&& ((this.getCoduser() == castOther.getCoduser()) || (this
						.getCoduser() != null
						&& castOther.getCoduser() != null && this.getCoduser()
						.equals(castOther.getCoduser())))
				&& ((this.getTipodep() == castOther.getTipodep()) || (this
						.getTipodep() != null
						&& castOther.getTipodep() != null && this.getTipodep()
						.equals(castOther.getTipodep())))
				&& ((this.getTasa() == castOther.getTasa()) || (this.getTasa() != null
						&& castOther.getTasa() != null && this.getTasa()
						.equals(castOther.getTasa())))
				&& (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getMpagodep() == castOther.getMpagodep()) || (this
						.getMpagodep() != null
						&& castOther.getMpagodep() != null && this
						.getMpagodep().equals(castOther.getMpagodep())))
				&& ((this.getReferdep() == castOther.getReferdep()) || (this
						.getReferdep() != null
						&& castOther.getReferdep() != null && this
						.getReferdep().equals(castOther.getReferdep())))
				&& ((this.getEstadocnfr() == castOther.getEstadocnfr()) || (this
						.getEstadocnfr() != null
						&& castOther.getEstadocnfr() != null && this
						.getEstadocnfr().equals(castOther.getEstadocnfr())))
				&& ((this.getTipoconfr() == castOther.getTipoconfr()) || (this
						.getTipoconfr() != null
						&& castOther.getTipoconfr() != null && this
						.getTipoconfr().equals(castOther.getTipoconfr())))
				&& (this.getUsrconfr() == castOther.getUsrconfr())
				&& (this.getUsrcreate() == castOther.getUsrcreate())
				&& (this.getCodcajero() == castOther.getCodcajero())
				&& (this.getIdbanco() == castOther.getIdbanco())
				&& ((this.getUsrcreacion() == castOther.getUsrcreacion()) || (this
						.getUsrcreacion() != null
						&& castOther.getUsrcreacion() != null && this
						.getUsrcreacion().equals(castOther.getUsrcreacion())))
				&& ((this.getUsrconfirm() == castOther.getUsrconfirm()) || (this
						.getUsrconfirm() != null
						&& castOther.getUsrconfirm() != null && this
						.getUsrconfirm().equals(castOther.getUsrconfirm())))
				&& ((this.getNombrecomp() == castOther.getNombrecomp()) || (this
						.getNombrecomp() != null
						&& castOther.getNombrecomp() != null && this
						.getNombrecomp().equals(castOther.getNombrecomp())))
				&& ((this.getNombresuc() == castOther.getNombresuc()) || (this
						.getNombresuc() != null
						&& castOther.getNombresuc() != null && this
						.getNombresuc().equals(castOther.getNombresuc())))
				&& ((this.getMetododesc() == castOther.getMetododesc()) || (this
						.getMetododesc() != null
						&& castOther.getMetododesc() != null && this
						.getMetododesc().equals(castOther.getMetododesc())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null
						&& castOther.getEstado() != null && this.getEstado()
						.equals(castOther.getEstado())))
				&& ((this.getNomcaja() == castOther.getNomcaja()) || (this
						.getNomcaja() != null
						&& castOther.getNomcaja() != null && this.getNomcaja()
						.equals(castOther.getNomcaja())))
				&& (this.getNobatch() == castOther.getNobatch())
				&& (this.getRecjde() == castOther.getRecjde())
				&& ((this.getCajero() == castOther.getCajero()) || (this
						.getCajero() != null
						&& castOther.getCajero() != null && this.getCajero()
						.equals(castOther.getCajero())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNodeposito();
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		result = 37 * result
				+ (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37
				* result
				+ (getReferencia() == null ? 0 : this.getReferencia()
						.hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result
				+ (getFechamod() == null ? 0 : this.getFechamod().hashCode());
		result = 37 * result
				+ (getHoramod() == null ? 0 : this.getHoramod().hashCode());
		result = 37 * result
				+ (getCoduser() == null ? 0 : this.getCoduser().hashCode());
		result = 37 * result
				+ (getTipodep() == null ? 0 : this.getTipodep().hashCode());
		result = 37 * result
				+ (getTasa() == null ? 0 : this.getTasa().hashCode());
		result = 37 * result + this.getConsecutivo();
		result = 37 * result
				+ (getMpagodep() == null ? 0 : this.getMpagodep().hashCode());
		result = 37 * result
				+ (getReferdep() == null ? 0 : this.getReferdep().hashCode());
		result = 37
				* result
				+ (getEstadocnfr() == null ? 0 : this.getEstadocnfr()
						.hashCode());
		result = 37 * result
				+ (getTipoconfr() == null ? 0 : this.getTipoconfr().hashCode());
		result = 37 * result + this.getUsrconfr();
		result = 37 * result + this.getUsrcreate();
		result = 37 * result + this.getCodcajero();
		result = 37 * result + this.getIdbanco();
		result = 37
				* result
				+ (getUsrcreacion() == null ? 0 : this.getUsrcreacion()
						.hashCode());
		result = 37
				* result
				+ (getUsrconfirm() == null ? 0 : this.getUsrconfirm()
						.hashCode());
		result = 37
				* result
				+ (getNombrecomp() == null ? 0 : this.getNombrecomp()
						.hashCode());
		result = 37 * result
				+ (getNombresuc() == null ? 0 : this.getNombresuc().hashCode());
		result = 37
				* result
				+ (getMetododesc() == null ? 0 : this.getMetododesc()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result
				+ (getNomcaja() == null ? 0 : this.getNomcaja().hashCode());
		result = 37 * result + this.getNobatch();
		result = 37 * result + this.getRecjde();
		result = 37 * result
				+ (getCajero() == null ? 0 : this.getCajero().hashCode());
		return result;
	}

}
