package com.casapellas.entidades;

// Generated 10-22-2009 04:07:11 PM by Hibernate Tools 3.2.0.b9

/**
 * Vdetallecambiorec generated by hbm2java
 */
public class Vdetallecambiorec implements java.io.Serializable {

	private VdetallecambiorecId id;

	public Vdetallecambiorec() {
	}

	public Vdetallecambiorec(VdetallecambiorecId id) {
		this.id = id;
	}

	public VdetallecambiorecId getId() {
		return this.id;
	}

	public void setId(VdetallecambiorecId id) {
		this.id = id;
	}

}
