package com.casapellas.entidades;

// Generated 10-22-2009 04:07:11 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * VdetallecambiorecId generated by hbm2java
 */
public class VdetallecambiorecId implements java.io.Serializable {

	private int numrec;

	private String codcomp;

	private String codsuc;

	private int caid;

	private BigDecimal montoapl;

	private BigDecimal montorec;

	private BigDecimal cambio;

	private String cliente;

	private Date fecha;

	private Date hora;

	private String tiporec;

	private String monedacamb;

	private String estado;

	public VdetallecambiorecId() {
	}

	public VdetallecambiorecId(int numrec, String codsuc, int caid,
			BigDecimal montoapl, BigDecimal montorec, BigDecimal cambio,
			String cliente, Date fecha, Date hora, String tiporec,
			String monedacamb, String estado) {
		this.numrec = numrec;
		this.codsuc = codsuc;
		this.caid = caid;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.cambio = cambio;
		this.cliente = cliente;
		this.fecha = fecha;
		this.hora = hora;
		this.tiporec = tiporec;
		this.monedacamb = monedacamb;
		this.estado = estado;
	}

	public VdetallecambiorecId(int numrec, String codcomp, String codsuc,
			int caid, BigDecimal montoapl, BigDecimal montorec,
			BigDecimal cambio, String cliente, Date fecha, Date hora,
			String tiporec, String monedacamb, String estado) {
		this.numrec = numrec;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.caid = caid;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.cambio = cambio;
		this.cliente = cliente;
		this.fecha = fecha;
		this.hora = hora;
		this.tiporec = tiporec;
		this.monedacamb = monedacamb;
		this.estado = estado;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public BigDecimal getMontoapl() {
		return this.montoapl;
	}

	public void setMontoapl(BigDecimal montoapl) {
		this.montoapl = montoapl;
	}

	public BigDecimal getMontorec() {
		return this.montorec;
	}

	public void setMontorec(BigDecimal montorec) {
		this.montorec = montorec;
	}

	public BigDecimal getCambio() {
		return this.cambio;
	}

	public void setCambio(BigDecimal cambio) {
		this.cambio = cambio;
	}

	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public String getMonedacamb() {
		return this.monedacamb;
	}

	public void setMonedacamb(String monedacamb) {
		this.monedacamb = monedacamb;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdetallecambiorecId))
			return false;
		VdetallecambiorecId castOther = (VdetallecambiorecId) other;

		return (this.getNumrec() == castOther.getNumrec())
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& (this.getCaid() == castOther.getCaid())
				&& ((this.getMontoapl() == castOther.getMontoapl()) || (this
						.getMontoapl() != null
						&& castOther.getMontoapl() != null && this
						.getMontoapl().equals(castOther.getMontoapl())))
				&& ((this.getMontorec() == castOther.getMontorec()) || (this
						.getMontorec() != null
						&& castOther.getMontorec() != null && this
						.getMontorec().equals(castOther.getMontorec())))
				&& ((this.getCambio() == castOther.getCambio()) || (this
						.getCambio() != null
						&& castOther.getCambio() != null && this.getCambio()
						.equals(castOther.getCambio())))
				&& ((this.getCliente() == castOther.getCliente()) || (this
						.getCliente() != null
						&& castOther.getCliente() != null && this.getCliente()
						.equals(castOther.getCliente())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getTiporec() == castOther.getTiporec()) || (this
						.getTiporec() != null
						&& castOther.getTiporec() != null && this.getTiporec()
						.equals(castOther.getTiporec())))
				&& ((this.getMonedacamb() == castOther.getMonedacamb()) || (this
						.getMonedacamb() != null
						&& castOther.getMonedacamb() != null && this
						.getMonedacamb().equals(castOther.getMonedacamb())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null
						&& castOther.getEstado() != null && this.getEstado()
						.equals(castOther.getEstado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumrec();
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getMontoapl() == null ? 0 : this.getMontoapl().hashCode());
		result = 37 * result
				+ (getMontorec() == null ? 0 : this.getMontorec().hashCode());
		result = 37 * result
				+ (getCambio() == null ? 0 : this.getCambio().hashCode());
		result = 37 * result
				+ (getCliente() == null ? 0 : this.getCliente().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result
				+ (getTiporec() == null ? 0 : this.getTiporec().hashCode());
		result = 37
				* result
				+ (getMonedacamb() == null ? 0 : this.getMonedacamb()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		return result;
	}

}
