package com.casapellas.entidades;

// Generated Oct 16, 2015 5:00:27 PM by Hibernate Tools 4.0.0

/**
 * Vdetrecibodev generated by hbm2java
 */
public class Vdetrecibodev implements java.io.Serializable {

	private static final long serialVersionUID = -6055450818870106402L;
	private VdetrecibodevId id;

	public Vdetrecibodev() {
	}

	public Vdetrecibodev(VdetrecibodevId id) {
		this.id = id;
	}

	public VdetrecibodevId getId() {
		return this.id;
	}

	public void setId(VdetrecibodevId id) {
		this.id = id;
	}

}
