package com.casapellas.entidades;

// Generated 2/10/2009 11:30:26 by Hibernate Tools 3.2.0.b9

/**
 * Vdfactura generated by hbm2java
 */
public class Vdfactura implements java.io.Serializable {

	private VdfacturaId id;

	public Vdfactura() {
	}

	public Vdfactura(VdfacturaId id) {
		this.id = id;
	}

	public VdfacturaId getId() {
		return this.id;
	}

	public void setId(VdfacturaId id) {
		this.id = id;
	}

}
