package com.casapellas.entidades;

// Generated Apr 2, 2009 4:41:52 PM by Hibernate Tools 3.2.0.b9

/**
 * Vf0002 generated by hbm2java
 */
public class Vf0002 implements java.io.Serializable {

	private Vf0002Id id;

	public Vf0002() {
	}

	public Vf0002(Vf0002Id id) {
		this.id = id;
	}

	public Vf0002Id getId() {
		return this.id;
	}

	public void setId(Vf0002Id id) {
		this.id = id;
	}

}
