package com.casapellas.entidades;

// Generated 08-15-2010 06:33:19 PM by Hibernate Tools 3.2.0.b9

/**
 * Vf0101 generated by hbm2java
 */
public class Vf0101 implements java.io.Serializable {

	private static final long serialVersionUID = 4695272318257963055L;
	private Vf0101Id id;

	public Vf0101() {
	}

	public Vf0101(Vf0101Id id) {
		this.id = id;
	}

	public Vf0101Id getId() {
		return this.id;
	}

	public void setId(Vf0101Id id) {
		this.id = id;
	}

}
