package com.casapellas.entidades;

import com.casapellas.util.CodeUtil;

// Generated 08-15-2010 06:33:19 PM by Hibernate Tools 3.2.0.b9

/**
 * Vf0101Id generated by hbm2java
 */
public class Vf0101Id implements java.io.Serializable {

	private static final long serialVersionUID = 7599844741731782205L;
	private int aban8;
	private String abalph;
	private String aladd1;
	private String wwrem1;
	private String abate;
	private String abatr;
	private String abatpr;
	private String abatp;
	private String abat1;
	private String abat2;
	private String abat3;
	private String abat4;
	private String abat5;
	private String abac01;
	private String abac02;
	private String abac03;
	private String abac04;
	private String abac05;
	private String abac06;
	private String abac07;
	private String abac08;
	private String abac09;
	private String abac10;
	private String a5arc;
	private String abtx2;
	private String abcm;
	private String abxab;

	private String wwgnnm;
	private String wwmdnm;
	private String wwsrnm;
	
	private String a5co;

	public Vf0101Id() {
	}

	public Vf0101Id(int aban8, String abalph, String aladd1, String wwrem1,
			String abate, String abatr, String abatpr, String abatp,
			String abat1, String abat2, String abat3, String abat4,
			String abat5, String abac01, String abac02, String abac03,
			String abac04, String abac05, String abac06, String abac07,
			String abac08, String abac09, String abac10, String a5arc, 
			String a5co, String abtx2, String abcm, String abxab) {
		this.aban8 = aban8;
		this.abalph = abalph;
		this.aladd1 = aladd1;
		this.wwrem1 = wwrem1;
		this.abate = abate;
		this.abatr = abatr;
		this.abatpr = abatpr;
		this.abatp = abatp;
		this.abat1 = abat1;
		this.abat2 = abat2;
		this.abat3 = abat3;
		this.abat4 = abat4;
		this.abat5 = abat5;
		this.abac01 = abac01;
		this.abac02 = abac02;
		this.abac03 = abac03;
		this.abac04 = abac04;
		this.abac05 = abac05;
		this.abac06 = abac06;
		this.abac07 = abac07;
		this.abac08 = abac08;
		this.abac09 = abac09;
		this.abac10 = abac10;
		this.a5arc = a5arc;
		this.a5co = a5co;
		this.abtx2 = abtx2;
		this.abcm = abcm;
		this.abxab = abxab;
	}

	public int getAban8() {
		return this.aban8;
	}

	public void setAban8(int aban8) {
		this.aban8 = aban8;
	}

	public String getAbalph() {
		if(this.abalph != null){
			this.abalph = CodeUtil.capitalize(this.abalph.trim(), null);
		}
		return this.abalph;
	}

	public void setAbalph(String abalph) {
		this.abalph = abalph;
	}

	public String getAladd1() {
		return this.aladd1;
	}

	public void setAladd1(String aladd1) {
		this.aladd1 = aladd1;
	}

	public String getWwrem1() {
		return this.wwrem1;
	}

	public void setWwrem1(String wwrem1) {
		this.wwrem1 = wwrem1;
	}

	public String getAbate() {
		return this.abate;
	}

	public void setAbate(String abate) {
		this.abate = abate;
	}

	public String getAbatr() {
		return this.abatr;
	}

	public void setAbatr(String abatr) {
		this.abatr = abatr;
	}

	public String getAbatpr() {
		return this.abatpr;
	}

	public void setAbatpr(String abatpr) {
		this.abatpr = abatpr;
	}

	public String getAbatp() {
		return this.abatp;
	}

	public void setAbatp(String abatp) {
		this.abatp = abatp;
	}

	public String getAbat1() {
		return this.abat1;
	}

	public void setAbat1(String abat1) {
		this.abat1 = abat1;
	}

	public String getAbat2() {
		return this.abat2;
	}

	public void setAbat2(String abat2) {
		this.abat2 = abat2;
	}

	public String getAbat3() {
		return this.abat3;
	}

	public void setAbat3(String abat3) {
		this.abat3 = abat3;
	}

	public String getAbat4() {
		return this.abat4;
	}

	public void setAbat4(String abat4) {
		this.abat4 = abat4;
	}

	public String getAbat5() {
		return this.abat5;
	}

	public void setAbat5(String abat5) {
		this.abat5 = abat5;
	}

	public String getAbac01() {
		return this.abac01;
	}

	public void setAbac01(String abac01) {
		this.abac01 = abac01;
	}

	public String getAbac02() {
		return this.abac02;
	}

	public void setAbac02(String abac02) {
		this.abac02 = abac02;
	}

	public String getAbac03() {
		return this.abac03;
	}

	public void setAbac03(String abac03) {
		this.abac03 = abac03;
	}

	public String getAbac04() {
		return this.abac04;
	}

	public void setAbac04(String abac04) {
		this.abac04 = abac04;
	}

	public String getAbac05() {
		return this.abac05;
	}

	public void setAbac05(String abac05) {
		this.abac05 = abac05;
	}

	public String getAbac06() {
		return this.abac06;
	}

	public void setAbac06(String abac06) {
		this.abac06 = abac06;
	}

	public String getAbac07() {
		return this.abac07;
	}

	public void setAbac07(String abac07) {
		this.abac07 = abac07;
	}

	public String getAbac08() {
		return this.abac08;
	}

	public void setAbac08(String abac08) {
		this.abac08 = abac08;
	}

	public String getAbac09() {
		return this.abac09;
	}

	public void setAbac09(String abac09) {
		this.abac09 = abac09;
	}

	public String getAbac10() {
		return this.abac10;
	}

	public void setAbac10(String abac10) {
		this.abac10 = abac10;
	}

	public String getA5arc() {
		return this.a5arc;
	}

	public void setA5arc(String a5arc) {
		this.a5arc = a5arc;
	}

	public String getAbtx2() {
		if(this.abtx2 == null)
			this.abtx2 = "";
		return this.abtx2;
	}

	public void setAbtx2(String abtx2) {
		this.abtx2 = abtx2;
	}

	public String getAbcm() {
		return this.abcm;
	}

	public void setAbcm(String abcm) {
		this.abcm = abcm;
	}

	public String getAbxab() {
		return abxab;
	}

	public void setAbxab(String abxab) {
		this.abxab = abxab;
	}

	public String getWwgnnm() {
		if(this.wwgnnm != null){
			this.wwgnnm = CodeUtil.capitalize(this.wwgnnm.trim(), null);
		}
		return wwgnnm;
	}

	public void setWwgnnm(String wwgnnm) {
		this.wwgnnm = wwgnnm;
	}

	public String getWwmdnm() {
		
		if(this.wwmdnm != null){
			this.wwmdnm = CodeUtil.capitalize(this.wwmdnm.trim(), null);
		}
		
		return wwmdnm;
	}

	public void setWwmdnm(String wwmdnm) {
		this.wwmdnm = wwmdnm;
	}

	public String getWwsrnm() {
		
		if(this.wwsrnm != null){
			this.wwsrnm = CodeUtil.capitalize(this.wwsrnm.trim(), null);
		}
		
		return wwsrnm;
	}

	public void setWwsrnm(String wwsrnm) {
		this.wwsrnm = wwsrnm;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((a5arc == null) ? 0 : a5arc.hashCode());
		result = prime * result + ((a5co == null) ? 0 : a5co.hashCode());
		result = prime * result + ((abac01 == null) ? 0 : abac01.hashCode());
		result = prime * result + ((abac02 == null) ? 0 : abac02.hashCode());
		result = prime * result + ((abac03 == null) ? 0 : abac03.hashCode());
		result = prime * result + ((abac04 == null) ? 0 : abac04.hashCode());
		result = prime * result + ((abac05 == null) ? 0 : abac05.hashCode());
		result = prime * result + ((abac06 == null) ? 0 : abac06.hashCode());
		result = prime * result + ((abac07 == null) ? 0 : abac07.hashCode());
		result = prime * result + ((abac08 == null) ? 0 : abac08.hashCode());
		result = prime * result + ((abac09 == null) ? 0 : abac09.hashCode());
		result = prime * result + ((abac10 == null) ? 0 : abac10.hashCode());
		result = prime * result + ((abalph == null) ? 0 : abalph.hashCode());
		result = prime * result + aban8;
		result = prime * result + ((abat1 == null) ? 0 : abat1.hashCode());
		result = prime * result + ((abat2 == null) ? 0 : abat2.hashCode());
		result = prime * result + ((abat3 == null) ? 0 : abat3.hashCode());
		result = prime * result + ((abat4 == null) ? 0 : abat4.hashCode());
		result = prime * result + ((abat5 == null) ? 0 : abat5.hashCode());
		result = prime * result + ((abate == null) ? 0 : abate.hashCode());
		result = prime * result + ((abatp == null) ? 0 : abatp.hashCode());
		result = prime * result + ((abatpr == null) ? 0 : abatpr.hashCode());
		result = prime * result + ((abatr == null) ? 0 : abatr.hashCode());
		result = prime * result + ((abcm == null) ? 0 : abcm.hashCode());
		result = prime * result + ((abtx2 == null) ? 0 : abtx2.hashCode());
		result = prime * result + ((abxab == null) ? 0 : abxab.hashCode());
		result = prime * result + ((aladd1 == null) ? 0 : aladd1.hashCode());
		result = prime * result + ((wwgnnm == null) ? 0 : wwgnnm.hashCode());
		result = prime * result + ((wwmdnm == null) ? 0 : wwmdnm.hashCode());
		result = prime * result + ((wwrem1 == null) ? 0 : wwrem1.hashCode());
		result = prime * result + ((wwsrnm == null) ? 0 : wwsrnm.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vf0101Id other = (Vf0101Id) obj;
		if (a5arc == null) {
			if (other.a5arc != null)
				return false;
		} else if (!a5arc.equals(other.a5arc))
			return false;
		if (a5co == null) {
			if (other.a5co != null)
				return false;
		} else if (!a5co.equals(other.a5co))
			return false;
		if (abac01 == null) {
			if (other.abac01 != null)
				return false;
		} else if (!abac01.equals(other.abac01))
			return false;
		if (abac02 == null) {
			if (other.abac02 != null)
				return false;
		} else if (!abac02.equals(other.abac02))
			return false;
		if (abac03 == null) {
			if (other.abac03 != null)
				return false;
		} else if (!abac03.equals(other.abac03))
			return false;
		if (abac04 == null) {
			if (other.abac04 != null)
				return false;
		} else if (!abac04.equals(other.abac04))
			return false;
		if (abac05 == null) {
			if (other.abac05 != null)
				return false;
		} else if (!abac05.equals(other.abac05))
			return false;
		if (abac06 == null) {
			if (other.abac06 != null)
				return false;
		} else if (!abac06.equals(other.abac06))
			return false;
		if (abac07 == null) {
			if (other.abac07 != null)
				return false;
		} else if (!abac07.equals(other.abac07))
			return false;
		if (abac08 == null) {
			if (other.abac08 != null)
				return false;
		} else if (!abac08.equals(other.abac08))
			return false;
		if (abac09 == null) {
			if (other.abac09 != null)
				return false;
		} else if (!abac09.equals(other.abac09))
			return false;
		if (abac10 == null) {
			if (other.abac10 != null)
				return false;
		} else if (!abac10.equals(other.abac10))
			return false;
		if (abalph == null) {
			if (other.abalph != null)
				return false;
		} else if (!abalph.equals(other.abalph))
			return false;
		if (aban8 != other.aban8)
			return false;
		if (abat1 == null) {
			if (other.abat1 != null)
				return false;
		} else if (!abat1.equals(other.abat1))
			return false;
		if (abat2 == null) {
			if (other.abat2 != null)
				return false;
		} else if (!abat2.equals(other.abat2))
			return false;
		if (abat3 == null) {
			if (other.abat3 != null)
				return false;
		} else if (!abat3.equals(other.abat3))
			return false;
		if (abat4 == null) {
			if (other.abat4 != null)
				return false;
		} else if (!abat4.equals(other.abat4))
			return false;
		if (abat5 == null) {
			if (other.abat5 != null)
				return false;
		} else if (!abat5.equals(other.abat5))
			return false;
		if (abate == null) {
			if (other.abate != null)
				return false;
		} else if (!abate.equals(other.abate))
			return false;
		if (abatp == null) {
			if (other.abatp != null)
				return false;
		} else if (!abatp.equals(other.abatp))
			return false;
		if (abatpr == null) {
			if (other.abatpr != null)
				return false;
		} else if (!abatpr.equals(other.abatpr))
			return false;
		if (abatr == null) {
			if (other.abatr != null)
				return false;
		} else if (!abatr.equals(other.abatr))
			return false;
		if (abcm == null) {
			if (other.abcm != null)
				return false;
		} else if (!abcm.equals(other.abcm))
			return false;
		if (abtx2 == null) {
			if (other.abtx2 != null)
				return false;
		} else if (!abtx2.equals(other.abtx2))
			return false;
		if (abxab == null) {
			if (other.abxab != null)
				return false;
		} else if (!abxab.equals(other.abxab))
			return false;
		if (aladd1 == null) {
			if (other.aladd1 != null)
				return false;
		} else if (!aladd1.equals(other.aladd1))
			return false;
		if (wwgnnm == null) {
			if (other.wwgnnm != null)
				return false;
		} else if (!wwgnnm.equals(other.wwgnnm))
			return false;
		if (wwmdnm == null) {
			if (other.wwmdnm != null)
				return false;
		} else if (!wwmdnm.equals(other.wwmdnm))
			return false;
		if (wwrem1 == null) {
			if (other.wwrem1 != null)
				return false;
		} else if (!wwrem1.equals(other.wwrem1))
			return false;
		if (wwsrnm == null) {
			if (other.wwsrnm != null)
				return false;
		} else if (!wwsrnm.equals(other.wwsrnm))
			return false;
		
		return true;
	}

	public String getA5co() {
		return this.a5co;
	}

	public void setA5co(String a5co) {
		this.a5co = a5co;
	}

}
