package com.casapellas.entidades;

// Generated 01-26-2010 09:00:58 AM by Hibernate Tools 3.2.0.b9

/**
 * Vf0901 generated by hbm2java
 */
public class Vf0901 implements java.io.Serializable {

	private Vf0901Id id;
	
	private String cuenta;

	public Vf0901() {
	}

	public Vf0901(Vf0901Id id) {
		this.id = id;
	}

	public Vf0901Id getId() {
		return this.id;
	}

	public void setId(Vf0901Id id) {
		this.id = id;
	}

	public String getCuenta() {
		return cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}
	

}
