package com.casapellas.entidades;

// Generated 01-26-2010 09:00:58 AM by Hibernate Tools 3.2.0.b9

/**
 * Vf0901Id generated by hbm2java
 */
public class Vf0901Id implements java.io.Serializable {

	private String gmco;

	private String gmaid;

	private String gmmcu;

	private String gmobj;

	private String gmsub;

	private String gmans;

	private String gmdl01;

	private String gmpec;

	private String gmcrcd;

	public Vf0901Id() {
	}

	public Vf0901Id(String gmco, String gmaid, String gmmcu, String gmobj,
			String gmsub, String gmans, String gmdl01, String gmpec,
			String gmcrcd) {
		this.gmco = gmco;
		this.gmaid = gmaid;
		this.gmmcu = gmmcu;
		this.gmobj = gmobj;
		this.gmsub = gmsub;
		this.gmans = gmans;
		this.gmdl01 = gmdl01;
		this.gmpec = gmpec;
		this.gmcrcd = gmcrcd;
	}

	public String getGmco() {
		return this.gmco;
	}

	public void setGmco(String gmco) {
		this.gmco = gmco;
	}

	public String getGmaid() {
		return this.gmaid;
	}

	public void setGmaid(String gmaid) {
		this.gmaid = gmaid;
	}

	public String getGmmcu() {
		return this.gmmcu;
	}

	public void setGmmcu(String gmmcu) {
		this.gmmcu = gmmcu;
	}

	public String getGmobj() {
		return this.gmobj;
	}

	public void setGmobj(String gmobj) {
		this.gmobj = gmobj;
	}

	public String getGmsub() {
		if(gmsub == null)
			gmsub = "";
		return this.gmsub;
	}

	public void setGmsub(String gmsub) {
		this.gmsub = gmsub;
	}

	public String getGmans() {
		return this.gmans;
	}

	public void setGmans(String gmans) {
		this.gmans = gmans;
	}

	public String getGmdl01() {
		return this.gmdl01;
	}

	public void setGmdl01(String gmdl01) {
		this.gmdl01 = gmdl01;
	}

	public String getGmpec() {
		return this.gmpec;
	}

	public void setGmpec(String gmpec) {
		this.gmpec = gmpec;
	}

	public String getGmcrcd() {
		return this.gmcrcd;
	}

	public void setGmcrcd(String gmcrcd) {
		this.gmcrcd = gmcrcd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Vf0901Id))
			return false;
		Vf0901Id castOther = (Vf0901Id) other;

		return ((this.getGmco() == castOther.getGmco()) || (this.getGmco() != null
				&& castOther.getGmco() != null && this.getGmco().equals(
				castOther.getGmco())))
				&& ((this.getGmaid() == castOther.getGmaid()) || (this
						.getGmaid() != null
						&& castOther.getGmaid() != null && this.getGmaid()
						.equals(castOther.getGmaid())))
				&& ((this.getGmmcu() == castOther.getGmmcu()) || (this
						.getGmmcu() != null
						&& castOther.getGmmcu() != null && this.getGmmcu()
						.equals(castOther.getGmmcu())))
				&& ((this.getGmobj() == castOther.getGmobj()) || (this
						.getGmobj() != null
						&& castOther.getGmobj() != null && this.getGmobj()
						.equals(castOther.getGmobj())))
				&& ((this.getGmsub() == castOther.getGmsub()) || (this
						.getGmsub() != null
						&& castOther.getGmsub() != null && this.getGmsub()
						.equals(castOther.getGmsub())))
				&& ((this.getGmans() == castOther.getGmans()) || (this
						.getGmans() != null
						&& castOther.getGmans() != null && this.getGmans()
						.equals(castOther.getGmans())))
				&& ((this.getGmdl01() == castOther.getGmdl01()) || (this
						.getGmdl01() != null
						&& castOther.getGmdl01() != null && this.getGmdl01()
						.equals(castOther.getGmdl01())))
				&& ((this.getGmpec() == castOther.getGmpec()) || (this
						.getGmpec() != null
						&& castOther.getGmpec() != null && this.getGmpec()
						.equals(castOther.getGmpec())))
				&& ((this.getGmcrcd() == castOther.getGmcrcd()) || (this
						.getGmcrcd() != null
						&& castOther.getGmcrcd() != null && this.getGmcrcd()
						.equals(castOther.getGmcrcd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGmco() == null ? 0 : this.getGmco().hashCode());
		result = 37 * result
				+ (getGmaid() == null ? 0 : this.getGmaid().hashCode());
		result = 37 * result
				+ (getGmmcu() == null ? 0 : this.getGmmcu().hashCode());
		result = 37 * result
				+ (getGmobj() == null ? 0 : this.getGmobj().hashCode());
		result = 37 * result
				+ (getGmsub() == null ? 0 : this.getGmsub().hashCode());
		result = 37 * result
				+ (getGmans() == null ? 0 : this.getGmans().hashCode());
		result = 37 * result
				+ (getGmdl01() == null ? 0 : this.getGmdl01().hashCode());
		result = 37 * result
				+ (getGmpec() == null ? 0 : this.getGmpec().hashCode());
		result = 37 * result
				+ (getGmcrcd() == null ? 0 : this.getGmcrcd().hashCode());
		return result;
	}

}
