package com.casapellas.entidades;

// Generated Aug 2, 2011 11:30:56 AM by Hibernate Tools 3.2.2.GA

/**
 * Vf55ca01 generated by hbm2java
 */
public class Vf55ca01 implements java.io.Serializable {

	private Vf55ca01Id id;

	public Vf55ca01() {
	}

	public Vf55ca01(Vf55ca01Id id) {
		this.id = id;
	}

	public Vf55ca01Id getId() {
		return this.id;
	}

	public void setId(Vf55ca01Id id) {
		this.id = id;
	}

}
