package com.casapellas.entidades;

// default package
// Generated Jun 29, 2012 10:26:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vf55ca036Id generated by hbm2java
 */
public class Vf55ca036Id implements java.io.Serializable {

	private String b6rp01;
	private String b6dct;
	private String b6ln;
	private String b6sts;
	private String drdl01;

	public Vf55ca036Id() {
	}

	public Vf55ca036Id(String b6rp01, String b6dct, String b6ln, String b6sts,
			String drdl01) {
		this.b6rp01 = b6rp01;
		this.b6dct = b6dct;
		this.b6ln = b6ln;
		this.b6sts = b6sts;
		this.drdl01 = drdl01;
	}

	public String getB6rp01() {
		return this.b6rp01;
	}

	public void setB6rp01(String b6rp01) {
		this.b6rp01 = b6rp01;
	}

	public String getB6dct() {
		return this.b6dct;
	}

	public void setB6dct(String b6dct) {
		this.b6dct = b6dct;
	}

	public String getB6ln() {
		return this.b6ln;
	}

	public void setB6ln(String b6ln) {
		this.b6ln = b6ln;
	}

	public String getB6sts() {
		return this.b6sts;
	}

	public void setB6sts(String b6sts) {
		this.b6sts = b6sts;
	}

	public String getDrdl01() {
		return this.drdl01;
	}

	public void setDrdl01(String drdl01) {
		this.drdl01 = drdl01;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((b6dct == null) ? 0 : b6dct.hashCode());
		result = prime * result + ((b6ln == null) ? 0 : b6ln.hashCode());
		result = prime * result + ((b6rp01 == null) ? 0 : b6rp01.hashCode());
		result = prime * result + ((b6sts == null) ? 0 : b6sts.hashCode());
		result = prime * result + ((drdl01 == null) ? 0 : drdl01.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vf55ca036Id other = (Vf55ca036Id) obj;
		if (b6dct == null) {
			if (other.b6dct != null)
				return false;
		} else if (!b6dct.equals(other.b6dct))
			return false;
		if (b6ln == null) {
			if (other.b6ln != null)
				return false;
		} else if (!b6ln.equals(other.b6ln))
			return false;
		if (b6rp01 == null) {
			if (other.b6rp01 != null)
				return false;
		} else if (!b6rp01.equals(other.b6rp01))
			return false;
		if (b6sts == null) {
			if (other.b6sts != null)
				return false;
		} else if (!b6sts.equals(other.b6sts))
			return false;
		if (drdl01 == null) {
			if (other.drdl01 != null)
				return false;
		} else if (!drdl01.equals(other.drdl01))
			return false;
		return true;
	}

 

}
