package com.casapellas.entidades;

// default package
// Generated Jun 29, 2012 10:26:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vf55ca036 generated by hbm2java
 */
public class Vf55ca036 implements java.io.Serializable {

	private Vf55ca036Id id;

	public Vf55ca036() {
	}

	public Vf55ca036(Vf55ca036Id id) {
		this.id = id;
	}

	public Vf55ca036Id getId() {
		return this.id;
	}

	public void setId(Vf55ca036Id id) {
		this.id = id;
	}

}
