package com.casapellas.entidades;

// Generated 3/02/2009 08:49:45 by Hibernate Tools 3.2.0.b9

/**
 * VmarcaId generated by hbm2java
 */
public class VmarcaId implements java.io.Serializable {

	private String drky;

	private String drdl01;

	private String drdl02;

	public VmarcaId() {
	}

	public VmarcaId(String drky, String drdl01, String drdl02) {
		this.drky = drky;
		this.drdl01 = drdl01;
		this.drdl02 = drdl02;
	}

	public String getDrky() {
		return this.drky;
	}

	public void setDrky(String drky) {
		this.drky = drky;
	}

	public String getDrdl01() {
		return this.drdl01;
	}

	public void setDrdl01(String drdl01) {
		this.drdl01 = drdl01;
	}

	public String getDrdl02() {
		return this.drdl02;
	}

	public void setDrdl02(String drdl02) {
		this.drdl02 = drdl02;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VmarcaId))
			return false;
		VmarcaId castOther = (VmarcaId) other;

		return ((this.getDrky() == castOther.getDrky()) || (this.getDrky() != null
				&& castOther.getDrky() != null && this.getDrky().equals(
				castOther.getDrky())))
				&& ((this.getDrdl01() == castOther.getDrdl01()) || (this
						.getDrdl01() != null
						&& castOther.getDrdl01() != null && this.getDrdl01()
						.equals(castOther.getDrdl01())))
				&& ((this.getDrdl02() == castOther.getDrdl02()) || (this
						.getDrdl02() != null
						&& castOther.getDrdl02() != null && this.getDrdl02()
						.equals(castOther.getDrdl02())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDrky() == null ? 0 : this.getDrky().hashCode());
		result = 37 * result
				+ (getDrdl01() == null ? 0 : this.getDrdl01().hashCode());
		result = 37 * result
				+ (getDrdl02() == null ? 0 : this.getDrdl02().hashCode());
		return result;
	}

}
