package com.casapellas.entidades;

// Generated Mar 21, 2010 10:01:56 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * VmonedafactrecId generated by hbm2java
 */
public class VmonedafactrecId implements java.io.Serializable {

	private int numrec;

	private String tiporec;

	private BigDecimal montoapl;

	private Date fecha;

	private Date hora;

	private Date horamod;

	private String refer1;

	private String refer2;

	private String refer3;

	private String refer4;

	private String cliente;

	private String restado;

	private int caid;

	private String codcomp;

	private String codsuc;

	private String mpago;

	private String rmoneda;

	private BigDecimal monto;

	private BigDecimal tasa;

	private BigDecimal equiv;

	private BigDecimal cambio;

	private String cmoneda;

	private String fmoneda;

	private BigDecimal domeaplicado;

	private BigDecimal forarecibido;

	public VmonedafactrecId() {
	}

	public VmonedafactrecId(int numrec, String tiporec, BigDecimal montoapl,
			Date fecha, Date hora, Date horamod, String refer1, String refer2,
			String refer3, String refer4, String cliente, String restado,
			int caid, String codsuc, String mpago, String rmoneda,
			BigDecimal monto, BigDecimal tasa, BigDecimal equiv,
			BigDecimal cambio, String cmoneda) {
		this.numrec = numrec;
		this.tiporec = tiporec;
		this.montoapl = montoapl;
		this.fecha = fecha;
		this.hora = hora;
		this.horamod = horamod;
		this.refer1 = refer1;
		this.refer2 = refer2;
		this.refer3 = refer3;
		this.refer4 = refer4;
		this.cliente = cliente;
		this.restado = restado;
		this.caid = caid;
		this.codsuc = codsuc;
		this.mpago = mpago;
		this.rmoneda = rmoneda;
		this.monto = monto;
		this.tasa = tasa;
		this.equiv = equiv;
		this.cambio = cambio;
		this.cmoneda = cmoneda;
	}

	public VmonedafactrecId(int numrec, String tiporec, BigDecimal montoapl,
			Date fecha, Date hora, Date horamod, String refer1, String refer2,
			String refer3, String refer4, String cliente, String restado,
			int caid, String codcomp, String codsuc, String mpago,
			String rmoneda, BigDecimal monto, BigDecimal tasa,
			BigDecimal equiv, BigDecimal cambio, String cmoneda,
			String fmoneda, BigDecimal domeaplicado, BigDecimal forarecibido) {
		this.numrec = numrec;
		this.tiporec = tiporec;
		this.montoapl = montoapl;
		this.fecha = fecha;
		this.hora = hora;
		this.horamod = horamod;
		this.refer1 = refer1;
		this.refer2 = refer2;
		this.refer3 = refer3;
		this.refer4 = refer4;
		this.cliente = cliente;
		this.restado = restado;
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.mpago = mpago;
		this.rmoneda = rmoneda;
		this.monto = monto;
		this.tasa = tasa;
		this.equiv = equiv;
		this.cambio = cambio;
		this.cmoneda = cmoneda;
		this.fmoneda = fmoneda;
		this.domeaplicado = domeaplicado;
		this.forarecibido = forarecibido;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public BigDecimal getMontoapl() {
		return this.montoapl;
	}

	public void setMontoapl(BigDecimal montoapl) {
		this.montoapl = montoapl;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Date getHoramod() {
		return this.horamod;
	}

	public void setHoramod(Date horamod) {
		this.horamod = horamod;
	}

	public String getRefer1() {
		return this.refer1;
	}

	public void setRefer1(String refer1) {
		this.refer1 = refer1;
	}

	public String getRefer2() {
		return this.refer2;
	}

	public void setRefer2(String refer2) {
		this.refer2 = refer2;
	}

	public String getRefer3() {
		return this.refer3;
	}

	public void setRefer3(String refer3) {
		this.refer3 = refer3;
	}

	public String getRefer4() {
		return this.refer4;
	}

	public void setRefer4(String refer4) {
		this.refer4 = refer4;
	}

	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public String getRestado() {
		return this.restado;
	}

	public void setRestado(String restado) {
		this.restado = restado;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getMpago() {
		return this.mpago;
	}

	public void setMpago(String mpago) {
		this.mpago = mpago;
	}

	public String getRmoneda() {
		return this.rmoneda;
	}

	public void setRmoneda(String rmoneda) {
		this.rmoneda = rmoneda;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}

	public BigDecimal getEquiv() {
		return this.equiv;
	}

	public void setEquiv(BigDecimal equiv) {
		this.equiv = equiv;
	}

	public BigDecimal getCambio() {
		return this.cambio;
	}

	public void setCambio(BigDecimal cambio) {
		this.cambio = cambio;
	}

	public String getCmoneda() {
		return this.cmoneda;
	}

	public void setCmoneda(String cmoneda) {
		this.cmoneda = cmoneda;
	}

	public String getFmoneda() {
		return this.fmoneda;
	}

	public void setFmoneda(String fmoneda) {
		this.fmoneda = fmoneda;
	}

	public BigDecimal getDomeaplicado() {
		return this.domeaplicado;
	}

	public void setDomeaplicado(BigDecimal domeaplicado) {
		this.domeaplicado = domeaplicado;
	}

	public BigDecimal getForarecibido() {
		return this.forarecibido;
	}

	public void setForarecibido(BigDecimal forarecibido) {
		this.forarecibido = forarecibido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VmonedafactrecId))
			return false;
		VmonedafactrecId castOther = (VmonedafactrecId) other;

		return (this.getNumrec() == castOther.getNumrec())
				&& ((this.getTiporec() == castOther.getTiporec()) || (this
						.getTiporec() != null
						&& castOther.getTiporec() != null && this.getTiporec()
						.equals(castOther.getTiporec())))
				&& ((this.getMontoapl() == castOther.getMontoapl()) || (this
						.getMontoapl() != null
						&& castOther.getMontoapl() != null && this
						.getMontoapl().equals(castOther.getMontoapl())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getHoramod() == castOther.getHoramod()) || (this
						.getHoramod() != null
						&& castOther.getHoramod() != null && this.getHoramod()
						.equals(castOther.getHoramod())))
				&& ((this.getRefer1() == castOther.getRefer1()) || (this
						.getRefer1() != null
						&& castOther.getRefer1() != null && this.getRefer1()
						.equals(castOther.getRefer1())))
				&& ((this.getRefer2() == castOther.getRefer2()) || (this
						.getRefer2() != null
						&& castOther.getRefer2() != null && this.getRefer2()
						.equals(castOther.getRefer2())))
				&& ((this.getRefer3() == castOther.getRefer3()) || (this
						.getRefer3() != null
						&& castOther.getRefer3() != null && this.getRefer3()
						.equals(castOther.getRefer3())))
				&& ((this.getRefer4() == castOther.getRefer4()) || (this
						.getRefer4() != null
						&& castOther.getRefer4() != null && this.getRefer4()
						.equals(castOther.getRefer4())))
				&& ((this.getCliente() == castOther.getCliente()) || (this
						.getCliente() != null
						&& castOther.getCliente() != null && this.getCliente()
						.equals(castOther.getCliente())))
				&& ((this.getRestado() == castOther.getRestado()) || (this
						.getRestado() != null
						&& castOther.getRestado() != null && this.getRestado()
						.equals(castOther.getRestado())))
				&& (this.getCaid() == castOther.getCaid())
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& ((this.getMpago() == castOther.getMpago()) || (this
						.getMpago() != null
						&& castOther.getMpago() != null && this.getMpago()
						.equals(castOther.getMpago())))
				&& ((this.getRmoneda() == castOther.getRmoneda()) || (this
						.getRmoneda() != null
						&& castOther.getRmoneda() != null && this.getRmoneda()
						.equals(castOther.getRmoneda())))
				&& ((this.getMonto() == castOther.getMonto()) || (this
						.getMonto() != null
						&& castOther.getMonto() != null && this.getMonto()
						.equals(castOther.getMonto())))
				&& ((this.getTasa() == castOther.getTasa()) || (this.getTasa() != null
						&& castOther.getTasa() != null && this.getTasa()
						.equals(castOther.getTasa())))
				&& ((this.getEquiv() == castOther.getEquiv()) || (this
						.getEquiv() != null
						&& castOther.getEquiv() != null && this.getEquiv()
						.equals(castOther.getEquiv())))
				&& ((this.getCambio() == castOther.getCambio()) || (this
						.getCambio() != null
						&& castOther.getCambio() != null && this.getCambio()
						.equals(castOther.getCambio())))
				&& ((this.getCmoneda() == castOther.getCmoneda()) || (this
						.getCmoneda() != null
						&& castOther.getCmoneda() != null && this.getCmoneda()
						.equals(castOther.getCmoneda())))
				&& ((this.getFmoneda() == castOther.getFmoneda()) || (this
						.getFmoneda() != null
						&& castOther.getFmoneda() != null && this.getFmoneda()
						.equals(castOther.getFmoneda())))
				&& ((this.getDomeaplicado() == castOther.getDomeaplicado()) || (this
						.getDomeaplicado() != null
						&& castOther.getDomeaplicado() != null && this
						.getDomeaplicado().equals(castOther.getDomeaplicado())))
				&& ((this.getForarecibido() == castOther.getForarecibido()) || (this
						.getForarecibido() != null
						&& castOther.getForarecibido() != null && this
						.getForarecibido().equals(castOther.getForarecibido())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumrec();
		result = 37 * result
				+ (getTiporec() == null ? 0 : this.getTiporec().hashCode());
		result = 37 * result
				+ (getMontoapl() == null ? 0 : this.getMontoapl().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result
				+ (getHoramod() == null ? 0 : this.getHoramod().hashCode());
		result = 37 * result
				+ (getRefer1() == null ? 0 : this.getRefer1().hashCode());
		result = 37 * result
				+ (getRefer2() == null ? 0 : this.getRefer2().hashCode());
		result = 37 * result
				+ (getRefer3() == null ? 0 : this.getRefer3().hashCode());
		result = 37 * result
				+ (getRefer4() == null ? 0 : this.getRefer4().hashCode());
		result = 37 * result
				+ (getCliente() == null ? 0 : this.getCliente().hashCode());
		result = 37 * result
				+ (getRestado() == null ? 0 : this.getRestado().hashCode());
		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getMpago() == null ? 0 : this.getMpago().hashCode());
		result = 37 * result
				+ (getRmoneda() == null ? 0 : this.getRmoneda().hashCode());
		result = 37 * result
				+ (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37 * result
				+ (getTasa() == null ? 0 : this.getTasa().hashCode());
		result = 37 * result
				+ (getEquiv() == null ? 0 : this.getEquiv().hashCode());
		result = 37 * result
				+ (getCambio() == null ? 0 : this.getCambio().hashCode());
		result = 37 * result
				+ (getCmoneda() == null ? 0 : this.getCmoneda().hashCode());
		result = 37 * result
				+ (getFmoneda() == null ? 0 : this.getFmoneda().hashCode());
		result = 37
				* result
				+ (getDomeaplicado() == null ? 0 : this.getDomeaplicado()
						.hashCode());
		result = 37
				* result
				+ (getForarecibido() == null ? 0 : this.getForarecibido()
						.hashCode());
		return result;
	}

}
