package com.casapellas.entidades;

// Generated 06/02/2010 11:03:53 AM by Hibernate Tools 3.2.0.b9

/**
 * Vmora generated by hbm2java
 */
public class Vmora implements java.io.Serializable {

	private VmoraId id;

	public Vmora() {
	}

	public Vmora(VmoraId id) {
		this.id = id;
	}

	public VmoraId getId() {
		return this.id;
	}

	public void setId(VmoraId id) {
		this.id = id;
	}

}
