package com.casapellas.entidades;

// Generated 05-09-2012 03:15:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * Vreciboxdevolucion generated by hbm2java
 */
public class Vreciboxdevolucion implements java.io.Serializable {

	private VreciboxdevolucionId id;

	public Vreciboxdevolucion() {
	}

	public Vreciboxdevolucion(VreciboxdevolucionId id) {
		this.id = id;
	}

	public VreciboxdevolucionId getId() {
		return this.id;
	}

	public void setId(VreciboxdevolucionId id) {
		this.id = id;
	}

}
