package com.casapellas.entidades;

// Generated Mar 24, 2010 3:48:28 PM by Hibernate Tools 3.2.0.b9

/**
 * Vrecibo generated by hbm2java
 */
public class Vrecibo implements java.io.Serializable {

	private VreciboId id;

	public Vrecibo() {
	}

	public Vrecibo(VreciboId id) {
		this.id = id;
	}

	public VreciboId getId() {
		return this.id;
	}

	public void setId(VreciboId id) {
		this.id = id;
	}

}
