package com.casapellas.entidades;

// Generated 09-25-2009 10:30:44 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * VrecibodetalleId generated by hbm2java
 */
public class VrecibodetalleId implements java.io.Serializable {

	private int numrec;

	private BigDecimal montoapl;

	private BigDecimal montorec;

	private String concepto;

	private String tiporec;

	private Date fecha;

	private String cliente;

	private int codcli;

	private String cajero;

	private String codcomp;

	private Date hora;

	private int numrecm;

	private int recjde;

	private int caid;

	private String codsuc;

	private String estado;

	private String motivo;

	private String codusera;

	private Date horamod;

	private String moneda;

	public VrecibodetalleId() {
	}

	public VrecibodetalleId(int numrec, BigDecimal montoapl,
			BigDecimal montorec, String tiporec, Date fecha, String cliente,
			int codcli, String cajero, Date hora, int numrecm, int recjde,
			int caid, String codsuc, String estado, String motivo,
			String codusera, Date horamod, String moneda) {
		this.numrec = numrec;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.tiporec = tiporec;
		this.fecha = fecha;
		this.cliente = cliente;
		this.codcli = codcli;
		this.cajero = cajero;
		this.hora = hora;
		this.numrecm = numrecm;
		this.recjde = recjde;
		this.caid = caid;
		this.codsuc = codsuc;
		this.estado = estado;
		this.motivo = motivo;
		this.codusera = codusera;
		this.horamod = horamod;
		this.moneda = moneda;
	}

	public VrecibodetalleId(int numrec, BigDecimal montoapl,
			BigDecimal montorec, String concepto, String tiporec, Date fecha,
			String cliente, int codcli, String cajero, String codcomp,
			Date hora, int numrecm, int recjde, int caid, String codsuc,
			String estado, String motivo, String codusera, Date horamod,
			String moneda) {
		this.numrec = numrec;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.concepto = concepto;
		this.tiporec = tiporec;
		this.fecha = fecha;
		this.cliente = cliente;
		this.codcli = codcli;
		this.cajero = cajero;
		this.codcomp = codcomp;
		this.hora = hora;
		this.numrecm = numrecm;
		this.recjde = recjde;
		this.caid = caid;
		this.codsuc = codsuc;
		this.estado = estado;
		this.motivo = motivo;
		this.codusera = codusera;
		this.horamod = horamod;
		this.moneda = moneda;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public BigDecimal getMontoapl() {
		return this.montoapl;
	}

	public void setMontoapl(BigDecimal montoapl) {
		this.montoapl = montoapl;
	}

	public BigDecimal getMontorec() {
		return this.montorec;
	}

	public void setMontorec(BigDecimal montorec) {
		this.montorec = montorec;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public int getCodcli() {
		return this.codcli;
	}

	public void setCodcli(int codcli) {
		this.codcli = codcli;
	}

	public String getCajero() {
		return this.cajero;
	}

	public void setCajero(String cajero) {
		this.cajero = cajero;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public int getNumrecm() {
		return this.numrecm;
	}

	public void setNumrecm(int numrecm) {
		this.numrecm = numrecm;
	}

	public int getRecjde() {
		return this.recjde;
	}

	public void setRecjde(int recjde) {
		this.recjde = recjde;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public String getCodusera() {
		return this.codusera;
	}

	public void setCodusera(String codusera) {
		this.codusera = codusera;
	}

	public Date getHoramod() {
		return this.horamod;
	}

	public void setHoramod(Date horamod) {
		this.horamod = horamod;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VrecibodetalleId))
			return false;
		VrecibodetalleId castOther = (VrecibodetalleId) other;

		return (this.getNumrec() == castOther.getNumrec())
				&& ((this.getMontoapl() == castOther.getMontoapl()) || (this
						.getMontoapl() != null
						&& castOther.getMontoapl() != null && this
						.getMontoapl().equals(castOther.getMontoapl())))
				&& ((this.getMontorec() == castOther.getMontorec()) || (this
						.getMontorec() != null
						&& castOther.getMontorec() != null && this
						.getMontorec().equals(castOther.getMontorec())))
				&& ((this.getConcepto() == castOther.getConcepto()) || (this
						.getConcepto() != null
						&& castOther.getConcepto() != null && this
						.getConcepto().equals(castOther.getConcepto())))
				&& ((this.getTiporec() == castOther.getTiporec()) || (this
						.getTiporec() != null
						&& castOther.getTiporec() != null && this.getTiporec()
						.equals(castOther.getTiporec())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())))
				&& ((this.getCliente() == castOther.getCliente()) || (this
						.getCliente() != null
						&& castOther.getCliente() != null && this.getCliente()
						.equals(castOther.getCliente())))
				&& (this.getCodcli() == castOther.getCodcli())
				&& ((this.getCajero() == castOther.getCajero()) || (this
						.getCajero() != null
						&& castOther.getCajero() != null && this.getCajero()
						.equals(castOther.getCajero())))
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& (this.getNumrecm() == castOther.getNumrecm())
				&& (this.getRecjde() == castOther.getRecjde())
				&& (this.getCaid() == castOther.getCaid())
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null
						&& castOther.getEstado() != null && this.getEstado()
						.equals(castOther.getEstado())))
				&& ((this.getMotivo() == castOther.getMotivo()) || (this
						.getMotivo() != null
						&& castOther.getMotivo() != null && this.getMotivo()
						.equals(castOther.getMotivo())))
				&& ((this.getCodusera() == castOther.getCodusera()) || (this
						.getCodusera() != null
						&& castOther.getCodusera() != null && this
						.getCodusera().equals(castOther.getCodusera())))
				&& ((this.getHoramod() == castOther.getHoramod()) || (this
						.getHoramod() != null
						&& castOther.getHoramod() != null && this.getHoramod()
						.equals(castOther.getHoramod())))
				&& ((this.getMoneda() == castOther.getMoneda()) || (this
						.getMoneda() != null
						&& castOther.getMoneda() != null && this.getMoneda()
						.equals(castOther.getMoneda())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumrec();
		result = 37 * result
				+ (getMontoapl() == null ? 0 : this.getMontoapl().hashCode());
		result = 37 * result
				+ (getMontorec() == null ? 0 : this.getMontorec().hashCode());
		result = 37 * result
				+ (getConcepto() == null ? 0 : this.getConcepto().hashCode());
		result = 37 * result
				+ (getTiporec() == null ? 0 : this.getTiporec().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getCliente() == null ? 0 : this.getCliente().hashCode());
		result = 37 * result + this.getCodcli();
		result = 37 * result
				+ (getCajero() == null ? 0 : this.getCajero().hashCode());
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result + this.getNumrecm();
		result = 37 * result + this.getRecjde();
		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result
				+ (getMotivo() == null ? 0 : this.getMotivo().hashCode());
		result = 37 * result
				+ (getCodusera() == null ? 0 : this.getCodusera().hashCode());
		result = 37 * result
				+ (getHoramod() == null ? 0 : this.getHoramod().hashCode());
		result = 37 * result
				+ (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		return result;
	}

}
