package com.casapellas.entidades;

import java.math.BigDecimal;

// Generated Nov 1, 2010 10:26:09 AM by Hibernate Tools 3.2.0.b9

/**
 * Vrecibosxtipompago generated by hbm2java
 */
public class Vrecibosxtipompago implements java.io.Serializable {

 
	private static final long serialVersionUID = 8568294149809275747L;

	private VrecibosxtipompagoId id;

	private BigDecimal monto;
	
	private boolean procesado;
	
	public Vrecibosxtipompago() {
	}

	public Vrecibosxtipompago(VrecibosxtipompagoId id) {
		this.id = id;
	}

	public VrecibosxtipompagoId getId() {
		return this.id;
	}

	public void setId(VrecibosxtipompagoId id) {
		this.id = id;
	}

	public BigDecimal getMonto() {
		return monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public boolean isProcesado() {
		return procesado;
	}

	public void setProcesado(boolean procesado) {
		this.procesado = procesado;
	}

}
