package com.casapellas.entidades;

// Generated Mar 11, 2010 5:37:03 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * VrecibodevreciboId generated by hbm2java
 */
public class VrecibodevreciboId implements java.io.Serializable {
	
	private static final long serialVersionUID = -2343429017416972303L;

	private int numrec;

	private int caid;

	private String codcomp;

	private String codsuc;

	private String tiporec;

	private String mpago;

	private BigDecimal monto;

	private int nodoco;

	private String tipodoco;

	private BigDecimal montoapl;

	private BigDecimal montorec;

	private String moneda;

	private Date fecha;

	private Date hora;

	private String cliente;

	private String refer1;

	private String refer2;

	private String refer3;

	private String refer4;

	private String estado;

	private String codunineg;

	private BigDecimal montoneto;

	private int devolucion;

	private BigDecimal afcomision;

	private String afnombre;

	private String vmanual;
	private int referencenumber;
	private int depctatran;
	
	public VrecibodevreciboId() {
	}

	public VrecibodevreciboId(int numrec, int caid, String codcomp,
			String codsuc, String tiporec, String mpago, BigDecimal monto,
			int nodoco, String tipodoco, BigDecimal montoapl,
			BigDecimal montorec, String moneda, Date fecha, Date hora,
			String cliente, String refer1, String refer2, String refer3,
			String refer4, String estado, String codunineg,
			BigDecimal montoneto, int devolucion, BigDecimal afcomision,
			String afnombre, String vmanual, int referencenumber, int depctatran) {
		super();
		this.numrec = numrec;
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.tiporec = tiporec;
		this.mpago = mpago;
		this.monto = monto;
		this.nodoco = nodoco;
		this.tipodoco = tipodoco;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.moneda = moneda;
		this.fecha = fecha;
		this.hora = hora;
		this.cliente = cliente;
		this.refer1 = refer1;
		this.refer2 = refer2;
		this.refer3 = refer3;
		this.refer4 = refer4;
		this.estado = estado;
		this.codunineg = codunineg;
		this.montoneto = montoneto;
		this.devolucion = devolucion;
		this.afcomision = afcomision;
		this.afnombre = afnombre;
		this.referencenumber = referencenumber;
		this.depctatran = depctatran;
		this.vmanual = vmanual ;
	}
	
	public VrecibodevreciboId(int numrec, int caid, String codsuc,
			String tiporec, String mpago, BigDecimal monto, int nodoco,
			BigDecimal montoapl, BigDecimal montorec, String moneda,
			Date fecha, Date hora, String cliente, String refer1,
			String refer2, String refer3, String refer4, String estado,
			String codunineg, int devolucion) {
		this.numrec = numrec;
		this.caid = caid;
		this.codsuc = codsuc;
		this.tiporec = tiporec;
		this.mpago = mpago;
		this.monto = monto;
		this.nodoco = nodoco;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.moneda = moneda;
		this.fecha = fecha;
		this.hora = hora;
		this.cliente = cliente;
		this.refer1 = refer1;
		this.refer2 = refer2;
		this.refer3 = refer3;
		this.refer4 = refer4;
		this.estado = estado;
		this.codunineg = codunineg;
		this.devolucion = devolucion;
	}

	public VrecibodevreciboId(int numrec, int caid, String codcomp,
			String codsuc, String tiporec, String mpago, BigDecimal monto,
			int nodoco, String tipodoco, BigDecimal montoapl,
			BigDecimal montorec, String moneda, Date fecha, Date hora,
			String cliente, String refer1, String refer2, String refer3,
			String refer4, String estado, String codunineg,
			BigDecimal montoneto, int devolucion, BigDecimal afcomision,
			String afnombre) {
		this.numrec = numrec;
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.tiporec = tiporec;
		this.mpago = mpago;
		this.monto = monto;
		this.nodoco = nodoco;
		this.tipodoco = tipodoco;
		this.montoapl = montoapl;
		this.montorec = montorec;
		this.moneda = moneda;
		this.fecha = fecha;
		this.hora = hora;
		this.cliente = cliente;
		this.refer1 = refer1;
		this.refer2 = refer2;
		this.refer3 = refer3;
		this.refer4 = refer4;
		this.estado = estado;
		this.codunineg = codunineg;
		this.montoneto = montoneto;
		this.devolucion = devolucion;
		this.afcomision = afcomision;
		this.afnombre = afnombre;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public String getMpago() {
		return this.mpago;
	}

	public void setMpago(String mpago) {
		this.mpago = mpago;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public int getNodoco() {
		return this.nodoco;
	}

	public void setNodoco(int nodoco) {
		this.nodoco = nodoco;
	}

	public String getTipodoco() {
		return this.tipodoco;
	}

	public void setTipodoco(String tipodoco) {
		this.tipodoco = tipodoco;
	}

	public BigDecimal getMontoapl() {
		return this.montoapl;
	}

	public void setMontoapl(BigDecimal montoapl) {
		this.montoapl = montoapl;
	}

	public BigDecimal getMontorec() {
		return this.montorec;
	}

	public void setMontorec(BigDecimal montorec) {
		this.montorec = montorec;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public String getRefer1() {
		return this.refer1;
	}

	public void setRefer1(String refer1) {
		this.refer1 = refer1;
	}

	public String getRefer2() {
		return this.refer2;
	}

	public void setRefer2(String refer2) {
		this.refer2 = refer2;
	}

	public String getRefer3() {
		return this.refer3;
	}

	public void setRefer3(String refer3) {
		this.refer3 = refer3;
	}

	public String getRefer4() {
		return this.refer4;
	}

	public void setRefer4(String refer4) {
		this.refer4 = refer4;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public BigDecimal getMontoneto() {
		return this.montoneto;
	}

	public void setMontoneto(BigDecimal montoneto) {
		this.montoneto = montoneto;
	}

	public int getDevolucion() {
		return this.devolucion;
	}

	public void setDevolucion(int devolucion) {
		this.devolucion = devolucion;
	}

	public BigDecimal getAfcomision() {
		return this.afcomision;
	}

	public void setAfcomision(BigDecimal afcomision) {
		this.afcomision = afcomision;
	}

	public String getAfnombre() {
		return this.afnombre;
	}

	public void setAfnombre(String afnombre) {
		this.afnombre = afnombre;
	}

	public int getReferencenumber() {
		return referencenumber;
	}

	public void setReferencenumber(int referencenumber) {
		this.referencenumber = referencenumber;
	}

	public int getDepctatran() {
		return depctatran;
	}

	public void setDepctatran(int depctatran) {
		this.depctatran = depctatran;
	}

	public String getVmanual() {
		return vmanual;
	}

	public void setVmanual(String vmanual) {
		this.vmanual = vmanual;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((afcomision == null) ? 0 : afcomision.hashCode());
		result = prime * result
				+ ((afnombre == null) ? 0 : afnombre.hashCode());
		result = prime * result + caid;
		result = prime * result + ((cliente == null) ? 0 : cliente.hashCode());
		result = prime * result + ((codcomp == null) ? 0 : codcomp.hashCode());
		result = prime * result + ((codsuc == null) ? 0 : codsuc.hashCode());
		result = prime * result
				+ ((codunineg == null) ? 0 : codunineg.hashCode());
		result = prime * result + depctatran;
		result = prime * result + devolucion;
		result = prime * result + ((estado == null) ? 0 : estado.hashCode());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		result = prime * result + ((hora == null) ? 0 : hora.hashCode());
		result = prime * result + ((moneda == null) ? 0 : moneda.hashCode());
		result = prime * result + ((monto == null) ? 0 : monto.hashCode());
		result = prime * result
				+ ((montoapl == null) ? 0 : montoapl.hashCode());
		result = prime * result
				+ ((montoneto == null) ? 0 : montoneto.hashCode());
		result = prime * result
				+ ((montorec == null) ? 0 : montorec.hashCode());
		result = prime * result + ((mpago == null) ? 0 : mpago.hashCode());
		result = prime * result + nodoco;
		result = prime * result + numrec;
		result = prime * result + ((refer1 == null) ? 0 : refer1.hashCode());
		result = prime * result + ((refer2 == null) ? 0 : refer2.hashCode());
		result = prime * result + ((refer3 == null) ? 0 : refer3.hashCode());
		result = prime * result + ((refer4 == null) ? 0 : refer4.hashCode());
		result = prime * result + referencenumber;
		result = prime * result
				+ ((tipodoco == null) ? 0 : tipodoco.hashCode());
		result = prime * result + ((tiporec == null) ? 0 : tiporec.hashCode());
		result = prime * result + ((vmanual == null) ? 0 : vmanual.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		VrecibodevreciboId other = (VrecibodevreciboId) obj;
		if (afcomision == null) {
			if (other.afcomision != null)
				return false;
		} else if (!afcomision.equals(other.afcomision))
			return false;
		if (afnombre == null) {
			if (other.afnombre != null)
				return false;
		} else if (!afnombre.equals(other.afnombre))
			return false;
		if (caid != other.caid)
			return false;
		if (cliente == null) {
			if (other.cliente != null)
				return false;
		} else if (!cliente.equals(other.cliente))
			return false;
		if (codcomp == null) {
			if (other.codcomp != null)
				return false;
		} else if (!codcomp.equals(other.codcomp))
			return false;
		if (codsuc == null) {
			if (other.codsuc != null)
				return false;
		} else if (!codsuc.equals(other.codsuc))
			return false;
		if (codunineg == null) {
			if (other.codunineg != null)
				return false;
		} else if (!codunineg.equals(other.codunineg))
			return false;
		if (depctatran != other.depctatran)
			return false;
		if (devolucion != other.devolucion)
			return false;
		if (estado == null) {
			if (other.estado != null)
				return false;
		} else if (!estado.equals(other.estado))
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		if (hora == null) {
			if (other.hora != null)
				return false;
		} else if (!hora.equals(other.hora))
			return false;
		if (moneda == null) {
			if (other.moneda != null)
				return false;
		} else if (!moneda.equals(other.moneda))
			return false;
		if (monto == null) {
			if (other.monto != null)
				return false;
		} else if (!monto.equals(other.monto))
			return false;
		if (montoapl == null) {
			if (other.montoapl != null)
				return false;
		} else if (!montoapl.equals(other.montoapl))
			return false;
		if (montoneto == null) {
			if (other.montoneto != null)
				return false;
		} else if (!montoneto.equals(other.montoneto))
			return false;
		if (montorec == null) {
			if (other.montorec != null)
				return false;
		} else if (!montorec.equals(other.montorec))
			return false;
		if (mpago == null) {
			if (other.mpago != null)
				return false;
		} else if (!mpago.equals(other.mpago))
			return false;
		if (nodoco != other.nodoco)
			return false;
		if (numrec != other.numrec)
			return false;
		if (refer1 == null) {
			if (other.refer1 != null)
				return false;
		} else if (!refer1.equals(other.refer1))
			return false;
		if (refer2 == null) {
			if (other.refer2 != null)
				return false;
		} else if (!refer2.equals(other.refer2))
			return false;
		if (refer3 == null) {
			if (other.refer3 != null)
				return false;
		} else if (!refer3.equals(other.refer3))
			return false;
		if (refer4 == null) {
			if (other.refer4 != null)
				return false;
		} else if (!refer4.equals(other.refer4))
			return false;
		if (referencenumber != other.referencenumber)
			return false;
		if (tipodoco == null) {
			if (other.tipodoco != null)
				return false;
		} else if (!tipodoco.equals(other.tipodoco))
			return false;
		if (tiporec == null) {
			if (other.tiporec != null)
				return false;
		} else if (!tiporec.equals(other.tiporec))
			return false;
		if (vmanual == null) {
			if (other.vmanual != null)
				return false;
		} else if (!vmanual.equals(other.vmanual))
			return false;
		return true;
	}
}
