package com.casapellas.entidades;

// Generated 2/10/2009 11:30:26 by Hibernate Tools 3.2.0.b9

/**
 * Vrecfac generated by hbm2java
 */
public class Vrecfac implements java.io.Serializable {

	private VrecfacId id;

	public Vrecfac() {
	}

	public Vrecfac(VrecfacId id) {
		this.id = id;
	}

	public VrecfacId getId() {
		return this.id;
	}

	public void setId(VrecfacId id) {
		this.id = id;
	}

}
