package com.casapellas.entidades;

import java.math.BigDecimal;

// Generated 07-21-2009 05:00:10 PM by Hibernate Tools 3.2.0.b9

/**
 * Vrecibosxtipoingreso generated by hbm2java
 */
public class Vrecibosxtipoingreso implements java.io.Serializable {

	private VrecibosxtipoingresoId id;
	
	private BigDecimal monto;
	

	public Vrecibosxtipoingreso() {
	}

	public Vrecibosxtipoingreso(VrecibosxtipoingresoId id) {
		this.id = id;
	}

	public VrecibosxtipoingresoId getId() {
		return this.id;
	}

	public void setId(VrecibosxtipoingresoId id) {
		this.id = id;
	}

	public BigDecimal getMonto() {
		return monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}



	
}
