package com.casapellas.entidades;

// Generated 09-06-2010 10:18:27 AM by Hibernate Tools 3.2.0.b9

/**
 * Vretencion generated by hbm2java
 */
public class Vretencion implements java.io.Serializable {

	private VretencionId id;

	public Vretencion() {
	}

	public Vretencion(VretencionId id) {
		this.id = id;
	}

	public VretencionId getId() {
		return this.id;
	}

	public void setId(VretencionId id) {
		this.id = id;
	}

}
