package com.casapellas.entidades;

// Generated Feb 8, 2011 11:05:26 AM by Hibernate Tools 3.2.0.b9

/**
 * Vrptmcaja006 generated by hbm2java
 */
public class Vrptmcaja006 implements java.io.Serializable {

	private Vrptmcaja006Id id;

	public Vrptmcaja006() {
	}

	public Vrptmcaja006(Vrptmcaja006Id id) {
		this.id = id;
	}

	public Vrptmcaja006Id getId() {
		return this.id;
	}

	public void setId(Vrptmcaja006Id id) {
		this.id = id;
	}

}
