package com.casapellas.entidades;

// Generated Apr 5, 2010 12:41:41 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * Vrptmcaja005Id generated by hbm2java
 */
public class Vrptmcaja005Id implements java.io.Serializable {

	private int numrec;

	private String tiporec;

	private int caid;

	private String codcomp;

	private String codsuc;

	private BigDecimal monto;

	private BigDecimal montoapl;

	private Date fecha;

	private Date hora;

	private String moneda;

	private String cliente;

	private String codunineg;

	private int nobatch;

	private String recjde;

	private int glaid;

	private String glani;

	private String gllt;

	private String glcrcd;

	private BigDecimal glaa;

	private String gljeln;
	
	private String gldct;
	
	private String fecharecibo;
	
	private String cuentacre;
	
	private String cuentadeb;
	
	private double montodeb;
	
	private double montocre;
	

	public Vrptmcaja005Id() {
	}

	public Vrptmcaja005Id(int numrec, String tiporec, int caid, String codsuc,
			BigDecimal monto, BigDecimal montoapl, Date fecha, Date hora,
			String moneda, String cliente, String codunineg, int nobatch,
			String recjde, int glaid, String glani, String gllt, String glcrcd,
			BigDecimal glaa, String gljeln, String gldct) {
		this.numrec = numrec;
		this.tiporec = tiporec;
		this.caid = caid;
		this.codsuc = codsuc;
		this.monto = monto;
		this.montoapl = montoapl;
		this.fecha = fecha;
		this.hora = hora;
		this.moneda = moneda;
		this.cliente = cliente;
		this.codunineg = codunineg;
		this.nobatch = nobatch;
		this.recjde = recjde;
		this.glaid = glaid;
		this.glani = glani;
		this.gllt = gllt;
		this.glcrcd = glcrcd;
		this.glaa = glaa;
		this.gljeln = gljeln;
		this.gldct = gldct;
	}

	public Vrptmcaja005Id(int numrec, String tiporec, int caid, String codcomp,
			String codsuc, BigDecimal monto, BigDecimal montoapl, Date fecha,
			Date hora, String moneda, String cliente, String codunineg,
			int nobatch, String recjde, int glaid, String glani, String gllt,
			String glcrcd, BigDecimal glaa, String gljeln) {
		this.numrec = numrec;
		this.tiporec = tiporec;
		this.caid = caid;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.monto = monto;
		this.montoapl = montoapl;
		this.fecha = fecha;
		this.hora = hora;
		this.moneda = moneda;
		this.cliente = cliente;
		this.codunineg = codunineg;
		this.nobatch = nobatch;
		this.recjde = recjde;
		this.glaid = glaid;
		this.glani = glani;
		this.gllt = gllt;
		this.glcrcd = glcrcd;
		this.glaa = glaa;
		this.gljeln = gljeln;
		this.gldct = gldct;
	}

	public int getNumrec() {
		return this.numrec;
	}

	public void setNumrec(int numrec) {
		this.numrec = numrec;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public BigDecimal getMontoapl() {
		return this.montoapl;
	}

	public void setMontoapl(BigDecimal montoapl) {
		this.montoapl = montoapl;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getCliente() {
		return this.cliente;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public int getNobatch() {
		return this.nobatch;
	}

	public void setNobatch(int nobatch) {
		this.nobatch = nobatch;
	}

	public String getRecjde() {
		return this.recjde;
	}

	public void setRecjde(String recjde) {
		this.recjde = recjde;
	}

	public int getGlaid() {
		return this.glaid;
	}

	public void setGlaid(int glaid) {
		this.glaid = glaid;
	}

	public String getGlani() {
		return this.glani;
	}

	public void setGlani(String glani) {
		this.glani = glani;
	}

	public String getGllt() {
		return this.gllt;
	}

	public void setGllt(String gllt) {
		this.gllt = gllt;
	}

	public String getGlcrcd() {
		return this.glcrcd;
	}

	public void setGlcrcd(String glcrcd) {
		this.glcrcd = glcrcd;
	}

	public BigDecimal getGlaa() {
		return this.glaa;
	}

	public void setGlaa(BigDecimal glaa) {
		this.glaa = glaa;
	}

	public String getGljeln() {
		return this.gljeln;
	}

	public void setGljeln(String gljeln) {
		this.gljeln = gljeln;
	}
	
	public String getCuentacre() {
		return cuentacre;
	}

	public void setCuentacre(String cuentacre) {
		this.cuentacre = cuentacre;
	}

	public String getCuentadeb() {
		return cuentadeb;
	}

	public void setCuentadeb(String cuentadeb) {
		this.cuentadeb = cuentadeb;
	}

	public String getFecharecibo() {
		return fecharecibo;
	}

	public void setFecharecibo(String fecharecibo) {
		this.fecharecibo = fecharecibo;
	}

	public double getMontocre() {
		return montocre;
	}

	public void setMontocre(double montocre) {
		this.montocre = montocre;
	}

	public double getMontodeb() {
		return montodeb;
	}

	public void setMontodeb(double montodeb) {
		this.montodeb = montodeb;
	}

	public String getGldct() {
		return gldct;
	}

	public void setGldct(String gldct) {
		this.gldct = gldct;
	}
 
	
	
}
