package com.casapellas.entidades;
// Generated Dec 23, 2013 10:39:01 AM by Hibernate Tools 3.2.1.GA

/**
 * Vsolecheque generated by hbm2java
 */
public class Vsolecheque  implements java.io.Serializable {

	private static final long serialVersionUID = -1855578295750581442L;
	private VsolechequeId id;

    public Vsolecheque() {
    }

    public Vsolecheque(VsolechequeId id) {
       this.id = id;
    }
   
    public VsolechequeId getId() {
        return this.id;
    }
    
    public void setId(VsolechequeId id) {
        this.id = id;
    }




}


