package com.casapellas.entidades;

// Generated 07-21-2009 02:57:07 PM by Hibernate Tools 3.2.0.b9

/**
 * Vtotaltipoingreso generated by hbm2java
 */
public class Vtotaltipoingreso implements java.io.Serializable {

	private VtotaltipoingresoId id;

	public Vtotaltipoingreso() {
	}

	public Vtotaltipoingreso(VtotaltipoingresoId id) {
		this.id = id;
	}

	public VtotaltipoingresoId getId() {
		return this.id;
	}

	public void setId(VtotaltipoingresoId id) {
		this.id = id;
	}

}
