package com.casapellas.entidades;

// Generated 07-21-2009 02:57:07 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * VtotaltipoingresoId generated by hbm2java
 */
public class VtotaltipoingresoId implements java.io.Serializable {

	private Date fecha;

	private String codcomp;

	private String codsuc;

	private int caid;

	private String tiporec;

	private BigDecimal cord;

	private BigDecimal usd;

	public VtotaltipoingresoId() {
	}

	public VtotaltipoingresoId(Date fecha, String codsuc, int caid,
			String tiporec) {
		this.fecha = fecha;
		this.codsuc = codsuc;
		this.caid = caid;
		this.tiporec = tiporec;
	}

	public VtotaltipoingresoId(Date fecha, String codcomp, String codsuc,
			int caid, String tiporec, BigDecimal cord, BigDecimal usd) {
		this.fecha = fecha;
		this.codcomp = codcomp;
		this.codsuc = codsuc;
		this.caid = caid;
		this.tiporec = tiporec;
		this.cord = cord;
		this.usd = usd;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public String getTiporec() {
		return this.tiporec;
	}

	public void setTiporec(String tiporec) {
		this.tiporec = tiporec;
	}

	public BigDecimal getCord() {
		return this.cord;
	}

	public void setCord(BigDecimal cord) {
		this.cord = cord;
	}

	public BigDecimal getUsd() {
		return this.usd;
	}

	public void setUsd(BigDecimal usd) {
		this.usd = usd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtotaltipoingresoId))
			return false;
		VtotaltipoingresoId castOther = (VtotaltipoingresoId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
				&& castOther.getFecha() != null && this.getFecha().equals(
				castOther.getFecha())))
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null
						&& castOther.getCodcomp() != null && this.getCodcomp()
						.equals(castOther.getCodcomp())))
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null
						&& castOther.getCodsuc() != null && this.getCodsuc()
						.equals(castOther.getCodsuc())))
				&& (this.getCaid() == castOther.getCaid())
				&& ((this.getTiporec() == castOther.getTiporec()) || (this
						.getTiporec() != null
						&& castOther.getTiporec() != null && this.getTiporec()
						.equals(castOther.getTiporec())))
				&& ((this.getCord() == castOther.getCord()) || (this.getCord() != null
						&& castOther.getCord() != null && this.getCord()
						.equals(castOther.getCord())))
				&& ((this.getUsd() == castOther.getUsd()) || (this.getUsd() != null
						&& castOther.getUsd() != null && this.getUsd().equals(
						castOther.getUsd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result + this.getCaid();
		result = 37 * result
				+ (getTiporec() == null ? 0 : this.getTiporec().hashCode());
		result = 37 * result
				+ (getCord() == null ? 0 : this.getCord().hashCode());
		result = 37 * result
				+ (getUsd() == null ? 0 : this.getUsd().hashCode());
		return result;
	}

}
