package com.casapellas.entidades;

// Generated Aug 9, 2016 2:43:42 PM by Hibernate Tools 4.3.1

/**
 * Vwcuentascontablesporbanco generated by hbm2java
 */
public class Vwcuentascontablesporbanco implements java.io.Serializable {

	private static final long serialVersionUID = -2458521160089164299L;
	private int rowid;
	private int codb;
	private String banco;
	private String estado;
	private boolean conciliar;
	private String conciliacion;
	private String cuentacontable;
	private String d3rp01;
	private String d3crcd;
	private String d3mcu;
	private String d3obj;
	private String d3sub;
	private String gmco;
	private String gmaid;
	private String nombrecuentacontable;
	private int conciliarxcompania;
	private String conciliacionxcomp;
	
	public Vwcuentascontablesporbanco(int rowid, int codb, String banco,
			String estado, boolean conciliar, String conciliacion,
			String cuentacontable, String d3rp01, String d3crcd, String d3mcu,
			String d3obj, String d3sub, String gmco, String gmaid,
			String nombrecuentacontable, int conciliarxcompania,
			String conciliacionxcomp) {
		super();
		this.rowid = rowid;
		this.codb = codb;
		this.banco = banco;
		this.estado = estado;
		this.conciliar = conciliar;
		this.conciliacion = conciliacion;
		this.cuentacontable = cuentacontable;
		this.d3rp01 = d3rp01;
		this.d3crcd = d3crcd;
		this.d3mcu = d3mcu;
		this.d3obj = d3obj;
		this.d3sub = d3sub;
		this.gmco = gmco;
		this.gmaid = gmaid;
		this.nombrecuentacontable = nombrecuentacontable;
		this.conciliarxcompania = conciliarxcompania;
		this.conciliacionxcomp = conciliacionxcomp;
	}
 
	public Vwcuentascontablesporbanco() {
		super();
	}

	public int getRowid() {
		return rowid;
	}

	public void setRowid(int rowid) {
		this.rowid = rowid;
	}

	public int getCodb() {
		return codb;
	}

	public void setCodb(int codb) {
		this.codb = codb;
	}

	public String getBanco() {
		return banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public boolean isConciliar() {
		return conciliar;
	}

	public void setConciliar(boolean conciliar) {
		this.conciliar = conciliar;
	}

	public String getConciliacion() {
		return conciliacion;
	}

	public void setConciliacion(String conciliacion) {
		this.conciliacion = conciliacion;
	}

	public String getCuentacontable() {
		return cuentacontable;
	}

	public void setCuentacontable(String cuentacontable) {
		this.cuentacontable = cuentacontable;
	}

	public String getD3rp01() {
		return d3rp01;
	}

	public void setD3rp01(String d3rp01) {
		this.d3rp01 = d3rp01;
	}

	public String getD3crcd() {
		return d3crcd;
	}

	public void setD3crcd(String d3crcd) {
		this.d3crcd = d3crcd;
	}

	public String getD3mcu() {
		return d3mcu;
	}

	public void setD3mcu(String d3mcu) {
		this.d3mcu = d3mcu;
	}

	public String getD3obj() {
		return d3obj;
	}

	public void setD3obj(String d3obj) {
		this.d3obj = d3obj;
	}

	public String getD3sub() {
		return d3sub;
	}

	public void setD3sub(String d3sub) {
		this.d3sub = d3sub;
	}

	public String getGmco() {
		return gmco;
	}

	public void setGmco(String gmco) {
		this.gmco = gmco;
	}

	public String getGmaid() {
		return gmaid;
	}

	public void setGmaid(String gmaid) {
		this.gmaid = gmaid;
	}

	public String getNombrecuentacontable() {
		return nombrecuentacontable;
	}

	public void setNombrecuentacontable(String nombrecuentacontable) {
		this.nombrecuentacontable = nombrecuentacontable;
	}
	
	public int getConciliarxcompania() {
		return conciliarxcompania;
	}

	public void setConciliarxcompania(int conciliarxcompania) {
		this.conciliarxcompania = conciliarxcompania;
	}

	public String getConciliacionxcomp() {
		return conciliacionxcomp;
	}

	public void setConciliacionxcomp(String conciliacionxcomp) {
		this.conciliacionxcomp = conciliacionxcomp;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((banco == null) ? 0 : banco.hashCode());
		result = prime * result + codb;
		result = prime * result
				+ ((conciliacion == null) ? 0 : conciliacion.hashCode());
		result = prime * result + (conciliar ? 1231 : 1237);
		result = prime * result
				+ ((cuentacontable == null) ? 0 : cuentacontable.hashCode());
		result = prime * result + ((d3crcd == null) ? 0 : d3crcd.hashCode());
		result = prime * result + ((d3mcu == null) ? 0 : d3mcu.hashCode());
		result = prime * result + ((d3obj == null) ? 0 : d3obj.hashCode());
		result = prime * result + ((d3rp01 == null) ? 0 : d3rp01.hashCode());
		result = prime * result + ((d3sub == null) ? 0 : d3sub.hashCode());
		result = prime * result + ((estado == null) ? 0 : estado.hashCode());
		result = prime * result + ((gmaid == null) ? 0 : gmaid.hashCode());
		result = prime * result + ((gmco == null) ? 0 : gmco.hashCode());
		result = prime
				* result
				+ ((nombrecuentacontable == null) ? 0 : nombrecuentacontable
						.hashCode());
		result = prime * result + rowid;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vwcuentascontablesporbanco other = (Vwcuentascontablesporbanco) obj;
		if (banco == null) {
			if (other.banco != null)
				return false;
		} else if (!banco.equals(other.banco))
			return false;
		if (codb != other.codb)
			return false;
		if (conciliacion == null) {
			if (other.conciliacion != null)
				return false;
		} else if (!conciliacion.equals(other.conciliacion))
			return false;
		if (conciliar != other.conciliar)
			return false;
		if (cuentacontable == null) {
			if (other.cuentacontable != null)
				return false;
		} else if (!cuentacontable.equals(other.cuentacontable))
			return false;
		if (d3crcd == null) {
			if (other.d3crcd != null)
				return false;
		} else if (!d3crcd.equals(other.d3crcd))
			return false;
		if (d3mcu == null) {
			if (other.d3mcu != null)
				return false;
		} else if (!d3mcu.equals(other.d3mcu))
			return false;
		if (d3obj == null) {
			if (other.d3obj != null)
				return false;
		} else if (!d3obj.equals(other.d3obj))
			return false;
		if (d3rp01 == null) {
			if (other.d3rp01 != null)
				return false;
		} else if (!d3rp01.equals(other.d3rp01))
			return false;
		if (d3sub == null) {
			if (other.d3sub != null)
				return false;
		} else if (!d3sub.equals(other.d3sub))
			return false;
		if (estado == null) {
			if (other.estado != null)
				return false;
		} else if (!estado.equals(other.estado))
			return false;
		if (gmaid == null) {
			if (other.gmaid != null)
				return false;
		} else if (!gmaid.equals(other.gmaid))
			return false;
		if (gmco == null) {
			if (other.gmco != null)
				return false;
		} else if (!gmco.equals(other.gmco))
			return false;
		if (nombrecuentacontable == null) {
			if (other.nombrecuentacontable != null)
				return false;
		} else if (!nombrecuentacontable.equals(other.nombrecuentacontable))
			return false;
		if (rowid != other.rowid)
			return false;
		return true;
	}
	 
 
}
