package com.casapellas.conciliacion.entidades;

// Generated Oct 7, 2011 4:09:23 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.casapellas.conciliacion.entidades.Conciliacion;

/**
 * Archivo generated by hbm2java
 */
public class Archivo implements java.io.Serializable {
 
	private static final long serialVersionUID = 2415149620910947747L;
	private int idarchivo;
	private String nombre;
	private BigDecimal tamanio;
	private int cantlinea;
	private int idbanco;
	private String moneda;
	private String direftp;
	private int estado;
	private int estadproc;
	private Date datearchivo;
	private Date fechacrea;
	private int usrcrea;
	private int usrmodi;
	private String observacion;
	private Date fechamod;
	private Set<Conciliacion> conciliacions = new HashSet<Conciliacion>(0);
	private Set<Depbancodet> depbancodets = new HashSet<Depbancodet>(0);

	public Archivo() {
	}

	public Archivo(int idarchivo, String nombre, BigDecimal tamanio,
			int cantlinea, int idbanco, String moneda, String direftp,
			int estado, int estadproc, Date datearchivo, Date fechacrea,
			int usrcrea, int usrmodi, String observacion, Date fechamod) {
		this.idarchivo = idarchivo;
		this.nombre = nombre;
		this.tamanio = tamanio;
		this.cantlinea = cantlinea;
		this.idbanco = idbanco;
		this.moneda = moneda;
		this.direftp = direftp;
		this.estado = estado;
		this.estadproc = estadproc;
		this.datearchivo = datearchivo;
		this.fechacrea = fechacrea;
		this.usrcrea = usrcrea;
		this.usrmodi = usrmodi;
		this.observacion = observacion;
		this.fechamod = fechamod;
	}

	public Archivo(int idarchivo, String nombre, BigDecimal tamanio,
			int cantlinea, int idbanco, String moneda, String direftp,
			int estado, int estadproc, Date datearchivo, Date fechacrea,
			int usrcrea, int usrmodi, String observacion, Date fechamod,
			Set<Conciliacion> conciliacions, Set<Depbancodet> depbancodets) {
		this.idarchivo = idarchivo;
		this.nombre = nombre;
		this.tamanio = tamanio;
		this.cantlinea = cantlinea;
		this.idbanco = idbanco;
		this.moneda = moneda;
		this.direftp = direftp;
		this.estado = estado;
		this.estadproc = estadproc;
		this.datearchivo = datearchivo;
		this.fechacrea = fechacrea;
		this.usrcrea = usrcrea;
		this.usrmodi = usrmodi;
		this.observacion = observacion;
		this.fechamod = fechamod;
		this.conciliacions = conciliacions;
		this.depbancodets = depbancodets;
	}

	public int getIdarchivo() {
		return this.idarchivo;
	}

	public void setIdarchivo(int idarchivo) {
		this.idarchivo = idarchivo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getTamanio() {
		return this.tamanio;
	}

	public void setTamanio(BigDecimal tamanio) {
		this.tamanio = tamanio;
	}

	public int getCantlinea() {
		return this.cantlinea;
	}

	public void setCantlinea(int cantlinea) {
		this.cantlinea = cantlinea;
	}

	public int getIdbanco() {
		return this.idbanco;
	}

	public void setIdbanco(int idbanco) {
		this.idbanco = idbanco;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getDireftp() {
		return this.direftp;
	}

	public void setDireftp(String direftp) {
		this.direftp = direftp;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public int getEstadproc() {
		return this.estadproc;
	}

	public void setEstadproc(int estadproc) {
		this.estadproc = estadproc;
	}

	public Date getDatearchivo() {
		return this.datearchivo;
	}

	public void setDatearchivo(Date datearchivo) {
		this.datearchivo = datearchivo;
	}

	public Date getFechacrea() {
		return this.fechacrea;
	}

	public void setFechacrea(Date fechacrea) {
		this.fechacrea = fechacrea;
	}

	public int getUsrcrea() {
		return this.usrcrea;
	}

	public void setUsrcrea(int usrcrea) {
		this.usrcrea = usrcrea;
	}

	public int getUsrmodi() {
		return this.usrmodi;
	}

	public void setUsrmodi(int usrmodi) {
		this.usrmodi = usrmodi;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public Set<Conciliacion> getConciliacions() {
		return this.conciliacions;
	}

	public void setConciliacions(Set<Conciliacion> conciliacions) {
		this.conciliacions = conciliacions;
	}

	public Set<Depbancodet> getDepbancodets() {
		return this.depbancodets;
	}

	public void setDepbancodets(Set<Depbancodet> depbancodets) {
		this.depbancodets = depbancodets;
	}

}
