package com.casapellas.conciliacion.entidades;

// Generated Oct 7, 2011 4:09:23 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conciliacion generated by hbm2java
 */
public class Conciliacion implements java.io.Serializable {
	private static final long serialVersionUID = -4215370556284868069L;
	private int idconciliacion;
	private Archivo archivo;
	private BigDecimal monto;
	private int nobatch;
	private int noreferencia;
	private String moneda;
	private String tipodoc;
	private int idcuenta;
	private int estado;
	private int usrcrea;
	private int usrmod;
	private Date fechamod;
	private Date fechacrea;
	private int rnobatch;
	private int rnodoc;
	private String usuariocomprobante;
	private int codigousrcomprobante;
	private Set<Ajusteconc> ajusteconcs = new HashSet<Ajusteconc>(0);
	private Set<Conciliadet> conciliadets = new HashSet<Conciliadet>(0);
	private String estadobatch;
	
	public static Conciliacion conciliacionFromVwConciliacion(Vwconciliacion v){
		return 
			new  Conciliacion(
			v.getId().getIdconciliacion(), null, v.getId().getMonto(), v.getId().getNobatch(),
			v.getId().getNoreferencia(),v.getId().getMoneda(), v.getId().getTipodoc(),v.getId().getIdcuenta(),v.getId().getEstado(),
			v.getId().getUsrcrea(),v.getId().getUsrmod(), v.getId().getFechamod(), v.getId().getFechacrea(), v.getId().getRnobatch(),
			v.getId().getRnodoc(),v.getId().getUsuariocomprobante(), v.getId().getCodigousrcomprobante()			
			);
	}
	
	public Conciliacion() {
	}
	
	public Conciliacion(int idconciliacion, Archivo archivo, BigDecimal monto,
			int nobatch, int noreferencia, String moneda, String tipodoc,
			int idcuenta, int estado, int usrcrea, int usrmod, Date fechamod,
			Date fechacrea, int rnobatch, int rnodoc,
			String usuariocomprobante, int codigousrcomprobante ) {
		super();
		this.idconciliacion = idconciliacion;
		this.archivo = archivo;
		this.monto = monto;
		this.nobatch = nobatch;
		this.noreferencia = noreferencia;
		this.moneda = moneda;
		this.tipodoc = tipodoc;
		this.idcuenta = idcuenta;
		this.estado = estado;
		this.usrcrea = usrcrea;
		this.usrmod = usrmod;
		this.fechamod = fechamod;
		this.fechacrea = fechacrea;
		this.rnobatch = rnobatch;
		this.rnodoc = rnodoc;
		this.usuariocomprobante = usuariocomprobante;
		this.codigousrcomprobante = codigousrcomprobante;
	}


	public Conciliacion(int idconciliacion, Archivo archivo, BigDecimal monto,
			int nobatch, int noreferencia, String moneda, String tipodoc,
			int idcuenta, int estado, int usrcrea, int usrmod, Date fechamod,
			Date fechacrea, int rnobatch, int rnodoc) {
		this.idconciliacion = idconciliacion;
		this.archivo = archivo;
		this.monto = monto;
		this.nobatch = nobatch;
		this.noreferencia = noreferencia;
		this.moneda = moneda;
		this.tipodoc = tipodoc;
		this.idcuenta = idcuenta;
		this.estado = estado;
		this.usrcrea = usrcrea;
		this.usrmod = usrmod;
		this.fechamod = fechamod;
		this.fechacrea = fechacrea;
		this.rnobatch = rnobatch;
		this.rnodoc = rnodoc;
	}

	public Conciliacion(int idconciliacion, Archivo archivo, BigDecimal monto,
			int nobatch, int noreferencia, String moneda, String tipodoc,
			int idcuenta, int estado, int usrcrea, int usrmod, Date fechamod,
			Date fechacrea, int rnobatch, int rnodoc,
			Set<Ajusteconc> ajusteconcs, Set<Conciliadet> conciliadets) {
		this.idconciliacion = idconciliacion;
		this.archivo = archivo;
		this.monto = monto;
		this.nobatch = nobatch;
		this.noreferencia = noreferencia;
		this.moneda = moneda;
		this.tipodoc = tipodoc;
		this.idcuenta = idcuenta;
		this.estado = estado;
		this.usrcrea = usrcrea;
		this.usrmod = usrmod;
		this.fechamod = fechamod;
		this.fechacrea = fechacrea;
		this.rnobatch = rnobatch;
		this.rnodoc = rnodoc;
		this.ajusteconcs = ajusteconcs;
		this.conciliadets = conciliadets;
	}

	public int getIdconciliacion() {
		return this.idconciliacion;
	}

	public void setIdconciliacion(int idconciliacion) {
		this.idconciliacion = idconciliacion;
	}

	public Archivo getArchivo() {
		return this.archivo;
	}

	public void setArchivo(Archivo archivo) {
		this.archivo = archivo;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public int getNobatch() {
		return this.nobatch;
	}

	public void setNobatch(int nobatch) {
		this.nobatch = nobatch;
	}

	public int getNoreferencia() {
		return this.noreferencia;
	}

	public void setNoreferencia(int noreferencia) {
		this.noreferencia = noreferencia;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	public int getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(int idcuenta) {
		this.idcuenta = idcuenta;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public int getUsrcrea() {
		return this.usrcrea;
	}

	public void setUsrcrea(int usrcrea) {
		this.usrcrea = usrcrea;
	}

	public int getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(int usrmod) {
		this.usrmod = usrmod;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public Date getFechacrea() {
		return this.fechacrea;
	}

	public void setFechacrea(Date fechacrea) {
		this.fechacrea = fechacrea;
	}

	public int getRnobatch() {
		return this.rnobatch;
	}

	public void setRnobatch(int rnobatch) {
		this.rnobatch = rnobatch;
	}

	public int getRnodoc() {
		return this.rnodoc;
	}

	public void setRnodoc(int rnodoc) {
		this.rnodoc = rnodoc;
	}

	public Set<Ajusteconc> getAjusteconcs() {
		return this.ajusteconcs;
	}

	public void setAjusteconcs(Set<Ajusteconc> ajusteconcs) {
		this.ajusteconcs = ajusteconcs;
	}

	public Set<Conciliadet> getConciliadets() {
		return this.conciliadets;
	}

	public void setConciliadets(Set<Conciliadet> conciliadets) {
		this.conciliadets = conciliadets;
	}


	public String getUsuariocomprobante() {
		return usuariocomprobante;
	}
	public void setUsuariocomprobante(String usuariocomprobante) {
		this.usuariocomprobante = usuariocomprobante;
	}
	public int getCodigousrcomprobante() {
		return codigousrcomprobante;
	}
	public void setCodigousrcomprobante(int codigousrcomprobante) {
		this.codigousrcomprobante = codigousrcomprobante;
	}
	public String getEstadobatch() {
		return estadobatch;
	}
	public void setEstadobatch(String estadobatch) {
		this.estadobatch = estadobatch;
	}
}
