package com.casapellas.conciliacion.entidades;
// Generated Feb 11, 2015 6:30:41 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * PcdConsolidadoDepositosConfirmados generated by hbm2java
 */
public class PcdConsolidadoDepositosConfirmados  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -9158838498869507136L;
	private int idresumendepositoconfirmado;
     private int idconsolidadobco;
     private int iddepbcodet;
     private int numeroreferenciaorg;
     private int numeroreferenciajde;
     private BigDecimal monto;
     private String moneda;
     private long codigobanco;
     private long numerocuenta;
     private Date fechadeposito;
     private String codigotransaccion;
     private String descripcion;
     private String estadodecuenta;
     private long cantidadcomparaciones;
     private Date fechaconfirmacion;
     private int tipoconfirmacion;
     private int usuarioconfirmacion;
     private String observaciones;
     private BigDecimal montodeajuste;
     private Date fechacreacion;

    public PcdConsolidadoDepositosConfirmados() {
    }

    public PcdConsolidadoDepositosConfirmados(int idresumendepositoconfirmado, int idconsolidadobco, int iddepbcodet, int numeroreferenciaorg, int numeroreferenciajde, BigDecimal monto, String moneda, long codigobanco, long numerocuenta, Date fechadeposito, String codigotransaccion, String descripcion, String estadodecuenta, long cantidadcomparaciones, Date fechaconfirmacion, int tipoconfirmacion, int usuarioconfirmacion, String observaciones, BigDecimal montodeajuste, Date fechacreacion) {
       this.idresumendepositoconfirmado = idresumendepositoconfirmado;
       this.idconsolidadobco = idconsolidadobco;
       this.iddepbcodet = iddepbcodet;
       this.numeroreferenciaorg = numeroreferenciaorg;
       this.numeroreferenciajde = numeroreferenciajde;
       this.monto = monto;
       this.moneda = moneda;
       this.codigobanco = codigobanco;
       this.numerocuenta = numerocuenta;
       this.fechadeposito = fechadeposito;
       this.codigotransaccion = codigotransaccion;
       this.descripcion = descripcion;
       this.estadodecuenta = estadodecuenta;
       this.cantidadcomparaciones = cantidadcomparaciones;
       this.fechaconfirmacion = fechaconfirmacion;
       this.tipoconfirmacion = tipoconfirmacion;
       this.usuarioconfirmacion = usuarioconfirmacion;
       this.observaciones = observaciones;
       this.montodeajuste = montodeajuste;
       this.fechacreacion = fechacreacion;
    }
   
    public int getIdresumendepositoconfirmado() {
        return this.idresumendepositoconfirmado;
    }
    
    public void setIdresumendepositoconfirmado(int idresumendepositoconfirmado) {
        this.idresumendepositoconfirmado = idresumendepositoconfirmado;
    }
    public int getIdconsolidadobco() {
        return this.idconsolidadobco;
    }
    
    public void setIdconsolidadobco(int idconsolidadobco) {
        this.idconsolidadobco = idconsolidadobco;
    }
    public int getIddepbcodet() {
        return this.iddepbcodet;
    }
    
    public void setIddepbcodet(int iddepbcodet) {
        this.iddepbcodet = iddepbcodet;
    }
    public int getNumeroreferenciaorg() {
        return this.numeroreferenciaorg;
    }
    
    public void setNumeroreferenciaorg(int numeroreferenciaorg) {
        this.numeroreferenciaorg = numeroreferenciaorg;
    }
    public int getNumeroreferenciajde() {
        return this.numeroreferenciajde;
    }
    
    public void setNumeroreferenciajde(int numeroreferenciajde) {
        this.numeroreferenciajde = numeroreferenciajde;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public long getCodigobanco() {
        return this.codigobanco;
    }
    
    public void setCodigobanco(long codigobanco) {
        this.codigobanco = codigobanco;
    }
    public long getNumerocuenta() {
        return this.numerocuenta;
    }
    
    public void setNumerocuenta(long numerocuenta) {
        this.numerocuenta = numerocuenta;
    }
    public Date getFechadeposito() {
        return this.fechadeposito;
    }
    
    public void setFechadeposito(Date fechadeposito) {
        this.fechadeposito = fechadeposito;
    }
    public String getCodigotransaccion() {
        return this.codigotransaccion;
    }
    
    public void setCodigotransaccion(String codigotransaccion) {
        this.codigotransaccion = codigotransaccion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstadodecuenta() {
        return this.estadodecuenta;
    }
    
    public void setEstadodecuenta(String estadodecuenta) {
        this.estadodecuenta = estadodecuenta;
    }
    public long getCantidadcomparaciones() {
        return this.cantidadcomparaciones;
    }
    
    public void setCantidadcomparaciones(long cantidadcomparaciones) {
        this.cantidadcomparaciones = cantidadcomparaciones;
    }
    public Date getFechaconfirmacion() {
        return this.fechaconfirmacion;
    }
    
    public void setFechaconfirmacion(Date fechaconfirmacion) {
        this.fechaconfirmacion = fechaconfirmacion;
    }
    public int getTipoconfirmacion() {
        return this.tipoconfirmacion;
    }
    
    public void setTipoconfirmacion(int tipoconfirmacion) {
        this.tipoconfirmacion = tipoconfirmacion;
    }
    public int getUsuarioconfirmacion() {
        return this.usuarioconfirmacion;
    }
    
    public void setUsuarioconfirmacion(int usuarioconfirmacion) {
        this.usuarioconfirmacion = usuarioconfirmacion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public BigDecimal getMontodeajuste() {
        return this.montodeajuste;
    }
    
    public void setMontodeajuste(BigDecimal montodeajuste) {
        this.montodeajuste = montodeajuste;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }




}


