package com.casapellas.conciliacion.entidades;
// Generated Feb 11, 2015 6:30:41 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * PcdExcepcionDeposito generated by hbm2java
 */
public class PcdExcepcionDeposito  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5151490148480875203L;
	private int idexcepciondeposito;
     private int iddeposito;
     private int numeroreferencia;
     private boolean tipodeposito;
     private long numerocuenta;
     private long codigobanco;
     private BigDecimal monto;
     private String moneda;
     private Date fechadeposito;
     private String tiposolicitud;
     private String descripcion;
     private int excepcionvalida;
     private int usuariovalida;
     private int numerocomparaciones;
     private Date fechaultimacomparacion;
     private Date fechacrea;
     private int usuariocrea;

    public PcdExcepcionDeposito() {
    }

    public PcdExcepcionDeposito(int idexcepciondeposito, int iddeposito, int numeroreferencia, boolean tipodeposito, long numerocuenta, long codigobanco, BigDecimal monto, String moneda, Date fechadeposito, String tiposolicitud, String descripcion, int excepcionvalida, int usuariovalida, int numerocomparaciones, Date fechaultimacomparacion, Date fechacrea, int usuariocrea) {
       this.idexcepciondeposito = idexcepciondeposito;
       this.iddeposito = iddeposito;
       this.numeroreferencia = numeroreferencia;
       this.tipodeposito = tipodeposito;
       this.numerocuenta = numerocuenta;
       this.codigobanco = codigobanco;
       this.monto = monto;
       this.moneda = moneda;
       this.fechadeposito = fechadeposito;
       this.tiposolicitud = tiposolicitud;
       this.descripcion = descripcion;
       this.excepcionvalida = excepcionvalida;
       this.usuariovalida = usuariovalida;
       this.numerocomparaciones = numerocomparaciones;
       this.fechaultimacomparacion = fechaultimacomparacion;
       this.fechacrea = fechacrea;
       this.usuariocrea = usuariocrea;
    }
   
    public int getIdexcepciondeposito() {
        return this.idexcepciondeposito;
    }
    
    public void setIdexcepciondeposito(int idexcepciondeposito) {
        this.idexcepciondeposito = idexcepciondeposito;
    }
    public int getIddeposito() {
        return this.iddeposito;
    }
    
    public void setIddeposito(int iddeposito) {
        this.iddeposito = iddeposito;
    }
    public int getNumeroreferencia() {
        return this.numeroreferencia;
    }
    
    public void setNumeroreferencia(int numeroreferencia) {
        this.numeroreferencia = numeroreferencia;
    }
    public boolean isTipodeposito() {
        return this.tipodeposito;
    }
    
    public void setTipodeposito(boolean tipodeposito) {
        this.tipodeposito = tipodeposito;
    }
    public long getNumerocuenta() {
        return this.numerocuenta;
    }
    
    public void setNumerocuenta(long numerocuenta) {
        this.numerocuenta = numerocuenta;
    }
    public long getCodigobanco() {
        return this.codigobanco;
    }
    
    public void setCodigobanco(long codigobanco) {
        this.codigobanco = codigobanco;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public Date getFechadeposito() {
        return this.fechadeposito;
    }
    
    public void setFechadeposito(Date fechadeposito) {
        this.fechadeposito = fechadeposito;
    }
    public String getTiposolicitud() {
        return this.tiposolicitud;
    }
    
    public void setTiposolicitud(String tiposolicitud) {
        this.tiposolicitud = tiposolicitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getExcepcionvalida() {
        return this.excepcionvalida;
    }
    
    public void setExcepcionvalida(int excepcionvalida) {
        this.excepcionvalida = excepcionvalida;
    }
    public int getUsuariovalida() {
        return this.usuariovalida;
    }
    
    public void setUsuariovalida(int usuariovalida) {
        this.usuariovalida = usuariovalida;
    }
    public int getNumerocomparaciones() {
        return this.numerocomparaciones;
    }
    
    public void setNumerocomparaciones(int numerocomparaciones) {
        this.numerocomparaciones = numerocomparaciones;
    }
    public Date getFechaultimacomparacion() {
        return this.fechaultimacomparacion;
    }
    
    public void setFechaultimacomparacion(Date fechaultimacomparacion) {
        this.fechaultimacomparacion = fechaultimacomparacion;
    }
    public Date getFechacrea() {
        return this.fechacrea;
    }
    
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }
    public int getUsuariocrea() {
        return this.usuariocrea;
    }
    
    public void setUsuariocrea(int usuariocrea) {
        this.usuariocrea = usuariocrea;
    }




}


