package com.casapellas.conciliacion.entidades;

// Generated May 13, 2016 8:48:29 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Vf0911Id generated by hbm2java
 */
public class Vf0911Id implements java.io.Serializable {

 
	private static final long serialVersionUID = -8018812538340634529L;
	private String glaid;
	private long glaa;
	private BigDecimal monto;
	private String glcrcd;
	private String glani;
	private String glmcu;
	private String globj;
	private String glsub;
	private String glsbl;
	private int glicu;
	private int gldoc;
	private String glkco;
	private int gldgj;
	private int glupmj;
	private BigDecimal glcrr;
	private String glxa;
	private String glexr;
	private String gltorg;
	private String gldct;
	private String glpost;
	private String tipoCargo;
	private String estado;
	private Date fechabatch;
	private Date fechamodbatch;
	private String nombrecuenta;
	private String programaorigen;

	public Vf0911Id() {
	}

	public Vf0911Id(String glaid, long glaa, BigDecimal monto, String glcrcd,
			String glani, String glmcu, String globj, String glsub,
			String glsbl, int glicu, int gldoc, String glkco, int gldgj,
			int glupmj, BigDecimal glcrr, String glxa, String glexr,
			String gltorg, String gldct, String glpost, String tipoCargo,
			Date fechabatch, Date fechamodbatch) {
		this.glaid = glaid;
		this.glaa = glaa;
		this.monto = monto;
		this.glcrcd = glcrcd;
		this.glani = glani;
		this.glmcu = glmcu;
		this.globj = globj;
		this.glsub = glsub;
		this.glsbl = glsbl;
		this.glicu = glicu;
		this.gldoc = gldoc;
		this.glkco = glkco;
		this.gldgj = gldgj;
		this.glupmj = glupmj;
		this.glcrr = glcrr;
		this.glxa = glxa;
		this.glexr = glexr;
		this.gltorg = gltorg;
		this.gldct = gldct;
		this.glpost = glpost;
		this.tipoCargo = tipoCargo;
		this.fechabatch = fechabatch;
		this.fechamodbatch = fechamodbatch;
	}

	public Vf0911Id(String glaid, long glaa, BigDecimal monto, String glcrcd,
			String glani, String glmcu, String globj, String glsub,
			String glsbl, int glicu, int gldoc, String glkco, int gldgj,
			int glupmj, BigDecimal glcrr, String glxa, String glexr,
			String gltorg, String gldct, String glpost, String tipoCargo,
			String estado, Date fechabatch, Date fechamodbatch,
			String nombrecuenta, String programaorigen) {
		this.glaid = glaid;
		this.glaa = glaa;
		this.monto = monto;
		this.glcrcd = glcrcd;
		this.glani = glani;
		this.glmcu = glmcu;
		this.globj = globj;
		this.glsub = glsub;
		this.glsbl = glsbl;
		this.glicu = glicu;
		this.gldoc = gldoc;
		this.glkco = glkco;
		this.gldgj = gldgj;
		this.glupmj = glupmj;
		this.glcrr = glcrr;
		this.glxa = glxa;
		this.glexr = glexr;
		this.gltorg = gltorg;
		this.gldct = gldct;
		this.glpost = glpost;
		this.tipoCargo = tipoCargo;
		this.estado = estado;
		this.fechabatch = fechabatch;
		this.fechamodbatch = fechamodbatch;
		this.nombrecuenta = nombrecuenta;
		this.programaorigen = programaorigen;
	}

	public String getGlaid() {
		return this.glaid;
	}

	public void setGlaid(String glaid) {
		this.glaid = glaid;
	}

	public long getGlaa() {
		return this.glaa;
	}

	public void setGlaa(long glaa) {
		this.glaa = glaa;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public String getGlcrcd() {
		return this.glcrcd;
	}

	public void setGlcrcd(String glcrcd) {
		this.glcrcd = glcrcd;
	}

	public String getGlani() {
		return this.glani;
	}

	public void setGlani(String glani) {
		this.glani = glani;
	}

	public String getGlmcu() {
		return this.glmcu;
	}

	public void setGlmcu(String glmcu) {
		this.glmcu = glmcu;
	}

	public String getGlobj() {
		return this.globj;
	}

	public void setGlobj(String globj) {
		this.globj = globj;
	}

	public String getGlsub() {
		return this.glsub;
	}

	public void setGlsub(String glsub) {
		this.glsub = glsub;
	}

	public String getGlsbl() {
		return this.glsbl;
	}

	public void setGlsbl(String glsbl) {
		this.glsbl = glsbl;
	}

	public int getGlicu() {
		return this.glicu;
	}

	public void setGlicu(int glicu) {
		this.glicu = glicu;
	}

	public int getGldoc() {
		return this.gldoc;
	}

	public void setGldoc(int gldoc) {
		this.gldoc = gldoc;
	}

	public String getGlkco() {
		return this.glkco;
	}

	public void setGlkco(String glkco) {
		this.glkco = glkco;
	}

	public int getGldgj() {
		return this.gldgj;
	}

	public void setGldgj(int gldgj) {
		this.gldgj = gldgj;
	}

	public int getGlupmj() {
		return this.glupmj;
	}

	public void setGlupmj(int glupmj) {
		this.glupmj = glupmj;
	}

	public BigDecimal getGlcrr() {
		return this.glcrr;
	}

	public void setGlcrr(BigDecimal glcrr) {
		this.glcrr = glcrr;
	}

	public String getGlxa() {
		return this.glxa;
	}

	public void setGlxa(String glxa) {
		this.glxa = glxa;
	}

	public String getGlexr() {
		return this.glexr;
	}

	public void setGlexr(String glexr) {
		this.glexr = glexr;
	}

	public String getGltorg() {
		return this.gltorg;
	}

	public void setGltorg(String gltorg) {
		this.gltorg = gltorg;
	}

	public String getGldct() {
		return this.gldct;
	}

	public void setGldct(String gldct) {
		this.gldct = gldct;
	}

	public String getGlpost() {
		return this.glpost;
	}

	public void setGlpost(String glpost) {
		this.glpost = glpost;
	}

	public String getTipoCargo() {
		return this.tipoCargo;
	}

	public void setTipoCargo(String tipoCargo) {
		this.tipoCargo = tipoCargo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechabatch() {
		return this.fechabatch;
	}

	public void setFechabatch(Date fechabatch) {
		this.fechabatch = fechabatch;
	}

	public Date getFechamodbatch() {
		return this.fechamodbatch;
	}

	public void setFechamodbatch(Date fechamodbatch) {
		this.fechamodbatch = fechamodbatch;
	}

	public String getNombrecuenta() {
		return this.nombrecuenta;
	}

	public void setNombrecuenta(String nombrecuenta) {
		this.nombrecuenta = nombrecuenta;
	}

	public String getProgramaorigen() {
		return this.programaorigen;
	}

	public void setProgramaorigen(String programaorigen) {
		this.programaorigen = programaorigen;
	}

	
	public String dataToExcel(String splitBy){
		return
		new SimpleDateFormat("yyyy-MM-dd").format( fechabatch ) + splitBy +
		new SimpleDateFormat("yyyy-MM-dd").format( fechamodbatch ) + splitBy +
		gltorg  + splitBy +
		glani   + splitBy +
		glsbl   + splitBy +
		glcrcd  + splitBy +
		glicu   + splitBy +
		gldoc   + splitBy +
		gldct   + splitBy +
		monto.toString()   + splitBy +
		glxa    + splitBy +
		glexr   + splitBy +
		estado  + splitBy +
		glcrr   + splitBy ;
	}
	
	
	@Override
	public String toString() {
		return "Vf0911Id [glaid=" + glaid + ", glaa=" + glaa + ", monto="
				+ monto + ", glcrcd=" + glcrcd + ", glani=" + glani
				+ ", glmcu=" + glmcu + ", globj=" + globj + ", glsub=" + glsub
				+ ", glsbl=" + glsbl + ", glicu=" + glicu + ", gldoc=" + gldoc
				+ ", glkco=" + glkco + ", gldgj=" + gldgj + ", glupmj="
				+ glupmj + ", glcrr=" + glcrr + ", glxa=" + glxa + ", glexr="
				+ glexr + ", gltorg=" + gltorg + ", gldct=" + gldct
				+ ", glpost=" + glpost + ", tipoCargo=" + tipoCargo
				+ ", estado=" + estado + ", fechabatch=" + fechabatch
				+ ", fechamodbatch=" + fechamodbatch + ", nombrecuenta="
				+ nombrecuenta + ", programaorigen=" + programaorigen + "]";
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Vf0911Id))
			return false;
		Vf0911Id castOther = (Vf0911Id) other;

		return ((this.getGlaid() == castOther.getGlaid()) || (this.getGlaid() != null
				&& castOther.getGlaid() != null && this.getGlaid().equals(
				castOther.getGlaid())))
				&& (this.getGlaa() == castOther.getGlaa())
				&& ((this.getMonto() == castOther.getMonto()) || (this
						.getMonto() != null && castOther.getMonto() != null && this
						.getMonto().equals(castOther.getMonto())))
				&& ((this.getGlcrcd() == castOther.getGlcrcd()) || (this
						.getGlcrcd() != null && castOther.getGlcrcd() != null && this
						.getGlcrcd().equals(castOther.getGlcrcd())))
				&& ((this.getGlani() == castOther.getGlani()) || (this
						.getGlani() != null && castOther.getGlani() != null && this
						.getGlani().equals(castOther.getGlani())))
				&& ((this.getGlmcu() == castOther.getGlmcu()) || (this
						.getGlmcu() != null && castOther.getGlmcu() != null && this
						.getGlmcu().equals(castOther.getGlmcu())))
				&& ((this.getGlobj() == castOther.getGlobj()) || (this
						.getGlobj() != null && castOther.getGlobj() != null && this
						.getGlobj().equals(castOther.getGlobj())))
				&& ((this.getGlsub() == castOther.getGlsub()) || (this
						.getGlsub() != null && castOther.getGlsub() != null && this
						.getGlsub().equals(castOther.getGlsub())))
				&& ((this.getGlsbl() == castOther.getGlsbl()) || (this
						.getGlsbl() != null && castOther.getGlsbl() != null && this
						.getGlsbl().equals(castOther.getGlsbl())))
				&& (this.getGlicu() == castOther.getGlicu())
				&& (this.getGldoc() == castOther.getGldoc())
				&& ((this.getGlkco() == castOther.getGlkco()) || (this
						.getGlkco() != null && castOther.getGlkco() != null && this
						.getGlkco().equals(castOther.getGlkco())))
				&& (this.getGldgj() == castOther.getGldgj())
				&& (this.getGlupmj() == castOther.getGlupmj())
				&& ((this.getGlcrr() == castOther.getGlcrr()) || (this
						.getGlcrr() != null && castOther.getGlcrr() != null && this
						.getGlcrr().equals(castOther.getGlcrr())))
				&& ((this.getGlxa() == castOther.getGlxa()) || (this.getGlxa() != null
						&& castOther.getGlxa() != null && this.getGlxa()
						.equals(castOther.getGlxa())))
				&& ((this.getGlexr() == castOther.getGlexr()) || (this
						.getGlexr() != null && castOther.getGlexr() != null && this
						.getGlexr().equals(castOther.getGlexr())))
				&& ((this.getGltorg() == castOther.getGltorg()) || (this
						.getGltorg() != null && castOther.getGltorg() != null && this
						.getGltorg().equals(castOther.getGltorg())))
				&& ((this.getGldct() == castOther.getGldct()) || (this
						.getGldct() != null && castOther.getGldct() != null && this
						.getGldct().equals(castOther.getGldct())))
				&& ((this.getGlpost() == castOther.getGlpost()) || (this
						.getGlpost() != null && castOther.getGlpost() != null && this
						.getGlpost().equals(castOther.getGlpost())))
				&& ((this.getTipoCargo() == castOther.getTipoCargo()) || (this
						.getTipoCargo() != null
						&& castOther.getTipoCargo() != null && this
						.getTipoCargo().equals(castOther.getTipoCargo())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getFechabatch() == castOther.getFechabatch()) || (this
						.getFechabatch() != null
						&& castOther.getFechabatch() != null && this
						.getFechabatch().equals(castOther.getFechabatch())))
				&& ((this.getFechamodbatch() == castOther.getFechamodbatch()) || (this
						.getFechamodbatch() != null
						&& castOther.getFechamodbatch() != null && this
						.getFechamodbatch()
						.equals(castOther.getFechamodbatch())))
				&& ((this.getNombrecuenta() == castOther.getNombrecuenta()) || (this
						.getNombrecuenta() != null
						&& castOther.getNombrecuenta() != null && this
						.getNombrecuenta().equals(castOther.getNombrecuenta())))
				&& ((this.getProgramaorigen() == castOther.getProgramaorigen()) || (this
						.getProgramaorigen() != null
						&& castOther.getProgramaorigen() != null && this
						.getProgramaorigen().equals(
								castOther.getProgramaorigen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGlaid() == null ? 0 : this.getGlaid().hashCode());
		result = 37 * result + (int) this.getGlaa();
		result = 37 * result
				+ (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37 * result
				+ (getGlcrcd() == null ? 0 : this.getGlcrcd().hashCode());
		result = 37 * result
				+ (getGlani() == null ? 0 : this.getGlani().hashCode());
		result = 37 * result
				+ (getGlmcu() == null ? 0 : this.getGlmcu().hashCode());
		result = 37 * result
				+ (getGlobj() == null ? 0 : this.getGlobj().hashCode());
		result = 37 * result
				+ (getGlsub() == null ? 0 : this.getGlsub().hashCode());
		result = 37 * result
				+ (getGlsbl() == null ? 0 : this.getGlsbl().hashCode());
		result = 37 * result + this.getGlicu();
		result = 37 * result + this.getGldoc();
		result = 37 * result
				+ (getGlkco() == null ? 0 : this.getGlkco().hashCode());
		result = 37 * result + this.getGldgj();
		result = 37 * result + this.getGlupmj();
		result = 37 * result
				+ (getGlcrr() == null ? 0 : this.getGlcrr().hashCode());
		result = 37 * result
				+ (getGlxa() == null ? 0 : this.getGlxa().hashCode());
		result = 37 * result
				+ (getGlexr() == null ? 0 : this.getGlexr().hashCode());
		result = 37 * result
				+ (getGltorg() == null ? 0 : this.getGltorg().hashCode());
		result = 37 * result
				+ (getGldct() == null ? 0 : this.getGldct().hashCode());
		result = 37 * result
				+ (getGlpost() == null ? 0 : this.getGlpost().hashCode());
		result = 37 * result
				+ (getTipoCargo() == null ? 0 : this.getTipoCargo().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37
				* result
				+ (getFechabatch() == null ? 0 : this.getFechabatch()
						.hashCode());
		result = 37
				* result
				+ (getFechamodbatch() == null ? 0 : this.getFechamodbatch()
						.hashCode());
		result = 37
				* result
				+ (getNombrecuenta() == null ? 0 : this.getNombrecuenta()
						.hashCode());
		result = 37
				* result
				+ (getProgramaorigen() == null ? 0 : this.getProgramaorigen()
						.hashCode());
		return result;
	}

}
