package com.casapellas.entidades.pmt;

// Generated Sep 29, 2016 7:43:35 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.casapellas.util.PropertiesSystem;

/**
 * PmtDtCobroAutomatico generated by hbm2java
 */
public class PmtDtCobroAutomatico implements java.io.Serializable {

	private static final long serialVersionUID = 3508334086512841689L;
	private int iddtcobroauto;
	private int idmtcobroauto;
	private int codigocliente;
	private int numerocontrato;
	private int numerocuota;
	private BigDecimal monto;
	private String moneda;
	private boolean estado;
	private Date fechageneracion;
	private int numerorecibo;
	private int numerotarjeta;
	private String codigoterminal;
	private long numerovoucher;
	private String observaciones;
	private Date createtime;
	private boolean notificacioncliente;
	private long rowcountBitacora;
	
	private String codigorespuestasp;
	private String descripcionrespuestasp;
	private String monedaCuota;
	private BigDecimal montoCuota;
		
	public PmtDtCobroAutomatico(int codigocliente, int numerocontrato,
			int numerocuota, BigDecimal monto, String moneda, 
			Date fechageneracion, int numerorecibo, int numerotarjeta,
			String codigoterminal, long numerovoucher, boolean estado, long rowcountBitacora) {
		super();
		this.codigocliente = codigocliente;
		this.numerocontrato = numerocontrato;
		this.numerocuota = numerocuota;
		this.monto = monto;
		this.moneda = moneda;
		this.fechageneracion = fechageneracion;
		this.numerorecibo = numerorecibo;
		this.numerotarjeta = numerotarjeta;
		this.codigoterminal = codigoterminal;
		this.numerovoucher = numerovoucher;
		this.estado = estado;
		this.rowcountBitacora = rowcountBitacora;
	}

	
	public  String insertStatement(){
		try {
			
			String sql = 
				" insert into @BDCAJA.PMT_DT_COBRO_AUTOMATICO " +
					"(idmtcobroauto, codigocliente, numerocontrato, numerocuota, " +
					" monto, moneda, estado, fechageneracion, numerorecibo, " +
					" numerotarjeta, codigoterminal, numerovoucher, observaciones," +
					" notificacioncliente, codigorespuestasp, descripcionrespuestasp, monedaCuota, montoCuota )" +
				" values " +
					"(@IDMTCOBROAUTO, @CODIGOCLIENTE, @NUMEROCONTRATO, @NUMEROCUOTA, " +
					" @MONTO@, '@MONEDA@', @ESTADO, '@FECHAGENERACION', @NUMERORECIBO, " +
					" @NUMEROTARJETA, '@CODIGOTERMINAL', @NUMEROVOUCHER, '@OBSERVACIONES'," +
					" @NOTIFICACIONCLIENTE, '@CODIGORESPUESTASP@', '@DESCRIPRESPUESTASP@', '@MONEDACUOTA@', '@MONTOCUOTA@'  )"  ;

			return sql
			.replace("@BDCAJA", PropertiesSystem.ESQUEMA)
			.replace("@IDMTCOBROAUTO", String.valueOf( idmtcobroauto ) ) 
			.replace("@CODIGOCLIENTE", String.valueOf( codigocliente ) ) 
			.replace("@NUMEROCONTRATO", String.valueOf( numerocontrato ) ) 
			.replace("@NUMEROCUOTA",  String.valueOf( numerocuota ) )
			.replace("@MONTO@", monto.toString() ) 
			.replace("@MONEDA@", moneda) 
			.replace("@ESTADO", ( (estado)? "1": "0") ) 
			.replace("@FECHAGENERACION", new SimpleDateFormat("yyyy-MM-dd").format(  ( (fechageneracion==null)? new Date() : fechageneracion ) ) ) 
			.replace("@NUMERORECIBO", String.valueOf( numerorecibo ) )
			.replace("@NUMEROTARJETA", String.valueOf( numerotarjeta )) 
			.replace("@CODIGOTERMINAL", ( (codigoterminal == null)? "" : codigoterminal )) 
			.replace("@NUMEROVOUCHER",  String.valueOf( numerovoucher )) 
			.replace("@OBSERVACIONES", ( (observaciones==null)? "" : observaciones ) )
			.replace("@NOTIFICACIONCLIENTE", ( notificacioncliente? "1" : "0" ) ) 
			
			.replace("@CODIGORESPUESTASP@", getCodigorespuestasp() ) 
			.replace("@DESCRIPRESPUESTASP@", getDescripcionrespuestasp()) 
			.replace("@MONEDACUOTA@", getMonedaCuota()) 
			.replace("@MONTOCUOTA@", getMontoCuota().toString() )  ;
 
			
			
			
		} catch (Exception e) {
			 e.printStackTrace();
//			 LogCrtl.imprimirError(e);
		}
		return "";
	}
	
	public PmtDtCobroAutomatico() {
	}

 
	public PmtDtCobroAutomatico(int iddtcobroauto, int idmtcobroauto,
			int codigocliente, int numerocontrato, int numerocuota,
			BigDecimal monto, String moneda, boolean estado,
			Date fechageneracion, int numerorecibo, int numerotarjeta,
			String codigoterminal, long numerovoucher, String observaciones,
			Date createtime) {
		super();
		this.iddtcobroauto = iddtcobroauto;
		this.idmtcobroauto = idmtcobroauto;
		this.codigocliente = codigocliente;
		this.numerocontrato = numerocontrato;
		this.numerocuota = numerocuota;
		this.monto = monto;
		this.moneda = moneda;
		this.estado = estado;
		this.fechageneracion = fechageneracion;
		this.numerorecibo = numerorecibo;
		this.numerotarjeta = numerotarjeta;
		this.codigoterminal = codigoterminal;
		this.numerovoucher = numerovoucher;
		this.observaciones = observaciones;
		this.createtime = createtime;
	}

	public int getIddtcobroauto() {
		return this.iddtcobroauto;
	}

	public void setIddtcobroauto(int iddtcobroauto) {
		this.iddtcobroauto = iddtcobroauto;
	}

	public int getIdmtcobroauto() {
		return this.idmtcobroauto;
	}

	public void setIdmtcobroauto(int idmtcobroauto) {
		this.idmtcobroauto = idmtcobroauto;
	}

	public int getCodigocliente() {
		return this.codigocliente;
	}

	public void setCodigocliente(int codigocliente) {
		this.codigocliente = codigocliente;
	}

	public int getNumerocontrato() {
		return this.numerocontrato;
	}

	public void setNumerocontrato(int numerocontrato) {
		this.numerocontrato = numerocontrato;
	}

	public int getNumerocuota() {
		return this.numerocuota;
	}

	public void setNumerocuota(int numerocuota) {
		this.numerocuota = numerocuota;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Date getFechageneracion() {
		return this.fechageneracion;
	}

	public void setFechageneracion(Date fechageneracion) {
		this.fechageneracion = fechageneracion;
	}

	public int getNumerorecibo() {
		return this.numerorecibo;
	}

	public void setNumerorecibo(int numerorecibo) {
		this.numerorecibo = numerorecibo;
	}

	public int getNumerotarjeta() {
		return this.numerotarjeta;
	}

	public void setNumerotarjeta(int numerotarjeta) {
		this.numerotarjeta = numerotarjeta;
	}

	public String getCodigoterminal() {
		return this.codigoterminal;
	}

	public void setCodigoterminal(String codigoterminal) {
		this.codigoterminal = codigoterminal;
	}

	public long getNumerovoucher() {
		return this.numerovoucher;
	}

	public void setNumerovoucher(long numerovoucher) {
		this.numerovoucher = numerovoucher;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getObservaciones() {
		if (observaciones == null )  observaciones = "" ;
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}
 
	public boolean isNotificacioncliente() {
		return notificacioncliente;
	}

	public void setNotificacioncliente(boolean notificacioncliente) {
		this.notificacioncliente = notificacioncliente;
	}

	@Override
	public String toString() {
		return "PmtDtCobroAutomatico [codigocliente=" + codigocliente
				+ ", numerocontrato=" + numerocontrato + ", numerocuota="
				+ numerocuota + ", monto=" + monto + ", moneda=" + moneda
				+ ", estado=" + estado + ", fechageneracion=" + fechageneracion
				+ ", numerorecibo=" + numerorecibo + ", numerotarjeta="
				+ numerotarjeta + ", codigoterminal=" + codigoterminal
				+ ", numerovoucher=" + numerovoucher + ", observaciones="
				+ observaciones + "]";
	}

	public long getRowcountBitacora() {
		return rowcountBitacora;
	}
	public void setRowcountBitacora(long rowcountBitacora) {
		this.rowcountBitacora = rowcountBitacora;
	}

	
	public String getCodigorespuestasp() {
		if(codigorespuestasp == null)
			codigorespuestasp = "";
		
		return codigorespuestasp;
	}
	public void setCodigorespuestasp(String p_codigorespuestasp) {
		codigorespuestasp = p_codigorespuestasp;
	}
	public String getDescripcionrespuestasp() {
		if(descripcionrespuestasp == null)
			descripcionrespuestasp = "";
		return descripcionrespuestasp;
	}
	public void setDescripcionrespuestasp(String p_descripcionrespuestasp) {
		descripcionrespuestasp = p_descripcionrespuestasp;
	}
	public String getMonedaCuota() {
		if(monedaCuota == null)
			monedaCuota = "";
		return monedaCuota;
	}
	public void setMonedaCuota(String p_monedaCuota) {
		monedaCuota = p_monedaCuota;
	}
	public BigDecimal getMontoCuota() {
		if (montoCuota == null)
			montoCuota = BigDecimal.ZERO;
		return montoCuota;
	}
	public void setMontoCuota(BigDecimal p_montoCuota) {
		montoCuota = p_montoCuota;
	}
 
}
