package com.casapellas.entidades.pmt;

// Generated Sep 29, 2016 7:43:35 PM by Hibernate Tools 4.3.1

import java.text.SimpleDateFormat;
import java.util.Date;

import com.casapellas.util.PropertiesSystem;

/**
 * PmtMtCobroAutomatico generated by hbm2java
 */
public class PmtMtCobroAutomatico implements java.io.Serializable {

	private static final long serialVersionUID = 7794315878594362666L;
	private int idcobroauto;
	private int codigousuario;
	private int caid;
	private int cuotas;
	private int procesados;
	private Date fecha;
	private Date horainicio;
	private Date horafinaliza;
	private String datapcinfo;

	public PmtMtCobroAutomatico() {
	}

	public String selectStatement(){
		
		String sql = " select idcobroauto, codigousuario, caid, cuotas, procesados, fecha, horainicio, horafinaliza, datapcinfo  " +
				" from @BDCAJA.PMT_MT_COBRO_AUTOMATICO " +
				" where  fecha = '@FECHA' and horainicio = '@HORAINICIO' and horafinaliza = '@HORAFINALIZA' " ;
		
		return sql
		.replace("@BDCAJA", PropertiesSystem.ESQUEMA)
		.replace("@FECHA",  new SimpleDateFormat("yyyy-MM-dd").format( fecha )  ) 
		.replace("@HORAINICIO", new SimpleDateFormat("HH:mm:ss").format( horainicio ) ) 
		.replace("@HORAFINALIZA", new SimpleDateFormat("HH:mm:ss").format( horafinaliza ) ) ;
		 
	}
	
	
	public String insertStatement(){
	try {
			
			String sql = 
				" insert into @BDCAJA.PMT_MT_COBRO_AUTOMATICO " +
					"(codigousuario, caid, cuotas, procesados, " +
					" fecha, horainicio, horafinaliza, datapcinfo)" +
				" values " +
				"(@CODIGOUSUARIO, @CAID, @CUOTAS, @PROCESADOS, " +
				" '@FECHA', '@HORAINICIO', '@HORAFINALIZA', '@DATAPCINFO')"  ;

			return sql
			.replace("@BDCAJA", PropertiesSystem.ESQUEMA)
			.replace("@CODIGOUSUARIO", String.valueOf( codigousuario ) ) 
			.replace("@CAID", String.valueOf( caid ) ) 
			.replace("@CUOTAS", String.valueOf( cuotas ) ) 
			.replace("@PROCESADOS",  String.valueOf( procesados ) )
			.replace("@FECHA",  new SimpleDateFormat("yyyy-MM-dd").format( fecha )  ) 
			.replace("@HORAINICIO", new SimpleDateFormat("HH:mm:ss").format( horainicio ) ) 
			.replace("@HORAFINALIZA", new SimpleDateFormat("HH:mm:ss").format( horafinaliza ) ) 
			.replace("@DATAPCINFO",  datapcinfo )  ;
			
			
		} catch (Exception e) {
			 e.printStackTrace();
//			 LogCrtl.imprimirError(e);
		}
		return "";
	}
	
	
	public PmtMtCobroAutomatico(int codigousuario, int caid, int cuotas,
			int procesados, Date fecha, Date horainicio, Date horafinaliza,
			String datapcinfo) {
		super();
		this.codigousuario = codigousuario;
		this.caid = caid;
		this.cuotas = cuotas;
		this.procesados = procesados;
		this.fecha = fecha;
		this.horainicio = horainicio;
		this.horafinaliza = horafinaliza;
		this.datapcinfo = datapcinfo;
	}

	public PmtMtCobroAutomatico(int idcobroauto, int codigousuario, int caid,
			int cuotas, int procesados, Date fecha, Date horainicio,
			Date horafinaliza, String datapcinfo) {
		this.idcobroauto = idcobroauto;
		this.codigousuario = codigousuario;
		this.caid = caid;
		this.cuotas = cuotas;
		this.procesados = procesados;
		this.fecha = fecha;
		this.horainicio = horainicio;
		this.horafinaliza = horafinaliza;
		this.datapcinfo = datapcinfo;
	}

	public int getIdcobroauto() {
		return this.idcobroauto;
	}

	public void setIdcobroauto(int idcobroauto) {
		this.idcobroauto = idcobroauto;
	}

	public int getCodigousuario() {
		return this.codigousuario;
	}

	public void setCodigousuario(int codigousuario) {
		this.codigousuario = codigousuario;
	}

	public int getCaid() {
		return this.caid;
	}

	public void setCaid(int caid) {
		this.caid = caid;
	}

	public int getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(int cuotas) {
		this.cuotas = cuotas;
	}

	public int getProcesados() {
		return this.procesados;
	}

	public void setProcesados(int procesados) {
		this.procesados = procesados;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHorainicio() {
		return this.horainicio;
	}

	public void setHorainicio(Date horainicio) {
		this.horainicio = horainicio;
	}

	public Date getHorafinaliza() {
		return this.horafinaliza;
	}

	public void setHorafinaliza(Date horafinaliza) {
		this.horafinaliza = horafinaliza;
	}

	public String getDatapcinfo() {
		return this.datapcinfo;
	}

	public void setDatapcinfo(String datapcinfo) {
		this.datapcinfo = datapcinfo;
	}

}
