package com.casapellas.entidades.pmt;
 
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.casapellas.controles.MetodosPagoCtrl;
import com.casapellas.entidades.MetodosPago;
import com.casapellas.util.CodeUtil;

/**
 * Vwbitacoracobrospmt generated by hbm2java
 */
public class Vwbitacoracobrospmt  implements java.io.Serializable {

	private static final long serialVersionUID = 1979350240415715441L;

	private long rowcount;
    private String mpbcia;
    private String mpbsuc;
    private Integer mpbnctto;
    private Date mpbfcgnr;
    private Integer mpbcli;
    private String mpbchas;
    private String mpbttrj;
    private String mpbdttrj;
    private String mpbetrj;
    private String mpbdetrj;
    private BigDecimal mpbntrj;
    private String mpbnttrj;
    private Integer mpbvtrj;
    private BigDecimal mpbvpag;
    private Integer mpbnpag;
    private Date mpbfpag;
    private String mpbmon;
    private BigDecimal mpbtcam;
    private String mpbobs;
    private Integer mpbnint;
    private Integer mpbintr;
    private String mpbsts1;
    private String mpbsts2;
    private String mpbcodcomp;
    private String mpbcodsuc;
    private String mpbunineg;
    private Integer mpbnumrec;
    private String mpbtiporec;
    private Date mpbfecha;
    private Integer mpbcaid;
    private String mpbhereg;
    private Date mpbfereg;
    private Date mpbhrreg;
    private String mpbpareg;
    private String mpbprreg;
    private String mpbhecam;
    private Date mpbfecam;
    private Date mpbhrcam;
    private String mpbpacam;
    private String mpbprcam;
    private String clientenombre;
    private String correo;
    private String codcomp;
    private String nomcomp;
    private String codsuc;
    private String nomsuc;
    private String codunineg;
    private String nomunineg;
    private BigDecimal montocobrarentarjeta;
    private String correocliente;
    
    private String authorizationNumber;
    private String referenceNumber;
    private String responseCode;
    private String responseCodeDescription;
    private String salesAmount;
    private String transactionId;
    private String systemTraceNumber;
	private String codigoafiliado;
	private String codigoterminal;
	private String nombreterminal;
	private String fechatransaccion;
    
	private String numerotarjetadsp;
    private String estadoProceso;
    private String excluirDebito;
    private boolean excluyeDebito;
    private boolean registroprocesado;
    private boolean errorpagotarjeta;
    
    private String observaciones;
    private int numerobatchpago;
    
    private int numerotarjeta4d;
    private String nombrecaja;
    private String nombrecajero;
    private boolean notificado;
    
    private String invoicenumber;
    
    private Integer codigovendedor;
    private String nombrevendedor;
    
    private Integer mpbvtrjcobro;
    
	 public  String dataToExcel(String concatwith){
	    	
	    	return 
	    	String.valueOf( mpbcaid ) + concatwith  +
	    	getNombrecaja() + concatwith  +
	    	nomcomp + concatwith  +
	    	String.valueOf( mpbnumrec )  + concatwith  + 
			String.valueOf(mpbcli ) + concatwith  +
	    	CodeUtil.capitalize( clientenombre )  + concatwith  + 
	    	String.valueOf( mpbnctto ) + concatwith  +
			CodeUtil.pad( String.valueOf( mpbnpag ), 3, "0" ) + concatwith  +
	    	new SimpleDateFormat("yyyy-MM-dd").format(mpbfcgnr)  + concatwith + 
	    	montocobrarentarjeta.toString() + concatwith  +
	    	mpbmon + concatwith  +
	    	getNumerotarjeta4d() + concatwith  +
	    	
	    	mpbvtrj + concatwith  +
	    	getMpbdttrj() + concatwith  +
	    	getMpbdetrj() + concatwith  +
	    	
	    	getEstadoProceso() + concatwith  +
	    	getObservaciones() + concatwith  +
	    	getNombrecajero() + concatwith  +
	    	new SimpleDateFormat("yyyy-MM-dd").format(mpbfecam)  + concatwith + 
	    	new SimpleDateFormat("HH:mm:ss").format(mpbhrcam)  + concatwith +
	    	String.valueOf( numerobatchpago ) + concatwith +
	    	getCorreocliente()  + concatwith +
	    	String.valueOf( codigovendedor ) + concatwith +
	    	getNombrevendedor()
	    	;
	    	
	    }
    
	public long getRowcount() {
		return rowcount;
	}
	public void setRowcount(long rowcount) {
		this.rowcount = rowcount;
	}
	public String getMpbcia() {
		return mpbcia;
	}
	public void setMpbcia(String mpbcia) {
		this.mpbcia = mpbcia;
	}
	public String getMpbsuc() {
		return mpbsuc;
	}
	public void setMpbsuc(String mpbsuc) {
		this.mpbsuc = mpbsuc;
	}
	public Integer getMpbnctto() {
		return mpbnctto;
	}
	public void setMpbnctto(Integer mpbnctto) {
		this.mpbnctto = mpbnctto;
	}
	public Date getMpbfcgnr() {
		return mpbfcgnr;
	}
	public void setMpbfcgnr(Date mpbfcgnr) {
		this.mpbfcgnr = mpbfcgnr;
	}
	public Integer getMpbcli() {
		return mpbcli;
	}
	public void setMpbcli(Integer mpbcli) {
		this.mpbcli = mpbcli;
	}
	public String getMpbttrj() {
		return mpbttrj;
	}
	public void setMpbttrj(String mpbttrj) {
		this.mpbttrj = mpbttrj;
	}
	public String getMpbdttrj() {
		if( mpbdttrj == null )
			mpbdttrj = "" ;
		return mpbdttrj;
	}
	public void setMpbdttrj(String mpbdttrj) {
		this.mpbdttrj = mpbdttrj;
	}
	public String getMpbetrj() {
		return mpbetrj;
	}
	public void setMpbetrj(String mpbetrj) {
		this.mpbetrj = mpbetrj;
	}
	public String getMpbdetrj() {
		if( mpbdetrj == null )
			mpbdetrj = "" ;
		return mpbdetrj;
	}
	public void setMpbdetrj(String mpbdetrj) {
		this.mpbdetrj = mpbdetrj;
	}
	public BigDecimal getMpbntrj() {
		return mpbntrj;
	}
	public void setMpbntrj(BigDecimal mpbntrj) {
		this.mpbntrj = mpbntrj;
	}
	public String getMpbnttrj() {
		return mpbnttrj;
	}
	public void setMpbnttrj(String mpbnttrj) {
		this.mpbnttrj = mpbnttrj;
	}
	public Integer getMpbvtrj() {
		return mpbvtrj;
	}
	public void setMpbvtrj(Integer mpbvtrj) {
		this.mpbvtrj = mpbvtrj;
	}
	public BigDecimal getMpbvpag() {
		return mpbvpag;
	}
	public void setMpbvpag(BigDecimal mpbvpag) {
		this.mpbvpag = mpbvpag;
	}
	public Integer getMpbnpag() {
		return mpbnpag;
	}
	public void setMpbnpag(Integer mpbnpag) {
		this.mpbnpag = mpbnpag;
	}
	public Date getMpbfpag() {
		return mpbfpag;
	}
	public void setMpbfpag(Date mpbfpag) {
		this.mpbfpag = mpbfpag;
	}
	public String getMpbmon() {
		return mpbmon;
	}
	public void setMpbmon(String mpbmon) {
		this.mpbmon = mpbmon;
	}
	public BigDecimal getMpbtcam() {
		return mpbtcam;
	}
	public void setMpbtcam(BigDecimal mpbtcam) {
		this.mpbtcam = mpbtcam;
	}
	public String getMpbobs() {
		return mpbobs;
	}
	public void setMpbobs(String mpbobs) {
		this.mpbobs = mpbobs;
	}
	public Integer getMpbnint() {
		return mpbnint;
	}
	public void setMpbnint(Integer mpbnint) {
		this.mpbnint = mpbnint;
	}
	public Integer getMpbintr() {
		return mpbintr;
	}
	public void setMpbintr(Integer mpbintr) {
		this.mpbintr = mpbintr;
	}
	public String getMpbsts1() {
		return mpbsts1;
	}
	public void setMpbsts1(String mpbsts1) {
		this.mpbsts1 = mpbsts1;
	}
	public String getMpbsts2() {
		return mpbsts2;
	}
	public void setMpbsts2(String mpbsts2) {
		this.mpbsts2 = mpbsts2;
	}
	public String getMpbcodcomp() {
		return mpbcodcomp;
	}
	public void setMpbcodcomp(String mpbcodcomp) {
		this.mpbcodcomp = mpbcodcomp;
	}
	public String getMpbcodsuc() {
		return mpbcodsuc;
	}
	public void setMpbcodsuc(String mpbcodsuc) {
		this.mpbcodsuc = mpbcodsuc;
	}
	public String getMpbunineg() {
		return mpbunineg;
	}
	public void setMpbunineg(String mpbunineg) {
		this.mpbunineg = mpbunineg;
	}
	public Integer getMpbnumrec() {
		return mpbnumrec;
	}
	public void setMpbnumrec(Integer mpbnumrec) {
		this.mpbnumrec = mpbnumrec;
	}
	public String getMpbtiporec() {
		return mpbtiporec;
	}
	public void setMpbtiporec(String mpbtiporec) {
		this.mpbtiporec = mpbtiporec;
	}
	public Date getMpbfecha() {
		return mpbfecha;
	}
	public void setMpbfecha(Date mpbfecha) {
		this.mpbfecha = mpbfecha;
	}
	public Integer getMpbcaid() {
		return mpbcaid;
	}
	public void setMpbcaid(Integer mpbcaid) {
		this.mpbcaid = mpbcaid;
	}
	public String getMpbhereg() {
		return mpbhereg;
	}
	public void setMpbhereg(String mpbhereg) {
		this.mpbhereg = mpbhereg;
	}
	public Date getMpbfereg() {
		return mpbfereg;
	}
	public void setMpbfereg(Date mpbfereg) {
		this.mpbfereg = mpbfereg;
	}
	public Date getMpbhrreg() {
		return mpbhrreg;
	}
	public void setMpbhrreg(Date mpbhrreg) {
		this.mpbhrreg = mpbhrreg;
	}
	public String getMpbpareg() {
		return mpbpareg;
	}
	public void setMpbpareg(String mpbpareg) {
		this.mpbpareg = mpbpareg;
	}
	public String getMpbprreg() {
		return mpbprreg;
	}
	public void setMpbprreg(String mpbprreg) {
		this.mpbprreg = mpbprreg;
	}
	public String getMpbhecam() {
		return mpbhecam;
	}
	public void setMpbhecam(String mpbhecam) {
		this.mpbhecam = mpbhecam;
	}
	public Date getMpbfecam() {
		return mpbfecam;
	}
	public void setMpbfecam(Date mpbfecam) {
		this.mpbfecam = mpbfecam;
	}
	public Date getMpbhrcam() {
		return mpbhrcam;
	}
	public void setMpbhrcam(Date mpbhrcam) {
		this.mpbhrcam = mpbhrcam;
	}
	public String getMpbpacam() {
		return mpbpacam;
	}
	public void setMpbpacam(String mpbpacam) {
		this.mpbpacam = mpbpacam;
	}
	public String getMpbprcam() {
		return mpbprcam;
	}
	public void setMpbprcam(String mpbprcam) {
		this.mpbprcam = mpbprcam;
	}
	public String getClientenombre() {
		return clientenombre;
	}
	public void setClientenombre(String clientenombre) {
		this.clientenombre = clientenombre;
	}
	public String getCorreo() {
		return correo;
	}
	public void setCorreo(String correo) {
		this.correo = correo;
	}
	public String getCodcomp() {
		return codcomp;
	}
	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}
	public String getNomcomp() {
		return nomcomp;
	}
	public void setNomcomp(String nomcomp) {
		this.nomcomp = nomcomp;
	}
	public String getCodsuc() {
		return codsuc;
	}
	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}
	public String getNomsuc() {
		return nomsuc;
	}
	public void setNomsuc(String nomsuc) {
		this.nomsuc = nomsuc;
	}
	public String getCodunineg() {
		return codunineg;
	}
	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}
	public String getNomunineg() {
		return nomunineg;
	}
	public void setNomunineg(String nomunineg) {
		this.nomunineg = nomunineg;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
    
    public String getAuthorizationNumber() {
		return authorizationNumber;
	}
	public void setAuthorizationNumber(String authorizationNumber) {
		this.authorizationNumber = authorizationNumber;
	}
	public String getReferenceNumber() {
		if(referenceNumber == null) referenceNumber = "0";
		
		return referenceNumber;
	}
	public void setReferenceNumber(String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}
	public String getResponseCode() {
		
		if(responseCode == null)
			responseCode = "" ;
		
		return responseCode;
	}
	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	public String getResponseCodeDescription() {
		if (responseCodeDescription == null)
			responseCodeDescription = "";
		return responseCodeDescription;
	}
	public void setResponseCodeDescription(String responseCodeDescription) {
		this.responseCodeDescription = responseCodeDescription;
	}
	public String getSalesAmount() {
		return salesAmount;
	}
	public void setSalesAmount(String salesAmount) {
		this.salesAmount = salesAmount;
	}
	public String getTransactionId() {
		return transactionId;
	}
	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}
	public String getSystemTraceNumber() {
		return systemTraceNumber;
	}
	public void setSystemTraceNumber(String systemTraceNumber) {
		this.systemTraceNumber = systemTraceNumber;
	}
	public String getFechatransaccion() {
		return fechatransaccion;
	}
	public void setFechatransaccion(String fechatransaccion) {
		this.fechatransaccion = fechatransaccion;
	}

	public String getObservaciones() {
		if(observaciones ==null)
			observaciones = "";
		return observaciones;
	}
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}
	public int getNumerobatchpago() {
		return numerobatchpago;
	}
	public void setNumerobatchpago(int numerobatchpago) {
		this.numerobatchpago = numerobatchpago;
	}
	public String getNumerotarjetadsp() {
		
		if(mpbntrj != null ){
			String numerotc = mpbntrj.toString();
			numerotc =  numerotc.substring(numerotc.length()-4, numerotc.length()) ;
			numerotarjetadsp = CodeUtil.pad(numerotc, 8, "*") ;
		}
		return numerotarjetadsp;
	}
	public void setNumerotarjetadsp(String numerotarjetadsp) {
		this.numerotarjetadsp = numerotarjetadsp;
	}
	
	public String getEstadoProceso() {
		
		if( estadoProceso==null || estadoProceso.isEmpty() )
			estadoProceso = "Pendiente";  
		
		return estadoProceso;
	}
	public void setEstadoProceso(String estadoProceso) {
		this.estadoProceso = estadoProceso;
	}
	public String getExcluirDebito() {
		excluirDebito = (excluyeDebito)? "Si":"No" ;
		return excluirDebito;
	}
	public void setExcluirDebito(String excluirDebito) {
		this.excluirDebito = excluirDebito;
	}
	public boolean isExcluyeDebito() {
		return excluyeDebito;
	}
	public void setExcluyeDebito(boolean excluyeDebito) {
		this.excluyeDebito = excluyeDebito;
	}
	public String getCodigoafiliado() {
		return codigoafiliado;
	}
	public void setCodigoafiliado(String codigoafiliado) {
		this.codigoafiliado = codigoafiliado;
	}
	public String getCodigoterminal() {
		return codigoterminal;
	}
	public void setCodigoterminal(String codigoterminal) {
		this.codigoterminal = codigoterminal;
	}
	public MetodosPago metodosPagoDesdeCuota(){
		MetodosPago mp = new MetodosPago();
		String formadepago = MetodosPagoCtrl.TARJETA;
		
		try {
			 
			String numerotarjeta = mpbntrj.toString().trim();
			numerotarjeta = numerotarjeta.substring(numerotarjeta.length()-4, numerotarjeta.length()) ;
			
			mp.setMetododescrip(MetodosPagoCtrl.descripcionMetodoPago(formadepago) );
			mp.setMetodo( formadepago );
			mp.setMoneda( mpbmon );
			
//			mp.setMonto( mpbvpag.doubleValue() );
			mp.setMonto( montocobrarentarjeta.doubleValue() );
			
//			mp.setTasa( BigDecimal.ONE );
			
			mp.setTasa( new BigDecimal(montocobrarentarjeta.doubleValue()/mpbvpag.doubleValue() ).setScale(4, RoundingMode.HALF_UP ));
			
//			mp.setEquivalente( mpbvpag.doubleValue() );
			mp.setEquivalente( montocobrarentarjeta.doubleValue() );
			
			mp.setCodigobanco(codigoafiliado );
			mp.setReferencia( codigoafiliado );
			mp.setReferencia2( mpbcli.toString() );
			
			mp.setReferencia3( numerotarjeta );
			mp.setReferencia4( referenceNumber);
			mp.setReferencia5( authorizationNumber);
			mp.setReferencia6( fechatransaccion );
			mp.setReferencia7( systemTraceNumber );	
			mp.setNombre( clientenombre);
			mp.setVmanual("2");
			
			mp.setCodigomarcatarjeta( mpbttrj );
			mp.setMarcatarjeta( mpbdttrj );
			mp.setMontorecibido( mpbvpag  );
			mp.setMontoendonacion(BigDecimal.ZERO);
			mp.setIncluyedonacion(false);
			mp.setIdentificador( rowcount ) ;
			mp.setStatuspago("PND");
 
		} catch (Exception e) {
			mp = null;
			e.printStackTrace();
//			LogCrtl.imprimirError(e);
		}
		
		return mp;
	}
	
	public MetodosPago metodosPagoDesdeCuota(String strMonedaContrato, BigDecimal tasaOficial){
		MetodosPago mp = new MetodosPago();
		String formadepago = MetodosPagoCtrl.TARJETA;
		
		try {
			 
			String numerotarjeta = mpbntrj.toString().trim();
			numerotarjeta = numerotarjeta.substring(numerotarjeta.length()-4, numerotarjeta.length()) ;
			
			mp.setMetododescrip(MetodosPagoCtrl.descripcionMetodoPago(formadepago) );
			mp.setMetodo( formadepago );
			mp.setMoneda( mpbmon );
			
//			mp.setMonto( mpbvpag.doubleValue() );
//			mp.setTasa( BigDecimal.ONE );
//			mp.setEquivalente( mpbvpag.doubleValue() );
			if(strMonedaContrato.compareTo(mpbmon)==0)
			{
				mp.setMonto( montocobrarentarjeta.doubleValue() );
				mp.setTasa( new BigDecimal(montocobrarentarjeta.doubleValue()/mpbvpag.doubleValue() ).setScale(4, RoundingMode.HALF_UP ));
				mp.setEquivalente( montocobrarentarjeta.doubleValue() );
			}
			else
			{
				if(mpbmon.compareTo("COR")==0)
				{
					mp.setMonto( montocobrarentarjeta.doubleValue() );
					mp.setTasa( new BigDecimal(montocobrarentarjeta.doubleValue()/mpbvpag.doubleValue() ).setScale(4, RoundingMode.HALF_UP ));
					mp.setEquivalente(  mpbvpag.doubleValue() );
				}
				else
				{
					mp.setMonto( montocobrarentarjeta.doubleValue() );
					mp.setTasa( tasaOficial);
					mp.setEquivalente( montocobrarentarjeta.multiply(tasaOficial).setScale(2, RoundingMode.HALF_UP ).doubleValue()  );
				}
			}
			
			mp.setCodigobanco(codigoafiliado );
			mp.setReferencia( codigoafiliado );
			mp.setReferencia2( mpbcli.toString() );
			
			mp.setReferencia3( numerotarjeta );
			mp.setReferencia4( referenceNumber);
			mp.setReferencia5( authorizationNumber);
			mp.setReferencia6( fechatransaccion );
			mp.setReferencia7( systemTraceNumber );	
			mp.setNombre( clientenombre);
			mp.setVmanual("2");
			
			mp.setCodigomarcatarjeta( mpbttrj );
			mp.setMarcatarjeta( mpbdttrj );
			mp.setMontorecibido( mpbvpag  );
			mp.setMontoendonacion(BigDecimal.ZERO);
			mp.setIncluyedonacion(false);
			mp.setIdentificador( rowcount ) ;
			mp.setStatuspago("PND");
 
		} catch (Exception e) {
			mp = null;
			e.printStackTrace();
//			LogCrtl.imprimirError(e);
		}
		
		return mp;
	}
	public boolean isRegistroprocesado() {
		return registroprocesado;
	}
	public void setRegistroprocesado(boolean registroprocesado) {
		this.registroprocesado = registroprocesado;
	}
	public boolean isErrorpagotarjeta() {
		return errorpagotarjeta;
	}
	public void setErrorpagotarjeta(boolean errorpagotarjeta) {
		this.errorpagotarjeta = errorpagotarjeta;
	}
	public String getMpbchas() {
		return mpbchas;
	}
	public void setMpbchas(String mpbchas) {
		this.mpbchas = mpbchas;
	}
	public String getNombreterminal() {
		return nombreterminal;
	}
	public void setNombreterminal(String nombreterminal) {
		this.nombreterminal = nombreterminal;
	}
	public BigDecimal getMontocobrarentarjeta() {
		return montocobrarentarjeta;
	}
	public void setMontocobrarentarjeta(BigDecimal montocobrarentarjeta) {
		this.montocobrarentarjeta = montocobrarentarjeta;
	}
	public int getNumerotarjeta4d() {
		try {
			String numerotarjeta = mpbntrj.toString().trim();
			
			if( numerotarjeta.length() <= 4 )
				return Integer.parseInt(numerotarjeta);
			
			numerotarjeta = numerotarjeta.substring(numerotarjeta.length()-4, numerotarjeta.length()) ;
			numerotarjeta4d  = Integer.parseInt(numerotarjeta);
			
		} catch (Exception e) {
			numerotarjeta4d = 0 ;
		}
		return numerotarjeta4d;
	}
	public void setNumerotarjeta4d(int numerotarjeta4d) {
		this.numerotarjeta4d = numerotarjeta4d;
	}
	public String getNombrecaja() {
		if(nombrecaja ==null)
			nombrecaja = "";
		return nombrecaja;
	}
	public void setNombrecaja(String nombrecaja) {
		this.nombrecaja = nombrecaja;
	}
	public String getNombrecajero() {
		if(nombrecajero ==null)
			nombrecajero = "";
		return nombrecajero;
	}
	public void setNombrecajero(String nombrecajero) {
		this.nombrecajero = nombrecajero;
	}

	public String getCorreocliente() {
		if(correocliente == null)
			correocliente = "" ;
		if( correocliente.length() == 0 )
			correocliente = "   ";
		return correocliente;
	}

	public void setCorreocliente(String correocliente) {
		this.correocliente = correocliente;
	}

	public boolean isNotificado() {
		return notificado;
	}

	public void setNotificado(boolean notificado) {
		this.notificado = notificado;
	}

	public String getInvoicenumber() {
		return invoicenumber;
	}

	public void setInvoicenumber(String invoicenumber) {
		this.invoicenumber = invoicenumber;
	}

	public Integer getCodigovendedor() {
		return codigovendedor;
	}

	public void setCodigovendedor(Integer p_codigovendedor) {
		codigovendedor = p_codigovendedor;
	}

	public String getNombrevendedor() {
		
		if(nombrevendedor == null  )
			nombrevendedor = "" ;
		
		nombrevendedor = CodeUtil.capitalize(nombrevendedor);
		
		return nombrevendedor;
	}

	public void setNombrevendedor(String p_nombrevendedor) {
		nombrevendedor = p_nombrevendedor;
	}

	public Integer getMpbvtrjcobro() {
		return mpbvtrjcobro;
	}

	public void setMpbvtrjcobro(Integer mpbvtrjcobro) {
		this.mpbvtrjcobro = mpbvtrjcobro;
	}

	
}




